### PR TITLE
Clarify current limitations on node.js and TiddlyWiki

### PR DESCRIPTION
**Pull request by anavarre**
Per #1222

### CODE REVIEW

**Comment by kewball** [comment]
This PR would be even more helpful if it linked directly to Tiddlers describing "HTTP or JavaScript API"

**Comment by rubaboo** [comment]
IMO this can be closed without merging. The only real piece of information it conveys is "If you edit the files directly, you need to restart nodejs for the changes to appear in the wiki." Which should not be very unexpected for anybody who feels comfortable enough to try running their TiddlyWiki on NodeJS.

**Comment by tobibeer** [comment]
@rubaboo: not so sure about that, syncing could well work both ways and I would even find that to be a reasonable expectation. But it's just not implemented right now.

**Comment by Jermolene** [comment]
Thanks @anavarre. This is something that does catch people out regularly, so I'm inclined to merge.

**Pull request merged**
