### PR TITLE
Minor cleanup of startup.js

### PR DESCRIPTION
**Pull request by NicolasPetton**
* Remove unused var declaration
* Remove trailing whitespaces

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @NicolasPetton.

I'd be in favour of performing a bulk operation to remove any trailing whitespace, and then to test for trailing whitespace within our test suite.

**Comment by NicolasPetton** [comment]
@Jermolene I totally agree. I can open a PR for that if you want.

**Comment by Jermolene** [comment]
> @Jermolene I totally agree. I can open a PR for that if you want.

That would be great, thank you.

We'd need to make sure that GitHub displays a clear message if a PR includes trailing spaces. The current system displays success/failure but I'm not sure that it displays detailed messages until one clicks through to the GitHub Actions logs.

**Comment by NicolasPetton** [comment]
> We'd need to make sure that GitHub displays a clear message if a PR includes trailing spaces. The current system displays success/failure but I'm not sure that it displays detailed messages until one clicks through to the GitHub Actions logs.

AFAIK that's how GitHub's UI works, regardless of the CI used.

**Pull request merged**
