### PR TITLE
fixes: #4349 ... bring tm-fold-xxx message docs on par with the code,…

### PR DESCRIPTION
**Pull request by pmario**
bring tm-fold-xxx message docs on par with the code that is executed.

### CODE REVIEW

**Comment by pmario** [comment]
This PR only contains doc files. 

There will be a follow-up, that will fix the view-template tiddlers, since they contain a `$param` attribute, which is ignored by the code executed in navigator.js

**Comment by pmario** [comment]
code can be found at: https://github.com/Jermolene/TiddlyWiki5/blob/6fa3e21116338e5fc7b59db2a327eedb04ba9288/core/modules/widgets/navigator.js#L576

**Comment by pmario** [comment]
@Jermolene ... this is docs only.

**Comment by Jermolene** [comment]
Thanks @pmario

**Pull request merged**
