### PR TITLE
"days" filter: yesterday and tomorrow edge cases

### PR DESCRIPTION
**Pull request by nameanyone**
Make it possible to get an interval ending with yesterday or starting with tomorrow.

### CODE REVIEW

**Comment by nameanyone** [comment]
There is a groups discussion [here](https://groups.google.com/forum/#!searchin/tiddlywiki/days$20filter/tiddlywiki/qv02EnGUwU8/qtdpneO2HwAJ) that made me realise that currently it's impossible to produce a range of days that ends yesterday (past days) or starts tomorrow (days in the future).

This PR addresses the problem by including the day (parameter) in the output of a negated operator.

**Comment by nameanyone** [comment]
It's only 1 AM of Apr 6th where I am, but the filter returns Apr 7th as today, and so on for any other day, everything is shifted ahead by a day. Do I need to look into $tw.utils.parseDate? I'll pickup later...

**Comment by Jermolene** [comment]
Hi @nameanyone it may be a timezone issue. There's been some discussion agreeing that TW's current time format is inadequate because it doesn't include a timezone offset. There is also currently some inconsistency as to whether dates are treated as UTC or the local timezone. (Apologies, I don't have the ticket references, but I think it was here on GitHub).

**Comment by nameanyone** [comment]
Well, it's the morning of 6th in UTC as well... Anyhow, this patch can still go in, since the filter only deals with difference between two dates rounded to midnight, and does not concern itself with timezone differences.

**Comment by Jermolene** [comment]
Hi @nameanyone I just saw your [comments over in the discussion group](https://groups.google.com/d/msg/tiddlywiki/qv02EnGUwU8/kJzZESJFBAAJ); would it be worth including any of that material in the tw5.com docs?

**Comment by nameanyone** [comment]
It might, but I'm not sure where. The existing filter operators documetation is very dry and formal, I followed suit. It's hard to build a good example set as well; ideally, it should revolve around the current date, but tw5.com content is static.

Can we go ahead with this patch for now, that at least will make the operator more useful, and hopefully people will stop trying to reinvent it.

I will try expanding the docs later by adding a button that generates a set of tiddlers with a date field ranging 7 days each way. That will take me some effort.

**Comment by Jermolene** [comment]
Hi @nameanyone my apologies for the delay

**Pull request merged**
