### PR TITLE
Signing the CLA

### PR DESCRIPTION
**Pull request by JesseWeinstein**

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @JesseWeinstein thanks for this, but my apologies, I'm afraid things are more complicated than I thought. We've recently adopted a new continuous integration system which requires us to keep a separate "tiddlywiki-com" branch for docs updates that get pushed directly to tiddlywiki.com versus the "master" branch which gets pushed to tiddlywiki.com/prerelease

This PR targetted "master" and so I edited it to target "tiddlywiki-com". That's worked fine in the past for PRs that were cloned before we made the change, but now it tries to bring in all the changes from "master" as well as the new changes you're submitting.

So, I'm afraid the fix is for you to adjust the PRs to target the "tiddlywiki-com" branch, and make sure that the changes already in "master" are excluded. My apologies for the extra work. I shall update the docs to try to avoid this happening in the future.

**Comment by JesseWeinstein** [comment]
No worries! Glad to be a test case for the new system. :-)

**Comment by JesseWeinstein** [comment]
Correctly rebased.

**Comment by Jermolene** [comment]
Hi @JesseWeinstein no need to apologise for the ping, apologies it's taken me so long to get to this. Anyhow, looks good, so thank you very much, and welcome to the project!

**Pull request merged**
