### PR TITLE
ControlPanel Button: use tv-story-list variable

### PR DESCRIPTION
**Pull request by BurningTreeC**
This PR makes the ControlPanel Button show as selected when the `tv-story-list` contains `$:/ControlPanel` in its list field

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @BurningTreeC good to see you here agin!

**Comment by BurningTreeC** [comment]
> Hi @BurningTreeC good to see you here agin!

Thanks @Jermolene - I'm working on a multi-column layout at the moment and if I find things that would be feasible for the core I will make PR's


https://user-images.githubusercontent.com/9407182/160272540-b59e1093-ec35-481b-ad02-cfecc4a54d77.mp4

**Comment by Jermolene** [comment]
Hi @BurningTreeC that's good to see.

You might be interested in the work that I've been doing along similar lines as part of TWPub:

https://twpub-tools.org/

I'm using the work there as a testbed for core enhancements. It's a way for me to work on stuff that's going to take much longer than the usual TW release cycle, but keeps the work in public so that others can follow along.

It features:

* A new navigator written in wikitext
* Multiple columns
* Multiple story rivers of different types
* Shift-clicking a link to bring up a popup to choose the target story river

You can use the sidebar to explore the new features.

**Comment by BurningTreeC** [comment]
Thanks @Jermolene,
my layout is indeed inspired by your twpub-tools
I didn't know about the navigator though :)

**Pull request merged**
