### PR TITLE
Toc recursion protection

### PR DESCRIPTION
**Pull request by pmario**
The attached file contains some test data and the modified `core/wiki/macros/toc.tid`. So it should be easy to test: [toc-recursion-prevention.zip](https://github.com/Jermolene/TiddlyWiki5/files/632636/toc-recursion-prevention.zip)

The _only_ "evil" tiddler, that causes infinite recursion is tiddler `a`. It is used several times in the tree, to test the edge cases. 

`test-???` tiddlers contain the test UI. 

The PR contains new variables: `exclude, excluded, path`

`exclude` is used as the parameter for the list widget
`excluded` is expanded with the new current tag value and then passed to the recursion function
`path` is used to create unique `toc-state` tiddlers for the expandable toc's

----

This PR also changes `itemClassFilter` to `itemClassFilter:" "`. This is needed, to assign the right CSS classes to the `li` elements. 

have fun!

### CODE REVIEW

**Comment by pmario** [comment]
This PR is the first step to improve the core TOC behaviour, as discussed in hangout#101. It doesn't contain the "toc auto-select" function, that Eric uses for InsideTW. 

To implement the auto-select / auto-open branches behaviour, we should rewrite the stuff, since we need predictable toc-state-path names. So we can't use `<qualify>` macro. We need to adopt Erics mechanism, that uses uniqe config-tiddler + unique path names, that can be calculated from tiddler names only. ...

So the proposal is: 

 - Use this PR as a fix for recursion problems and for backwards compatibility. 
 - Create a new toc-XXXX macro with the improved functions
    - the name: `toc-tree` is taken by Eric. So we need a different one.

**Comment by pmario** [comment]
ping @tiddlytools @Jermolene

**Comment by Jermolene** [comment]
Thanks very much @pmario

**Comment by pmario** [comment]
cool. Now I can go on and **try** to implement the branch "auto-select" feature, that Eric introduced for his `toc-tree` macro.

**Pull request merged**
