### PR TITLE
Create TiddlyLang

### PR DESCRIPTION
**Pull request by Serj-Aleks**
Translation of DocTW5

### CODE REVIEW

**Comment by tobibeer** [comment]
Hi @Serj-Aleks: What is this? / What does this do?

**Comment by pmario** [comment]
@Jermolene ... Please close this PR. It seems to be a "miss-click"

**Comment by Serj-Aleks** [comment]
Tiddlywiki is not only some kind of program, but also a certain model and
therefore has its own meta-language. I still do not know how to formalize
it, but the idea has a place to be.

вт, 27 нояб. 2018 г. в 13:02, Mario Pietsch <notifications@github.com>:

**Comment by Jermolene** [comment]
Hi @Serj-Aleks that sounds interesting, but this pull request doesn't do anything useful and so I'm closing it -- PRs are not intended for open ended discussion.

**Pull request closed without merging**
