### PR TITLE
Menubar plugin: make sidebar-scrollable top margin adjust ...

### PR DESCRIPTION
**Pull request by BurningTreeC**
... to height of menubar

Peek 2020-11-04 10-31

### CODE REVIEW

**Comment by BurningTreeC** [comment]
Peek 2020-11-04 11-37

**Comment by BurningTreeC** [comment]
This PR also rotates the sidebar-chevrons when the menubar has its narrow styles

**Comment by BurningTreeC** [comment]
Peek 2020-11-05 12-10

**Comment by pmario** [comment]
Did you test it in a way, where the menu bar is only 1 line high. .. Does the height calculation still work?

**Comment by BurningTreeC** [comment]
>Did you test it in a way, where the menu bar is only 1 line high. .. Does the height calculation still work?

@pmario - yes I did test that, it works also in that case

**Comment by BurningTreeC** [comment]
for the screen-width between the sidebarbreakpoint and the narrow-breakpoint this needs some work

**Comment by Jermolene** [comment]
Good stuff thank you @BurningTreeC. Using wikitext processing in stylesheets is like a magical power in TiddlyWiki, great to see it used more.

**Comment by BurningTreeC** [comment]
@Jermolene, I've updated the styles and the menu

Peek 2020-11-06 13-55

**Comment by BurningTreeC** [comment]
>Using wikitext processing in stylesheets is like a magical power in TiddlyWiki, great to see it used more.

Yes it's really *magical* :smile:

**Comment by BurningTreeC** [comment]
@Jermolene - are you interested in this?

I was also thinking, how browser support is for calculating media queries directly like:

```

@media (max-width: calc({{$:/config/plugins/menubar/breakpoint}} - 1px) ) {

...

}

```

**Comment by Jermolene** [comment]
> @Jermolene - are you interested in this?

Yes!
> I was also thinking, how browser support is for calculating media queries directly like:
> ```
> @media (max-width: calc({{$:/config/plugins/menubar/breakpoint}} - 1px) ) {
> ...
> }
> ```

We could do that with a filter, couldn't we?

**Comment by Jermolene** [comment]
Sorry @BurningTreeC I misunderstood

**Comment by BurningTreeC** [comment]
@Jermolene - in this PR I'm not calculating media queries like described

the currently used filter that removes the "px" suffix, adds "1" and adds the "px" suffix again works only for widths with px units. if a user chooses em or vw it wouldn't work anymore ... That's why I'm wondering about browser support for media queries that use calc()

**Comment by Jermolene** [comment]
Ouch, that is indeed not very satisfying, I imagine it won't prove to be a problem.

**Comment by BurningTreeC** [comment]
>I imagine it won't prove to be a problem.

Yout think we can use:

```
@media (max-width: calc({{$:/config/plugins/menubar/breakpoint}} - 1px) ) {

...

}
```

?

**Comment by Jermolene** [comment]
Indeed @BurningTreeC Googling suggests that there is only partial browser support at the moment.

**Comment by kookma** [comment]
Hi @BurningTreeC 
I just checked this on Android running cell phone, opening tiddlywiki.com/prerelease see below images

WhatsApp Image 2020-11-26 at 2 40 17 PM
WhatsApp Image 2020-11-26 at 2 39 53 PM

See the sidebar toggle button! Is this a bug? 

I also tested in Firefox using design mode and different WxH. It seems below W=640px the toggle button is not visible and see it like above image. So on some Mobile phone you see this issue.

**Comment by rmunn** [comment]
#5150 is probably related to this.

**Pull request merged**
