### PR TITLE
getElementById support for fakedom

### PR DESCRIPTION
**Pull request by tobibeer**
**Note:** This is intended for comparison and @Jermolene has [already expressed no desire to merge](https://github.com/tobibeer/tw5-dom/issues/1) it.

Uses a basic hash-table applying "the winner takes it all" logic. Specifically, the first element to register an id is the one the id points to, so long as...

* it exists
* the id attribute is not removed from it

### CODE REVIEW

**Comment by pmario** [comment]
IMO this implementation is not according to the standards. 

ID is a MUST be unique in the whole document in the html spec: https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute

Also see browser implementations: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id and the linked living standard at: https://dom.spec.whatwg.org/#interface-nonelementparentnode which imo defines the behaviour for getElementById()

>The getElementById(elementId)
method must return the first element, in tree order, within context object’s descendants, whose ID is elementId, and null if there is no such element otherwise.

So imo the implementation is a bit more complicated, than implemented here, since it basically takes the "starting node" into account and returns the first descendant node, that matches the id string.

**Comment by tobibeer** [comment]
> ID is a MUST be unique in the whole document in the html spec

It is. Only one element will be returned for a given id. Whether a user / developer implements the id attribute wrongly is handled in just about the same (arbitrary) way a browser handles this case.

> There are a lot of links in the standards page, that I didn't copy over, so follow the link

I have changed the PR so that a reference for an id, once set, can only be overwritten if...

* the node that registered it first no longer exists
* the id is removed form that node via **removeAttribute()**

This appears to conform to the standard logic.

**Comment by tobibeer** [comment]
Pssibly, removing the id attribute from a node / or any node having an id also requires to reevaluate whether other nodes have it (wrongfully) assigned already.

I think it is quite superfluous and complex... and highly irrelevant for our usecase where we wish to render static pages.

**Comment by tobibeer** [comment]
With respect to my last comment, there would sure be another little bit of functionality not in **fakedom**: **document.contains(node)**.

**Pull request closed without merging**
