### PR TITLE
added documentation tiddler "HiddenTiddlers"

### PR DESCRIPTION
**Pull request by tobibeer**
As suggested in https://github.com/Jermolene/TiddlyWiki5/issues/1210#issuecomment-72818255

*Perhaps also missing: proper documentation for all sidebar tabs?*

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @tobibeer I'm not sure about this. "HiddenTiddlers" isn't really a core concept of TiddlyWiki. This is really about SystemTiddlers, I think. 

What do you mean by imported media being hidden from sidebar lists? I'm not aware of that happening, apart from stuff that's omitted from the Recent tab because it lacks a modification date.

**Comment by tobibeer** [comment]
Shadows are hidden, too... and thus make third (or rather second) on the list, with or without `$:/`. Perhaps you don't think of it as a feature, but it's a fact and a confusing one when you don't know about it or understand which things have what implications. This articulates something in need of explaining, imho.

**Comment by Jermolene** [comment]
My main point is that it doesn't fit the definition for the "concepts" tag: those are supposed to be the primitive concepts that make up TiddlyWiki. Hidden tiddlers are a consequence or observable property of a TiddlyWiki, not a core concept.

But lets say that you add a description of shadow tiddlers as another example of a way that tiddlers are hidden. That mechanism is (like SystemTiddlers) already the subject of a "concepts" tiddler. So, is this new tiddler in existence to tie together these disparate mechanisms by which tiddlers can be hidden? If so, then it may be more appropriate to structure it as a how-to tip ("How to hide the tiddlers that make up your TiddlyWiki") or a FAQ ("Why are some tiddlers visible in some lists and not in others?").

**Comment by tobibeer** [comment]
I don't quite see it as a "how to" although it can be articulated as one. To me it is a "what is what".

**Comment by Jermolene** [comment]
But @tobibeer I can only repeat myself: "hidden tiddlers" isn't one of the concepts that makes up TiddlyWiki's design. The concepts that are combined to make TiddlyWiki are things like Tiddlers, Fields, ShadowTiddlers, SystemTiddlers, Plugins etc. Those are the building blocks from which TiddlyWiki is built. "Hidden tiddlers" is drawing together several underlying concepts, explaining how they each give rise to tiddlers that are hidden in some lists.

By the way, I still don't know what you meant about imported images being hidden?

**Comment by tobibeer** [comment]
> By the way, I still don't know what you meant about imported images being hidden?

Show me any "Motovun Jack" in a tab other than "Types".

**Comment by Jermolene** [comment]
I see these in More/All:

```
Motovun Jack.jpg
Motovun Jack.pdf
Motovun Jack.svg
```

None of them have modification dates, so they don't appear in Recent until you modify them.

**Comment by Jermolene** [comment]
@tobibeer my comments were about the tagging of this material. I'm not against adding the material in the right place.

**Comment by tobibeer** [comment]
To me, it's very much a conceptual thing that certain things are hidden form the default ui and to properly understand the rationale it needs to be explained from a conceptual point of view.

Before there is some **FAQ** or **How To** showing how to better understand or leverage this, I believe a conceptual statement needs to be made as to why, how and where certain things are hidden. Now, this can be scattered throughout different places, e.g. section five of widget foo or tiddler of type bar ...but I don't think that's a reasonable approach, because that's not how a user approaches the topic of "hidden stuff".

**Comment by Jermolene** [comment]
> To me, it's very much a conceptual thing when things are hidden form the default ui and to properly understand the rationale it needs to be explained from a conceptual point of view.

But the "concepts" tag doesn't denote topics that are explained from a conceptual point of view, it has the more precise definition I offered above.

>  I believe a conceptual statement needs to be made as to why, how and where certain things are hidden

I think there are only two things being explained here: system tiddlers and shadow tiddlers. Both are critical to an understanding of TiddlyWiki, and I agree that they both share the characteristic of allowing tiddlers to be hidden. But I'm not sure that that is the best way of explaining them. So perhaps the role of this material is to provide an overview of the different ways that an author might try to keep the plumbing from sight. In which case it's more of a Q&A/tip thing.

**Comment by tobibeer** [comment]
Mhhh, right now I am not sure how to approach the mildly complex landscape of topics revolving around hiding (or showing) (all kinds of) things.

Might actually warrant a section of its own either in "Working with TiddlyWiki" or "Customizing TiddlyWiki"... as we can hide (or sometimes want to show hidden) tiddler list items, tiddler contents, ui elements, etc...

**Pull request closed without merging**
