### PR TITLE
Toggle list-ops operator

### PR DESCRIPTION
**Pull request by saqimtiaz**
Extended list-ops filter that can be used to toggle a value in a list. This is a very common user query and something I've been using for myself for some time.

This is the last filter PR for now related to my custom filters that I think might be useful in the core.

A button to toggle a tag becomes as simple as:

```
<$button> {{custom-icon}}
<$action-listops  $tiddler="target" $tags="+[toggle[done]]" />
</$button>
```

or with a custom field:

```
<$button> {{custom-icon}}
<$action-listops $tiddler="target" $field="my-field" $subfilter="+[toggle[done]]" />
</$button>
```

While this can be done with existing filters, it is a fair bit more complicated. 
So the argument for merging is convenience, though I understand if we don't.

Will add a PR with docs if this is merged.

PS: with multiple filter operands #4964  this could be extended to toggle between two values.

### CODE REVIEW

**Comment by Jermolene** [comment]
Looks good thanks @saqimtiaz

**Comment by kookma** [comment]
@saqimtiaz  now creating a todolist in TW gets much more easier! Thank you!

**Comment by joshuafontany** [comment]
That simplifies so many common scenarios. Well done!!!

**Comment by saqimtiaz** [comment]
@joshuafontany can you see a use case for toggling between a value pair? 

`[toggle[tag1],[tag2]]`

I updated the code and added tests etc but haven't made a PR as I wasn't sure how useful that would be in practice.

If you start off with a tiddler with the tag `todo` you can just do `[toggle[todo]toggle[done]]` to toggle between todo and done.

However if you start off without either tag then the above won't work but `toggle[todo],[done]` will add `todo` on the first usage and then toggle between them on subsequent usages (with the extended toggle operator).

**Comment by kookma** [comment]
Hi @saqimtiaz,

I prefer `[toggle[tag1],[tag2]]`  this is more semantic!


 I like to give some examples for possible use cases.

Right now toggling is implemented using two button widgets and if something should be displayed two $reveal widgets. One example is toggling expand/collapse a set of sliders (e.g https://groups.google.com/g/tiddlywiki/c/5yPwhKTEZFs/m/AD29b6rtCgAJ)
In TW 5.1.22 this case needs two buttons to expand and collapse by using some stateTiddlers.


Other examples:

- Slider / accordion 
- Toggle palette: to switch between light/dark palette from UI
- Toggle between two stroyview (author mode/view mode) like what is used in Tiddlyshow (switch classic/zoomin) 
- Toggle menu
- Toggle sidebar
- Any kind of switch, when the user needs to decide between two opposing states.

**Comment by saqimtiaz** [comment]
@kookma the code is good to go, I just need to find time to update the docs as well.

**Comment by joshuafontany** [comment]
@saqimtiaz 
I agree with @kookma, he lays out the most common use case, and yes the double-operator would be ideal for weird corner cases, like starting without either tag, or some of the more complicated Page Template / UI adjustments that I use to toggle between "Reader" and "Dev" modes in my wiki. Here's the reader-mode toggle, for example, which could be completely re-factored:


`caption: Toggle Reader On Actions
creator: Joshua Fontany
description: Actions to Shows or Hide UI Elements
tags: $:/tags/ReaderMode/Off
title: $:/plugins/joshuafontany/pagetools/actions/reader-mode-off

<$action-listops $tiddler="$:/core/ui/SideBarSegments/search" $tags="[[$:/tags/SideBarSegment]]"/>
<$action-listops $tiddler="$:/plugins/joshuafontany/pagetools/ui/SideBarSegments/SimpleSearch" $tags="-[[$:/tags/SideBarSegment]]"/>

<$list variable="actionTid" filter="Tools More +[addprefix[$:/core/ui/SideBar/]]">
  <$action-listops $tiddler=<<actionTid>> $tags="[[$:/tags/SideBar]]"/>
</$list>

<$list variable="actionTid" filter="save-wiki control-panel more-page-actions new-tiddler +[addprefix[$:/config/PageControlButtons/Visibility/$:/core/ui/Buttons/]]">
  <$action-setfield $tiddler=<<actionTid>> $field="text" $value="show"/>
</$list>

<$action-setfield $tiddler="$:/plugins/joshuafontany/pagetools/ReaderMode" $field="text" $value="no"/>`

and

`caption: Toggle Reader On Actions
creator: Joshua Fontany
description: Actions to Shows or Hide UI Elements
tags: $:/tags/ReaderMode/On
title: $:/plugins/joshuafontany/pagetools/actions/reader-mode-on

<$action-listops $tiddler="$:/core/ui/SideBarSegments/search" $tags="-[[$:/tags/SideBarSegment]]"/>
<$action-listops $tiddler="$:/plugins/joshuafontany/pagetools/ui/SideBarSegments/SimpleSearch" $tags="[[$:/tags/SideBarSegment]]"/>

<$list variable="actionTid" filter="Tools More +[addprefix[$:/core/ui/SideBar/]]">
  <$action-listops $tiddler=<<actionTid>> $tags="-[[$:/tags/SideBar]]"/>
</$list>

<$list variable="actionTid" filter="save-wiki control-panel more-page-actions new-tiddler +[addprefix[$:/config/PageControlButtons/Visibility/$:/core/ui/Buttons/]]">
  <$action-setfield $tiddler=<<actionTid>> $field="text" $value="hide"/>
</$list>

<$action-setfield $tiddler="$:/plugins/joshuafontany/pagetools/ReaderMode" $field="text" $value="yes"/>`

**Comment by saqimtiaz** [comment]
@joshuafontany this has since been merged. See the end of #5015 for the continuation of the discussion, where your input would be very welcome.

**Comment by kookma** [comment]
@joshuafontany  @saqimtiaz 

See here https://kookma.github.io/TW-Utility/   and try to press combination alt+ctlr+a and see how you can toggle between author/reader mode! I

**Pull request merged**
