### PR TITLE
sort unlisted tags by title

### PR DESCRIPTION
**Pull request by tobibeer**
When tiddlers are not listed in the **list** field, sort them by title nonetheless, otherwise we get a real poor taglist from **$:/core/ui/TagTemplate**

### CODE REVIEW

**Comment by tobibeer** [comment]
You can see that working on (any tag at) [tb5](http://tb5.tiddlyspot.com/#filters).

**Comment by aelocson** [comment]
This is a great improvement. I was about to start looking at how to implement it myself, but you've saved me the trouble :)

**Comment by Jermolene** [comment]
Thanks @tobibeer looks good. Again it would be terrific to have some tests, and to update the docs on tagging.

**Comment by Jermolene** [comment]
But I'll merge for the moment anyhow.

**Comment by aelocson** [comment]
I'll update the documentation.

**Comment by tobibeer** [comment]
:+1:  thanks @aelocson :-)

**Pull request merged**
