### PR TITLE
Move the version number to the top of the upgrader

### PR DESCRIPTION
**Pull request by pmario**
This PR only moves the version number to the top area of the upgrader UI

**Start View**

image

**Import View**

image

### CODE REVIEW

**Comment by twMat** [comment]
Nitpick... possibly someone might interpret it to mean that it is the wizard itself that has this version number. Maybe it should explicitly state "TiddlyWiki version..." ?
As I said: nitpick.

**Comment by pmario** [comment]
The wizard and the TW have that version number. So I don't see a problem here. The upgrader can only upgrade to that version number -- nothing else.

**Comment by twMat** [comment]
OK, I just thought it was a bit clearer, especially for the group we turn to with this modification to begin with. But no biggie if you disagree.

**Comment by pmario** [comment]
You are right. I did change it and did update the OT

**Comment by twMat** [comment]
Your idea to put it as the *top* headline makes things much clearer! Good idea!

**Comment by Jermolene** [comment]
Thanks @pmario I think it would be clearer if the heading "Upgrade Wizard" was the first and largest heading.

**Comment by pmario** [comment]
@Jermolene Updated as requested. I did also change the images in the OP

**Comment by pmario** [comment]
bump

**Comment by twMat** [comment]
bump

**Comment by pmario** [comment]
@Jermolene pls merge

**Pull request merged**
