### PR TITLE
Reduced indexOf calls in wiki.sortByList

### PR DESCRIPTION
**Pull request by flibbles**
PR for issue #4275

Examined the tests in test-tag. They already cover all the use cases
I could think of. I agree with Arlen22 that this change is functionally
identical to what was.

I also changed the name of the recursive function, and added some
comments to make this function easier to understand.

### CODE REVIEW

**Comment by pmario** [comment]
The advantage is?

**Comment by pmario** [comment]
hmm it should be linked to: #4275 right?

**Comment by flibbles** [comment]
Yes, it should. I made the inexcusable error of thinking that linking to the issue in the title would create the link.

**Comment by Jermolene** [comment]
Thanks @flibbles

**Pull request merged**
