### PR TITLE
fix Simplified Chinese

### PR DESCRIPTION
**Pull request by heroboy**
`缺失` is better in Simplified Chinese

### CODE REVIEW

**Comment by Jermolene** [comment]
@BramChen are you happy with this and #1658?

**Comment by BramChen** [comment]
@Jermolene it's fine with me.

Thanks @heroboy, but it looks like you haven't yet signed the Contributor License Agreement, which is needed before accepting a contribution.

**Comment by heroboy** [comment]
ok.
I have just signed it. #1667

**Comment by Jermolene** [comment]
Thanks @heroboy

**Pull request merged**
