### PR TITLE
implements emptyStoryMessage

### PR DESCRIPTION
**Pull request by tobibeer**
implements #1428 

added ControlPanel settings => reordered **ControlPanel / Basics** a bit to have **DefaultTiddlers** next to **EmptyMessage** but not shifting important stuff too far down

### CODE REVIEW

**Comment by tobibeer** [comment]
I did split up that language switcher message as wrapping the prompt was awkward, i.e. putting "language" on the next line but having "Hello!" on the first.

**Comment by Jermolene** [comment]
Hi @tobibeer that's great, sorry for the slow response. One small thing is please can you put the language switcher message change into a separate pull request?

**Comment by tobibeer** [comment]
@Jermolene I could but that will have to wait until this is merged... and then I might possibly not do it again.

**Comment by tobibeer** [comment]
@Jermolene — removed

**Comment by Jermolene** [comment]
Thanks @tobibeer

**Comment by Jermolene** [comment]
Hi @tobibeer there is a problem with this it turns out - every character typed in the text area causes the story river to be refreshed, and hence to lose the focus.

**Comment by tobibeer** [comment]
Perhaps just take it out of the **ControlPanel** and use as a "hidden feature"?

**Comment by Jermolene** [comment]
Yes that makes sense for the moment, please send a new pull request; I can't remerge this one.

**Comment by tobibeer** [comment]
No problem.

**Pull request merged**
