### PR TITLE
More sidebar tabs horizontal

### PR DESCRIPTION
**Pull request by pmario**
This PR fixes: **Make "tc-vertical" optional in $:/core/ui/SideBar/More** #1674 ... And can be merged after TW v5.2.4 has been released. I just wanted to close the issue ;)

Edit: This setting is a Hidden Setting now. 

image

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @pmario 

I don't think it's worth exposing a user interface for this setting because of the cost of the additional translation strings, and the absence of evidence that significant numbers of people don't like the vertical tabs. From my perspective, I'm only considering this PR because in the discussion in #1674 it became clear that it couldn't be done in CSS.

**Comment by pmario** [comment]
So you think it should be a hidden setting, which only needs a docs tiddler and no translation

**Comment by Jermolene** [comment]
> So you think it should be a hidden setting, which only needs a docs tiddler and no translation

Exactly that, thank you @pmario, and apologies for the confusion.

**Comment by pmario** [comment]
@Jermolene ... I did update the PR so it is a "Hidden Setting" now

**Comment by Jermolene** [comment]
> @Jermolene ... I did update the PR so it is a "Hidden Setting" now

Thank you @pmario

**Pull request merged**
