### PR TITLE
Preserve the scroll-position over refresh cycles

### PR DESCRIPTION
**Pull request by BurningTreeC**
This PR preserves the scroll position in the root window and new windows over page-refresh cycles

### CODE REVIEW

**Comment by BurningTreeC** [comment]
Edited the OP

**Comment by pmario** [comment]
I'm not sure, if I understand this. .. What happens, if the Story river after refresh is much shorter as the story river before?

**Comment by BurningTreeC** [comment]
> I'm not sure, if I understand this. .. What happens, if the Story river after refresh is much shorter as the story river before?

@pmario, you mean if we remove a tiddler from the StoryRiver for example? As far as my testings go, nothing special happens

**Comment by Jermolene** [comment]
Hi @BurningTreeC if we're going to try to do scroll position preservation then I think we need to adopt a technique that will also handle scroll positions within scrollable elements as well as the document body.

**Comment by BurningTreeC** [comment]
> Hi @BurningTreeC if we're going to try to do scroll position preservation then I think we need to adopt a technique that will also handle scroll positions within scrollable elements as well as the document body.

Hi @Jermolene, how would such a technique look like? Would we store the scroll positions somewhere globally and the corresponding domNode when the page refresh starts and then restore it when it ends?

**Comment by Jermolene** [comment]
> Hi @Jermolene, how would such a technique look like? Would we store the scroll positions somewhere globally and the corresponding domNode when the page refresh starts and then restore it when it ends?

Actually, aren't you doing just that as part of the focus preservation PR?

**Comment by Jermolene** [comment]
Apologies @BurningTreeC by "just that" I meant "aren't you restoring scroll positions as part of your focus preservation PR"?

**Comment by BurningTreeC** [comment]
> Apologies @BurningTreeC by "just that" I meant "aren't you restoring scroll positions as part of your focus preservation PR"?

Yes that's true @Jermolene

**Pull request closed without merging**
