### PR TITLE
Amendments to warnings upon loading content via _canonical_uri (#2796)

### PR DESCRIPTION
**Pull request by xcazin**
The discussion in #2796 lead to these proposed modifications in two locations (warnings in EditTemplate when using `_canonical_uri` and in ViewTemplate if something goes wrong). 

While I'm at it, adding French translations.

--Xavier.

### CODE REVIEW

**Comment by sukima** [comment]
I can't make heads or tails of this PR. I hope @Jermolene has more code-fu then I do.

**Comment by twMat** [comment]
Thanks Xavier! A detail, the second "paragraphs" is missing a "the":

>"you may either need to adjust the tiddler content type to _THE_ type of your external content"

**Comment by xcazin** [comment]
Hi @sukima,

Most commits are useless. The actual PR makes a few changes to 4 files: https://github.com/Jermolene/TiddlyWiki5/pull/2803/files

Cheers,
X.
P.S. : thanks @twMat, fixed!

**Comment by pmario** [comment]
@Xavier
If you use TW environment variables, you don't need to add directories to your dev repo. see: http://tiddlywiki.com/#Environment%20Variables%20on%20Node.js

Those environment vars can contain several paths. So it's easy to include 3rd party plugins, by just cloning their repos and set the variables.

**Comment by xcazin** [comment]
Wow, I had hoped that nobody would notice :-) I eventually squashed the
last two superfluous commits, but thanks anyway for the advice which I'll
follow from now on. I agree that using environment variables would have
been far more elegant!

X.

-- Xavier Cazin.
immatériel·fr — R.C.S. Paris 509 139 937
http://immateriel.fr — Skype : immateriel.fr
Mobile: +33 6 06 54 55 65 — Phone: +33 1 75 43 72 83

**Comment by xcazin** [comment]
Hi @Marxsal, I agree that such links to empty tiddlers are confusing. Still, the concept itself is important enough to deserve at least a small description of what is going on. What about coming up with an actual tiddler (that would rather be called `ExternalContent` once we understand why text or json files don't load while images files (or for that matter pdf, mp3, mp4) do load?

**Comment by Jermolene** [comment]
Thanks @xcazin and apologies for the late response!

**Pull request merged**
