### PR TITLE
Correct pointer shape and color for disabled button

### PR DESCRIPTION
**Pull request by kookma**
This PR addresses the #5625 where the disabled button shall have

- grey out color
- default pointer shape

### CODE REVIEW

**Review by saqimtiaz — CHANGES_REQUESTED** [review]
@kookma is it just me or is there 1 space + 1 tab character for indentation on the new lines you added?

**Comment by kookma** [comment]
Hi @Jermolene 
Following the discussion with you, @pmario and @saqimtiaz I have created this PR to address the issue of pointer shape and grey out color for disabled button! I think @BurningTreeC has recently maintained the Stylesheets!

By the way I see based.tid needs to be carefully checked and cleaned up! I did not this as I am afraid to mess it up. But I would be happy to help!

One question: If in body of tiddlers you create two buttons as below

```
<$button disabled=no class="tc-btn-invisible">{{$:/core/images/options-button}}</$button>

<$button disabled=no >{{$:/core/images/options-button}}</$button>
```

They show different pointer shape on mouse hover! The second shows the default cursor! Is it intentional?

**Comment by kookma** [comment]
> @kookma is it just me or is there 1 space + 1 tab character for indentation on the new lines you added?

Let me check! I used Notepad++ to edit!

**Comment by kookma** [comment]
@saqimtiaz I removed extra spaces!

**Review by saqimtiaz — APPROVED** [review]

**Comment by saqimtiaz** [comment]
@Jermolene CSS changes for disabled buttons as per your suggestion in #5625

**Comment by Jermolene** [comment]
Thanks @kookma @saqimtiaz

**Pull request merged**
