### PR TITLE
Add testcase to illustrate the bug in #8330

### PR DESCRIPTION
**Pull request by btheado**
Added a test that when run against the code prior to #8333, it crashes as mentioned in #8330. When run against the code after the fix, the test passes.

### CODE REVIEW

**Comment by btheado** [comment]
I added the test to `editions/test/tiddlers/tests/data/data-widget` rather than `editions/tw5.com/tiddlers/testcases/DataWidget`. I'm not sure if a copy is needed in both directories?

**Comment by Jermolene** [comment]
> I added the test to `editions/test/tiddlers/tests/data/data-widget` rather than `editions/tw5.com/tiddlers/testcases/DataWidget`. I'm not sure if a copy is needed in both directories?

Thanks @btheado.

My thinking was that we should use `editions/tw5.com/tiddlers/testcases` for all new test cases.

I would also like to move the existing testcases from `editions/test` into `tw5.com` but at the same time we would need to add a "Narrative" tiddler, which those test cases lack at the moment.

**Comment by btheado** [comment]
> My thinking was that we should use `editions/tw5.com/tiddlers/testcases` for all new test cases.
> 
> I would also like to move the existing testcases from `editions/test` into `tw5.com` but at the same time we would need to add a "Narrative" tiddler, which those test cases lack at the moment.

Will these test cases also be "included" into the test edition somehow? Or maybe change the `npm run test` script so it somehow invokes all the test cases from both editions? It is very convenient during development to be able to run all the tests from the command line.

**Comment by Jermolene** [comment]
> Will these test cases also be "included" into the test edition somehow? Or maybe change the `npm run test` script so it somehow invokes all the test cases from both editions? It is very convenient during development to be able to run all the tests from the command line.

There's a `tiddlywiki.files` in the test edition that pulls in the testcases from the tw5.com edition:

https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/test/tiddlers/tests/from-tw5.com/tiddlywiki.files

**Comment by btheado** [comment]
Thanks, @Jermolene. Good to know.  I moved the testcase. If this PR doesn't get merged to master prior to the next release, I can move it to target the tw5-com branch (it shouldn't go to tw5-com branch yet since it causes RSOD).

**Comment by Jermolene** [comment]
Thanks @btheado I think under the circumstances we can merge this to 'master'

**Pull request merged**
