### PR TITLE
[doc] SystemTag doc template

### PR DESCRIPTION
**Pull request by twMat**
Ref
https://github.com/Jermolene/TiddlyWiki5/discussions/6792

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @twMat

**Comment by pmario** [comment]
@Jermolene ... This path can't be checked out with windows. I do get the following error message from git pull

```
error: invalid path 'editions/tw5.com/tiddlers/$:/editions/tw5.com/systemtag-template.tid'
```

**Comment by Jermolene** [comment]
Thanks @pmario. Is this the same issue that you fixed the other day @saqimtiaz?

**Comment by saqimtiaz** [comment]
@Jermolene yes, I fixed it in the master branch, not realizing that it impacted the tw-com branch as well

**Pull request merged**
