### PR TITLE
add keyboard shortcut to add new field

### PR DESCRIPTION
**Pull request by BurningTreeC**

### CODE REVIEW

**Comment by BurningTreeC** [comment]
... it's `enter` by default but configurable

**Comment by pmario** [comment]
That's strange. ... If I type enter in the textarea, I do create a field??

**Comment by BurningTreeC** [comment]
@pmario - it's a shortcut in the value field of a new field. one can add it to the tiddler pressing `enter`

**Comment by pmario** [comment]
ah. ok

**Comment by morosanuae** [comment]
@BurningTreeC can you add a shortcut for starting the editing for tiddlers? For example, the content of some system tiddlers cover the tiddler buttons of the view bar and I cannot press the edit button and enter the edit mode. I've created a workaround but I don't like it. I've searched for a shortcut like that but I couldn't find one.
Thanks.

**Comment by BurningTreeC** [comment]
> can you add a shortcut for starting the editing for tiddlers?

Hi @morosanuae , we can do that when @pmario's work on storing the "focused-tiddler" or "viewed-tiddler" is merged. I don't know when that will happen

**Comment by Jermolene** [comment]
> Hi @morosanuae , we can do that when @pmario's work on storing the "focused-tiddler" or "viewed-tiddler" is merged. I don't know when that will happen

My current hope is to merge a simplified version of #3975 that doesn't include the new focused-tiddler stuff.

**Comment by Jermolene** [comment]
By the way @BurningTreeC why did you close this? I haven't looked properly, but seems like a great idea.

**Comment by BurningTreeC** [comment]
Hi @Jermolene , I closed this because I thought that `enter` could still be (somehow) used to insert new line characters, but I've reopened this PR now, it's configurable anyway

**Comment by BurningTreeC** [comment]
closing in favor of a new PR

**Pull request closed without merging**
