### PR TITLE
Add new focus attribute to $select widget

### PR DESCRIPTION
**Pull request by kookma**
This PR addresses the request by @ericshulman. See https://github.com/Jermolene/TiddlyWiki5/issues/7070.

The docs also updated.

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @kookma

**Comment by pmario** [comment]
IMO there should also be some CSS, that makes the focus visible. eg: 

The following CSS should be near the `select` css definition at line 3101 in vanilla/base.tid

```
select:focus {
	outline: 2px solid <<colour primary>>;
	outline-offset: -2px;
}
```

**Comment by Jermolene** [comment]
Hi @pmario is that a problem in a particular browser? The focus is already visible for the select widget in the browsers I tried:

image

**Comment by pmario** [comment]
Yes. It's a problem in FF. I'm testing with FF on ubuntu atm. Will need a bit more investigation. 

We actually could add it to the existing definition at line: 235 ... I will have a closer look

**Comment by Jermolene** [comment]
Hi @pmario I'm not seeing the problem in Firefox on macOS:

image

**Comment by pmario** [comment]
The problem imo comes from the reset. I'll have a closer look, at the reset itself we are using. May be there is a new version. ... Or we have to contribute the reset upstream. 

I think the decisions made in upstream are wrong or at least should be discussed

**Comment by pmario** [comment]
I think the difference between your 2 screenshots is significant. .. In FF the outline is barely visible. With my laptop I don't see it at all.

**Comment by Jermolene** [comment]
> With my laptop I don't see it at all.

That would seem to be a general problem with Firefox, and so I'm not sure that the core should be specially accommodating it.

**Comment by pmario** [comment]
As I wrote I'll have a discussion with the reset.css folks .. upstream. I did create a new issue. 

>That would seem to be a general problem with Firefox, and so I'm not sure that the core should be specially accommodating it.

As I wrote it's _not_ a firefox problem. It's a problem caused by the reset.css which the core uses. So IMO it _is_ a core problem and should be addressed there if upstream doesn't change it.

**Comment by Jermolene** [comment]
Thanks @pmario it does seem to be a reset problem.

**Pull request merged**
