### PR TITLE
[doc] Update Importing Tiddlers.tid

### PR DESCRIPTION
**Pull request by twMat**
[discussion](https://talk.tiddlywiki.org/t/importing-tiddlers-drag-a-link/2227)

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @twMat. Perhaps the phrase "TiddlyWiki internal link" might be better than "title link"?

**Comment by twMat** [comment]
Do I make a new PR for this then? I don't know how to modify a PR (is that even possible)?
Thanx

**Comment by pmario** [comment]
>Do I make a new PR for this then? I don't know how to modify a PR (is that even possible)?

Yes. That shouldn't be a problem. But I don't exactly know, where the button is.

**Comment by pmario** [comment]
The selected answer there may help https://stackoverflow.com/questions/10147445/github-adding-commits-to-existing-pull-request

**Comment by twMat** [comment]
Well, I can tell one method that does not work. To do this:

image

That does lead to a page where you can edit it... and then you click to "Commit changes" and... POOF! Gone in cyberspace! 

I dunno. Too weird system. I'm posting a new PR instead and closing this one.

**Pull request closed without merging**
