### PR TITLE
Show tags with contrast colour in edit template

### LINKED ISSUE #2483: Tags in edit mode should use `contrastcolour` macro
I have a tag and in tag manager I gave it the colour yellow.
Here is how the tag looks like in different areas:
* in the tag manager - color is yellow, text color is black
* on the tiddler in view mode - color is yellow, text color is black
* in the tiddler in edit mode - color is yellow, text color is white!!!

So only when editing a tiddler, the tag is unreadable.

### PR DESCRIPTION
**Pull request by sukima**
Closes #2483

Copy the same pattern from `core/ui/TagTemplate.tid` and use it in `core/ui/EditTemplate/tags.tid`

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @sukima and apologies for the delay in merging.

**Comment by tobibeer** [comment]
@Jermolene, unfortunately, this doesn't fix the wrong color being used in the popup for assigning tags

**Comment by Jermolene** [comment]
Yes @tobibeer I saw the discussion on the mailing list. Would you or @sukima be interested in creating a new pull request with the remaining fix?

**Comment by Jermolene** [comment]
Welcome back @tobibeer by the way!

**Comment by tobibeer** [comment]
Thank you @Jermolene, been busy starting a new job and before that, busy finding one. ;-)

**Pull request merged**
