### PR TITLE
implements #2042 — $tw.utils.uuid() and <<uuid>> macro

### PR DESCRIPTION
**Pull request by tobibeer**
These two components should cater for all uuid generation needs of #2042.

* **$tw.utils.uuid()**
    * generates a unique uuid, fast
* **&lt;&lt;uuid>>**
    * a wikitext macro that implements the above and returns the id

### CODE REVIEW

**Comment by tobibeer** [comment]
Everything else may be implemented as needed later / independently / incrementally.

**Comment by Jermolene** [comment]
Hi @tobibeer a few points:

* I'm not convinced that the core needs to be changed to accommodate people working with GUIDs
* The Stanford JavaScript Crypto Library already implements a [decent random number generator](http://bitwiseshiftleft.github.io/sjcl/doc/symbols/sjcl.prng.html), and we should use it
* A macro isn't a good way to expose the GUID generation since it is (by definition) not a "safe" macro: it is not guaranteed to always generate the same output for the same parameters, regardless of the state of the tiddler store. As I said on the hangout yesterday, "unsafe macros" are useful, but don't belong in the core

**Comment by tobibeer** [comment]
> I'm not convinced that the core needs to be changed to accommodate people working with GUIDs

The ability to create them is the very starting point and core requirement to working with them.

> The Stanford JavaScript Crypto Library already implements a decent random number generator, and we should use it

That is a micro optimization we can always do later. For now, I would not know how to (best) leverage it and I see no urgent need to explore that.

> A macro isn't a good way to expose the GUID generation since it is (by definition) not a "safe" macro: it is not guaranteed to always generate the same output for the same parameters, regardless of the state of the tiddler store. As I said on the hangout yesterday, "unsafe macros" are useful, but don't belong in the core

The point of the macro is precisely that it **never** returns the same output. It creates a unique uuid that can be used in things like action widgets that create tiddlers or set an id as needed if it isn't set already. I don't see anything "unsafe" about that. The created and modified dates also constantly change. The only difference is that we do not have a macro for them.

**Comment by Jermolene** [comment]
> That is a micro optimization we can always do later.

No. This pull request is proposing a change to the core - in fact, to the boot kernel, which is kind of like the core of the core. I'm trying to avoid adding experimental, speculative code to the core. There's nothing I can see about this pull request that can't be accomplished with a plugin.

> The point of the macro is precisely that it never returns the same output.

But, macros are designed to support text transformations that *do* always return the same result for a given set of inputs. It is JS macros that disobey that requirement that create the difficulties with the refresh circuitry that we've discussed. As I said above, it's sometimes useful to work with macros that disobey that rule, but I'd try to avoid such macros in the core. (There's one already, the `<<now>>` macro, which does cause some problems and performance issues).

Here's a simple example: the refresh method of a widget computes the up-to-date values for the attributes of the widget, and only refreshes the widget if the values of any of the attributes change, or if the values of any referenced tiddlers  change. Any widget using the `<<uid>>` macro as an attribute value would therefore get refreshed on every single refresh cycle. That has some negative performance implications, meaning that any page using such a widget will have a lower bound below which the refresh cycle cannot run. 

Another way of looking at it: imagine you've wrapped a block of wikitext with `<$set name="my-uuid" value=<<uid>>>`. When would a new UID be generated?

I think you need more control over exactly when a new UUID is generated than can be afforded by using a macro.

**Comment by tobibeer** [comment]
> I'm trying to avoid adding experimental, speculative code to the core. 

I don't see anything speculative about `Math.random()`, except that it returns a random number than may or may not be as perfect as the one sjcl generates. I have not yet understood sjcl's way to generate random numbers and how I would go about generating one that is as efficient as it is catering for the currently suggested code.

> There's nothing I can see about this pull request that can't be accomplished with a plugin.

Everything can be a plugin, and every plugin can repeat the same code, even mistakes.

> As I said above, it's sometimes useful to work with macros that disobey that rule, but I'd try to avoid such macros in the core. (There's one already, the <<now>> macro, which does cause some problems and performance issues).

I have no feel for the performance impact on any such, mostly buttons.

> Any widget using the `<<uuid>>` macro as an attribute value would therefore get refreshed on every single refresh cycle. That has some negative performance implications, meaning that any page using such a widget will have a lower bound below which the refresh cycle cannot run.

That is true. Perhaps we can devise a way where specific action widgets (those that manipulate fields) are able to parse a new form of attribute syntax that interprets a macro syntax as a function call, i.e. only at the exact moment the action is performed.

So, instead of:

`<$action-setfield $field="uuid" $value=<<uuid>>/>`

We could use something like:

`<$action-setfield $field="uuid" $value=%uuid%/>`

...the avove never refreshing anything as the actual attribute never changes.

> Another way of looking at it: imagine you've wrapped a block of wikitext with `<$set name="my-uuid" value=<<uid>>>`. When would a new UID be generated?

This will and should never work. The only way to properly use a macro evaluated only at execution is through the very widget that performs the execution. As for the set-widget, there is not execution going on, we merely do `a=b`, we never do `c()`... and the `<<uuid>>` macro should be implemented as doing the latter, as performing a function call upon execution only, maybe:

`<$action-setfield $field="uuid" $value=call(uuid, args)/>`

**Comment by Jermolene** [comment]
>> I'm trying to avoid adding experimental, speculative code to the core.
> I don't see anything speculative about Math.random()

The speculative part is the idea that adding a (poor) GUID generation function to the core is a useful first step in exploring how to implement GUIDs. I don't think it is. There may be obstacles to exploring GUIDs, but generating them isn't one of them.

By the way, you may be interested in this article that crossed my path today:

https://medium.com/@betable/tifu-by-using-math-random-f1c308c4fd9d

**Comment by tobibeer** [comment]
Not having the impression that this is going to be accepted, I'm closing this PR ...and will thus (for now / have to) pursue along such a path on my own as needed, as does TiddlyMap.

> There may be obstacles to exploring GUIDs, but generating them isn't one of them.

1. There is no other way to put it: To leverage UUIDs, GUIDs or any other pseudo-unique id format, we need to generate them.
2. I don't plan on pursuing a phd in cryptography, neither are we facing the kind of sophisticated security requirements of a broker software for financial transactions.
    * So, why (re-)invent or implement [node-uuid](https://github.com/broofa/node-uuid/blob/master/uuid.js), which doesn't appear to know of sjcl either?
3. We can improve our implementation later, should there ever be an actual need.

As for the "bad example" code discussed here:

> https://medium.com/@betable/tifu-by-using-math-random-f1c308c4fd9d

...it is **significantly** inferior (meaning: by magnitudes) to the implementation proposed in this PR, not just for the mere 22 random letters (to which all their statistical musings apply!) rather than the 31 here.

We can wait for someone to write a phd over which (CS)PRNGs are best for UUIDs or how to meaningfully implement them and how not to, or we can take off and amend for (some currently quite hypothetical) shortcomings later.

It sounds like, instead of being much concerned with the uuid generating code above, you are actually asking to replace `Math.random()` with something like:

```
$tw.utils.random = function(args) {}
```

...thus facing complex requirements for a harmonized set of arguments — developers thus need to be knowledgeable of — passed down to a bit of tbd code invoking whichever actual implementation is eventually being leveraged / available in the respective environment, be that some `crypto.getRandomValues()`, `sjcl.foodoo()` or eventually `Math.random()`, [compare to this](http://stackoverflow.com/a/19203948).

As things stand, I see no grounds to employ the word "poor" for the [thoughtfully crafted code](http://stackoverflow.com/a/21963136) when it comes to uuid generation as proposed in this PR as I also do not see much of a reason for this project to be discouraged by or wasting all too much consideration on [musings like these](https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2011/august/javascript-cryptography-considered-harmful).

**Comment by Jermolene** [comment]
Sorry for the late reply @tobibeer to be clear, all I'm saying is that there is already a high quality random number generator in the TiddlyWiki core so let's use it. Very simple.

My second point is that while I'm interested in exploring support for GUIDs, I don't think it's worth a core commit that just addresses GUID generation, because that's pretty easy to do in a JS macro.

**Comment by tobibeer** [comment]
I agree. I'll leave it to you to explore the options as needed.

**Pull request closed without merging**
