### PR TITLE
add action-popup widget ...

### PR DESCRIPTION
**Pull request by BurningTreeC**
... that allows triggering popups via keyboard shortcuts (popups need to be positioned using css)

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @BurningTreeC interesting! Is the idea that the action-popup widget would contain the content that is to go into the popup? Does it work properly if used within an action string attribute, rather than inline within the main widget tree?

**Comment by BurningTreeC** [comment]
Hi @Jermolene , the idea is much simpler. It's supposed to trigger a popup tiddler using keyboard shortcuts which gets deleted when clicking somewhere or triggering it again

**Comment by twMat** [comment]
IMO related to #4159

**Comment by BurningTreeC** [comment]
>Does it work properly if used within an action string attribute, rather than inline within the main widget tree?

@Jermolene could you give me an example to understand what you mean?

**Comment by BurningTreeC** [comment]
>Is the idea that the action-popup widget would contain the content that is to go into the popup?

I think the answer is no. There still needs to be a reveal widget somewhere that makes use of the popup state tiddler

**Comment by Jermolene** [comment]
Hi @BurningTreeC is the idea to extract the popup-triggering logic of the button widget to make it a generic action widget? The trouble is that it relies on the action-popup widget rendering a DOM node, does that work if rendering into the fakedom?

**Comment by BurningTreeC** [comment]
@Jermolene, do you have a tip for how to render into the fakedom?

**Comment by BurningTreeC** [comment]
>Hi @BurningTreeC is the idea to extract the popup-triggering logic of the button widget to make it a generic action widget?

Yes that's the idea

**Comment by twMat** [comment]
>extract the popup-triggering logic of the button widget to make it a generic action widget

+1 (sounds like a step that is also in the right direction for #3784 )

**Comment by Jermolene** [comment]
Hi @BurningTreeC apologies for this languishing for so long. I've actually recently needed the same thing in one of my projects. I've slightly extended it to handle passing the popup coordinates. I'll commit it shortly.

**Comment by BurningTreeC** [comment]
Thanks @Jermolene!

**Pull request closed without merging**
