### PR TITLE
Better readability for codemirror linenumbers + CupertinoDark muted-foreground better contrast

### PR DESCRIPTION
**Pull request by BurningTreeC**

### CODE REVIEW

**Comment by BurningTreeC** [comment]
Ping @Jermolene

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Comment by kookma** [comment]
Thank you @BurningTreeC 
I just tried all official palettes with new line number colors, unfortunately some of them have very low contrast. I attached below.
I may suggest to use color from https://codemirror.net/demo/theme.html#ttcn, may be it is better to remove the background color of  line number for active line/current line.

## Solarized light
solarized light

## Spartan day
spartan day

## TWlight
TWlight

## Vanilla
vanilla

## Contrast light
contrast-light

## Rocker
Rocker

## Solar fair
solar fair

## Desert sand
desert sand

## Solarized dark
solarized dark

**Comment by BurningTreeC** [comment]
@kookma, I've already prepared a fix for that in #5181

**Pull request merged**
