### PR TITLE
change plugin list h2 color to improve readability

### PR DESCRIPTION
**Pull request by pmario**
nothing more to say: IMO it gives a much better overview and plugins are much easier to find. 

plugin-new-color

### CODE REVIEW

**Comment by Jermolene** [comment]
Looks great. Only problem is that it's not using the palette mechanism, and so will fail with eg. a green background colour. Not sure that that matters...

One thought is that maybe we should add a `secondary` green colour to the palette, and use it here in the plugin library, and perhaps in other places where we've got similar issues?

**Comment by pmario** [comment]
I'll have a look at the palette.

**Comment by pmario** [comment]
>One thought is that maybe we should add a secondary green colour to the palette, and use it here in the plugin library, and perhaps in other places where we've got similar issues?

I did analyse the built in palettes. ... They have a lot of repetition going on. The default theme has about 23 different shades of grey. And about 20 other colors, where several are also similar with different shades. 

So I'd like to add some base colours similar to TWclassic. 
Foreground, Background, (1 color)
Primary, Secondary, Tertiary, Error (each has 4 shades)
ButtonSucess, ButtonError, ButtonWarning, ButtonPrimary, ButtonSecondary (1 color)

I would define: PrimaryPale, PrimaryLight, -Mid and -Dark ... plus a new `<<color>>` macro that lets me say: 

`<<color PrimaryPale darker>>` or `<<color PrimaryMid lighter>>` and so on. ... So instead of 4 different shades we would have 12 per element. 

Background, Foreground have no shades

Button have a colour and 2 shades eg:  `<<color ButtonSccess lighter / darker>>` .

So I would want to define maximum 23 colours and have enough shades, that I can assign to the different existing fields of the palette. 

@Jermolene @tobibeer ... what do you think?

**Comment by Jermolene** [comment]
Hi @pmario 

Generally, that sounds like a good approach. Some questions:

> `<<color PrimaryPale darker>>`

What exactly would this new macro do?

> Primary, Secondary, Tertiary, Error (each has 4 shades)

Colours in TW5 are named lower case with dashes (eg `sidebar-background`). Are you proposing that we have a convention to use camelcase for the "base" colours?

Overall, I'd just be worried that this might be quite a lot of work; we'd want to make these changes across all the core palettes, for example.

**Comment by pmario** [comment]
>What exactly would this new macro do?

Something similar to less: darken, but  much easier: http://lesscss.org/functions/#color-operations

>Colours in TW5 are named lower case with dashes (eg sidebar-background). Are you proposing that we have a convention to use camelcase for the "base" colours?

no. I just used them that way, because TWc did it. primary-pale is just fine.

> Overall, I'd just be worried that this might be quite a lot of work; we'd want to make these changes across all the core palettes, for example.

yea, but we have to start somewhere .... and for my taste, touching100++ settings for a pallete is way too much work.

**Comment by pmario** [comment]
With TWc 

Primary ... was the base color for many things
Secondary ... was for tables and `@@` ... wikitext specials
Tertiary ... tabs in the sidebar
Error ..: :)

see: http://web.archive.org/web/20161205112713/http://pmario.tiddlyspace.com/#ViewColorPalette

It worked quite well. ... at least for me.

**Comment by twMat** [comment]
The OP is definitely more readable but why introduce a new color (the green). We should be careful with colors. Currently *all* text in a plugin "box" is blue, but why not just have the text that is not the name simply be black? (+ make the version text big enough to actually read)

**Comment by pmario** [comment]
The green color was a suggestion. We can make it black. It just needs to be different than blue.

**Comment by BurningTreeC** [comment]
... The `Get more plugins` button could also get the `primary` color

**Comment by pmario** [comment]
code is too old to be tested when checked out. Close in favour of a new pr

**Pull request closed without merging**
