### PR TITLE
Fix #4673 - Adding tags in $:/Manager does not work

### LINKED ISSUE #4673: [BUG]  Adding a tag from the dropdown in the manager does not work.
**Describe the bug**

Adding a tag in the manager does not work. Neither typing one or selecting one from the dropdown.

Tested with a fresh TiddlyWiki, same issue.

**To Reproduce**

1. Go to $:/Manager.
1. Click on a listed tiddler.
1. Tags section -> Add a tag.

**Expected behavior**

A new tag should be added.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox, Chrome
 - Version: 5.1.22

### PR DESCRIPTION
**Pull request by BurningTreeC**
this PR fixes #4673

because of the last changes of the tag-picker macro the tag-picker in the $:/Manager didn't work anymore because it still relied on the `actions` parameter which has been removed. The `actions` parameter is now back in again, and, as a goodie, adding tags with the <kbd>enter</kbd> key also works which didn't work before

### CODE REVIEW

**Comment by saqimtiaz** [comment]
Thank you @BurningTreeC

**Comment by BurningTreeC** [comment]
This PR also adds 1 small `div` so that the tags-dropdown now shows below the input field, not always at the left as before

**Comment by Jermolene** [comment]
Hi @BurningTreeC are you able to resolve the conflicts on this?

**Comment by BurningTreeC** [comment]
> Hi @BurningTreeC are you able to resolve the conflicts on this?

Resolved @Jermolene

**Pull request merged**
