### PR TITLE
Serving via a mini web server

### PR DESCRIPTION
**Pull request by hffqyd**
Saving via a mini web server, and uploading files/images for use like [img[images_folder/example.jpg]].

### CODE REVIEW

**Comment by Jermolene** [comment]
Many thanks @hffqyd for your contribution! With apologies for the bureaucracy, please could you prepare a separate PR to the 'tiddlywiki-com' branch with your signature for the Contributor License Agreement (see [contributing.md](https://github.com/Jermolene/TiddlyWiki5/blob/master/contributing.md)).

**Comment by pmario** [comment]
Is it possible to upload any file-type with this server? If yes, this is an extremely dangerous thing. 

I'm not a python guy, but I can't see any code, that filters file types. 
I'm also not sure, if it is possible to access files outside the initial serving directory. 

I do have security concerns.

**Comment by hffqyd** [comment]
> Is it possible to upload any file-type with this server?

Yes ..., if uploaded executable files might cause damage, I'll consider filter out such files, if it's a big concern.

> if it is possible to access files outside the initial serving directory

No, as least in my tests.

**Comment by Jermolene** [comment]
> Is it possible to upload any file-type with this server? If yes, this is an extremely dangerous thing.

Whether is dangerous to upload arbitrary file types depends on the context and threat models being considered. I think this concern is better raised separately, it's not really a blocker to merging this PR.

> I'm not a python guy, but I can't see any code, that filters file types. I'm also not sure, if it is possible to access files outside the initial serving directory.
> 
> I do have security concerns.

I also don't have enough Python to verify the operation of @hffqyd's code. But I think this is more of a policy issue: we can't do a security review of every third party saver/syncer that we list. I'm not sure the best way to address the concerns you've raised:

* Perhaps we should emphasise that third party savers have no warranty, and haven't been reviewed from a security perspective. But that seems overly broad: some third savers are surely safe to use, and we shouldn't scare users off
* Perhaps we should introduce a security checklist for third party savers as a way to encourage developers to consider the steps that they have taken. That's a lot of work, and might well just serve to scare users

As ever, security can really only be addressed by educating users. That's not entirely practical, so perhaps the best we can do is to clearly signpost the solutions that are generally recommended.

**Pull request closed without merging**
