### PR TITLE
Fix type and editor fields autofocus: Test in factory.js if the activeElement should keep focus

### PR DESCRIPTION
**Pull request by BurningTreeC**
This PR tests in factory.js if there's the activeElement with the class `tc-keep-focus`
If so, the editor doesn't set autofocus to itself

### CODE REVIEW

**Comment by BurningTreeC** [comment]
I don't know why Vercel doesn't deploy the Preview...

**Comment by Jermolene** [comment]
Hi @BurningTreeC the Vercel preview is failing with an error:

image

**Comment by BurningTreeC** [comment]
Ah OK, I'll fix this 👍

**Comment by Jermolene** [comment]
Hi @BurningTreeC the error from the last run was this:

image

**Pull request closed without merging**
