### PR TITLE
Update fields.tid

### PR DESCRIPTION
**Pull request by Infurnoape**
Add a new field drop down

### CODE REVIEW

**Comment by Infurnoape** [comment]
Playing around with it led me to discover a strange anomaly when clicking the field name and then the type field which blinks but doesn't get rid of the field name drop down and then clicking the name field again it seems to kill the focus-popup until you click anywhere outside these fields and then it resets.

**Comment by Jermolene** [comment]
Hi @Infurnoape great stuff, I'll experiment with it and get back to you. I may leave it until after 5.1.9, but will do my best to get it in.

**Comment by Infurnoape** [comment]
Cool it looks better than before. I was hoping I could get my name @infurnoape in with contributors. 




Sent from my Samsung Epic™ 4G TouchJeremy Ruston <notifications@github.com> wrote:Merged #1849.

**Comment by Jermolene** [comment]
Apologies, @Infurnoape, you're in the 5.1.9 contributor list now.

**Comment by felixhayashi** [comment]
This is a great feature! It would be very nice if the fields are filtered when a field name is entered, just like it is the case with tags.

**Pull request merged**
