### PR TITLE
Rename default layout to "Standard Layout"

### PR DESCRIPTION
**Pull request by linonetwo**
https://talk.tiddlywiki.org/t/what-is-the-name-of-default-layout-is-it-story-river/9296/2

Only change filename and translation, and `$:/core/images/default-layout` which is not yet released.

`$:/core/ui/PageTemplate` is untouched, it will influence too many things. This could be a todo for large version bump.

### CODE REVIEW

**Comment by linonetwo** [comment]
@BramChen Note that `~Tiddlywiki` is translated to `太微` which is simillar to pronouncation in Chinese. I may apply this change to other translations in the future. But I'm not sure if this pronouncation also apply to Hong Kong Cantonese and Taiwan Hokkien, so I'm not gonna modify it. I will only modify zh-Hans in this case.

**Comment by saqimtiaz** [comment]
@linonetwo thank you, I agree that renaming the "default layout" to "standard layout" would be helpful. However, renaming the images is problematic as it can break user code where the old tiddler titles are used. Could you please modify the PR to only change the layout name?

**Comment by linonetwo** [comment]
@saqimtiaz That image was added during this prerelase, so won't break anything other than my plugins (I push the https://github.com/Jermolene/TiddlyWiki5/pull/8020 so I'm using it immediately), and I will update my plugins.

**Comment by saqimtiaz** [comment]
Thank you @linonetwo. 

@Jermolene this looks good to be merged.

**Comment by Jermolene** [comment]
Great thanks @linonetwo @saqimtiaz

**Pull request merged**
