### PR TITLE
Proposal for new GettingStarted tiddler for empty.html

### PR DESCRIPTION
**Pull request by pmario**
also see: [Proposal for a new GettingStarted page, for empty.html](https://groups.google.com/forum/#!topic/tiddlywiki/H6Gmby9gvYg)

and: [TiddlyWiki on HackADay.com](https://groups.google.com/forum/#!topic/tiddlywiki/MKVwkEmCimQ)

The discussion about TiddlyWiki on HackADay.com once more raised the question about an easier start.

I did create a new GettingStarted tiddler, that also contains a "self explaining" "startup app", that should get new users going.

It contains 5 new elements.

 - Show Home button
 - Show Journal button
 - Create Table of Contents
 - Create a basic ToDo app
 - Lead the new user to the ControlPanel - Theme Tweaks .. to adjust the story width.

All of this can be created by the user in 3 minutes.

I did a short video, so you can see how it should work.
see: https://youtu.be/rhYgfbs_rCA

I did forget 1 thing in the video. ... about "Change the Layout", which should lead a new user to the Theme Tweaks, that allows, to change the story river width.

### CODE REVIEW

**Comment by pmario** [comment]
GettingStarted-Proposal

**Comment by pmario** [comment]
slightly related https://github.com/Jermolene/TiddlyWiki5/issues/1344

**Comment by pmario** [comment]
Once the user is finished it looks like this: 

GettingStarted-Proposal-expanded

**Comment by pmario** [comment]
@Jermolene ... It would be possible to add a list widget like this at the end.

```
<$list filter="[tag[GettingStarted]!has[draft.of]]"><$transclude mode="block"></$list>
```

Which would allow plugin authors to add more content, without the need to modify the core GettingStarted

**Comment by bimlas** [comment]
I fully support this idea! Whatever note-taking software I encountered, each had a quick settings, wizzard, or at least one example document to help you get started. Even browsers have such a "Welcome" page, although they really do not require much configuration! I think this is a hotspot to help novices make the wiki easy to use.

**Comment by Jermolene** [comment]
I support the idea of improving the user experience when opening an empty wiki, but I have some reservations about the details of the approach here:

* The reliance on textual descriptions is a problem for beginners. How would someone new to TiddlyWiki know the meaning of terms like "Home Button", "Table of Contents", "Story Layout"?
* The choice of UI items to elevate to the GettingStarted tiddler seems arbitrary: why these particular customisations?
* Generally, we're missing the opportunity to teach new users how to accomplish things, and instead we're giving them a small and inscrutable choice of customisations with a non-standard UI

I think we need to be more ambitious: for example, a wizard that guides the user through the initial setup, and teaches them the basics of the TiddlyWiki user interface. It would have to be a plugin, of course, with some mechanism for unloading it when it is no longer useful.

**Comment by bimlas** [comment]
I don't think everyone wants to use Tiddly at a higher level. Some people wants to being able to store their notes in a single HTML, but they don't know what a macro is and generally don't know much about IT at all. For them, there would be no need for a tutorial that writes about the ToC macro, fields, and other tech terms. I understand that this way they are not getting familiar with the main strengths of TiddlyWiki, but those who are open to hacking will recognize the underlying mechanisms, or at least start looking at how things works.

**Comment by Jermolene** [comment]
Hi @bimlas apologies for the confusion. I'm not suggesting that the GettingStarted wizard should teach people the internals of TiddlyWiki. I'm trying to say that it would be more useful to show people how to add page control buttons in general than to give them the magic capability of adding one particular button. So I think it would be better to embed the list we have in the "Tools" sidebar and invite people to choose their own buttons.

**Comment by bimlas** [comment]
Sorry, I misunderstood you.

> I think we need to be more ambitious: for example, a wizard that guides the user through the initial setup, and teaches them the basics of the TiddlyWiki user interface. 

It's almost done: click on Start Tutorial in Maarfapad demo: https://cdn.rawgit.com/abesamma/TW5-editions/78846468/empty.html

I think the automatic creation of ToC should be included, because this tutorial can discourage the really beginners:
https://tiddlywiki.com/#Adding%20a%20table%20of%20contents%20to%20the%20sidebar

**Comment by Jermolene** [comment]
> It's almost done: click on Start Tutorial in Maarfapad demo: https://cdn.rawgit.com/abesamma/TW5-editions/78846468/empty.html

That's great, but it's not what I meant either. I'm suggesting that magic checkboxes (such as the one for switching on the "home button") aren't very helpful because (a) there's no obvious way to choose which user interface features warrant one of these magic checkboxes and (b) we miss the opportunity to teach the user anything about how TiddlyWiki works. The specific remedy I suggested was that instead of having a magic checkbox for the home button it would be better to embed the list of checkboxes from the "Tools" sidebar tab (or a subset of it). That way the user has a chance of subsequently recognising the same list in the control panel or the sidebar tab, and thus has a way of understanding what they did.

**Comment by pmario** [comment]
@Jeremy ... please watch the video. https://youtu.be/rhYgfbs_rCA It's only 6 minutes long. 

I did explain, why the structure is as it is. I do link users to the Tools tab, where the see other possibilities. 

The Home button is used, because for newbie users it's intimidating if they have an empty story river if they close all tiddlers. Home gets them started again. 

The Journal button is chosen, because we have discussions in the GG all the times, where activating Journals causes problems. If the Journal button is activated there is additional info about the ControlPanel : Info : Basics tab which leads new users to the CP

The Table of Content is a pain point since years. There isn't a month without a discussion, where a new user want's to use TW and saw the nice TOC at tiddlywiki.com but empty doesn't have it. ... 

ToDo lists are the HelloWorld of wikis. IMO empty should contain the most basic version, that is good enough to get users started. Once they need more, there are plenty of possibilities. 

The last point guides the user to the "story width" setting which is the same PITA as the TOC.

**Comment by jeremy** [comment]
@pmario Wrong @jeremy, FYI. ✌🏼

**Comment by pmario** [comment]
@Jermolene Here is the code to play with at tiddlywiki.com 

[GettingStarted(1).zip](https://github.com/Jermolene/TiddlyWiki5/files/4224914/GettingStarted.1.zip)

**Comment by pmario** [comment]
@Jermolene I did edit this post https://github.com/Jermolene/TiddlyWiki5/pull/4460#issuecomment-587125323 since I used the wrong name

**Comment by bimlas** [comment]
@pmario 

If you already refer to ControlPanel settings in several places, I think the "New Here" option could also describe how to place additional toolbar buttons.

**Comment by Jermolene** [comment]
Hi @pmario 

> please watch the video

Sorry, I never watch videos (apart from entertainment), I find them painfully slow and inefficient as a means of exchanging information. GitHub tickets and PRs should be self-contained, and I need to be able to understand them without following links to external rationales buried in long Google Groups threads or in videos.

I can see that the items picked out for inclusion in the Getting Started tiddler are based on feedback, but I think it's a rather crude way of responding to that feedback. We give the user a big block of information that is very complex to understand, and it's not really at the right time. If the user is a beginner then they wouldn't yet recognise that they needed those specific items. It all feels like checking into a hotel and immediately being handed detailed instructions for opening the blinds, before we've even seen the room. It just makes the guest think there's something wrong with the blinds.

**Comment by pmario** [comment]
@Jermolene at https://github.com/Jermolene/TiddlyWiki5/pull/4460#issuecomment-586996695 you wrote: 

> - The reliance on textual descriptions is a problem for beginners. How would someone new to TiddlyWiki know the meaning of terms like "Home Button", "Table of Contents", "Story Layout"?

I made an "interactive" GettingStarted accompanied by a 6 minute video. The video can be shortened. 

You wrote text isn't good enough. It seems interactive tiddlers (as proposed in the PR) aren't good enough and the 6 minute video that demonstrates the use of the new interactive GettingStarted isn't good enough. 

But I think, it reflects the needs of newbie users. 

At: https://hackaday.com/2020/02/14/it-aint-over-til-the-paperwork-is-done-test-driving-tiddlywiki/
TW is introduced. At the end is a 15min intro video, which is part of a [series of intro videos](https://www.youtube.com/watch?list=PLzZCajspPU_UjFn0uy-J9URz0LP4zhxRK&time_continue=2&v=ZMGpAW0z_Bo&feature=emb_logo), that try to get new users up to speed. 

The first 3 videos need about 45 minutes to show the user how they can configure empty.html, to make it usable ... for beginners. 

**The same thing and even more can be done with the proposed GettingStarted in about 5 minutes.** 

I think that is a big improvement. Most users are not interested, how it works in detail. They want it to be there and it should work out of the box. 

-------------

Dave found [1] a podcast which starts with: "Alex has been installing wikis for 2 weeks. ... " at second 5

at: https://pca.st/k2ru8w3h#t=1184 he mentions TW as a "goto option" with some "buts" (not sure if this is proper English :)

At: https://pca.st/k2ru8w3h#t=1296 there is some info about the pain points. about 2 minutes from the link. 

It's always the same: Some jokes about the name and the road to GettingStarted is bumpy and there is _no_ TOC out of the box. 

The PR tries to improve this. .. but without merging it we can't test is with a broader audience. 

I'll e-mail the guy and ask, if he can test it. 

[1] Dave's GG thread is at: https://groups.google.com/forum/#!searchin/tiddlywiki/podcast%7Csort:date/tiddlywiki/7YcKmdAfuZY/eMkMuvRJBwAJ

-------------

Joe Armstrong talks about his [Eureka moment in 2018 with TiddlyWiki](https://joearms.github.io/#2019-01-08%20My%20Eureka%20Moment%20with%20the%20TiddlyWiki:%5B%5B2019-01-08%20My%20Eureka%20Moment%20with%20the%20TiddlyWiki%5D%5D%20%5B%5B2018-12-26%20Fun%20with%20the%20TiddlyWiki%5D%5D%20%5B%5B2019-02-26%20Setting%20up%20a%20TiddlyWiki%20website%20on%20GitHub%20Pages%5D%5D). It's all about ToDo's and goes on using TW tags creating a triage system, which took him 45 minutes to build. 

BUT 45 after how much time spending in the GG. His first posts with TW5 where in Feb. 2018 after a 7 year break from 2011. 

[search term used in GG-dev](https://groups.google.com/forum/#!searchin/tiddlywikidev/joearms%7Csort:date)

I think a basic ToDo app is one of the best entry points for digging deeper into TW.

**Comment by pmario** [comment]
Closing this one. Have an idea for a better approach.

**Pull request closed without merging**
