### PR TITLE
add "equals" filter that returns [] if not equal

### PR DESCRIPTION
**Pull request by BurningTreeC**

### CODE REVIEW

**Comment by BurningTreeC** [comment]
... oh, I noticed now that this needs additional handling for `!equals[value]`

**Comment by BurningTreeC** [comment]
I reopened this for discussion

**Comment by twMat** [comment]
Side note: I believe `regexp[^...$]` achieves "equals". I do think we need a dedicated "equals" but if the regexp does this then just maybe maybe this simplifies the implementation for it. Just sayin'.

**Comment by BurningTreeC** [comment]
@twMat I think you're right and we can probably close this

**Comment by twMat** [comment]
So no mistake; I do think a dedicated "equals" is of value. Regexp is a bit scary and not as obvious.

**Comment by BurningTreeC** [comment]
We have a match filter now

**Pull request closed without merging**
