### PR TITLE
Make editTiddler in sidebarsegments/search available as variable

### PR DESCRIPTION
**Pull request by BurningTreeC**

### CODE REVIEW

**Comment by saqimtiaz** [comment]
@BurningTreeC is the idea that custom search solutions can have access to this variable?

**Comment by BurningTreeC** [comment]
> @BurningTreeC is the idea that custom search solutions can have access to this variable?

Yes, I'm planning to extend the documentation about custom search results

**Comment by saqimtiaz** [comment]
@BurningTreeC excellent idea

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Pull request merged**
