### PR TITLE
Bugfix/3117 inconsistent each

### PR DESCRIPTION
**Pull request by Skeeve**
Following Jeremy's proposal of introducing the suffix "value" to "each"

### CODE REVIEW

**Comment by pmario** [comment]
So, this is the backwards compatible version now?

**Comment by Skeeve** [comment]
Yes, it is. It should be a bit faster for longer lists though.

Will you test?

**Comment by pmario** [comment]
I will. But I'll have to do "family business" for the next 3 days! ... But I'll have a laptop with me ;)

**Comment by Jermolene** [comment]
Thanks @Skeeve looks good

**Pull request merged**
