### PR TITLE
bug: fix bug where input-tag is empty

### PR DESCRIPTION
**Pull request by BurningTreeC**
Bildschirmfoto vom 2019-07-10 10-38-57

### CODE REVIEW

**Comment by morosanuae** [comment]
@BurningTreeC thanks. I was so annoyed by this bug.

**Comment by BurningTreeC** [comment]
ping for 5.1.20

**Comment by BurningTreeC** [comment]
This is just a simple bug-fix

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Pull request merged**
