### PR TITLE
Motovun Jack.svg shape now as close as possible

### PR DESCRIPTION
**Pull request by pmario**
Motovun Jack.svg shape now as close as possible

### CODE REVIEW

**Comment by pmario** [comment]
jack

**Comment by Jermolene** [comment]
Oops, I think I may have just commented on the wrong pull request. Is this the latest and greatest?

**Comment by pmario** [comment]
The other pull request showed a merge conflict. This one should be fine.

**Comment by Jermolene** [comment]
OK, given that I can see visual differences I think we should explore using the other tool I mentioned. I've committed a 50% reduction in `$:/core/icon`, with no differences I can see.

**Comment by Jermolene** [comment]
Hi @pmario do you think this is still an issue?

**Comment by pmario** [comment]
I still think, the original (http://tiddlywiki.com/#Motovun%20Jack.svg) svg size is to big. IMO it contains redundant points and the `viewBox` should be `0 0 x y`. 

With the last commit to this PR, I did use https://jakearchibald.github.io/svgomg/, that you mentioned. It reduces the svg size and I manually removed the connection of the hind legs. The result can be seen here: https://github.com/pmario/TiddlyWiki5/blob/18bf0d869ddcf214737fe498b90bf7e2ea2707ec/editions/tw5.com/tiddlers/images/Motovun%20Jack.svg  The above gif image is obsolete.

For me the hind legs should not be connected in the svg path. It looks ugly if the image is big, with high zoom levels.  ... but it seems I've been unable to create a version, that works for you, so the PR is obsolete and you are free to close it.

**Pull request closed without merging**
