### PR TITLE
Fix Date format for date display date in "recent" tabs

### PR DESCRIPTION
**Pull request by dedioste**
Moved from GG MM AAAA to DD MM YYYY to ensure that the date is correctly displayed in the "Recent" tab

### CODE REVIEW

**Comment by tobibeer** [comment]
Hi @dedioste, why'd you close the issue?

**Comment by dedioste** [comment]
Actually I read the section on tiddlywiki.com and saw that the process for
submitting translations is different.
I'd prepare a file that way and submit it.

If you tell me that a pull request is OK, I'll reopen the issue






Il 18 gen 2017 12:55 PM, "Tobias Beer" <notifications@github.com> ha
scritto:

Hi @dedioste <https://github.com/dedioste>, why'd you close the issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Jermolene/TiddlyWiki5/pull/2716#issuecomment-273456914>,
or mute the thread

**Comment by Jermolene** [comment]
Hi @dedioste we're very happy to accept translation improvements as PRs. The docs emphasise the non-GitHub workflow because that's what most of our translators are more comfortable with.

**Comment by dedioste** [comment]
PR made.
Had to create another one as I already deleted this branch.

**Pull request closed without merging**
