### PR TITLE
revert preventing dragging within textarea

### PR DESCRIPTION
**Pull request by BurningTreeC**
this reverts #3070 which prevents dragging text from one codemirror instance to another

there are other ways to solve the issue I tried to solve with this, so we should revert this to the standard behavior

... deletes `t.preventDefault&&t.preventDefault(),` at character 138562

### CODE REVIEW

**Comment by pmario** [comment]
@BurningTreeC ... Did you change the default codemirror.js file? .. If yes, that would be a general issue.

Because if I would have updated the CM library to a new version I would use the default files, without any mods ... So the next update done by me would fail. ...

**Comment by BurningTreeC** [comment]
@pmario Look at #3070 and you see what i did. It was a PR before the new modularized Plugin. This PR reverts it

**Comment by BurningTreeC** [comment]
> So the next update done by me would fail. ...

It wouldn't fail

**Comment by Jermolene** [comment]
Thanks @BurningTreeC @pmario

**Comment by BurningTreeC** [comment]
Thank you!

**Comment by pmario** [comment]
So now the codemirror.js is the same again as downloaded from the codemirror.net homepage. right?

**Pull request merged**
