### PR TITLE
All colour codes use 6 digits now

### PR DESCRIPTION
**Pull request by pmario**
While working on the $:/PaletteManager I did stumble upon this problem again. 

Does not work

grafik

Would work ... I know that this PR is only a partial fix, but it is a baby step in the right direction and the PR already changes 16 files. So the chance to get it merged with 16 more is close to 0. 

grafik

<details><summary> Initial text for this PR </summary>
This PR is important for consistency reasons, to make it possible to create CSS settings as follows. 

To test the PR copy the following content to tiddlywiki.com and to your localhost, to see the difference!

```
<style>
.test-3 {
  background: <<colour "tag-background">>4;  /* this is the inconsistency that should be fixed */
}

.test-6 {
  background: <<colour "tag-background">>40;  /* it should always be possible like this */
}

.test-x {
  background: #eecc6640;
}

.test-full {
  background: #eecc66;
}
</style>

<div class="test-3">test text - works but is inconsistent</div>

<div class="test-6">test text - background color ''fails'' atm but should work</div>

<div class="test-x">test text - transparant background</div>

<div class="test-full">test text - full background</div>
```
</details>

### CODE REVIEW

**Comment by pmario** [comment]
I'll fix the docs in the TW-docs branch if this will be merged. see: https://tiddlywiki.com/#ColourPalettes

OR

@Jermolene I can add the docs here if you want

**Comment by kookma** [comment]
@pmario - thank you for this. It is good to add such requirement in Tiddlywiki documentation. I mean any new palettes should follow the six digits hex color code.

By the way I think if the palette itself needs a eight digits color code, then a call like `<<colour "tag-background">>40;` can be used.

One other recommendation is to define some main colors in a palette and derive all other colors from them. Right now there are too many colors in a palette.

**Comment by pmario** [comment]
>... One other recommendation is to define some main colors in a palette and derive all other colors from them. Right now there are too many colors in a palette.

I think you are right. ... TW classic has been much simpler in this regard. ... (good ol' times ;)

**Comment by pmario** [comment]
I would like to have something like this: 

```
<<colour "tag-background">><<lighter>>;
<<colour "tag-background">><<darker>>;

<<colour "tag-color">>;
<<colour-hover "tag-color">>;
```

`<<colour-hover>>` would use something like [contrastcolour macro](https://tiddlywiki.com/#%24%3A%2Fcore%2Fmodules%2Fmacros%2Fcontrastcolour.js) if needed. .. So if the "foreground/background" contrast is too low, the "colour" should be "inverse" or something like this

But this would be a completely different PR ;)

**Comment by saqimtiaz** [comment]
This and related issues like using alpha channel values in colours was the motivation behind #5236 

Recommend reading the comments linked in the first post of that issue.

**Comment by pmario** [comment]
@saqimtiaz ... Yea, For 1 of my plugins I wanted to use a predefined "palette colour". I couldn't find one, but I found one that was pretty close and also works for the purpose. So no weird naming confusions, but I wanted it to be "lighther". ... 

I did create a $:/StyleSheet tiddler and used `background: <<xxx>>50` ... but it didn't work. It needed to be `<<xxx>>5` ... BUT the problem now is, that different palettes may have different number of digits. 

That's the reason for this PR

**Comment by Jermolene** [comment]
Hi @pmario it's a nice idea but sadly I don't think we can restrict the result of the `<<colour>>` macro to be a simple CSS hex colour. For example, one of my projects uses [wide colours](https://css-tricks.com/wide-gamut-color-in-css-with-display-p3/) and thus has colour definitions like:

```
background-color: color(display-p3 1 1 0);
```

Nor, of course, can we enforce that user generated palettes use any particular format.

**Comment by pmario** [comment]
@Jermolene I didn't try to restrict the result of the colour-macro. This PR tries to make the existing palettes, that are shipped with the core consistent.

So that the macro can be used in a consistent way.  ... That's all. 

If we need to adjust the macros for other color formats IMO it would be a separated PR

**Comment by pmario** [comment]
But you are right, I should probably change all "core settings" to CSS hex colours for consistency reasons. ... 

Our users most of the time use the mechanism, the core suggests. ... 

If not, it won't be compatible as long as someone makes it compatible. ... BUT at least the core is consistent!

**Comment by pmario** [comment]
I did update [the OP](https://github.com/Jermolene/TiddlyWiki5/pull/5459#issue-798462426)

--------

@Jermolene  wrote

>Hi @pmario it's a nice idea but sadly I don't think we can restrict the result of the <<colour>> macro to be a simple CSS hex colour. For example, one of my projects uses [wide colours](https://css-tricks.com/wide-gamut-color-in-css-with-display-p3/) and thus has colour definitions like:
>
>`background-color: color(display-p3 1 1 0);`
>
>Nor, of course, can we enforce that user generated palettes use any particular format.

I don't want to restrict anybody from using any CSS colour settings they want to use. 

This PR should be 1 little step towards a broader fix. If this PR would be out of the way we could build on it and implement more possibilities.

**Comment by pmario** [comment]
The new palette-manager code can handle this edge case. So close

**Pull request closed without merging**
