### PR TITLE
FIX? `currentVariable` -> `currentTiddler`

### PR DESCRIPTION
**Pull request by n9**
Not sure about this. Maybe I just do not understand the text.

### CODE REVIEW

**Comment by morosanuae** [comment]
Hello,
your correction is correct :) but a pull request with a fix already is on the waiting list. See #2859. You forgot to search first ;)

**Comment by n9** [comment]
I thought that such corrections get merged immediately:D I was not expecting that a long lasting code review will be performed:)

**Comment by morosanuae** [comment]
I agree, but this is the sad reality!

**Comment by n9** [comment]
Ok, next time, I will search first whether a typo is not already fixed in a pull request.

**Pull request closed without merging**
