### PR TITLE
Sign the CLA.

### PR DESCRIPTION
**Pull request by ndarilek**
**Is your PR related to a problem? Please describe.**

**Describe the solution you are proposing**
A clear and concise description of the changes you are proposing. Include images to show visual changes.

**Describe alternatives you've considered**

**Additional context**

If you link to discussions elsewhere then please copy and paste the important text, and don't expect readers to scan the entire discussion to find the relevant part.

## Checklist before requesting a review

- [ ] Illustrate any visual changes (however minor) with before/after screenshots
- [ ] Self-review of code
- [ ] Documentation updates (for user-visible changes)
- [ ] Tests (for core code changes)
- [ ] Complies with coding style guidelines (for JavaScript code)

### CODE REVIEW

**Comment by Jermolene** [comment]
Thank you @ndarilek, and welcome to the project.

Apologies for the lack of clarity in the instructions, but CLA signatures should target the tiddlywiki-com branch, not the master branch.

**Comment by pmario** [comment]
@Jermolene ... I think the CLA is related to a discussion at Talk:  https://talk.tiddlywiki.org/t/how-do-i-get-started-as-a-new-contributor/3688 ...

I think the changes will touch js-code. So IMO master should work fine.

**Comment by pmario** [comment]
>Not sure what makes changes require master vs. tiddlywiki-com, but yes, I've already tweaked JS code to allow for setting roles and aria-checked on buttons.

The `tiddlywiki-com` branch is used for documentation contributions, which are published immediately. So they can be updated much faster as js-code changes. 

Code changes are published with a new version and should target a "feature-branch". ... eg:

```
git checkout master
git pull 
git checkout -b my-new-features
git add .
git commit -m "some description"
git push
```

In this case your commits are part of a separated "feature" branch, which makes it easier to review and merge. 

So you should always commit to a new feature-branch in **your** repo, that is pulled from "jermolene/master"

**Comment by pmario** [comment]
>In any case, I've got a handful of useful changes ready to PR once my
CLA signature is merged.

I think, you don't have to wait. If you create a PR, we can already start to review the new stuff, while waiting for the CLA ;)

**Comment by rmunn** [comment]
> Ugh, OK. Is it possible to change the base branch? The GitHub docs seem to indicate this should be possible with an edit button near the title, but all I'm finding is a way to edit the title and not the branch.

I just did it recently on a PR in one of my repos (where I have repo admin rights); the edit button let me edit the title *and* turned the base branch into a dropdown menu. I haven't tried it on repos where I have fewer permissions; it's possible you have to have some level of access permissions to the repo in order to change the base branch.

Otherwise, you just have to close the PR and open a new one. :cry:

**Comment by Jermolene** [comment]
> I just did it recently on a PR in one of my repos (where I have repo admin rights); the edit button let me edit the title _and_ turned the base branch into a dropdown menu. I haven't tried it on repos where I have fewer permissions; it's possible you have to have some level of access permissions to the repo in order to change the base branch.

I get the "edit" button for PRs to this repo, but when I've tried it in the past it hasn't worked as expected.

I'll try it now with this PR so we can see.

**Comment by Jermolene** [comment]
> I'll try it now with this PR so we can see.

Yup, it didn't work; now we've got 211 changed files. Sorry @ndarilek I'm afraid I'm not much of a Git expert...

**Comment by pmario** [comment]
@ndarilek .. It seems this PR has gone "haywire" now. .. I think it's best to close it and create a new one, with a feature-branch on your side and target: tiddlywiki-com on this side.

**Comment by Jermolene** [comment]
Hi @ndarilek @pmario I've reverted this PR back to the "master" branch, which has made it return to the original single commit. But I'm afraid it confirms that the available means to rebase the PR don't work in this situation. So I'd be very grateful if you could prepare a new PR @ndarilek – thank you!

**Comment by ndarilek** [comment]
OK, thanks, will get to it soon. The upstairs neighbor's shower started leaking into my living room so it may be a few days.

**Comment by Jermolene** [comment]
> OK, thanks, will get to it soon. The upstairs neighbor's shower started leaking into my living room so it may be a few days.

Thanks @ndarilek much appreciated, and good luck with the crisis!

**Comment by rmunn** [comment]
For future reference, the reason for the massive number of changed files is because when you made the commit adding your name to the CLA list, you had made that commit off of the `master` branch. So when you tried to change the base branch, it was then trying to merge "master branch plus this one commit" into the tiddlywiki-com branch, which meant all the recent activity on the master branch was being included in the proposed merge.

I believe the way to do this, if you really wanted to keep this PR open (which isn't really necessary), would be to:

1. Rebase your commit onto `tiddlywiki-com` instead of `master`
2. Do a `git push --force` so that your branch gets updated (this will make the PR look like it's got hundreds of commits)
3. Change the target branch of the PR to `tiddlywiki-com`, which will make the PR have one single commit again

**Except** that step 2 is only a good idea if you created a branch in your repo before pushing the commit, i.e. if the PR says "wants to merge 1 commit into Jermolene:master from your-username:some-branch-name". And here, I see "ndarilek:master". It's not a good idea to rebase your master branch somewhere else and then do a `git push --force` operation; that's just asking for pain down the road. So in this particular case, closing the PR and opening a new one is definitely the right thing to do.

Finally, a word of advice for anyone who wants to become more of a Git expert. Go to https://learngitbranching.js.org/ and play around with their tutorials and examples for a while. It's the best Git learning environment I've ever seen; it certainly made me a lot more comfortable with Git once I had worked through that tutorial and gained a good understanding of how Git branches work. Highly recommended.

**Comment by ndarilek** [comment]
FWIW, I've used Git since GitHub was new and Gitorious was a contender, 
so 2008. It just wasn't clear which branch to use unless you read the 
step-by-step instructions, which I didn't because a) I didn't think I 
needed them and b) I'm a command line user. I was hoping I could just 
change the base branch and be done with it. Might be useful to update 
the non-step-by-steps to explicitly state which branch you want used.

NBD, I'll just cherrypick the commit when things calm down here.

**Pull request closed without merging**
