### PR TITLE
fix [is[missing]]

### PR DESCRIPTION
**Pull request by tobibeer**
the filter didn't check against `options.wiki.getMissingTitles()`

### CODE REVIEW

**Comment by aelocson** [comment]
Your fix is testing for the `!` prefix on each iteration of the `source` loop. Compare orphan.js, which follows the pattern used in most of the other filter operators. I imagine @Jermolene deliberately chose to place the prefix test outside the loop for performance reasons.

**Comment by aelocson** [comment]
Related group discussion:

https://groups.google.com/forum/#!topic/tiddlywikidev/2FXH2_Wy05g

**Comment by tobibeer** [comment]
Thanks @aelocson, good point.
Updated the code, but still just one function.

**Comment by Jermolene** [comment]
@tobibeer this doesn't seem a backwards compatible change. I appreciate that the current `is[missing]` operator is redundant, but I think it's too late to redefine it's behaviour.

**Comment by tobibeer** [comment]
When not mission critical, I see little need to uphold backwards "compatibility" as the highest of standards when things are basically incorrect, if not wrong. I am much in favor of not dragging those things along but fix them. In fact, I actually consider this a bug.

**Comment by Jermolene** [comment]
> When not mission critical, 

What does that mean? I agree that we need to assess the impact of any proposed break in backwards compatibility.

> I see little need to uphold backwards "compatibility" as the highest of standards when things are basically incorrect, if not wrong.

I'm afraid that my experience with the project is that being cavalier with backwards compatibility causes big problems downstream. The only sensible way to make progress is to have full backwards compatibility as the default. I've repeatedly found that it is very hard to anticipate the full impact of a change.

> I am much in favor of not dragging those things along but fix them. In fact, I actually consider this a bug.

I think we'd normally use "bug" to mean an error in the implementation. A mistake in the design is usually harder to sort out than a bug. But the usual way to fix them is to deprecate components and replace them with something else.

**Comment by tobibeer** [comment]
> What does that mean? I agree that we need to assess the impact of any proposed break in backwards compatibility.

It means that I don't see how the missing filter is a critical filter that should break something when fixed to what one would reasonably expect.

> I've repeatedly found that it is very hard to anticipate the full impact of a change.

I understand the problem and I don't take it lightly. However, there are bugs / deficient implementations and then there are modifications / enhancements that require to "break" backwards compatibility to move on. To me, this is one of the former... an error in implementation, as you say... whether that originated from a (lack of a well defined) spec or not seems irrelevant.

This kind of backwards compatibility is a bit equivalent to being compatible to a mildly deficient wheel on a car. We got used to it, so let's keep it. Why? Fix the bumpy thing and keep rolling.

There is no approval process here so long as you write the spec as you go along in the form of code. Please don't think I'd be complaining. I am not. I think it's ok, even entirely refreshing to see you do your thing. Sure, sometimes giving the design of new features a little more (of a standardized) thought (process) and fetching those buckets of feedback over iterations is much needed.

> But the usual way to fix them is to deprecate components and replace them with something else.

We may have mild differences in philosophy. I think it's ok to move on and fix specific, well encapsulated aspect that is wrong or broken ...so long as we're not expecting users to literally lose faith and collapse by the change.

Sure, there is an expectation of continuity. To me, that is a bit pointless when things don't work as expected ...or perhaps when they work in (such inefficient) ways where they are quite untenable.

**Comment by tobibeer** [comment]
is fixing this (presumably minor) issue much different from the changes made in #1419?

**Comment by Jermolene** [comment]
The existing functionality is officially documented and so I think users have an expectation that it won't be changed unless it's broken. The new behaviour of checking the missing list is potentially useful, but I think it should be implemented as a new operand for the `is` operator.

**Comment by tobibeer** [comment]
You mean as in `is[trulymissing]`? ^^

**Comment by Jermolene** [comment]
Ha! Or `[!is[linked]]`.

**Comment by pmario** [comment]
There is a mechanism, to remove things that should be avoided. Deprecated functions. ... We have the possibility to keep stuff for backwards compatibility reasons, but display a message in the console. eg: "[is[deprecated]] should be changed to [!is[linked]]" ... "[is[deprecated]]" will be removed with V.5.2.0

**Comment by tobibeer** [comment]
> FireFox does this a lot for stuff, that will break in a year or so.

TiddlyWiki is a looong way from comparing to the Mozilla project in terms of backwards-compatibility... and look at just how many things have been changed over the years or were quite wrong or broken in some earlier days, and surely past-beta.

They may deprecate custom Firefox features, but when adopting something like a standard, say HTML5, or their own project standards where the term "missing" has a definition in that dictionary, and then realizing that an implementation doesn't quite live up to it ...it's time to fix it rather than invent a new term that adds more complexity to a dictionary that would sure benefit from being slim and straight forward rather than "missing, you ask? could mean this or could mean that".

This is about the `[is[missing]]` filter, a less significant aspect of TiddlyWiki, hardly a critical feature where plenty folks would possibly ask "How could they've changed it? I'm all confused now."

It's what keeps me discussing this most of all, this attachment to keeping a non-vital thing alive that could easily be thrown overboard, plus for a good reason.

Would a filter like `[exists[]]` be meaningful? Perhaps. But then have that on top rather than instead. Keep that dictionary free from contradictions, same as with negation.

Dare to have things break every now and then, if it's for the better. It's keeping things alive. However, this clearly isn't even breaking for me, it's fixing.

If you honestly feel that this is a sign of "Oh, look, now it's going down the gutter, now ...you can't rely on anything." ...I don't know, the world keeps changing around you and so it will and must.

Here's my final idea `is:truly[missing]`... just kidding. ^^

**Comment by Jermolene** [comment]
I think that one of the issues is that the TW core has two senses in which the term "missing" is used in connection with tiddlers:

* When displaying tiddlers and links, "missing tiddlers" are those that don't exist. These missing tiddlers are displayed in italics
* In the sidebar tabs, "missing tiddlers" are those that are not the target of an explicit link

@tobibeer's original statement about "what one would reasonably expect" depends rather on which of those definitions is uppermost in ones mind.

I wonder if we might explore alternative terms for "missing" in the sense of "unlinked" - bearing in mind that we may want to redefine it to include "untranscluded" as well.

**Comment by tobibeer** [comment]
there's `[all[missing]]` (in use) and `[is[missing]]`... implementing a different thing... which is why I find this confusing most of all ...both of these should do refer to the same thing, imho

**Comment by Jermolene** [comment]
That's what I'm saying: the core uses the word "missing" to mean two different things, and that that is actually the underlying problem here. Both concepts exist and need talking about, but shouldn't have the same name.

**Comment by aelocson** [comment]
> In the sidebar tabs, "missing tiddlers" are those that are not the target of an explicit link

That's not true. The sidebar "missing tiddlers" are the non-existent ones that *are* the target of an explicit link.

The two kinds of "missing" are currently defined as follows:

* `is[missing]` – simply doesn't exist as a tiddler (ignoring shadows)
  * i.e. this is *identical* to `!is[tiddler]`
* `all[missing]` – has a hard link to it but doesn't exist as either a tiddler or a shadow

The word "(un)linked" would be a confusing choice, as its directionality isn't clear. In different contexts, a "linked" tiddler could be one that contained a link, or one to which another tiddler contained a link.

A possible alternative is "(un)referenced". This would handle transclusions as well as links. An unreferenced tiddler would be one that is never linked to or transcluded by any other tiddler.

More strictly, we could speak of "hard references", i.e. those that can be detected syntactically.

**Comment by Jermolene** [comment]
> The sidebar "missing tiddlers" are the non-existent ones that are the target of an explicit link.

Sorry, my typo.

I like the terminology "(un)referenced", but I'm not sure that it's enough: we need a word for "referenced but not existing". Frustratingly, "missing" still feels like a reasonable shorthand (and is conventional for wikis).

**Comment by aelocson** [comment]
I agree. "Missing" suggests that something somewhere (a link, as it happens) is aware of the absence of these tiddlers.

Perhaps the answer is to use a different word for tiddlers that simply don't exist, full stop. "Absent" or "non-existent" would fit the bill.

**Comment by Jermolene** [comment]
"Missing Links" is not bad, then we get to keep "missing" as meaning "non-existent". (Also it's funny for English speakers: http://en.wikipedia.org/wiki/Missing_Link).

**Comment by aelocson** [comment]
But a "missing link" should be a link that is missing, rather than a link that exists but has a missing target. The latter is a "broken link".

**Comment by Jermolene** [comment]
Very good, I like "Broken links", it's nice and clear.

**Comment by aelocson** [comment]
Ah, but what's "broken" is the link or transclusion itself, not the tiddler that's referenced by the link or transclusion. And we were looking for a word to describe a tiddler that is "non-existent but referenced by a link or transclusion".

**Comment by tobibeer** [comment]
> And we were looking for a word to describe a tiddler that is "non-existent but referenced by a link or transclusion".

To me, that is not a tiddler... albeit a placeholder for one. It is indeed just a "broken link"... whether that target existed before or never has is almost irrelevant.

**Comment by aelocson** [comment]
But it seems muddled to use the phrase "broken link" to mean a missing target. The link and the target are not the same thing, even if the link happens to be broken.

In ordinary text, the clearest option is to say "the target of a broken link".

In concise filter notation, we could say `all[broken]` as a synonym for the present meaning of `all[missing]`, and perhaps deprecate the latter.

`all[broken]` would be read as a shorthand for "all tiddlers that are targets of broken links", rather than "all tiddlers that are broken links".

**Comment by pmario** [comment]
As  new user, if I read `all[broken]` I associate this with a broken tiddler. .. So my TW is damaged. ... I don't like this "shorthand" term.

**Comment by aelocson** [comment]
@pmario, you're quite right. Let me retract the idea of `all[broken]`.

This essentially comes back to the same point I was making a few comments ago. A link can be "broken", but the word "broken" doesn't transfer well to describing the target tiddler of such a link.

**Comment by tobibeer** [comment]
To me that has always been the meanign of missing... if you will, since the dawn of TWc. So, I am not sure if and why we would be changing notions here. If anything, let's invent "non-existing".

**Comment by aelocson** [comment]
If you're happy with `all[missing]`, then all we need do is cough politely and brush `is[missing]` under the carpet of deprecation. Its meaning can already be represented (more clearly) by `!is[tiddler]`.

**Comment by tobibeer** [comment]
To me, there is no deprecating here, there only is fixing... which means to deprecate that old behavior, sure... by replacing it with a more consistent one.

**Pull request closed without merging**
