### PR TITLE
SVG Update: Add 3 Jacks and Optimize 1 Example

### PR DESCRIPTION
**Pull request by telmiger**
Using SVG: Use .svg in example instead of .jpg
Add ReadyJack, AnxiousJack and SleepyJack illustrations

The new cats should look like this: https://tid.li/tw5/hacks.html#SleepyJack.svg:SleepyJack.svg%20ReadyJack.svg%20AnxiousJack.svg

### CODE REVIEW

**Comment by sukima** [comment]
The three new files look good. the four changed files look good. Not sure why there are **27** commits for this? Also if the SVGs are in their own file with a meta file then GitHub will render the images.

Would you like me to make a PR that doesn't have so many commits?

**Comment by sukima** [comment]
I have rebased the changes in PR #2981 

This PR can be **closed**!!

**Comment by sukima** [comment]
If anyone is interested.

1.  `git checkout master && git pull`
2.  `git checkout -b feature/improved-svgs`
3.  `curl https://github.com/Jermolene/TiddlyWiki5/pull/2980.patch > 2980.patch`
4.  `git am 2980.patch`

Each time the patch failed (due because the code changes were already in master from previous pull requests) I performed `git am --skip`.

Eventually the whole thing applied. I looked at each commit and mentally remembered their grouping. I then ran `git rebase -i master` and rearranged / marked for fixup as follows:

```
drop dc24909db2cc30e54409ed449a0bf09de631920e Remove additional blank line
pick 9329b84e6 Using SVG: Use .svg in example instead of .jpg
pick 89b1ce7a2 SleepyJack.svg
fixup fe1eb7470 rename including .tid
pick f059b785b AnxiousJack.svg
fixup 2159f97e9 Update timestamp
fixup 4a25a3b5f Create AnxiousJack.svg.tid
fixup e724009cf Delete version with wrong filename
pick 6f763152f ReadyJack.svg
fixup 92125db90 Update modified timestamp
```

I then added the final commit to move meta data to separate files so GitHub could display the SVG changes correctly.

**Comment by telmiger** [comment]
Thank you @sukima for cleaning up! I guess the whole mess comes from my exclusive use of github in the browser. (No git client or command line in use at the moment. I am only an amateur who likes to dedicate some time to this great tool.) Maybe I will have to learn git in the future …

**Comment by sukima** [comment]
I had always thought GitHub allowed you to create a branch when you make edits. That fixes up most of this. There is also a [GitHub desktop client](https://desktop.github.com/) that does wonders.

**Comment by telmiger** [comment]
Yep, I had a branch at some time – but then again it was not in sync with Jermolene/master so the only way I could see was to update my master, merge my branch and start the PR from there. Obviously not ideal. Thanks anyway!

**Comment by sukima** [comment]
Yet another nail in the GitHub coffin. I really wish GitHub offered better tools on their web site.

**Pull request closed without merging**
