### PR TITLE
Add pop storyview to ViewToolbar buttons

### PR DESCRIPTION
**Pull request by BurningTreeC**
This PR adds the `pop storyview` to the `ViewToolbar` buttons

### CODE REVIEW

**Comment by saqimtiaz** [comment]
@BurningTreeC using the `lookup[]` operator here might be a good idea.

I think we need to invest some time in setting up our CI to automatically build and make available TiddlyWiki files for PRs, as that would make testing and providing feedback on PRs so much easier.

**Comment by BurningTreeC** [comment]
@saqimtiaz I don't know how I should realize this with the lookup operator ...

**Comment by saqimtiaz** [comment]
It would be something along these lines:

`[all[shadows+tiddlers]tag[$:/tags/ViewToolbar]!has[draft.of]] :filter[lookup[$:/config/ViewToolbarButtons/Visibility/]!match[hide]]
`

**Comment by pmario** [comment]
I don't understand this PR. Why do we need a "storyview" button in the tiddler toolbar?

**Comment by Jermolene** [comment]
Hi @BurningTreeC @pmario actually I like this: the pop animation makes it much more obvious what's happening when clicking the toolbar visibility checkboxes in the first tab of the tiddler info panel.

**Comment by saqimtiaz** [comment]
> Hi @BurningTreeC @pmario actually I like this: the pop animation makes it much more obvious what's happening when clicking the toolbar visibility checkboxes in the first tab of the tiddler info panel.

Likewise. We should however confirm that removing the reveal widget does not have other consequences, for instance in terms of qualified state tiddlers etc. I think that should be OK but I don't have the opportunity to consider it properly at present.

**Comment by pmario** [comment]
>Hi @BurningTreeC @pmario actually I like this: the pop animation makes it much more obvious what's happening when clicking the toolbar visibility checkboxes in the first tab of the tiddler info panel.

uups, I didn't have a look at the code. ... I did miss, that it's the animation that will be added and not the button.  ... So just ignore my comment. 

Which still should remind us, that PR request descriptions should be clear. This one wasn't .. At least for me :/

**Comment by BurningTreeC** [comment]
@Jermolene , this PR would be ready for review

**Comment by Jermolene** [comment]
Thanks @BurningTreeC @saqimtiaz I'm fairly confident that removing the reveal widget won't affect any generated qualifiers.

**Pull request merged**
