### PR TITLE
allows custom html element to be created by RevealWidget

### PR DESCRIPTION
**Pull request by tobibeer**
**discussion**: [Conditional table rows](https://groups.google.com/d/msg/tiddlywiki/hR4LntIK_DY/Fm-gh7nSecEJ)

**demo**: http://tbdemo.tiddlyspot.com/#reveal%3Atr

### CODE REVIEW

**Comment by pmario** [comment]
It would be nice to have a bit more documentation in the pull request description. eg: what's the advantage over the existing version.

**Comment by tobibeer** [comment]
Added a link to a discussion in the description.

I prefer to add documentation once a pull request is accepted.

All in all, this enhancement is a bit of a no-brainer in terms of...

* what it does
* being necessary

**Comment by Jermolene** [comment]
> I prefer to add documentation once a pull request is accepted.

A quick thought on that: without documentation about the change it's very hard for me to assess pull requests. I often have to run the code in my head to see what it does. I'd much prefer documentation and it seems that writing the docs in the final form isn't much more work than including them in the pull request description.

> All in all, this enhancement is a bit of a no-brainer in terms of...

I'm not so sure. The reveal widget only generates an element so that it can use CSS to hide it's content in retained mode. The list widget doesn't generate any intrinsic elements, which means that it can be used for conditional table rows. I'm more interested in extending the list widget so that it can cover the remaining use-cases of the reveal widget. Then we'd just have the problem that the name of the `list` widget would be confusing; but we can easily alias it to a new name.

Also, note that as written this proposal allows the user to specify the tag as "script" and thereby surreptitiously include executable code. (We've got the same problem with the edit-text widget, I think).

**Comment by tobibeer** [comment]
I won't start documentating for pull requests upfront. I started to provide more demos and tests and that is much more reasonable a demand. Chances are way too big that things get rejected, discarded, changed, spending hours for well documented naught.

This fix seemed very obvious from the context of Astrids post, not needing a further demo, so I thought.

> The reveal widget only generates an element so that it can use CSS to hide it's content in retained mode. 

It is precisely this problematic element — as refered to in the discussion — which needs fixing ...in the reveal widget, not any possible other widget surrounding it.

How else will you have a conditional table row if not through reveal? How do you get rid of the offending element if not by defining it to what you need?

**Comment by pmario** [comment]
I think Tobias is right here. ... The reveal widget creates a `div` or `span`. In the use case mentioned in the discussion it should create a table `tr` element. So imo the pull request makes sense.

**Comment by felixhayashi** [comment]
Hi,

I am highly in favour of being able to determine which child element type is produced by the reveal widget. In my opinion it would be great if we could even force the reveal widget to not produce a child widget at all! I faced many situations where I wished I had control over the child element. For me the reveal widget should only focus on its main purpose: to hide or not hide. In many cases I actually don't want it to produce unnecessary html elements which force me to rewrite my css rules accordingly.

**Comment by tobibeer** [comment]
> In my opinion it would be great if we could even force the reveal widget to not produce a child widget at all!

I believe this may not be possible. After all, there will be nothing in the dom to handle a refresh.

**Comment by felixhayashi** [comment]
> I believe this may not be possible. After all, there will be nothing in the dom to handle a refresh.

Ah, ok.

**Comment by Jermolene** [comment]
> Please accept that I won't start documentating for pull requests upfront. I started to provide more demos and tests and that is much more reasonable a demand. Chances are way too big that things get rejected, discarded, changed, spending hours for well documented naught.

A pull request with no documentation explaining what it does is unlikely to get accepted. Nor am I keen to trace through other discussion threads to try to figure out the underlying proposal. If you want a pull request to be accepted then that pull request needs to clearly explain itself. I'm sure you'll appreciate that the workload for pull requests is pretty heavy for me, and I really appreciate contributors making it as easy as possible.

That's why I said that if you are writing documentation it's often going to be quickest and less ambiguous to actually propose the docs changes as part of the pull request.

> It is precisely this problematic element — as refered to in the discussion — which needs fixing ...in the reveal widget, not any possible other widget surrounding it.

It's too late to "fix" the reveal widget; it does what it does. We can only extend it's behaviour now.

> How else will you have a conditional table row if not through reveal? How do you get rid of the offending element if not by defining it to be of the type you need?

The other alternative is to use the list widget. As I've pointed out before, list and reveal are almost interchangeable. The key difference is that reveal always generates a DOM element where the list widget does not.

**Comment by felixhayashi** [comment]
> The other alternative is to use the list widget. As I've pointed out before, list and reveal are almost interchangeable. The key difference is that reveal always generates a DOM element where the list widget does not.

Great idea, I never thought about that.

**Comment by tobibeer** [comment]
> It's too late to "fix" the reveal widget; it does what it does. We can only extend it's behaviour now.

This extension provides a **straight forward** way to make ammends for what otherwise breaks the html.

> The key difference is that reveal always generates a DOM element where the list widget does not.

**$list** and **$reveal** work differently in how they evaluate things, one uses **filters** the other uses **type** and compares attributes

> That's why I said that if you are writing documentation it's often going to be quickest and less ambiguous to actually propose the docs changes as part of the pull request.

I believe you understand this type of upfront end-user-documentation as a kind of spec.

I sure see the workload on your end, please see the one on mine, as well. Implementing a feature / enhancement along with all the documentation for it and then finding things rejected or fundamentally overturned, above all, creates more work, you know that yourself.

Agile puts the focus on well packaged, testable, integrated, runnable codebits based on a clean spec... one of which this is. At least, I thought the title would say it all.

I added a link to a demo to the description.

**Comment by Jermolene** [comment]
> This extension provides a straight forward way to make ammends for what otherwise breaks the html.

Maybe, that's what I'm not convinced of yet!

> I sure see the workload on your end, please see the one on mine, as well. Implementing a feature / enhancement along with all the documentation for it and then finding things rejected or fundamentally overturned, above all, creates more work, you know that yourself.

I don't think it's quite like that. Clearly I have to understand a pull request in order to be able to accept it. If you want to maximise the chances of acceptance you need to make it as easy as possible for me to understand what's going on. It's up to you how you try to do that. You certainly don't need to provide documentation updates in the pull request up front, but it's one of the stages that will have to happen at some point.

> Agile puts the focus on well packaged, testable, integrated, runnable codebits based on a clean spec... one of which this is.

Just to be clear I need to be able to understand a pull request without running the code, just by looking at the information in the pull request.

**Comment by tobibeer** [comment]
> Clearly I have to understand a pull request in order to be able to accept it. If you want to maximise the chances of acceptance you need to make it as easy as possible for me to understand what's going on. 

Duly noted. I do see that I have been presupposing a bit too much. I guess it's more a lack of (perhaps referred to) specs rather than final documentation though. In simple cases, the latter may do fine.

**Comment by pmario** [comment]
@Jermolene 

Example
```
<table>
  <tr><td>January</td><td>2015</td></tr>
    <$reveal default="y" type="match" text="y">
      <tr><td>February</td><td>2016</td></tr>
    </$reveal>
  <tr><td>March</td><td>2017</td></tr>
</table>
```

creates the following html, which breaks the table: 

```
<table>
<tr><td>January</td><td>2015</td></tr>
  <span class=" tc-reveal">
    <tr><td>February</td><td>2016</td></tr>
  </span>
<tr><td>March</td><td>2017</td></tr>
</table>
```

With a merged pull request it is possible to create a table like this:

```
<table>
<tr><td>January</td><td>2015</td></tr>
  <tr class=" tc-reveal">
      <td>February</td><td>2016</td> 
  </tr>
<tr><td>March</td><td>2017</td></tr>
</table>
```

So the table is well formated. The code to achieve the above would be:

```
<table>
  <tr><td>January</td><td>2015</td></tr>
    <$reveal default="y" type="match" text="y" element=tr>
        <td>February</td><td>2016</td>
    </$reveal>
  <tr><td>March</td><td>2017</td></tr>
</table>
```

**Comment by Jermolene** [comment]
@pmario I understand the problem. I'm not being very clear in pointing out that an alternative to changing the behaviour of the reveal widget is to extend the list widget so that it can be used instead. The core already liberally uses the list widget for conditional content, particularly in situations where the DOM element generated by the reveal widget gets in the way.

So, to take this approach we'd need to extend the filter language to cover similar logic to the reveal widget.

Your example would be expressed by something like:

```
<table>
  <tr><td>January</td><td>2015</td></tr>
    <$list filter=""" [{myTiddler}[y]] """>
      <tr><td>February</td><td>2016</td></tr>
    </$list>
  <tr><td>March</td><td>2017</td></tr>
</table>
```

**Comment by pmario** [comment]
But how can I define an animation if the the open / close status changes?
IMO I'd need a reveal widget to get this behaviour. So covering the list in a reveal will break the table again :/

**Comment by tobibeer** [comment]
So much effort to find work-arounds for the obvious, energy spent on (re)searching complicated solutions for simple issues. What I see here is a most minor change, implemented, ready to go, fixing what's otherwise limited, if not broken.

* "Let's try to do this with a (convoluted) macro."
* "Let's construct some (monumental) template."
* "Let's find some work-around that wouldn't come to mind but works in its twisted ways."

My 2 cts: Let's do slightly less of all that. Let's (**keep** the) focus on...

* making and keeping things simple and straight forward, for users (!)
* modular, reusable, properly exposed, straight forward components
* implementing things at the right spot / in plain js / at the core level as much as possible
    * without unduly bloating things for no good, of course

I don't need a bazillion ControlPanel options, but I do need that flexibility and a focus on being able to work things out **with as little markup / syntax / components as possible**.

**Comment by tobibeer** [comment]
related discussion: [reveal or Slider within a table](https://groups.google.com/d/msg/tiddlywiki/Z9xgAOUD0v4/jaG_Fdd_AwAJ)

**Comment by tobibeer** [comment]
closing as it appears to be in the core now as of https://github.com/Jermolene/TiddlyWiki5/commit/1808b1597e5a61379e4e5381d6d78bb73fa3a523

**Pull request closed without merging**
