### PR TITLE
allows to alt-click a link to open tiddler in edit mode instead

### PR DESCRIPTION
**Pull request by tobibeer**
discussion:
https://groups.google.com/d/msg/tiddlywiki/2HQ6dXiAwyI/gXI1187pk_8J

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @tobibeer thanks for this. The combination of ctrl and alt doesn't work correctly. I think we need to refactor a helper function for adding an edit mode tiddler to the story out of handleEditTiddlerEvent, and then re-use that so that we can use the existing history processing.

**Comment by tobibeer** [comment]
For me, it does what it advertises. Is it failing for you? 

Could you expand a little more on which part precisely is problematic / missing? There should be no combination of CTRL+ALT kicking in, ALT supersedes CTRL here and forwards you to the editor.

I don't yet understand what the purpose of the helper function would be, how you envision reusing that or why history-prosessing would perhaps be negatively affected with the code as is.

I did not pass down the **altKey** directly to **handleEditTiddlerEvent** but a **navigateEdit** flag... so as to indicate that we're really looking to edit the target, not simply navigating to it.

One problem I noticed, though, is that this behavior should not do anything when navigating to drafts / ALT+clicking links to drafts. I pushed another commit to fix this.

**Comment by Jermolene** [comment]
> There should be no combination of CTRL+ALT kicking in, ALT supersedes CTRL here and forwards you to the editor.

I would have expected ctrl-alt-clicking a link to open the target tiddler in edit mode without navigating to it, just as ctrl-clicking on it's own doesn't navigate to the target tiddler.

> I don't yet understand what the purpose of the helper function would be, how you envision reusing that or why history-prosessing would perhaps be negatively affected with the code as is.

You're currently calling handleEditTiddlerEvent when the alt key is pressed. That function both puts the tiddler into edit mode and updates the history. When ctrl is also down we shouldn't update the history (thus suppressing the navigation scroll). To do that we'll need to break handleEditTiddlerEvent apart.

**Comment by pmario** [comment]
>>There should be no combination of CTRL+ALT kicking in, ALT supersedes CTRL here and forwards you to the editor.

>I would have expected ctrl-alt-clicking a link to open the target tiddler in edit mode without navigating to it, just as ctrl-clicking on it's own doesn't navigate to the target tiddler.

hmmm, IMO alt should win here. If you want to directly open a tiddler in edit mode, imo it should scroll.

**Comment by tobibeer** [comment]
I see. So you do want the behaviour of opening a tiddler in edit-mode in the background, thus combine both key-events. I can agree to that. After all, why shouldn't it be possible... especially if I wanted to open, say, 10 tiddlers in edit mode to look at them, in a minute... as I would do with reading them.

Would you want me to do the adjustment? Or do you prefer to create that helper function yourself. The thing is, I am not quite sure where to put that helper or what exactly to refactor into it. However, I take it, you're generally appreciative of providing this functionality. :+1:

**Comment by Jermolene** [comment]
> Would you want me to do the adjustment

I've realised a potentially easier way to handle the concern. You could update `handleEditTiddlerEvent()` in navigator.js so that it looks at a flag `event.navigateUpdateHistory` to decide whether to update the history list. Then when you invoke it you can modify the event parameter to control the navigation behaviour.

**Comment by tobibeer** [comment]
> You could update `handleEditTiddlerEvent()` in navigator.js so that it looks at a flag `event.navigateUpdateHistory`

What would fire `handleEditTiddlerEvent()` if not the rerouting in `handleNavigateEvent()`? I still fail to grasp what's the issue with the history list.

You seem to be talking of rerouting to some navigation event starting from an edit event whereas the current proposal is the reverse.

**Comment by Jermolene** [comment]
I think the situation is that we want to reuse the logic of `handleEditTiddlerEvent()` that handles creating a tiddler in edit mode, but that we need to be able to suppress the navigation handling when Ctrl is pressed. To do that we either need to break the operations of `handleEditTiddlerEventI()` into separate, reusable helpers that we can use selectively, or we can make `handleEditTiddlerEvent()` respect a flag to control whether it performs the navigation step (ie updates the history list).

**Comment by tobibeer** [comment]
Ah, now I see, all you want is for `handleEditTiddlerEvent()` to also respect the CTRL modifier so as to not navigate to that tiddler.

**Comment by Jermolene** [comment]
@tobibeer yes, exactly that.

**Comment by tobibeer** [comment]
At the moment, the chain of events triggered at the end of `handleEditTiddlerEvent()` is a bit beyond me... in terms of what it is you (don't) want to happen to the story list.

May I ask why there even is a `replaceFirstTitleInStory()`? How come there is that exception of putting some things up top?

**Comment by Jermolene** [comment]
> At the moment, the chain of events triggered at the end of handleEditTiddlerEvent() is a bit beyond me... in terms of what it is you (don't) want to happen to the story list.

The bit we want to avoid is the update to the history list that triggers the navigation behaviour: `addToHistory()`.

> May I ask why there even is a replaceFirstTitleInStory()? How come there is that exception of putting some things up top?

In practice, the same title shouldn't appear more than once in the story, so the name of the function is a bit misleading.

**Comment by tobibeer** [comment]
Thanks for clearing that up.

**Comment by tobibeer** [comment]
Can we possibly merge this for now and add the additional functionality later? Trying to clean up some branches.

**Comment by tobibeer** [comment]
@Jermolene: While I would like to see this capability, I never did manage to wrap my head around your objections or how to implement things differently. So, for now, I'll leave it to someone else to propose something different later.

**Pull request closed without merging**
