### PR TITLE
Typo fix: "ot" should be "to"

### PR DESCRIPTION
**Pull request by rmunn**

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @rmunn. Pure documentation changes that apply to earlier versions should target the tiddlywiki-com branch so that the change can go live on tiddlywiki.com

**Comment by rmunn** [comment]
Oh yeah. I knew that but had forgotten it due to my most recent documentation work being against the prerelease version and therefore needing to be against the master branch. I'll update the PR's target branch.

**Comment by rmunn** [comment]
Whoa. Changing the target branch in the GitHub PR pulled in a whole bunch of commits I didn't intend to merge. I'll close this, rebase the commit, and open a proper PR.

**Comment by rmunn** [comment]
Rebasing and force-pushing to the branch while this PR was closed has confused GitHub beyond all hope of recovery, so I can't reopen this PR. Instead, I've opened #4951 for this typo fix.

**Pull request closed without merging**
