### PR TITLE
Markdown plugin: add rel="noopener noreferrer" to external links

### PR DESCRIPTION
**Pull request by ento**
### Motivation
This applies https://github.com/Jermolene/TiddlyWiki5/commit/3a3754aebb73a55d0be56e14628ec6317aa6ad50 to the markdown plugin, which guards against malicious use of `window.opener` and tells the browser not to send the URL of the TiddlyWiki instance to the server at the linked URL.

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @ento this looks good, could you please resolve the conflict? Many thanks.

**Comment by ento** [comment]
@Jermolene Done!

**Comment by saqimtiaz** [comment]
@Jermolene this can now be rmerged, the conflict has been resolved.

**Comment by Jermolene** [comment]
Thanks @ento @saqimtiaz and apologies for the delay

**Pull request merged**
