### PR TITLE
Updated documentation on developing for TiddlyWiki5 to hopefully help el...

### PR DESCRIPTION
**Pull request by dullroar**
...iminate some confusion about how to test changes.

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @dullroar.

One complication with this wording is that it is actually OK to run TiddlyWiki from the root of the repo. If TiddlyWiki can't load a wiki folder from the specified folder (or the current folder), then it just initialises an in-memory store. This is useful for some operations where you don't need a persistent wiki folder (eg, reading the tiddlers from a standalone TW HTML file and writing them out to a given directory)

I can't immediately find the thread where you described the problem as you encountered it originally. Can you point me at the thread?

**Comment by dullroar** [comment]
I have updated the generateTiddlerFilename method to better handle case-insensitive file systems. Went down a path that was way too complex, then ended up settling for the current code. It works for all my testing, although that isn't to say it couldn't use some scrutiny.

**Comment by dullroar** [comment]
@Jermolene, it was in the original post about [my ATOM plugin](https://groups.google.com/forum/#!topic/tiddlywiki/lDayriKvtUI), in the second part where I asked you a question about that behavior (which you didn't answer, but I figured you're just busy :).

**Comment by Jermolene** [comment]
Thanks @dullroar.

> 1. Forked TW5 into my own GitHub repo.
> 2. Cloned it down to my local machines (same symptoms occur on Windows and Linux boxes, so it is not that).
> 3. Changed into the TiddlyWiki5 directory and did npm link.
> 4. Made my changes.
> 5. Copied a "Basic client-server edition" tiddlywiki.info file into the root of the repo, to wit:

It's step 5 that's the problem; if you'd tried to initialise the wiki with the `tiddlywiki --init` command then you'd have got an error stating that the directory wasn't empty. Manually creating the `tiddlywiki.info` file means that TiddlyWiki considers the folder a valid wiki folder, leading to the crash when it finds that the `plugins` folder isn't laid out correctly.

I guess we could detect the specific situation of the user trying to use the repo folder as a wiki folder, and raise an error, regardless of whether we find a valid `tiddlywiki.info`.

I think the confusion in the referenced thread is because the layout of the `plugins` folder is different in the repo and in wiki folders. In the repo we have `plugins/publisher/name/tiddlywiki.info`, while in the wiki folder we have `plugins/name/tiddlywiki.info`. We should probably support using the publisher name within wiki folders too.

**Comment by dullroar** [comment]
That is ***precisely*** the problem - my misunderstanding of that point. And yes, I think you should support publisher name in the wiki folders because otherwise the possibility of collision of names is higher. If I had named my "atomfeed" plugin "atom" instead, some physicist's plugin could collide (producing sub-atomic particles! :).

**Comment by Jermolene** [comment]
Hi @dullroar I've created two tickets: #1309 "Support `plugins/publisher` in wiki folders" and #1310 "Detect using repo as wiki folder"

**Comment by dullroar** [comment]
Thanks.

What should I do about this pull request, since it actually has two different commits in it, the documentation update which I should probably remove, and the actual code fix for the case insensitive file systems?

**Comment by Jermolene** [comment]
Hi @dullroar I think we'd have the cleanest audit trail if you could create a new pull request with just the fix for #1303. Many thanks

**Comment by dullroar** [comment]
Closing this pull request.

**Pull request closed without merging**
