### PR TITLE
should it be "[title[ScrambledEggs]]"?

### PR DESCRIPTION
**Pull request by alexhough**

### CODE REVIEW

**Comment by tobibeer** [comment]
for consistency, yes...

**Comment by aelocson** [comment]
Absolutely.

**Comment by aelocson** [comment]
I'm busy working on these filter-related tiddlers at the moment. To avoid a merge conflict, I'll correct this mistake in my local copy and it will form part of my next pull request, probably later this weekend.

@alexhough, could I therefore ask you to close this pull request, please? Thanks for spotting the mistake.

**Comment by alexhough** [comment]
@astrid - I've just closed it.

its the first time I've done this.... hope there are not problems

Alex

**Comment by aelocson** [comment]
Thanks, Alex – that'll be fine now.

If more than one person modifies the same file, GitHub doesn't like it.

Normally, what I would do is wait for Jeremy to accept your pull request. Then I would merge *that* into my own copy before sending my pull request. But as Jeremy's currently away for a fortnight, that's not really possible.

**Pull request closed without merging**
