### PR TITLE
update twitter plugin readme

### PR DESCRIPTION
**Pull request by mandarvaze**
Document extra installation step mentioned [here](https://github.com/Jermolene/TiddlyWiki5/issues/3314#issuecomment-617360686)

### CODE REVIEW

**Comment by mandarvaze** [comment]
This PR is not required anymore since @Jermolene has already addressed it in [here](https://github.com/Jermolene/TiddlyWiki5/commit/678e25f510786fbc38f505f8b594f57f39e33a04)

Closing.

**Comment by Jermolene** [comment]
Thanks @mandarvaze PRs are very welcome. We do have one minor bit of bureaucracy, if you could please sign the Contributor License Agreement as outlined in contributing.md in the root of this repo. Many thanks!

**Comment by mandarvaze** [comment]
@Jermolene I've already signed it once - I suppose I don't need to do it fr each PR, correct ?

**Comment by Jermolene** [comment]
Apologies, @mandarvaze that is my poor memory! Thanks.

**Comment by mandarvaze** [comment]
Not a problem.

**Pull request closed without merging**
