### PR TITLE
Login plugin to store user name in a cookie

### PR DESCRIPTION
**Pull request by koke24**
Hi!

Here is a plugin to store user name in a cookie in the browser. It is almost independent but It needs a minimal change in tiddlyweb plugin to allow it to retrieve user name from the stored cookie and use it as the user name for the TiddlyWiki.

I have changed style and fixed remarks sent by @felixhayashi 

Best regards

### CODE REVIEW

**Comment by pmario** [comment]
@Jermolene ... This PR IMO contains an unrelated change to the "wikitext list parser". ... So it can't be merged as it is! 

The local-storage plugin may do the same thing as this PR. 

close?

**Comment by pmario** [comment]
@Jermolene ... In Aug. 2019 I did mention, that this PR can't be merged, because it contains changes to unrelated parts of the core code. ... The author didn't change anything. 

So I think it's safe to close this PR

**Comment by Jermolene** [comment]
Thanks @pmario

**Comment by koke24** [comment]
Sorry for not pursuing this. I worked with it a long time ago and I am no longer with it. Anyway, thank you for your time, your efforts and this great software!

**Pull request closed without merging**
