### PR TITLE
Adding the "Font Awesome 5 SVGs for TiddlyWiki" resource site

### PR DESCRIPTION
**Pull request by morosanuae**
@Jermolene I've recreated it. Is it good? Thanks.

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @morosanuae looks good. I'll merge it and then you should see it appear in 10 minutes or so (you can see the build progress at https://travis-ci.org/Jermolene/TiddlyWiki5/builds).

**Comment by morosanuae** [comment]
@Jermolene a little question if you don't mind. I don't understand where should I see it. Will this be available online immediately after merging or it has something to do with testing (CI)? Thanks.

**Comment by Jermolene** [comment]
Hi @morosanuae it turns out there was a problem that I had missed — the file you added doesn’t have the required `.tid` extension. Fixed in 27b75f392

**Comment by Jermolene** [comment]
>  I don't understand where should I see it. Will this be available online immediately after merging or it has something to do with testing (CI)? Thanks.

It takes about 10 minutes until commits go through CI and appear on tiddlywiki.com

**Comment by morosanuae** [comment]
@Jermolene thanks.

**Pull request merged**
