### PR TITLE
Added flag to $tw.utils.parseStringArray to allow non-unique entries

### PR DESCRIPTION
**Pull request by inmysocks**
With this change if you use $tw.utils.parseStringArray(list) you get identical behavior to before and enforces uniqueness in lists, but if you use $tw.utils.parseStringArray(list,true) it allows duplicate values in the list.

Because of how JavaScript handles overloaded functions this shouldn't have any affect on existing code that just passes one argument to the function.

### CODE REVIEW

**Comment by tobibeer** [comment]
:+1:  looks good (-:

**Comment by tobibeer** [comment]
@Jermolene, please consider for #2143. This is very important for further, independent developments concerning any list-handling filters.

**Comment by tobibeer** [comment]
@inmysocks / @matabele: Doesn't this PR lack the ability to instruct **filterTiddlers** to use this paradigm?

**Comment by matabele** [comment]
I'm not sure of the repercussions of your approach, however. if you're interested, the x-listops filters contain a unique[] filter operator (at the bottom): 

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/filters/x-listops.js

This takes any string of items as input and returns a unique string of items as output -- might be worth having a look for an alternative approach where duplicates are only removed after the list has been formed (by default for existing functions such as parseStringArray().)

**Comment by tobibeer** [comment]
> This takes any string of items as input and returns a unique string of items as output -- might be worth having a look for an alternative approach where duplicates are only removed after the list has been formed (by default for existing functions such as parseStringArray().)

Let me phrase it differently since I think your suggestion doesn't work, at least I don't see how.... in order to get a **list** of values rather than a set of unique values, e.g.:

```
[tag[foo]get[bar]]
```

Now. I want for every tiddler tagged `foo` the value of field `bar` without duplicates removed. How would the listops filters help me with that?

**Comment by matabele** [comment]
@tobibeer The parseStringArray() filter still needs to be fixed.

**Comment by tobibeer** [comment]
Ok, I see, so it is your intention to extend the listops filters whereas it is mine to see the core extended in a more generic manner allowing a user to use filters with lists rather than sets.

**Comment by matabele** [comment]
@tobibeer The listops widget uses the parseStringArray() function and therefore, by default results in a unique list. I could have used different code but stuck to the standard function to avoid duplication (a fix for the parseStringArray() function would be preferable.)

**Comment by Jermolene** [comment]
Thanks @inmysocks @tobibeer

**Pull request merged**
