### PR TITLE
Tank adjustments

### PR DESCRIPTION
**Pull request by cdent**
This is probably not complete for a pull request, but I wanted to indicate that this stuff is still percolating along.

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @cdent thanks for this.

> This is probably not complete for a pull request, but I wanted to indicate that this stuff is still percolating along.

It's very helpful. Currently the changes here break TW5 compatibility with TiddlySpace and with the TW5 native serverside. I can fix up the TW5 server support pretty easily by the looks of it, but I also need to figure out the best way of encapsulating/enabling the TiddlySpace-specific code.

**Comment by cdent** [comment]
> figure out the best way of encapsulating/enabling the TiddlySpace-specific code

Probably the most straightforward thing to do is bring back the check to /status and then do a variety of different things based on what's in there. Tiddlyspace will have the `space` datastructure. Tank has a specific challenger: `"challengers": ["tiddlywebplugins.tank.challenger"]`.

Something along those lines perhaps?

**Comment by Jermolene** [comment]
Thanks @cdent that makes sense.

**Comment by ght** [comment]
This PR should probably be closed, it has no description of what it achieves, has been inactive for >6years, and consists of ~60% merge commits, so even if the changes are wanted, it would be better to make a new clean PR.

**Pull request closed without merging**
