### PR TITLE
make editor use tiddler-editor-background color

### PR DESCRIPTION
**Pull request by BurningTreeC**
so we can customise it better if we don't like what we see

### CODE REVIEW

**Comment by Jermolene** [comment]
As noted in 87b3e470c2618801c9371eeb3cad6bcb12874d82, I think we  should defer these enhancements until v5.1.19

**Comment by BurningTreeC** [comment]
@Jermolene , thanks! I'd like to close this in favor of a ticket about text-editor customisability

**Comment by BurningTreeC** [comment]
Ping

**Comment by Jermolene** [comment]
Hi @BurningTreeC I'm happy to merge if you can resolve the conflict. Many thanks.

**Comment by BurningTreeC** [comment]
@Jermolene, the conflicts are resolved

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Pull request merged**
