### PR TITLE
Adding SolarizedDark Palette, updated SolarizedLight and one tiny UI fix

### PR DESCRIPTION
**Pull request by adithya-badidey**
- The SolarizedDark and updated SolarizedLight can be previewed here: http://adithyab.tiddlyspot.com/
-- The updated SolarizedLight can be used by selecting the "SolarizedLight 2" entry in the palettes setting
- The tiny ui fix can be seen at the above address too.

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @adithya-badidey many thanks for your contribution! With apologies for the bureaucracy, please could you prepare a separate PR to the 'tiddlywiki-com' branch with your signature for the Contributor License Agreement (see [contributing.md](https://github.com/Jermolene/TiddlyWiki5/blob/master/contributing.md)).

**Comment by pmario** [comment]
@Jermolene ... Please wait a little bit before merging. I think there are 1 or 2 improvements needed. But overall the are really good!

**Comment by BurningTreeC** [comment]
I do prefer @adithya-badidey's solarized light over mine (which is in the core)

**Comment by pmario** [comment]
ControlPanel-Plugins-tab

See the "Get More Plugins" button. ... It's almost invisible

AND

If you **hover** "Core: TiddlyWiki5 core" plugin in the list, it will also be almost invisible. 

-----------

That's also true for the SolarizedLight2 theme. It has the same issue. ... IMO SolarizedLight2 may replace SolarizedLight since BTC also would prefer it. IMO a second PR

**Comment by pmario** [comment]
I did test most of the TW config pages, popups and tiddler edit mode + popups. Implemented a TOC into the dem .. Everything looks good. except the issue above. 

Did test both the Dark and Light2 pallette. 

I hope I did test most of the UI stuff.

**Comment by adithya-badidey** [comment]
@Jermolene I have made a pull-request for the CLA.

@pmario Thanks for the testing and the feedback. Will update in a bit.

**Comment by adithya-badidey** [comment]
@pmario I have fixed the problems you highlighted. 

The new fixes are up on http://adithyab.tiddlyspot.com/ too.
The pull request will replace the old Solarized by BurningTreeC with the new version.

**Comment by pmario** [comment]
From my point of view both palettes look great. That's the first dark palette I think I could work with and the light version imo can be used in the evening. ... well done!

Did test it with FF latest in Windows 10 and ubuntu 20.04. 

The light palette imo works better with "snowwhite theme" and 
dark works better with "vanilla" theme. .... but that's just my point of view.

**Comment by adithya-badidey** [comment]
I generally use the SolarizedDark palette at all times. The Light palette uses the same colours as the dark one, except the non-accent colours are inverted pairwise. I use the solarized palette everywhere. Very good on the eyes :)

**Comment by pmario** [comment]
For me Solarized palettes have a strange contrast, which makes it hard to read.

I personally don't like dark themes. I prefer light themes. ... But your dark theme colours are well balanced for me. .. So it would be one that I could use. 

For the light theme I'd make the "Tiddler Background" and may be other backgrounds less yellow"ish", then I think I can use it too.

**Comment by Jermolene** [comment]
Thanks @adithya-badidey @pmario @BurningTreeC

**Pull request merged**
