### PR TITLE
Prevent long no-space field values from overflowing

### PR DESCRIPTION
**Pull request by felixhayashi**
The pictures contain complete dummy json data

After the fix

selection_513

Without the fix

selection_514

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @felixhayashi. I notice in the first screenshot that line breaks are appearing in the middle of words. I'm pretty sure that CSS supports breaking on word boundaries when possible, falling back to mid-work breaks.

**Comment by felixhayashi** [comment]
> I notice in the first screenshot that line breaks are appearing in the middle of words. I'm pretty sure that CSS supports breaking on word boundaries when possible, falling back to mid-work breaks.

I think it doesn't have a fallback startegy: either word  is either all or nothing:  `word-break: normal|break-all|keep-all|initial|inherit;`

So there are two solutions:

* Add spaces to stored json so it may break and we can forget this pull request. But storing spaces just for layout is not nice, data and layout should be a separate thing. However, long urls or other stuff might cause trouble as well. 
* Accept this pull request and accept that breaks may occur at any place. Then it fits the cell but may go against grammar rules.

I would go with the pull request since fields in almost all cases hold mere data that is not supposed to be viewed directly by the normal user. It is like looking at SQL rows in a webinterface. String-breaks are ok and the smaller evil, but cell overflows look really bad and hard to work with.

**Comment by Jermolene** [comment]
I think you may need to use the `word-wrap` property as well: https://developer.mozilla.org/en-US/docs/Web/CSS/word-wrap

**Comment by felixhayashi** [comment]
Hi @Jermolene 

> I think you may need to use the word-wrap property as well: https://developer.mozilla.org/en-US/docs/Web/CSS/word-wrap

But `word-wrap: break-word;` is already set in the current tw css and applies to `body.tc-body`. Or maybe I didn't understand your point...

**Comment by Jermolene** [comment]
I'd forgotten. With `word-wrap: break-word; ` in force, I don't understand why your first example shows the text broken mid-word in preference to breaking at word boundaries.

**Comment by felixhayashi** [comment]
> I don't understand why your first example shows the text broken mid-word in preference to breaking at word boundaries.

Me neither :confused:

**Pull request closed without merging**
