### PR TITLE
add theme font size settings to Open in New Window CSS

### PR DESCRIPTION
**Pull request by pmario**
This Pr fixes issue #7936

It sets the ControlPanel -> Appearence -> Theme Tweaks -> "[Font size for tiddler body](https://tiddlywiki.com/#%24%3A%2Fthemes%2Ftiddlywiki%2Fvanilla%2Fmetrics%2Fbodyfontsize)" setting, with the same specificity to the `tc-tiddler-body` element.

**New settings are active in the screenshot**

image

### CODE REVIEW

**Comment by gernert** [comment]
Hi @pmario. I am a little bit confused: I have to increase the font size for the tiddler body (so all for all tiddlers) to get it in line with the (bigger) table font size when displayed in a new window?

I did the following tests importing the tiddler $:/plugins/tg/layout/upgrade into your linked preview.

Note: borderless style and icn macro (for showing icons correctly within text) missing.

1) Font size for tiddler body 15 px (default), capturing the normal tiddler and the tiddler shown in a new window

Default_15px_normal_tiddler
Default_15px_new_window

2) Font size for tiddler body 16 px, capturing the normal tiddler and the tiddler shown in a new window

16_px_normal_tiddler
16px_new_window

It reveals a new problem when displaying this tiddler in a new window: the '1' is shown outside the table! In retrospect it could already be seen in the images I submitted with the issue.

For convenience of testing I add the tiddler $:/plugins/tg/layout/upgrade

[Upgrade_tiddler.json](https://github.com/Jermolene/TiddlyWiki5/files/14040860/Upgrade_tiddler.json)

**Comment by pmario** [comment]
>I have to increase the font size for the tiddler body (so all for all tiddlers) to get it in line with the (bigger) table font size when displayed in a new window?

May be I did miss something. I'll have an other look

**Comment by pmario** [comment]
It seems there was a problem with `<!doctype html>` missing in the New Window template code, so the browsers switch to  quirks-mode and reset TABLE font-size to initial. 

Details see at: https://github.com/Jermolene/TiddlyWiki5/issues/7936#issuecomment-1908819327 ff

**Comment by pmario** [comment]
@gernert -- There is a new preview available now. Can you test again?

**Comment by gernert** [comment]
@pmario - Can you give a link to the new preview? The link given earlier is the 'old' one.

**Comment by pmario** [comment]
@gernert -- The very first **vercel** link **almost at the top** should contain the latest preview.

https://tiddlywiki5-git-fork-pmario-7936-fix-font-size-05eb09-jermolene.vercel.app/

grafik

------

"vercel" also creates a new button after every push. So every change can be reviewed separately if needed. 

grafik

**Comment by gernert** [comment]
@pmario - It is OK now. Font size of tiddler in new window is the same as the table font size. The image below is made with the default settings. Increasing the 'font size for tiddler body' increases the text and table font size in the same way.

Note the '1' in the table is OK now as well!

New_window

**Comment by pmario** [comment]
@Jermolene -- I did test it with FF v122  and Edge latest - windows 11 pro

So you should **have a closer look at Safari**

**Comment by pmario** [comment]
@Jermolene please review

**Comment by pmario** [comment]
@Jermolene -- If this PR had been merged in time, it would have fixed the DOCTYPE problem handled with PR #8095 2 months ago.

**Comment by Jermolene** [comment]
Thanks @pmario

**Pull request merged**
