### PR TITLE
Improve filter documentation

### PR DESCRIPTION
**Pull request by aelocson**
I've completely rewritten the step-by-step guide to the notation, improved the formal syntax explanations, and moved some of the most fundamental introductory material to the concept tiddler.

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @aelocson

**Comment by tobibeer** [comment]
This is not entirely true...

let

...at least not for LetFilter...

http://let.tiddlyspot.com

...which uses the above for a whole range of `options`.

**Comment by aelocson** [comment]
The diagram you've quoted isn't what was in the pull request. The content that's now been accepted into the master repository says that a filter "method" consists of `[operator] [: suffix]`, with a note that the suffix is *usually* a field name.

**Comment by tobibeer** [comment]
thanks

**Pull request merged**
