### PR TITLE
Add Reveal.js plugin entry to Resources

### PR DESCRIPTION
**Pull request by sukima**
reveal.js enables you to create beautiful interactive slide decks using HTML.

With the power of TiddlyWiki and Reveal.js one can…

* …make an interactive tiddler with fancy animations
* …Make it go full screen for professional keynote
* …Distribute the slideshow with examples and additional resources in one HTML file

https://sukima.github.io/tiddlywiki-reveal-js/

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @sukima please target the "tiddlywiki-com" branch for documentation updates; they'll then get deployed automatically once merged.

**Comment by sukima** [comment]
@Jermolene Done. 😉  PR rebased. 🏁

**Comment by Jermolene** [comment]
Thanks @sukima

**Comment by kookma** [comment]
@sukima  This is one of the best plugin of 2020. Using integrated TW+Reveal.js creating presentation is a piece of cake! 
Thank you a million!

**Pull request merged**
