### PR TITLE
Remove spaces around the fold button

### PR DESCRIPTION
**Pull request by nameanyone**
...by removing newlines betwen widgets. Makes source harder to read but eliminates space characters from the end result.

### CODE REVIEW

**Comment by nameanyone** [comment]
Here is what I'm talking about: make sure fold button is visible and do a "select all".
screenshot_2015-12-28_22-32-40_crop

**Comment by nameanyone** [comment]
Trailing space is still there because of Github editor adding newline at the end of the file...

**Comment by Jermolene** [comment]
Hi @nameanyone the repo doesn't contain the newline; it could be that your editor or git client is adding the newline when it clones the repo. I know that Atom does this for example (see https://github.com/atom/atom/issues/4741)

**Comment by nameanyone** [comment]
Oh, good to know. Ready to merge then ;)

**Comment by nameanyone** [comment]
@Jermolene It did contain the newline. But I found a way to deal with that myself. See the last commit. Tested, no space on either side of the fold button now. I missed that the first time because the trailing space only appears if the button is not the last one on the toolbar.

**Comment by Jermolene** [comment]
Great thanks @nameanyone

**Pull request merged**
