### PR TITLE
action-setfield command

### PR DESCRIPTION
**Pull request by BurningTreeC**
allows setting fields of tiddlers to a specified value from the command line or scripts

### CODE REVIEW

**Comment by pmario** [comment]
I'm not really sure, what you try to achieve here?

There is a CLI command: https://tiddlywiki.com/#SetFieldCommand 
and a widget: https://tiddlywiki.com/#ActionSetFieldWidget

**Comment by BurningTreeC** [comment]
Hi @pmario - A cli command that allows setting a field of a tiddler to a certain value
The setfield command is strange ... it needs an existing tiddler ... setfield doesn't seem to allow just saying "set field <A> of tiddler <B> to <C>" - have you tried it?

**Comment by BurningTreeC** [comment]
what I want to achieve is being able to use `tw mywiki set "my tiddlah" "text" "hello world"`in my terminal, without having to write bash scripts for it

**Comment by pmario** [comment]
>what I want to achieve is being able to use tw mywiki set "my tiddlah" "text" "hello world"in my terminal, without having to write bash scripts for it

I see. ... 

rant :) But for my your command would set the field: "my tiddlah" to value: "text" ... and ... imo it breaks with the existing conventions. eg: `set` vs `--set` 

So I would prefer a completely new CLI, that allows options like `-s` as a short form or `--set` as the long form. ... 

eg. `tw ?` or `tw --help or -h` should give us a completel new experience independent form the `tiddlywiki` command. ... 

eg: `tw --init` should ask for the missing parameters and guide the user. 

I think you should start a new CLI project, where tiddlywiki is a dependency. Once it's tested it may be merged ...

**Comment by BurningTreeC** [comment]
@pmario 

>But for me your command would set the field: "my tiddlah" to value: "text"

really? I tested this and it did set the text field of tiddler "my tiddlah" to "hello world"...
I was thinking about a shell alias making `$PATH./tiddlywiki.js $MYWIKI --action-setfield "..." "..." "..."` to `tw <wikiname> <tiddler> <field> <value>` ... that's what I meant

**Comment by BurningTreeC** [comment]
... I'd like to be able to set that up, and I tried the setfield command which doesn't provide that functionality but a kinda strange one

**Comment by pmario** [comment]
>... shell alias

You mean ... Windows Power Shell. right? ;)

**Comment by pmario** [comment]
>... shell alias

With ubuntu I'm using "liquidprompt". ... It would be nice to have a more interactive CLI, that also shows additional info in the prompt line. .... 

At the moment for `git` it looks like this: 

```
[mario:~/git/tiddly/tiddlywiki/TiddlyWiki5] master(11)+ 2m52s ± 
-> 
```

So it could be: 

```
[mario:~] tw(mywiki) 7m0s $ 
-> 
```

Which would indicate that `myWiki` is the selected edition at the moment. ... 
With 

 - `tw select` ... you could be asked which one to choose from a list 
 - or
 - `tw select newEdition` .. would directly select it. 

I'd love this behaviour :)

**Comment by BurningTreeC** [comment]
@Jermolene @pmario 
I'm glad that we're talking about a new CLI here :+1: 
I'll close this and open a ticket

**Pull request closed without merging**
