### PR TITLE
Add focus-popups mechanism

### PR DESCRIPTION
**Pull request by BurningTreeC**
This PR does the following:

- It focuses a doNode specified with the `focus-selector` attribute for the `<$reveal>` widget when a popup is positioned
  - That can be used to focus a domNode within the popup, which is surrounded by `<$keyboard>` widgets
- Currently only the stamp dropdown uses this mechanism

This PR arises from the discusson at #5989 
@saqimtiaz what do you think?

### CODE REVIEW

**Comment by BurningTreeC** [comment]
@saqimtiaz @pmario 

This now uses a `<$focus>` widget to set focus to a domNode on render time
I now have made the image picker dropdown also navigatable by kb shortcuts

**Comment by saqimtiaz** [comment]
Beware of the bug described in #5979

**Comment by BurningTreeC** [comment]
> Beware of the bug described in #5979

Yes, I use the `insert-text` operation which should work fine but I'll test it further

**Comment by saqimtiaz** [comment]
The bug described in #5979 impacts insert-text as well. Test it with the framed editor.

**Comment by BurningTreeC** [comment]
> The bug described in #5979 impacts insert-text as well. Test it with the framed editor.

Ok @saqimtiaz , then I'll probably add your proposed solution to this PR

**Comment by BurningTreeC** [comment]
Closing this PR in favour of #6004 which resolves conflicts

**Pull request closed without merging**
