### PR TITLE
Add radio actions, th-radio-variables hook and fix label refresh problem

### PR DESCRIPTION
**Pull request by pmario**
@Jermolene please add this to 5.1.23 .. I desperately need it for 1 of my plugins. 

Docs will follow if merged!

 - This PR adds an "actions" parameter to the widget 
 - It adds a `th-radio-variables` hook call, which allows plugin authors to pass additional variables to the actions. 
 - it fixes the "label" refresh problem see: [Google groups](https://groups.google.com/g/tiddlywiki/c/IUjHMUxxfKo/m/tbeGOu0oBAAJ) thread

Simple test code:

```
\define newText() value: $(actionValue)$

\define radioActions()
<$action-sendmessage $message="tm-notify" $param="test-radio-simple-template" value=<<actionValue>>
    current=<<currentTiddler>> />
<$action-createtiddler $basetitle="test-x" $overwrite="yes" text=<<newText>>/>
\end

<$tiddler tiddler="$:/temp/test">
	<$radio field="id" value="a" actions=<<radioActions>> > a </$radio>|
	<$radio field="id" value="b" actions=<<radioActions>> > b </$radio>|
	<$radio field="id" value="c" actions=<<radioActions>> > c </$radio>|
</$tiddler>

<$radio field="id" value="d"  actions=<<radioActions>> > d </$radio>|
<$radio field="id" value="e" actions=<<radioActions>> > e </$radio>|
```

test-radio-simple-template

```
value = <<value>>
```

### CODE REVIEW

**Comment by pmario** [comment]
@Jermolene I'll add the same mechanism to the "range-widget" if you want?

**Comment by pmario** [comment]
By default this PR only sends the `<<actionValue>>` variable to the actions function, which is consistent with all other functions that are used atm.

**Comment by saqimtiaz** [comment]
@pmario this looks good for the most part and I think you should go ahead and add the docs to this PR for the `actions` parameter and the `actionValue` variable.

With regards to the new hook `th-radio-variables`, we probably have to consider that it will become a backwards compatibility concern later and something we have to maintain indefinitely. Especially if we want to revisit the original idea of the widget creating variables later this may not be prudent. 

I am not in favour of this hook unless perhaps it can somehow be implemented as a generic `get-action-variables` hook so that we do not need one such hook per triggering widget....

If we want to avoid the hook, one alternative would be for you @pmario to just subclass the radio widget for your plugin, and define your own `handleChangeEvent()` method. Minimal code and gives you a lot of flexibility.

**Comment by pmario** [comment]
>I am not in favour of this hook unless perhaps it can somehow be implemented as a generic get-action-variables hook so that we do not need one such hook per triggering widget....

You are right. It probably should be implemented as a generic hook: `th-get-action-variables`. Since we also pass `this` along, it should be possible to do everything.

**Comment by pmario** [comment]
@saqimtiaz .. I did have a closer look at the widgets, that allow us to have actions. The problem is, that the widget attribute init behaviour is fundamentally different. So the code for a generic hook will need complex code to make it work.

So I think using different hook names is way less overhead and will be much faster.

**Comment by saqimtiaz** [comment]
@pmario not only will having so many hooks be confusing for developers/documentation, but consider though that when a plugin adds such a hook, it will change the behaviour for all `radio` widgets in the TiddlyWiki. This could lead to unexpected and unwelcome side effects with user defined variables getting overwritten etc. Especially if the same pattern is applied to other widgets.

Also adding hooks doesn't make sense if this is supposed to be a temporary fix until we have time to re-consider the original PR. Once we have the hook it is there to stay. We cannot remove it later.

Instead if you subclass the `radio` widget as say `wikilabs-radio`, you can customize the behaviour as you like and not clash with the expected behaviour of other radio widgets. Your custom behaviour will apply to only your custom subclassed radio widgets, not to all radio widgets. So I do think that subclassing widgets is the better approach for these situations.

```
/*\
title: $:/wikilabs-radio.js
type: application/javascript
module-type: widget-subclass
\*/
(function(){

/*jslint node: true, browser: true */
/*global $tw: false */
"use strict";

exports.baseClass = "radio";

exports.name = "wikilabs-radio";

exports.constructor = function(parseTreeNode,options) {
	this.initialise(parseTreeNode,options);
}

exports.prototype = {};

exports.prototype.handleChangeEvent = function(event) {
	//customize variables here and handle change event
}

})();
```

**Comment by pmario** [comment]
OK .. I did remove the hook

**Comment by saqimtiaz** [comment]
@pmario I think this is good to go.

And we should create a ticket to continue the discussion on adding variables via attributes.

**Comment by pmario** [comment]
New issue: widgets, that allow "actions" should be able to pass on "user defined" variables and attributes #5155

**Comment by Jermolene** [comment]
Thanks @pmario @saqimtiaz

**Pull request merged**
