### PR TITLE
Use ascii escaping instead of unicode in new json store area

### PR DESCRIPTION
**Pull request by simonbaird**
Includes also a commit to fix some bad indenting.

### CODE REVIEW

**Comment by simonbaird** [comment]
Actually it seems like it doesn't work.. So maybe this is no good after all.

**Comment by simonbaird** [comment]
If I run this with bin/serve.sh I get this in the browser:

    Uncaught SyntaxError: Unexpected token x in JSON at position 439

So I suppose it doesn't work like I expected it would.

I probably won't spend more time on this, but I'll leave the PR open for a bit. Maybe there's an obvious reason it doesn't work. Any one have an idea?

Feel free to cherry pick the whitespace fix if you want, or lmk if you want that in a separate PR.

**Comment by pmario** [comment]
Simon. Did you see Jeremy's comment. https://github.com/Jermolene/TiddlyWiki5/pull/5708#issuecomment-871669306 It seems the JSON spec doesn't allow this

**Comment by simonbaird** [comment]
> Simon. Did you see Jeremy's comment. [#5708 (comment)](https://github.com/Jermolene/TiddlyWiki5/pull/5708#issuecomment-871669306) It seems the JSON spec doesn't allow this

Yeah, I did. I was a little premature with the commit and MR!

I did something this and felt like it was certain to work.. :S
````
> console.log('\x3C\u003c', '\x3C' == '\u003c')
<< true
````

Oh well...

**Comment by simonbaird** [comment]
Should have tried this:

````
> JSON.parse('"\\u003C"')
'<'
> JSON.parse('"\\x3C"')
Uncaught SyntaxError: Unexpected token x in JSON at position 2
> 
````

**Pull request closed without merging**
