### PR TITLE
Rudimentary fs.watch usage in filesystemadaptor

### PR DESCRIPTION
**Pull request by natecain**
Will only watch for changes on wiki files loaded during startup or created by runtime
    (Does not yet track renames/deletes)
    (Will not notice new files)
  May become confused by directory structure changes on some platforms
    (see node docs on fs.watch for caveats!)

### CODE REVIEW

**Comment by linonetwo** [comment]
Wow this looks very simple, I will try if this still works in 2021.

If performance is a problem, can I include 3rd.js (which bundles chokidar) in  https://github.com/tiddly-gittly/tiddlywiki-plugins/tree/master/plugins/linonetwo/watch-fs into tiddlywiki core? Will it be too large?

**Comment by pmario** [comment]
@linonetwo Your source doesn't contain any reference to the original js-code or library that has been used. ... So it's hard to verify the integrity. .. I did find: https://www.npmjs.com/package/chokidar .. which seems to be used by VSCode and others. .. 

2013 the / all file watchers where super buggy and did only work for some OSes. ... This may have changed since then. 

I think, if the file-watcher will be implemented as a server plugin, there wouldn't be a problem. If some changes in the core are needed to support the plugin IMO it should be worth a try.

**Comment by linonetwo** [comment]
I didn't found a standard way to package npm dependency into tw plugin, so I now just use rollup to pack all things into 3rd.js using this simple rollup config https://github.com/tiddly-gittly/tiddlywiki-plugins/tree/master/deps 

Surely it will lose dep version information...Hope there can be a better framework to build tw plugin.

**Comment by pmario** [comment]
TW uses this, to implement 3rd party stuff. eg: https://github.com/Jermolene/TiddlyWiki5/tree/master/plugins/tiddlywiki/codemirror/files

**Comment by linonetwo** [comment]
This is similar to mine, I was just minify chokidar into 3rd.js , and it has tons of dependencies, so rollup bundle them all together.

**Comment by pmario** [comment]
>This is similar to mine, I was just minify chokidar into 3rd.js , and it has tons of dependencies, so rollup bundle them all together.

Yes. I saw it, but "tons of dependencies" is the problem here. ... With TW we try to avoid 3rd party dependencies as good as we can. Especially with npm-libraries you have "dependency hell". 

The package-lock has about 3500 lines. ... chokidar has 7 dependencies. 

 - `anymatch` has 2 dependencies. `normalize-path and picomatch`
 - `braces` has 1 but is 4 levels deep with other dependencies. 

... That's a pain. ... Tiddlywiki's backwards compatibility is probably the strongest argument to use it. TW5 is 10 years old and you can still open a V5.1.0 wiki without problems. 

With every release, we have to make sure, that the dependencies don't break TW. ... If something is part of the core, it's very hard to get rid of it again. 

So the file-watcher should be a plugin and only a generic API, that is needed should go into the core.

**Comment by linonetwo** [comment]
Okay, I will try modify some of core API, and try pick up my watch-fs plugin again, instead of trying to put this feature into the core (as I can't let go chokidar).

**Pull request merged**
