### PR TITLE
Add default "tiddlywiki" styles to CodeMirror and Highlight.js

### PR DESCRIPTION
**Pull request by BurningTreeC**
This PR adds the "tiddlywiki" theme to CodeMirror. It's based on the solarized colors, but with the background and foreground from the current palette. The solarized colors fit well for dark and light backgrounds.

The same for the highlight.js styles. The back- and foregroundcolors are from the different palettes, the other colors from the solarized color scheme

### CODE REVIEW

**Comment by kookma** [comment]
@BurningTreeC 
Would you please upload a test to give a try?

**Comment by BurningTreeC** [comment]
@kookma 

[codemirror_highlightjs.zip](https://github.com/Jermolene/TiddlyWiki5/files/5610264/codemirror_highlightjs.zip)

**Comment by kookma** [comment]
@BurningTreeC  Thank you for sharing!
I tested on Windows 10, Chrome, Edge  and Firefox!

- CodeMirror: in both drak/light mode text is readable an has enough contrast.
- Highlight.js: tested for css, fortran, python and it works fine.

So, I confirm it works and has no issue with limited tests I have done.

Thank for all your efforts.

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Comment by BurningTreeC** [comment]
Thanks for merging @Jermolene, I hope the colors fit tiddlywiki well enough

**Comment by Jermolene** [comment]
> Thanks for merging @Jermolene, I hope the colors fit tiddlywiki well enough

I do wonder if this will be foolproof in the face of arbitrary palettes, but we need feedback from users really.

**Pull request merged**
