### PR TITLE
update normalze.css from 3.0.0 to 8.0.1

### LINKED ISSUE #4163: Update to latest normalize.css
We currently use v3.0.0 of [normalize.css](https://necolas.github.io/normalize.css/) but v8.0.1 is available.

### PR DESCRIPTION
**Pull request by pmario**
Update to latest normalize.css fixes #4163

### CODE REVIEW

**Comment by pmario** [comment]
I did test it with a side by side view in FF 68 latest. Navigating entry-page, sidebar TOC, sidebar more (all tabs), 

Couldn't see a visual difference.

**Comment by pmario** [comment]
using windows 10

**Comment by pmario** [comment]
Did also test Edge-beta, which is basically Chromium from MS. looks good there too.

**Comment by pmario** [comment]
@Jermolene ... bump

**Comment by Jermolene** [comment]
Thanks @pmario

**Pull request merged**
