### PR TITLE
New filter operator "days"

### PR DESCRIPTION
**Pull request by nameanyone**
Filter operator that selects tiddlers with a specified date field within a specified date interval.
As discussed in #1863 and #1895.

### CODE REVIEW

**Comment by nameanyone** [comment]
This is to replace or in addition to "recent" operator.

Alternative, "expanded" wording for `op-output`:
```
if <<.place D>> is positive, those input tiddlers in which field <<.place F>> is <<.place D>> days in the future or any time before that, including past; if <<.place D>> is negative, those input tiddlers in which field <<.place F>> is <<.place D>> days in the past or any time after that, including future
```

**Comment by nameanyone** [comment]
@Jermolene,

Sorry, I introduced another change 9924433, but not sure how to submit it as a separate pull request, short of forking the project again into a different account. Let me know if this "combo deal" is not acceptable, I'll revert the last change, to be re-submitted later.

**Comment by Jermolene** [comment]
Hi @nameanyone your change 9924433 was included in the pull request correctly. There's also a modification to the base stylesheet which shouldn't be here. Also, does this filter replace the "recent" filter? If so, perhaps we should delete the associated files in this same pull request?

**Comment by Jermolene** [comment]
Apologies @nameanyone I see that the 9924433 **is** the commit with the stylesheet modifications. I think that should be a separate pull request please.

**Comment by nameanyone** [comment]
Will cleanup and resubmit.

**Comment by tobibeer** [comment]
@nameanyone, seeing as 5.1.10 is coming up soon, is the days[] filter going to make it or will we keep recent[] after all?

**Comment by nameanyone** [comment]
This thread is dead. Resubmitted days[] as #1909. That includes removing recent[].

**Pull request closed without merging**
