### PR TITLE
Allow widget actions to propagate to children

### PR DESCRIPTION
**Pull request by ng110**
Modified invokeActions() in widget.js to recursively propagate action trigger event to all descendants.  Maintains compatibility with call from button widget.

Modified select.js to add action triggering capability.  Requires the widget.js modification to work.

### CODE REVIEW

**Comment by tobibeer** [comment]
Don't exactly know why but someone once quite emphasisised never to pull on master https://github.com/Jermolene/TiddlyWiki5/issues/1371#issuecomment-70701229 ...so, I believe you're going to have to close this one and create a branch.

**Comment by tobibeer** [comment]
hi @ng110, what I don't think your code handles is the case of there being html elements, so if you want that code to recursively traverse down the dom, you will have to wrap the recursion in na function and call it on any html elements that act as intermediary wrappers

**Comment by Jermolene** [comment]
@ng110 it's OK to send a pull request on your master, but it means that you'll need to create a fork for any further unrelated modifications you might make.

There is still an unresolved problem with extending the select widget to invoke action widgets, which is that the there will not have been a refresh cycle to propogate the new value of the select widget. (I saw some discussion on another ticket or in the groups, but can't find the reference).

The best approach might be to separate the modification to the select widget into a separate pull request. I'll merge the propogation change and then we can address the select widget issue.

**Comment by ng110** [comment]
Yes there was discussion on the refresh issue in the thread on the group that lead me into working on this.  I didn't go on to look at that matter though because I solved my immediate problem with a bespoke widget, and life got in the way of doing more general purpose solutions.

Cheers,

Neil.


---- On Tue, 27 Jan 2015 13:07:39 +0000 Jeremy Ruston&lt;notifications@github.com&gt; wrote ---- 

@ng110 it's OK to send a pull request on your master, but it means that you'll need to create a fork for any further unrelated modifications you might make.
 There is still an unresolved problem with extending the select widget to invoke action widgets, which is that the there will not have been a refresh cycle to propogate the new value of the select widget. (I saw some discussion on another ticket or in the groups, but can't find the reference).
 The best approach might be to separate the modification to the select widget into a separate pull request. I'll merge the propogation change and then we can address the select widget issue.

**Comment by Jermolene** [comment]
@ng110 are you in a position to revise the pull request by removing the modification to the select widget? It'll leave a more confusing history if I merge the entire PR and then revoke that change.

**Comment by ng110** [comment]
@Jermolene: I have committed a reverted select.js.  Do I also need to update the pull request or is that automatic?

Would it be better if I also reverted the widget.js change and resubmitted on a separate branch?

N.

**Comment by Jermolene** [comment]
Hi @ng110 no, this is fine to merge.

**Comment by tobibeer** [comment]
What happens if the action widgets are not immediate children in the dom?

**Comment by Jermolene** [comment]
As long as they are descendents in the widget tree then they'll be triggered.

**Comment by tobibeer** [comment]
Ok, thanks.

**Pull request merged**
