### PR TITLE
allows to define the tag for keyboard widget

### PR DESCRIPTION
**Pull request by tobibeer**
prerequisite for #2592

### CODE REVIEW

**Comment by pmario** [comment]
I made a line comment, but used the wrong empty.html to test it. So I did remove the line comment. sry. 

---

Tested again and now it LGTM

**Comment by tobibeer** [comment]
to do: add documentation for "available as of version such and such"

**Comment by tobibeer** [comment]
@Jermolene, added `<<.from-version "5.1.14">>`.

Could we perhaps change the .from-version macro and its usage? I would:

1. I don't see why this needs to be screaming in your face so much, I find that highly distracting, especially with more versions around
2. for the same reason, I would much prefer it at the end, since the focus of the documentation needs to be on the content, and some extra information that appears relevant at the time of publishing
3. even gently, it's still prominent enough, see http://2593-from.tiddlyspot.com

**Comment by pmario** [comment]
>Could we perhaps change the .from-version macro and its usage?

fully agree with the request. all points.

**Comment by tobibeer** [comment]
@Jermolene, could you perhaps comment on whether we update the .from-version macro & usage?

**Comment by Jermolene** [comment]
Hi @tobibeer @pmario 

> Could we perhaps change the **.from-version** macro and its usage?
> 1. I don't see why this needs to be screaming in your face so much, I find that highly distracting, especially with more versions around

Do you mean that you don't like the CSS styling? I agree that the current style is a bit aggressive, and I'm open to suggestions for refinement.

When you speak of "more versions around", the plan is to update the macro to change the styling according to how old the version is so that they fade away over time; eg one would only get the orange background for the most recent version. We can choose to suppress the display entirely if we want to, and just use it for tagging or searching.

> 2. for the same reason, I would much prefer it at the end, since the focus of the documentation needs to be on the content, and not some meta-information that appears relevant at the time of publishing

Hmm I'm not sure that I follow your argument. I think it makes more sense to have the tag at the start.

> 3. even gently, it's still prominent enough, see http://2593-from.tiddlyspot.com

You're suggesting just using italics, and no other styling? I think that's a bit spartan.

---

On reflection, I wonder if we should incorporate the version number in the macro name itself, to make it easier to redefine how each version is displayed:

```
\define .from-version-5.1.14()
...
```

**Comment by pmario** [comment]
>When you speak of "more versions around", the plan is to update the macro to change the styling according to how old the version is so that they fade away over time; eg one would only get the orange background for the most recent version. We can choose to suppress the display entirely if we want to, and just use it for tagging or searching.

As it is at the moment, I think it's way to aggressive, especially it is at the beginning of the text. If it fades out over time and it would be at the end of the line, I'd be OK (kind of)

So it's just to define "over time". I'd suggest 3 stages: 

 - stage 1: as it is atm
 - stage 2: remove color and put it at the end of the line. 
 - stage 3: Version that is suggested here

**Comment by Jermolene** [comment]
Hi @pmario 

> stage 2: remove color and put it at the end of the line.

But that wouldn't just be a change to the from-version macro, it would require each instance of the macro to be changed, wouldn't it?

**Comment by pmario** [comment]
@Jermolene .. you are right. Bad suggestion

**Comment by Jermolene** [comment]
Hmmm unless we made the macro take text to which it applies as a parameter, then we could move the marker to the start or end as we needed...

**Comment by tobibeer** [comment]
@Jermolene, we're quite getting off topic while the OP remains unmerged. However we handle some .from-version macro, we we shouldn't over-engineer, the KeyboardWidget quite begs for the ability to define a **tag**.

**Comment by Jermolene** [comment]
@tobibeer good point!

**Pull request merged**
