### PR TITLE
search-replace string operator

### PR DESCRIPTION
**Pull request by saqimtiaz**
This depends on #4964 (multiple operands for operators) and adds an operator to search and replace in strings.

### Syntax

`[[....]search-replace:<flag-list>:<regexp-mode>[searchterm],[replacement]]`

**suffix1 (flag-list):** optional
- `g` for global mode to replace all matches 
- `i` for case-insensitive mode

**suffix2 (regexp-mode):** optional
- `regexp` to interpret operand1 as a regular expression, absent to interpret as a string

**operand1 (search-term):**
- can be a regular expression with the regex-flag set, otherwise is interpreted as a string

**operand2 (replacement):**
- string to replace the search-term with.

### Examples
1) replace one string with another.
`{{{[[The quick brown fox jumps over the lazy dog]search-replace[dog],[cat]] }}}`
=>
`The quick brown fox jumps over the lazy cat`

2) replace all matches of a regular expression
`\define myregexp() e|o`
`{{{[[Hello There]search-replace:g:regexp<myregexp>,[]] }}}`
=>
`Hll Thr`

3) replace all matches of a string irrespective of case
`{{{[[Hello There]search-replace:gi[H],[]] }}}`
=>
`ello Tere`

4) the following also works with capture groups!
`\define names() (\w+)\s(\w+)`
`{{{ [[John Smith]search-replace::regexp<names>,[$2,$1]] }}}`
=>
`Smith,John`

**I welcome any feedback on syntax.**
The flag-list is modeled after the splitregexp operator.

### Question:
The operator requires two operands. What should the behaviour be when we do not have two operands? Currently it just returns the unchanged input.

### Potential next steps:
Once there is consensus on this, I will add tests which will also serve as further tests for multiple operands. In a separate PR I will add docs for this operator, as well as use this as an example to add to docs for multiple operands.

### CODE REVIEW

**Comment by BurningTreeC** [comment]
@saqimtiaz - I've been testing this operator in one of my wikies and it works great!

**Comment by Jermolene** [comment]
Thanks @saqimtiaz

**Comment by kookma** [comment]
@saqimtiaz  your discussion above is great and contains very useful examples, worth to be added to TW documentation!

**Comment by saqimtiaz** [comment]
@kookma I'm working on documentation for all the new filter operators.

**Comment by kookma** [comment]
Thank you Saq!

**Pull request merged**
