### PR TITLE
Bug in plugin Ordering

### PR DESCRIPTION
**Pull request by mklauber**
Comparing plugin A without a `plugin-priority` field to plugin B with a `plugin-priority = 1` results in the plugins being ordered B, A when it seems like they should be ordered A, B.

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @mklauber this is a tricky one. I think my original logic was that a plugin without a plugin-priority field was opting out of the priority mechanism, and would get pushed to the end of the list. I can see how that behaviour can seem inconsistent if approached with different expectations.

But I'm not sure whether we should change it at this point, if it's just a matter of the present behaviour being counter intuitive. Once again, it's a question of backwards compatibility. It seems plausible that there are wikis out there with carefully configured plugin ordering.

**Comment by mklauber** [comment]
Fair enough.  I'm not committed to this as a solution.  I ran into this issue because I was bundling up my theme tweaks for the vanilla theme into a plugin, and I couldn't get my "preferences" plugin to be rendered after the vanilla theme by setting a `plugin-priority` on my plugin.  I'd suggest as a solution all the standard plugins/themes having a defined `plugin-priority` of `0` unless another value is needed. 

If you like that solution, I'll rework this PR to achieve that.

**Comment by Jermolene** [comment]
Hi @mklauber 

> I couldn't get my "preferences" plugin to be rendered after the vanilla theme by setting a plugin-priority on my plugin. I'd suggest as a solution all the standard plugins/themes having a defined plugin-priority of 0 unless another value is needed.

I think that that may raise the same backwards compatibility issues.

The workaround I use in this particular case is to use a "list-after" field referencing the Vanilla base tiddler on your `$:/tags/Stylesheet` tiddler(s).

**Comment by mklauber** [comment]
Hi @Jermolene, unfortunately, list-after doesn't seem to be able to help here.  The issue is I've got two plugins with the same tiddler in them (`$:/plugins/mklauber/preferences` and `$:/themes/tiddlywiki/vanilla`) both containing `$:/themes/tiddlywiki/vanilla/metrics/tiddlerwidth` and I need mine loaded second so it's shadows override the base theme.  

Looking at the code, there's no check against list-after during `unpackPluginTiddlers` so I can't control plugin order using that.

**Comment by pmario** [comment]
>`$:/zzz/plugins/mklauber/preferences` as this changes the order things are listed in during unpackPluginTiddlers.

Ouch!  ... There should be a better way ;)

**Comment by Jermolene** [comment]
Hi @mklauber maybe we should explore whether the quick fix you suggested of giving a default plugin priority to the core plugins could be done without any unexpected side effects?

**Comment by mklauber** [comment]
I'll take a run at it.  Anything in particular you think I should test?

**Comment by mklauber** [comment]
I fixed the problem just for the two built in themes.  I don't know how many of the built in plugins we wanted to implement this on, and `$:/core` already has `plugin-priorty: 0` on it.

**Comment by Jermolene** [comment]
Hi @mklauber I'm inclined to merge this, post a pre-release and then ask in the dev group for people to test it.

**Comment by mklauber** [comment]
I'm fine with that.

**Comment by Jermolene** [comment]
Sorry for the delay @mklauber

**Comment by CrossEye** [comment]
This has [come up again][tt]:

The current behavior means that a plugin writer cannot override a tiddler from another plugin, unless

  - The base tiddler has a `plugin-priority` field
  - or, The overriding tidder has a name alphabetically later than the overridden one.

And in that latter case the overriding tiddler can also not declare its own priority.

I understand that fixing this might have some backward-compatibility problems.  But AFAICT, the only case where this would override intentional behavior is if a user went to override a plugin with priority `n` not by choosing a higher priority but by not including a priority at all.  That sounds like a vanishingly small use case.  But there is the fact that it might break unintentional behavior that the user has come to rely upon.  I have no idea how common that might be.

Is there any guidance available on how to choose appropriate priorities?


  [tt]: https://talk.tiddlywiki.org/t/plugin-priority-with-two-same-name-tiddlers/8429

**Comment by saqimtiaz** [comment]
I have hit my head against this issue a few times as well when wanting to override a plugin that does not set a `plugin-priority` field.

**Comment by Jermolene** [comment]
I agree that this needs fixing. It's hard to see how any fix can be totally backwards compatible, so I'd be interested in ideas for the least harm we can get away with.

**Pull request merged**
