### PR TITLE
Fix focusPopups like described in #4654

### PR DESCRIPTION
**Pull request by BurningTreeC**
this PR fixes the sticky focusPopups of tiddlers in edit mode and the sidebar search by cancelling all popups when the input gets focus and before an eventual focusPopup is triggered

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @BurningTreeC thanks, the changes look reasonable at a first glance, but given the brittleness of the popup mechanism I think we'll have to do some fairly careful testing of this.

For example, there are a few UI elements that don't look like popups but are implemented that way (eg the tiddler info panel). It might be helpful to identify and verify that these cases aren't impacted by these changes.

**Comment by BurningTreeC** [comment]
The PR can be tested [here](http://focus-popups-fix.tiddlyspot.com/) @Jermolene

**Comment by BurningTreeC** [comment]
Perhaps this could be realized with a `tv-config-cancel-popups` variable like the `tv-config-wiki-links`?

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Comment by Jermolene** [comment]
Hi @BurningTreeC I only thought to try it after merging, but I think this breaks usage of text inputs within dropdowns.

**Comment by BurningTreeC** [comment]
Yes @Jermolene, it isn't thought for text inputs within drop downs, only for inputs with the `cancelPopups=yes` attribute

**Comment by Jermolene** [comment]
Thanks @BurningTreeC.

**Pull request merged**
