### PR TITLE
Edit Template: hide empty fields table

### PR DESCRIPTION
**Pull request by saqimtiaz**
Alternative approach to #5063 

@BurningTreeC please confirm if this is OK. If you feel it needs further tweaking, just copy this to your PR and go at it.

The new filter syntax is fun :D

### CODE REVIEW

**Comment by BurningTreeC** [comment]
@saqimtiaz I'm not at my desk, but I'm wondering if the field add animation when adding the first field works with your approach

**Comment by saqimtiaz** [comment]
@BurningTreeC no idea, I never pay attention to animations. But you could also use the same filter to set a class for the table, without the need for a separate set widget.

**Comment by pmario** [comment]
I don't think, that an animation is needed here for the first field. If I add a new field, I'm already 100% focused to the field area.

If there are many fields already it's OK, since it shows where the new field goes to.

**Comment by saqimtiaz** [comment]
@Jermolene #5063 does the same thing as this, but preserves animation for the first field added, at the cost of adding a CSS class.

I don't have a preference so please choose whatever you consider appropriate.

**Comment by BurningTreeC** [comment]
Hi @saqimtiaz , #5063 preserves animation for ALL field, where this PR here I think removes the animations

**Comment by saqimtiaz** [comment]
This PR results in no animations for the first field added, that is correct.

**Comment by BurningTreeC** [comment]
@saqimtiaz, this PR results in no animations for all fields as far as I have tested now

**Pull request closed without merging**
