### PR TITLE
Communicate on the revival of vis.js Timeline plugin

### PR DESCRIPTION
**Pull request by kixam**
Hello Jeremy,

Thank you for your great tool, I use it every day at work.

For my purpose, I needed to be able to display my tiddlers into a timeline. I have been using emkay's plugin that is based on vis.js, but at some point last year it stopped working with the later versions of tiddlywiki. So, since emkay confirmed he does not have time to maintain his plugin, I decided to revive this project. I reached a point where I am ready to share it with the community.

Please consider adding this little post on the next release of tiddlywiki for the community to know that they can have timelines in their tiddlywikis again.

Keep up the good work,

Regards

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @kixam that's great, I'm delighted for people to add their own links like this.

One minor piece of bureaucracy is that we need you to sign the Contributor License Agreement, as described in `contributing.md` in the root of the repo.

**Comment by pmario** [comment]
The plugin is great btw :)

**Comment by kixam** [comment]
Here you go :)

**Comment by felixhayashi** [comment]
+1

**Comment by Jermolene** [comment]
Thanks @kixam 

I'll update tiddlywiki.com with the change as soon as I can.

**Comment by Jermolene** [comment]
Hi @kixam I've pushed the new content to tiddlywiki.com:

http://tiddlywiki.com/#vis.js%20Timeline%20by%20emkay%2C%20revived%20by%20kixam

**Comment by kixam** [comment]
Hi @Jermolene , thanks, I hope this will be useful to the community

**Pull request merged**
