### PR TITLE
Make tags in tags-dropdown change bg-color on hover

### PR DESCRIPTION
**Pull request by BurningTreeC**
This PR makes the tags in the tags-dropdown (edit-mode) change their background-color to the primary color on hover

### CODE REVIEW

**Comment by saqimtiaz** [comment]
@BurningTreeC  appreciate all the attention to detail! A screenshot of the before/after would be very helpful.

**Comment by BurningTreeC** [comment]
Note: the mouse hovers on a tag in the tags-dropdown

Before:
Bildschirmfoto von 2020-06-12 09-44-53
After:
Bildschirmfoto von 2020-06-12 09-44-29

**Comment by saqimtiaz** [comment]
@BurningTreeC Thank you!

**Comment by BurningTreeC** [comment]
Now this PR uses the correct class `tc-btn-invisible` instead of (mistake) `tc-button-invisible`

**Pull request closed without merging**
