### PR TITLE
Use promise resolve when calling loadTiddlersNode

### PR DESCRIPTION
**Pull request by Arlen22**
Per our discussion here and @sukima's comment in particular(https://github.com/Jermolene/TiddlyWiki5/pull/2914#issuecomment-311993973), I added this pull request to implement those changes. If this change is acceptable, then I won't need https://github.com/Jermolene/TiddlyWiki5/pull/2914.

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @Arlen22 Promises are an EcmaScript 6 feature; currently we only use EcmaScript 5 features in TW5. Moving to ES6 is a step that we need to take carefully, because it has an impact on the platforms that will run TiddlyWiki.

Apologies for being slow to catch up with these threads. The changes being discussed are huge, and will necessarily require careful review. Where's the best summary of your overall goals with this work?

**Comment by danielo515** [comment]
If we are including something like the crypto library gy default I don't see a reason to don't include also a promise polifill by default too

**Comment by Jermolene** [comment]
> If we are including something like the crypto library gy default I don't see a reason to don't include also a promise polifill by default too

I've tried to keep polyfills out of TiddlyWiki; they tend to be brittle, and frequently don't fit the spec 100%. For browser features like drag and drop it's no problem to make a polyfill into a plugin.

Generally, I favour the core using a conservative dialect of JS to aid maximum comprehensibility and compatibility.

**Comment by Arlen22** [comment]
Well, I was thinking that we would only use it on the node side of things (in `if($tw.node)`). Node has full support for promises since v4, which shouldn't be too hard to require. But whatever. 

However, the promises polyfills are probably the most used ES6 polyfills out there I would guess, so they should be mature and stable. And if we want to bring them into Tiddlywiki in the browser, I could see them being useful for us devs.

**Comment by Arlen22** [comment]
>Where's the best summary of your overall goals with this work?

Well, all my recent PRs relate to TiddlyServer. And for this one and the related ones, I am thinking scalability on a large server. In short, I want to serve other requests for other TiddlyWikis while waiting for this one to load. 

In my tests, when I converted the `$tw.loadTiddlersNode` section to async IO, boot times barely improved, but a CPU profile showed a lot of "program" time where the event loop could be doing other things. 

For TiddlyServer's current user base where it is all personal wikis, this is not really needed, so if this is too big of a switch, I can let it go. I don't want to be a pain :) and I really enjoy working with TiddlyWiki :)

**Comment by sukima** [comment]
When I wanted to use Promises in my wiki I just added a polyfill as a plugin. Though the use case was another plugin I was working on.

**Comment by sukima** [comment]
>I am thinking scalability on a large server. In short, I want to serve other requests for other TiddlyWikis while waiting for this one to load.

You can likely get the scale you want without modifying the core by simply calling the TiddkyWiki code through `child_process.fork()`.

That would fix the initial scale problem. Then worry about refactoring when your scale problem grows beyond that.

**Comment by Arlen22** [comment]
> You can likely get the scale you want without modifying the core by simply calling the TiddkyWiki code through child_process.fork().
> 
> That would fix the initial scale problem. Then worry about refactoring when your scale problem grows beyond that.

I don't need it for single user mode. Opening 500 wikis in your browser tabs will crash your browser faster than you can load all those TiddlyWikis. Opening 50 will only take about 2 minutes. And that is only the very first request for each wiki. And I doubt wants to access 50 at once. So I don't need it there.

This more applies to the future of TiddlyWiki because I need it when dealing with more than one user. But at that point I will probably include a carefully vetted and bundled version of TiddlyWiki that has core and all the plugins bundled. But by then we will probably be needing a more robust TiddlyWeb server anyway so this may be a moot point. I don't know :)

**Comment by Arlen22** [comment]
>I've tried to keep polyfills out of TiddlyWiki; they tend to be brittle, and frequently don't fit the spec 100%. For browser features like drag and drop it's no problem to make a polyfill into a plugin.

I would say Promises is the exception. It is now part of the ES6 spec, and there are ES6 polyfills available for this one. I would not call them brittle -- a little testing should easily tell us whether they will work or not. And Promises is not like some other things, in that it is just a class with a couple methods rather than depending on disparate browser features. 

Personally, I would like to see Promises available in TiddlyWiki, at least in boot.js, as I feel there is not enough ability to build drop-in replacement functions that change the sync/async flow of the boot process.

The number of stars and forks on Github, as well as general activity, should be a good indication of whether a library is stable, I would think.

**Pull request closed without merging**
