### PR TITLE
Static export macro

### PR DESCRIPTION
**Pull request by welford**
Fixing issues Jeremy highlighted with the last pull request #1509.

It now passes the bin/test.cmd and should correctly output to passed through path when no macro is present,

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @welford looks good

**Comment by welford** [comment]
need to make one change still...

**Comment by Jermolene** [comment]
Whoops! I've already merged it I'm afraid...

**Comment by Jermolene** [comment]
I'm not sure whether that means you'd have to open a new pull request.

**Comment by welford** [comment]
no worries, a new pull request will do, had a small oversight in the rendertiddlers command

**Pull request merged**
