### PR TITLE
add data-title and data-tags to the tiddler DOM in ViewTemplate

### PR DESCRIPTION
**Pull request by pmario**
~~DOCUMENTATION: -> TODO~~

as discussed in: https://groups.google.com/d/msg/tiddlywiki/NiS6c9yO-Lg/Avw34W5lBwAJ
and https://groups.google.com/d/msg/tiddlywiki/NiS6c9yO-Lg/0wgTP3wACAAJ

This new version adds `data-title`, which is useful if users use the TW namespace for styling. Info about possibilities can be found at [mdn help](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors) and [the spec](https://www.w3.org/TR/css3-selectors/#attribute-selectors)

eg: blue border for every tiddler that starts with: ``$:/tags/

```
[data-title^="$:/tags/"] {
  border: 1px solid blue;
}
```

---------

The second element added is: `data-tags` which will fix:  #958 since no escaping is needed anymore. 

IMO we should `depricate tc-tagged-`, since `data-tags` is able to completely replace it, without the disadvantages.

### CODE REVIEW

**Comment by Jermolene** [comment]
Great stuff @pmario, thank you. I agree about deprecating tc-tagged. I'll look forward to merging when you've done the docs.

**Comment by pmario** [comment]
[Docs done. visit tiddlyspot](http://2737.tiddlyspot.com/#Using%20Stylesheets:%5B%5BUsing%20Stylesheets%5D%5D%20%5B%5BHard%20Linebreaks%20with%20CSS%20-%20Example%5D%5D%20%5B%5BHard%20Linebreaks%20with%20CSS%5D%5D%20%5B%5BHow%20to%20apply%20custom%20styles%5D%5D%20%5B%5BCustom%20styles%20by%20data-tags%5D%5D%20%5B%5BCustom%20styles%20by%20title%5D%5D%20%5B%5BCustom%20data-styles%5D%5D%20%5B%5BAttribute%20Selectors%5D%5D%20%5B%5BCustom%20styles%20by%20tag%5D%5D%20%5B%5BDeprecated%20-%20What%20does%20it%20mean%5D%5D)

**Comment by tobibeer** [comment]
@pmario, this is great stuff. May I suggest, rather than having a visible tag like **data-tags-hardlinebreaks**, can we perhaps (in addition) introduce / add a `data-tags` or `tc-data-tags` field where one could define a list of titles used as data tags?

**Comment by tobibeer** [comment]
It's just, tags are a very prominent thing in TiddlyWiki and I think that everything purely used for triggering presentation / layout / style must not be a directly visible feature in TiddlyWiki... with the exception of system tiddlers, perhaps... since those generally are not part of the usual content.

**Comment by pmario** [comment]
> visible tag like data-tags-hardlinebreaks, 

The PR is about replacing / deprecating `tc-tagged-xxxx` attribute, that causes problems with escaping. see #958 

... and there is the second mechanism `data-title` which can be used for styling too. ... It's meant to be used for "single tiddlers" but with the `data-title*^$|=` mechanism there is regexp like selection for TW namespaces. 

------------- 

I need to think about the "special field".

**Comment by tobibeer** [comment]
I understand. I just found it odd to see tags called **data-tags-hardlinebreaks** or **data-tags-test**, because I don't think there should be general purpose tagging via prominent system-like tags.

If one just wanted tiddlers tagged "Learning" to be styled a certain way, sure thing. But if one would be thinking it has to be tagged "Learning" and also "data-tags-my-fancy-style"... then the lesson would be a bit misguided.

**Comment by pmario** [comment]
>I understand. I just found it odd to see tags called data-tags-hardlinebreaks or data-tags-test, because I don't think there should be general purpose tagging via prominent system-like tags.

I just used those names, so I don't create conflicts with the existing tags. I could have used any existing tags, but that would have created "unexpected behaviour" eg: blue border for "HelloThere" and so on. ...

**Comment by pmario** [comment]
I can rename the tags named: `data-tags-hardlinebreaks` into `example-hardlinebreaks` and `example-test`. ... Plus some info that it can be any name. eg: Learning

**Comment by pmario** [comment]
[TS updated. visit tiddlyspot](http://2737.tiddlyspot.com/#Using%20Stylesheets:%5B%5BUsing%20Stylesheets%5D%5D%20%5B%5BHard%20Linebreaks%20with%20CSS%20-%20Example%5D%5D%20%5B%5BHard%20Linebreaks%20with%20CSS%5D%5D%20%5B%5BHow%20to%20apply%20custom%20styles%5D%5D%20%5B%5BCustom%20styles%20by%20data-tags%5D%5D%20%5B%5BCustom%20styles%20by%20title%5D%5D%20%5B%5BCustom%20data-styles%5D%5D%20%5B%5BAttribute%20Selectors%5D%5D%20%5B%5BCustom%20styles%20by%20tag%5D%5D%20%5B%5BDeprecated%20-%20What%20does%20it%20mean%5D%5D)

**Comment by tobibeer** [comment]
Hi @pmario, ok I understand now. While I think we do want to trigger style based on tagging, I would think we should not use "extra tags" that only exist to achieve the result, at least not in a visible manner... hence the field proposal. So, I think this kind of "hidden" option would complete this great package.

**Comment by pmario** [comment]
>Hi @pmario, ok I understand now. While I think we do want to trigger style based on tagging, I would think we should not use "extra tags" that only exist to achieve the result, at least not in a visible manner... hence the field proposal. So, I think this kind of "hidden" option would complete this great package.

IMO we don't need to add additional tags, just to activate styling.

 - If a tiddler has no tags, but needs styling use: `data-title` as CSS selector
    - There is only one tiddler 
 - If a user wants to style system tiddlers in a custom way: use: `[data-title^="$:"/]` as a selector
    - using the TW namespace functionality
 - If the user wants special behaviour for tagged tiddlers. eg: Learning
    - use: `[data-tags*="Learning"]` as CSS selector. 

The names I'm using are only used for documentation purpose, without changing the existing wiki. I don't want, that the docs has side effects. 

--------

The only real problem I found is, that it's impossible to say: `[data-tags*="[[tag with spaces]] secondTag"]` since the core doesn't sort the tags field. That's why the order can also be `secondTag otherTag [[tag with spaces]]` So the selector doesn't match anymore :(

So we don't have the possibility to say: I want special styling if a tiddler is tagged `a` AND `b`. At the moment we only have OR, which will be a problem. ... This PR has the exact same functionality as the existing core. ... just no escape mechanism needed, which is (kind of) broken in the existing core. 

That's the only reason, why we have to think about a special field, that is "sorted". The problem is, that this will need very low level code, that IMO shouldn't be part of this PR. .. May be a new one!

----

**Comment by tobibeer** [comment]
Hi, @pmario, while your example tags may not have the intention of suggesting some special "data-tags-foo" tagging construct, I would suspect about 50% or more of all users would simply think that's what they need. So, imho... the example tags should at least not contain the prefix "data-tags-", e.g. "StyledByTag" or whatever... anything that looks more like an example than a naming convention.

**Comment by pmario** [comment]
They are named `example` already, but I forgot to mention, that I did update tiddlyspot. So should be more obvious now.

**Comment by danielo515** [comment]
Thank you for this @pmario 

I would like to have another mechanism to add `data-stuff` to a tiddler, not just by tags or title, because as @tobibeer has suggested, those are elements very prominent and that are part of the actual information a tiddler has. I would like to have some field hidden on the default viewTemplate that I can use just for styling purposes.

In any case, this is a very good thing!

**Comment by pmario** [comment]
I am inclined to add a `data-stuff` element, instead of `data-title` since imo it is kind of redundant then. .. 

We also have the bulk-renaming function now. So it's more likely, that users change their tiddler names, since it has less side effects. .. but it may break Stylesheets. 

@Jermolene what do you think: Remove `data-title` and add `data-css-class` instead.  So the field name would be: `css-class`

@tobibeer @danielo515 ... better, more generic field names, that don't cause conflicts.

**Comment by tobibeer** [comment]
@pamario, to me, `data-title` is a thing of its own

Perhaps a field called `data-class` could allow to define css classes applied to the tiddler element.

**Comment by danielo515** [comment]
Would you consider using prefixes ? Like data-tc-something , that aderes to the syntax and will avoid collisions

**Comment by danielo515** [comment]
About the other topic I don't see why not include both things, the title and the something. The title will be easier for regular users while power users/plugin creators could keep more flexibility.

**Comment by tobibeer** [comment]
While `data-title` does not require you to add anything to the tiddler, some `data-class` or `tc-class` or whatever allows you to specifically style an individual tiddler by assigning it a predefined class.

Both use-cases have their merits, neither covers the other.

**Comment by pmario** [comment]
>While data-title does not require you to add anything to the tiddler, some data-class or tc-class or whatever allows you to specifically style an individual tiddler by assigning it a predefined class.
>
>Both use-cases have their merits, neither covers the other.

That's right. ... 

The problem, that I have with a special field for "styling" purpose is: "the special field for styling purpose" ... 
Some users including you don't want to "misuse" tags for styling only. 

So we should use, whatever is already there. ... Now there is a [new discussion going on in the group](https://groups.google.com/forum/#!topic/tiddlywiki/J0MjGWFiPNU), with a new usecase. There is a field named: `rank`, which can hold different values eg: `species` as described in the thread. 

So we could tell the user s/he should use `tc-class` field instead of rank. ... But that's counter intuitive and doesn't fit, if there is a second field, that should be used. ... 

So the idea is now: We dynamically create the stylesheet. It wouldn't need new behavior. **This PR is completely efficient**. The style-sheet can look like this: 

```
<$list filter="[rank[species]]"> 
[data-title^="<$view field=title/>"] .tc-tiddler-body {
    column-count: 2;
}
</$list> 
```

This creates a CSS rule for every tiddler-title, that has a field `rank` and value `species`. 

I personally would go with [title-prefix](http://2737.tiddlyspot.com/#Custom%20styles%20by%20title), but that's just my opinion.

**Comment by twMat** [comment]
@Jermolene 

This is such a valuable addition. Please merge.

Applause for @pmario !

**Comment by tobibeer** [comment]
@pmario: While you've put quite some effort into adding more flexibility, your `data-foo` method comes with similar limitations as `tagged-foo`, i.e. css classes cannot be assigned or identified flexibly enough.

I therefore set out to pursue a different route for which I may end up proposing an alternative implementation for the same underlying wish.

Please take a look at http://apply.tiddlyspot.com and let me know what you think.

**Comment by pmario** [comment]
>@pmario: While you've put quite some effort into adding more flexibility, your data-foo method comes with similar limitations as tagged-foo, i.e. css classes cannot be assigned or identified flexibly enough.
>
>I therefore set out to pursue a different route for which I may end up proposing an alternative implementation for the same underlying wish.
>
>Please take a look at http://apply.tiddlyspot.com and let me know what you think.

That's nice, but this should be a completely new PR! It has nothing to do with the initial OP! 

[As you wrote](http://apply.tiddlyspot.com/#Apply) at:

>This may not only be useful for css classes. This way you can dynamically apply a whole range of template rules that render additional content ...before.

That's out of the range of this PR!

I did want to change 1 line in the existing ViewTemplate, which deprecates a "broken" mechanism, that only causes problems.

https://github.com/pmario/TiddlyWiki5/blob/6d589e2cd6e55f146e39623261a7eefad8fa480d/core/ui/ViewTemplate.tid#L9

The new mechanism in the PR doesn't need new filter functions, where we don't know and can't predict the side effects, performance wise. 

The "old" tagging class mechanism needs to be deprecated!!!!!!!!!!!!!!!! It's broken!!!!!!!!!!!!!!!
That's all, what this OP should be!

**Comment by pmario** [comment]
I'll close this PR since it can't be merged anyway. We can still use it for discussion.

**Comment by tobibeer** [comment]
> That's out of the range of this PR!

While true, I'm always a fan of foundations that allow you to do more than cater a narrowly, strictly defined usecase. In other words, I wouldn't see it as a short-comming but rather as a beneficial side-effect.

Also, for performance sake, the general rule should definitely be that one should try to define as few classes as necessary. If you end up having 200 of those, you might just be doing something wrong, conceptually.

On the other hand, it would be good to do some performance testing for that case.

I guess the peformance implications are not all that big since we're talking about loading an individual tiddler into the story.

> The "old" tagging class mechanism needs to be deprecated!!!!!!!!!!!!!!!! It's broken!!!!!!!!!!!!!!!
That's all, what this OP should be!

It seems the one thing "broken" about it is merely that the titles become encoded in an invalid way.

Instead of introducing a new mechanism, we might as well fix the old one that is broken. This code in [$:/core/modules/widgets/tiddler.js](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/tiddler.js) does not yield defective classes:

```
/*
Create a string of CSS classes derived from the tags of the current tiddler
*/
TiddlerWidget.prototype.getTagClasses = function() {
	var tiddler = this.wiki.getTiddler(this.tiddlerTitle);
	if(tiddler) {
		var tags = [];
		$tw.utils.each(tiddler.fields.tags,function(tag) {
			tags.push("tc-tagged-" + encodeURIComponent(tag));
		});
		return tags.join(" ");
	} else {
		return "";
	}
};
```

Why? Because this is an invalid class definition in css:

```
.tc-tagged-Filter%20Operators {background:red; }
```

So, rather than use a simply wrong encodeURIComponent(), we should instead replace any blanks and other basic non-letter-characters, except dashes, with underscores and that's basically it!

Because, the following **is** valid css:

```
.tc-tagged-Filter_Öperätors {
background:red;
}
```

For example, something as simple as the [answer here](https://stackoverflow.com/a/7627603) would be a simple step to make it work as it should:

```
function makeSafeForCSS(name) {
    return name.replace(/[^a-z0-9]/g, function(s) {
        var c = s.charCodeAt(0);
        if (c == 32) return '-';
        if (c >= 65 && c <= 90) return '_' + s.toLowerCase();
        return '__' + ('000' + c.toString(16)).slice(-4);
    });
}
```

This could / should even be returned by a helper macro, e.g.

```
<<makeSafeForCSS "Some Stränge Tötle?!?">>
```

**Comment by pmario** [comment]
>For example, something as simple as the answer here would be a simple step to make it work as it should:

Replacing `%20` with `_` is no fix. IMO it's as broken as the existing mechanism. Users don't know, how the system is going to replace the characters. `data-tags` attributes can work with every tiddler title. ... No limits. 

Have a closer look: ... "Safe for CSS" but "broken" for users.

```
makeSafeForCSS("сломанный")
/*
__0441__043b__043e__043c__0430__043d__043d__044b__0439
*/

makeSafeForCSS("خَرْبان")
/*
__062e__064e__0631__0652__0628__0627__0646
*/
```

Also the `data-` attributes give us more possibilities to access the stored values from widgets with dataset().

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#attr-dataset ... See `HTMLElement.dataset` ...

[TS updated. visit tiddlyspot](http://2737.tiddlyspot.com/#Using%20Stylesheets:%5B%5BUsing%20Stylesheets%5D%5D%20%5B%5BHard%20Linebreaks%20with%20CSS%20-%20Example%5D%5D%20%5B%5BHard%20Linebreaks%20with%20CSS%5D%5D%20%5B%5BHow%20to%20apply%20custom%20styles%5D%5D%20%5B%5BCustom%20styles%20by%20data-tags%5D%5D%20%5B%5BCustom%20styles%20by%20title%5D%5D%20%5B%5BCustom%20data-styles%5D%5D%20%5B%5BAttribute%20Selectors%5D%5D%20%5B%5BCustom%20styles%20by%20tag%5D%5D%20%5B%5BDeprecated%20-%20What%20does%20it%20mean%5D%5D) should be able to handle cyrillyic and arabic chars. 

```
[data-tags*="خَرْبان"] { border: 3px solid blue; }
```

Works as expected. No surprises for the user.

**Comment by tobibeer** [comment]
> IMO it's as broken as the existing mechanism. Users don't know, how the system is going to replace the characters.

That is simply not true. If you use custom CSS classes based on tags, chances are you are comfortable launching your browser's inspect tools and check what class the tiddler has. And that's one probem solved.

You see... this is **no problem whatsoever**.

```
makeSafeForCSS("сломанный")
/*
__0441__043b__043e__043c__0430__043d__043d__044b__0439
*/
```

A user can easily comment in CSS. Done.

**Comment by tobibeer** [comment]
So...

`makeSafeForCSS("мне нравится")`

> `__043c__043d__0435-__043d__0440__0430__0432__0438__0442__0441__044f`

```
/*форма́т: мне нравится*/
.__043c__043d__0435-__043d__0440__0430__0432__0438__0442__0441__044f {
color:green;
}
```

**Comment by tobibeer** [comment]
In fact, `makeSafeForCSS("<some title>")` could even be displayed in the info panel for each tiddler, so you can look it up rather than guess.

**Pull request closed without merging**
