### PR TITLE
fix HelloThere layout for calls to action

### PR DESCRIPTION
**Pull request by tobibeer**
should only be at most 4 images per row, centered

the visuals of seeing 6 in the first row and 2 in the second is rather displeasing

### CODE REVIEW

**Comment by tobibeer** [comment]
Proposal:

image

State of affairs:

image

**Comment by pmario** [comment]
For me it's only one row. So no problem here. 

github-response

**Comment by tobibeer** [comment]
> For me it's only one row. So no problem here.

Think of it as looking through the design from the perspective of other visitors. Do you feel that at most four images per row are a problem? If not, those 6 and 2, they are, for my visual tastebuds.

**Comment by tobibeer** [comment]
On the other hand, I'm not exactly sure if centering content in tiddlers is visually all too appealing.

**Comment by pmario** [comment]
I'm ok with 4 per row. ... I just wanted to point out, that users have very different monitor settings.

**Comment by pmario** [comment]
I also don't care, if it is 6 / 2 or 5/3 ... It just doesn't matter for me. I didn't even think about this topic.

**Comment by tobibeer** [comment]
I find those calls to action slightly hard to read as they are... so, at least they should be presented in a harmoneous manner that makes them feel less scattered (knowing they were not for you ;-). However, all 8 being in one row as well adds to the "scatter" factor for me, because you need to scan the whole line which is more challenging to the observer than doing 4 per row and then the next row.

Point being, you might just not look at those as much as first time visitors do. ;-)

**Comment by pmario** [comment]
@Jermolene ... pls consider this one. IMO it looks nicer. ... so merge or reject

**Comment by Jermolene** [comment]
Thanks @pmario @tobibeer

**Pull request merged**
