### PR TITLE
Record state saving timestamp

### PR DESCRIPTION
**Pull request by pmario**
This PR will fix: **[IDEA] Last saved timestamp and what it may enable #6684**

Every save action that saves a file-wiki will create 2 new `$:/state/` tiddlers. 

- $:/state/saving/timestamp
- $:/state/saving/lastModifiedSha

Link to more [detailed documentation](https://tiddlywiki5-git-fork-pmario-record-state-savin-654a0f-jermolene.vercel.app/#PreSaveActions)

In short. 

All tiddlers tagged: **$:/tags/PreSaveAction** are invoked, similar to the [StartupActions](https://tiddlywiki.com/#StartupActions)

**$:/config/presave/action/timestamp** creates `$:/state/saving/timestamp` that contains a unix Date [TIMESTAMP](https://tiddlywiki.com/#DateFormat)

```
<$action-setfield $tiddler="$:/state/saving/timestamp" text={{{ [<now "TIMESTAMP">] }}} />
```

**$:/config/presave/action/lastModifiedSha** creates `$:/state/saving/lastModifiedSha` which contains an information about the last modified tiddler as a SHA256. This makes sure that _no_ information about tiddlers with an encrypted wiki are leaked.

```
<$action-setfield $tiddler="$:/state/saving/lastModifiedSha" text={{{ [!is[system]!sort[modified]limit[1]] :map[get[modified]addsuffix<currentTiddler>sha256[64]] }}} />
```

- Those 2 tiddlers make it possible to identify if a file wiki is opened in 2 or more browser tabs. and
- Which one was  modified last
- The startup actions to detect this info are _not_ part of this PR.

**New Hidden Setting**

The PreSaveActions are active by default. If the actions should be disabled the tiddler $:/config/InvokePreSaveActions has to be set to no.

### CODE REVIEW

**Comment by saqimtiaz** [comment]
I think that it would be better to separate the generic mechanism of pre-save actions into a separate PR, which can be considered independently of saving a timestamp for the last save.

One of the potential issues with pre-save actions is that depending on how they are used, they could modify the store, making the wiki state dirty or even trigger another save.

**Comment by pmario** [comment]
>I think that it would be better to separate the generic mechanism of pre-save actions into a separate PR, which can be considered independently of saving a timestamp for the last save.

The timestamp tiddler for the last save was confirmed by Jeremy at: https://github.com/Jermolene/TiddlyWiki5/issues/6684#issuecomment-1133640239

This PR implements the core functions and the related action to create it.

>One of the potential issues with pre-save actions is that depending on how they are used, they could modify the store, making the wiki state dirty or even trigger another save.

For exactly that reason my first suggestion was hardcoded and therefore doesn't have that problem. See the comment: https://github.com/Jermolene/TiddlyWiki5/issues/6684#issuecomment-1351672650 and comment https://github.com/Jermolene/TiddlyWiki5/issues/6684#issuecomment-1351683249 which shows an image created with the hardcoded implementation.

----

@saqimtiaz 

This PR implements your idea from comment: https://github.com/Jermolene/TiddlyWiki5/issues/6684#issuecomment-1352224407 

>I think a more flexible affordance to invoke actions before saving via tagged tiddlers would be preferable, and would also satisfy the OP.
>
>For instance I would like to update a tiddler before the wiki is saved, specifying when and where a backup was last saved.

@Jermolene 

So the question now is: **Is it too dangerous for normal users to execute arbitrary actions prior to a save as implemented here.** 

If the answer is yes, then I'll close the PR and create a new one that only implements the hardcoded TIMESTAMP as requested and confirmed by issue: **[IDEA] Last saved timestamp and what it may enable** #6684

If the answer is no, we can use this PR to discuss the problems, because I think it contains enough info and test cases to play with the mechanism.

**Comment by Jermolene** [comment]
Thanks @pmario and apologies, I realise that I hadn't replied here or on #6684 with an update on my thinking. I share @saqimtiaz's concern that modifying the tiddler store in response to the save request is brittle because of the possibility that the modification to the tiddler store triggers another save. This is an area in which I think we have to be cautious because there are so many different saver modules out in the field.

So, I'd prefer to add the capability to dynamically insert tiddlers into the save template that do not originate from the store. It would be similar to the way that skinny tiddlers are handled in the current save templates.

The great advantage of this approach is that the saved file no longer has to be a precise replica of the in-memory wiki. So if the save template included a tiddler with a dynamic title that includes a timestamp "Save at 11:32pm on 2023-01-23" then that timestamp tiddler would appear in the saved wiki but not in the in-memory wiki.

It's important to remember that browser semantics mean that in general, from the perspective of a wiki in which the user has clicked the save button, we will never be able to confirm that a save worked successfully except by inspecting the saved file.

**Comment by pmario** [comment]
I'll close this PR and create a new one which injects new tiddlers when the wiki is saved according to Jeremy's response.

**Comment by pmario** [comment]
new pr

- #7953

**Pull request closed without merging**
