### PR TITLE
Signing CLA

### PR DESCRIPTION
**Pull request by springerspandrel**
Signing CLA

---
<small>Submitted using https://saqimtiaz.github.io/tw5-docs-pr-maker/.</small>

### CODE REVIEW

**Comment by pmario** [comment]
@springerspandrel Signing the CLA is only needed once

**Comment by pmario** [comment]
@Jermolene -- You should merge the pending CLAs, otherwise the doc-pr-maker will request them everytime it checks for missing CLAs

**Comment by Jermolene** [comment]
Thanks @springerspandrel

**Comment by pmario** [comment]
@springerspandrel -- You can close your duplicate CLA signatures now - Thx for your engagement also at Talk - o7

**Comment by springerspandrel** [comment]
I'm afraid I have no idea where the multiple CLAs exist such that I could close the duplicates... (The pr-maker prompted me to reload before starting a new issue, and reloading prompts the tour again, all the way through the CLA step. In future I'll just close the tour. But if the CLA is somewhere accessible, perhaps the presence of a signed CLA could be checked-for, and the tour would not prompt again?)

**Comment by saqimtiaz** [comment]
@springerspandrel below are the links for the extraneous CLA signature PRs.

The PR maker does indeed check if the CLA has been signed and if so skips that step. However, it has no means to know if a CLA signature has been submitted (as a PR) and not yet accepted, which led to the duplication in this case. So you should not face this issue again now that your signature submission has been accepted, and should indeed reload the wiki before starting a new submission.

Duplicate CLA signature PRs that can be closed.
* https://github.com/Jermolene/TiddlyWiki5/pull/8309
* #8311 
* #8312

**Comment by pmario** [comment]
The Pullrequests overview offers a nice filter for your own PRs 
The same thing also works for issues you created 

`author:springerspandrel` ... filters for you as an author - So you started the issue, PR, discussion
`commenter:springerspandrel` ... only shows issue, PR, discussions where you added a comment (IMO that's very handy)

Also see: https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-author
or: https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-commenter

image

**Pull request merged**
