### PR TITLE
Add keyboard-selectable search-dropdown

### PR DESCRIPTION
**Pull request by BurningTreeC**

### CODE REVIEW

**Comment by BurningTreeC** [comment]
This PR needs #4340 to work

**Comment by pmario** [comment]
Hi @BurningTreeC ... Opening and closing PRs without any comment is extremely confusing and **time consuming** for us. 

Please do write comments, otherwise we always need to guess, what's going on.

**Comment by BurningTreeC** [comment]
@pmario, sorry my bad. closing this because of trouble with the list-entries not being ordered correctly

**Comment by BurningTreeC** [comment]
it only works with unique items in the dropdown lists which isn't the case in the search dropdown. This is a recession, it worked before

**Comment by BurningTreeC** [comment]
reopening this because I've found the bug in #4340

**Comment by BurningTreeC** [comment]
Peek 2019-10-24 11-30

**Comment by BurningTreeC** [comment]
see #4340

**Pull request closed without merging**
