### PR TITLE
Second try: update core tabs-macro to make it easier to extend for plugin authors. 

### PR DESCRIPTION
**Pull request by pmario**
This PR contains several commits, that create a step by step review, to exactly see what's going on. The DOM structure isn't changed, except `\whitespace trim` is applied. See test changes in first commit. 

- https://github.com/Jermolene/TiddlyWiki5/commit/eb20d02717ae92b6bf795a0241a3b7a6315fe646 
  - adds the `\whitespace trim` pragma
  - activates the new tests, to make the test-run green

- https://github.com/Jermolene/TiddlyWiki5/commit/d8a5258a4013d9dd0948cdd5dea8f3dd45cadf43
  - adds indentation only
  - tests are green, so HTML doesn't change

- https://github.com/Jermolene/TiddlyWiki5/commit/046f43d080ea010745f98e8fee5b702bdb8f8c85
  - converts `$parameters$` to `<<__parameters__>>`
    - qualify and class definitions need to be adjusted to work with `<<__params__>>`
  - all the tests are green

- https://github.com/Jermolene/TiddlyWiki5/commit/1c81e372270e16f1cc055bc99ac3dd782c2b0673
  - split tabs-macro macro into different elements, to improve readability and "hackability"
    - tabs-button
    - tabs-tab
    - tabs-tab-list
    - tabs-tab-body
    - tabs ... main macro
  - all tests are green

- https://github.com/Jermolene/TiddlyWiki5/commit/659811aabb0c0c9988813ccb9c2b99125244cfab
  - adds the `code_body`
  - removes an experiment with the `default` parameter I accidentally committed.
  - all tests are green

I did plan 2 or 3 more PRs, where I do need to create issues first to explain, why I think they are important.

### CODE REVIEW

**Comment by pmario** [comment]
>@pmario would you mind copying the description from the original PR to the OP of this PR? 

I did that, as I created the PR. I also checked, that the commit links still work.

**Comment by pmario** [comment]
@Jermolene ... It seems the change hasn't been propagated to https://tiddlywiki.com/prerelease/#%24%3A%2Fcore%2Fmacros%2Ftabs yet. It seems the automated build process stopped working, or is that process still manual. ... 

tiddlywiki-com for the docs seems to be automated. right?

**Comment by Jermolene** [comment]
Hi @pmario I think the CI is fixed now

**Comment by Jermolene** [comment]
Thanks @pmario it seems that my "fix" actually just stopped files being written to the destination repo. I'll investigate further.

**Comment by Jermolene** [comment]
By the way in these situations it's worth checking the $:/build tiddler to see when the prerelease was last successfully built:

https://tiddlywiki.com/prerelease/#%24%3A%2Fbuild

**Comment by Jermolene** [comment]
Seems to be fixed again now.

I ended up reverting all of the fixes, so nothing has actually changed. Baffling, since we were clearly seeing several failed jobs.

**Pull request merged**
