### PR TITLE
Docs: New Quick Start section for HelloThere

### PR DESCRIPTION
**Pull request by Jermolene**
This PR is a work in progress of some tweaks to the "HelloThere" tiddler to add a quick start section to try to address reports of frustration from first time users:

image

In the interests of paying the bills, this update includes a much more prominent advertisement for Xememex, the commercial hosting service for TiddlyWiki that I operate through Federatial. I hope that this is not controversial.

<details><summary>Full screenshot of HelloThere tiddler </summary>
image

</details>

### CODE REVIEW

**Comment by pmario** [comment]
I think that's ok. .. But it is not obvious that the bars can be clicked. You have to hover them to see a "little" animation, which I almost missed on my laptop screen, which does not show any shadows. 

I think those 4 bars should probably use a much bigger font size. 

The commercial bar links to: https://tiddlywiki5-git-getting-started-tweaks-feb-2023-jermolene.vercel.app/#Xememex, which does not have any external link to the page itself. IMO it should have. .. 

It's also a bit confusing, that the Federatial-card links to a different tiddler as the Commercial-bar ... So is it something different or is it the same company?

**Comment by Jermolene** [comment]
> I think that's ok. .. But it is not obvious that the bars can be clicked. You have to hover them to see a "little" animation, which I almost missed on my laptop screen, which does not show any shadows.

If the bars don't look clickable we need to find a better solution than hover effects because we need to consider mobile devices.

> I think those 4 bars should probably use a much bigger font size.

I tried making the text a little bigger but the trouble is that when they get bigger we push down the other content more and more. I don't think this looks good:

image

> The commercial bar links to: https://tiddlywiki5-git-getting-started-tweaks-feb-2023-jermolene.vercel.app/#Xememex, which does not have any external link to the page itself. IMO it should have. ..

The Xememex tiddler in particular is a work in progress.

> It's also a bit confusing, that the Federatial-card links to a different tiddler as the Commercial-bar ... So is it something different or is it the same company?

The Federatial card is advertising consultancy services, the Xememex card is advertising hosting services.

**Comment by pmario** [comment]
I personally would like this much more. But I would **make the text bigger again**, so it can be read. With 100% browser zoom imo the text is way to small. 

Which will also look much better on mobile

image

**Comment by pmario** [comment]
Mobile view

image

**Comment by yaisog** [comment]
Personally, I like the bars better than the tiles.
However, they should have a maximum width. Here's how they look on my machine:

image

They'd look much nicer with a width not much wider than their widest content, and then centered on screen. The tiles below could also benefit from some centering.

Also, why would one assume that the only four elements below "Quick Start" would not be clickable? What else would there be to do? If I really wanted to make this any clearer, I'd _maybe_ put a "→" at the end as an indication to follow.

**Comment by yaisog** [comment]
Personally, I like the bars better than the tiles.
However, they should have a maximum width. Here's how they look on my machine:

image

They'd look much nicer with a width not much wider than their widest content, and then centered on screen. The tiles below could also benefit from some centering (the way it currently is, but with a fixed gap instead of spread out – in flexbox terms, `justify-content: center` instead of `space-evenly`).

Also, why would one assume that the only four elements below "Quick Start" would not be clickable? What else would there be to do? If I really wanted to make this any clearer, I'd _maybe_ put a "→" at the end as an indication to follow.

**Comment by pmario** [comment]
>Also, why would one assume that the only four elements below "Quick Start" would not be clickable?

For me the image cards are much more attractive. I'd definitely click them first. 

If I would be new, the very first thing I would want to know is: **What is it good for**. So IMO  "Introduction to TW" would be the first thing I would open. 

The last sentence in the video is "Visit GettingStarted" ... Where we know already, that users are overwhelmed with the possibilities shown there. 

So from my point of view if we want new users to start with TiddlyHost, GettingStarted needs exactly that info. 

DIY should go to a "Do It Yourself" tiddler and not to GettingStarted.

**Comment by Jermolene** [comment]
Thank you @pmario @yaisog 

I was keen to make these quick links look different than the main link badges to give more visual variety. It's easy to switch them back to horizontal badges as @pmario has done, and it's worth playing about with the options.

@yaisog suggests making the quicklinks narrower, and centering them. I've found that centering things doesn't work as well within a tiddler as with ordinary full page layouts. There are still a lot of left justified elements within the tiddler (toolbar, headings, text etc) and so mixing in centred stuff looks a bit clumsy to me.

@pmario also mentions GettingStarted. I think that's pretty much of a disaster right now. The checkboxes do not work how anyone would expect (for example, checking them all does not give a list of all the available options, but unexpectedly gives a completely empty list). I'm keen to revisit GettingStarted, but I think that's a bigger job and so I wanted to deal with these quicklinks first.

**Comment by pmario** [comment]
>... but I think that's a bigger job and so I wanted to deal with these quicklinks first.

The quicklinks are definitely better as it is now. ... As you wrote we also need a follow up.

**Comment by yaisog** [comment]
I hope this is not too off-topic, but I didn't want to start another TWTalk thread for it...

Isn't the _one thing_ that separates TW from all those other note-taking tools that TW doesn't need any additional installed software or an online connection to be used? The others I know of either need some software tool or are in the cloud. Shouldn't this be extolled on this front page a little bit more? Are we being to modest about it?

I'm thinking of the average Joe, who already has a browser because he is looking at tiddlywiki.com. He also does not care about the node.js version. He probably googled something like "note-taking tool" and is now comparing his options. Wouldn't that then be the most important information about TW he needs to make a decision?

Just musing...

**Comment by Jermolene** [comment]
> I hope this is not too off-topic, but I didn't want to start another TWTalk thread for it...

Not at all, this is very germane.

> Isn't the _one thing_ that separates TW from all those other note-taking tools that TW doesn't need any additional installed software or an online connection to be used? The others I know of either need some software tool or are in the cloud. Shouldn't this be extolled on this front page a little bit more? Are we being to modest about it?

Quite possibly yes.

There always seems to be a tension between the desire to present TiddlyWiki through a conventional lens to make it less scary and the need to clearly communicate what makes TiddlyWiki different.

That's the idea of the heading for Tiddlyhost being "online" and "desktop", I'm trying to signpost the conventional routes for those that need them, but ranking them equally with the "diy" option which is, of course, where the good stuff happens. I'm not at all sure about the phrase "diy", but it's not terrible: it conveys the customisability reasonably well.
 
> Maybe we could rewrite "TiddlyWiki lets you choose where to keep your data" a bit, because that's true for e.g. Obsidian, too.

Good point. I haven't really touched the introduction paragraphs yet.

**Comment by yaisog** [comment]
Back on the topic of the OP: Shouldn't the first interaction of a new user with TW be to play around on the site he's currently looking at? All the _Quick Start_ options send him/her somewhere else (except DIY, which doesn't target new users, though). At the top I'd like something like "Try it out", leading to a tiddler that teaches him the first steps: how to create a new tiddler, how to edit others, how the editor works, what happens when one clicks the save button on TW.com, ... This doesn't even have to cover WikiText (except maybe a simple transclusion). Maybe should have a list of doc tiddlers to basic concepts and some links with explanations to empty.html, TiddlyHost, what savers are and why they are needed, etc.

Maybe it's just me, but I don't like if I have to go somewhere else, or sign up or download software to try a thing out, after arriving from Google or a link from a friend. And it is a nice thing about TW (and tiddlywiki.com) that you can just start right where you are – and that the whole documentation site is a TW. But nowhere in the default tiddlers does it say: "Just start playing with it! Click the + and write something!"

Also, while I don't mind "DIY", maybe "Custom" ist better? Implies the vast possibilities of customization possible with TW. "DIY" sounds like work... ;-)

**Comment by Jermolene** [comment]
Thanks @yaisog good points. It does partly illustrate a big challenge with home page updates: there's a lot that needs fixing and a lot that could be better, and everything is intertwingled, and so attempts to make simple tweaks can escalate to become overwhelming.

I have been noodling on an idea for an interactive tour that guides users through the basics of getting started with the TiddlyWiki user interface. It's just a branch at the moment, but I'll make a PR for it soon:

https://github.com/Jermolene/TiddlyWiki5/tree/confetti-plugin

There's a preview here:

https://tiddlywiki5-git-confetti-plugin-jermolene.vercel.app

I'm also keen to make some improvements to the "introduction" edition, and link it together with the tour.

**Comment by pmario** [comment]
>.. It does partly illustrate a big challenge with home page updates: there's a lot that needs fixing and a lot that could be better, and everything is intertwingled, and so attempts to make simple tweaks can escalate to become overwhelming.

That's right. .. It starts small, One little change here needs an other little change there, so lo and behold it's needed to change 20 tiddlers or more. :/

I was thinking about @yaisog's https://github.com/Jermolene/TiddlyWiki5/pull/7254#issuecomment-1423706531 too and thought about the "automated screenshot" capability of the inner-wiki plugin. ... I didn't test it yet.

But ... I did create some new screenshots for my bundler plugin lately and it always is a pain, since every new version would basically need a completely new set of screenshots to be "up to date". 

I think we should have some editions in the build process, that can "spit out" several sets of screenshots that can be used by tw-com and the community to document TWs basic behaviours. ..

For me personally 1 image is worth a 1000 words. 

I'll try to create a set of screenshots that is needed to satisfy the suggestions made at: https://github.com/Jermolene/TiddlyWiki5/pull/7254#issuecomment-1423706531 .. I hope I can find some time at the weekend.

**Comment by yaisog** [comment]
@Jermolene: The tour idea is neat, took me a minute to figure out why you called it _confetti_. ;-)
It does remind me a bit of Clippy the office assistant from Microsoft from the 90s. I don't mean that in a bad way, though! Am I really that old?
Even though I'll usually go into the settings menu first when I use a new software, I wouldn't start the tour with the control panel. But I guess right now you're just laying the technological groundwork for the tour?

Oh, and one comment directly on _confetti_: I wouldn't put _next_ on a button. Switch to the next step automatically and congratulate there, first thing. Too much clicking, otherwise. I'd leave _back_, though.

@pmario: Maybe we don't need many screenshots. To explain the important buttons, you could just transclude them right into their explanation? At least as long as we're just talking about the basic functionality of TW...

To put my money where my mouth is, I'll also try to come up with an example for a "try it out" tiddler like I mentioned in the previous comment. Just as an inspiration, for the tour maybe? At least I can imagine something like this working _very well_ with _confetti_, because one wouldn't have to go back an forth between the instructions tiddler and the actual trying out tiddler.

**Comment by pmario** [comment]
>@pmario: Maybe we don't need many screenshots. To explain the important buttons, you could just transclude them right into their explanation? At least as long as we're just talking about the basic functionality of TW...

It's not about the screenshots. It's about the repeatability with the latest version. If you have a look at our videos, that are linked in the tw-com page. They are all outdated and the UI most of the time is not even close to what it looks now.

**Comment by pmario** [comment]
I think we should merge it and the see, what's the feedback. We should try different iterations to see what works best. ...

**Comment by Jermolene** [comment]
I've just come back to this and found I agree with @pmario that horizontal cards might work better. I've tweaked them to look more like calls to action. Here's what things look with the latest commits:

image

**Comment by Jermolene** [comment]
I've added pale background gradients to the quickstart cards; I'm not sure if it is an improvement over the plain version:

image

Previously:

image

**Comment by Jermolene** [comment]
I'm merging this now but remain open to suggestions for improvements.

**Comment by Jermolene** [comment]
I messed things up, and have recreated these changes over in #7399

**Comment by twMat** [comment]
Apropos Confetti: I was alerted about this project when requesting a very much related feature on the forum, see: [Requesting an official guide plugin](https://talk.tiddlywiki.org/t/requesting-an-official-guide-plugin)

A main difference is that my idea relies on detecting what tiddler/s the user navigates or scrolls to show in the viewport and have the "popup" react to this, whereas Confetti steers a strict and predefined order of events.

**Comment by CrossEye** [comment]
Something at the time made me look at this thread and see confetti, but when I wanted to learn more, I'd forgotten where it was.  

Has there been any progress on this?  I would really love to create a product tour like this for a subset of users, so would hope that this could be manually launched, preferably with a certain fragment identifier (hash) in the initial load, but also with some obvious UI such as a button.  My own idea was more of a traditional tour without the interactive "Do this, then that".  But I think this version might be much better.  I've thought about importing one of the tour libraries, but something like this that knows more about TW would be quite powerful.

**Pull request closed without merging**
