### PR TITLE
cancel open popups when input gets focus

### PR DESCRIPTION
**Pull request by BurningTreeC**

### CODE REVIEW

**Comment by BurningTreeC** [comment]
I believe we additionally need to query in popup.cancel() if a focused input is embedded within a popup and don't cancel it in that case

**Comment by BurningTreeC** [comment]
>I believe we additionally need to query in popup.cancel() if a focused input is embedded within a popup and don't cancel it in that case

the `link` toolbar button for example would cancel its own popup

if I recall correctly, @Jermolene mentioned a way to query for the element that has focus... we could then detect if it's nested within a popup that would get cancelled

**Comment by BurningTreeC** [comment]
I've added a way in popup.js that detects if a focused input is within a popup that would get cancelled. Now the link dropdown works and the popup cancelling works as one would expect

**Comment by Jermolene** [comment]
> if I recall correctly, @Jermolene mentioned a way to query for the element that has focus... we could then detect if it's nested within a popup that would get cancelled

We can use `this.domNode.ownerDocument.activeElement` to get the element with focus, and then `$tw.utils.domContains()` to check containership.

**Comment by BurningTreeC** [comment]
Hi @Jermolene , I did it a bit differently by querying for `input:focus-within` and detecting if it exists and if it's within a domNode that's about to be cancelled...

**Comment by BurningTreeC** [comment]
Peek 2019-07-08 16-10

**Pull request closed without merging**
