### PR TITLE
fix for 2634 problems with week calculation

### PR DESCRIPTION
**Pull request by pmario**
There are some new week calculation tests. some tests fail with the old formular. 
All tests pass with the new formular.

### CODE REVIEW

**Comment by Jermolene** [comment]
Great stuff, thanks @pmario

**Comment by pmario** [comment]
I'm confused. What's wrong with the tests?

**Comment by Jermolene** [comment]
Hi @pmario it looks like I utterly messed things up, and deleted the commits. Could you kindly prepare a new pull request?

The commit history is now an utter mess, thanks to my bumblings. All the recent changes have now been committed twice... Do you think it would be possible to clear it up?

**Comment by pmario** [comment]
I see. IMO if something is pushed to github, it's hard to be undone. ... So I wouldn't mess too much with it. 

---

I'll prepare a new PR.

**Pull request merged**
