### PR TITLE
Enhancements to plugin installation doc and new entry for uninstallation

### PR DESCRIPTION
**Pull request by Spangenhelm**
I have added bold markup to emphase and explain the need to refresh.

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @Spangenhelm thanks. To my surprise, it looks like you haven't yet signed the Contributor License Agreement, which is needed before accepting a contribution. You just need to send a separate pull request to add your name to `cla-individual.md` as described in https://github.com/Jermolene/TiddlyWiki5/blob/master/contributing.md

**Comment by Spangenhelm** [comment]
Hi @Jermolene you were right i had forgotten.. i have just signed it. Thanks

**Comment by Jermolene** [comment]
Hi @Spangenhelm did you close this in error?

**Comment by Spangenhelm** [comment]
@Jermolene My bad.. it is reopened now !

**Pull request merged**
