### PR TITLE
cancel open popups when inputs get focus

### PR DESCRIPTION
**Pull request by BurningTreeC**
This is a new PR based on #4078 

This uses the domNode passed from factory.js - no need to query for a focused element, that domNode has focus at that point

It also detects if an input is placed within a popup and doesn't cancel that one

### CODE REVIEW

**Comment by BurningTreeC** [comment]
Peek 2019-07-10 12-13

**Comment by morosanuae** [comment]
@BurningTreeC very nice! Jeremy was right. It is much easier now with the help of animations to understand what you are doing.

**Comment by BurningTreeC** [comment]
thanks @morosanuae 

another one that shows nested popups with inputs... the first popup has the class `tc-popup-keep`

Peek 2019-07-10 14-48

**Comment by BurningTreeC** [comment]
Peek 2019-07-14 06-47

**Comment by Jermolene** [comment]
Hi @BurningTreeC I think this is simple enough to merge for v5.1.20 but I'd appreciate your help double checking things once merged.

**Comment by BurningTreeC** [comment]
>but I'd appreciate your help double checking things once merged.

Thanks @Jermolene, I will test test test

**Pull request merged**
