### PR TITLE
Extend Eventcatcher to handle multiple events

### PR DESCRIPTION
**Pull request by saqimtiaz**
@Jermolene this makes the following changes:
- replaces `type` attribute with `events`, which is a space separated list of events.
- replaces `actions` attribute with support for separate actions per event, where each event type is prefixed with `actions-` to get the attribute name for the actions. For example: `actions-dblclick`
- adds variables for `event.type` and `event.details` properties of the event
- updates documentation.

Code changes are minimal, the diff shows a lot of green due to a change in indent level for the code that is now inside a loop.

Background: https://github.com/Jermolene/TiddlyWiki5/pull/5086#issuecomment-737308560

### CODE REVIEW

**Comment by saqimtiaz** [comment]
@Jermolene one thought was to allow plugins to customize what variables are created via a hook just before invocation of actions:

`variables = $tw.hooks.invokeHook("th-eventcatcher-getvars",event,variables,selectedNode,domNode);`

**Comment by Jermolene** [comment]
Great thanks @saqimtiaz. I'll be looking forward to see what people do with this.

**Comment by saqimtiaz** [comment]
@Jermolene just to be clear I didn't add the hook I mentioned at this time.

It could be useful if there are variables needed that we haven't thought of but can also be added later.

**Comment by Jermolene** [comment]
Sorry I meant to say that here I'm not sure a hook is appropriate here. We generally use them when there's a clear use case that we have opted not to cater for in the core. Here the scope for what information might be exposed as variables is limited to what we have available, which is known in advance. So, if there's information that the current design doesn't expose then there's probably a case for doing so for everyone, rather than continuing to support a hook.

**Comment by saqimtiaz** [comment]
@Jermolene that makes sense, I had mixed feelings about it myself.

**Comment by Jermolene** [comment]
These are tricky decisions! Hooks feel like an unavoidable hostage to fortune sometimes.

**Pull request merged**
