### PR TITLE
Add actions parameter to range-widget + docs!

### PR DESCRIPTION
**Pull request by pmario**
This is WIP. The docs contains an example, that creates a log-like temporary tiddler, where users can exactly see, what's going on and when the different actions fire!

This PR adds 4 actions:

 - actionsStart
 - actionsStop
 - actions

2 variables: `actionValue` and `actionValueHasChanged` See the docs!

It behaves the same way in modern browsers and contains some lines of code to behave well with IE11.
I did test it with IE11 wondows 10, FF latest, Edge latest. ..

[range-actions.zip](https://github.com/Jermolene/TiddlyWiki5/files/5618393/range-actions.zip)

@twMat ... Please test!

### CODE REVIEW

**Comment by pmario** [comment]
It contains some extra code, to make it compatible with IE! Once IE is gone, the code can be simplified.

**Comment by Jermolene** [comment]
Looks good thanks @pmario

**Comment by pmario** [comment]
@Jermolene ... marked the PR as "ready for review".

**Comment by Jermolene** [comment]
Thank you @pmario

**Pull request merged**
