### PR TITLE
Introduce text editor toolbar

### LINKED ISSUE #1747: Toolbar for tiddler text editor
Hello, 

Since it is a planned feature to allow external widgets access edit text selection and content we are going to have lots of plugins customizations to add editor buttons. It will be easier for anyone that just wants to add a button to a toolbar to just create the button and tag it accordingly like we do with other Toolbars. This toolbar should be placed over the edit text  widget on the edit template and should be only visible if there is any button to display. 

Maybe this bar should even render the button to assure a button style  consistency and the button creator provide only the logic and content of his/her button. 

What do you think?

### PR DESCRIPTION
**Pull request by Jermolene**
A first pass at adding an extensible toolbar to the text editor.

Preview available at http://rich-text-editor.tiddlyspot.com/

Still to do:

* [x] Merge the functionality of edit-text-iframe into the main edit-text widget (thus avoiding the messing with EditorTypeMappings)
* [x] Deal with the fact that the undo/redo buttons don’t work in Firefox (solution is to use CodeMirror)
* [ ] Documentation:
 * [ ] adding custom text editor toolbar button
 * [x] colour-picker macro
 * [ ] keyboard shortcut mechanism
* [x] Ensure compatibility with CodeMirror plugin
* [x] Consider using colour-picker macro elsewhere in the core
* [x] Refactor image picker dropdown into a reusable macro
* [x] Add support for keyboard shortcuts
* [x] More snippets (help needed!)
* [x] I18n and tooltips
* [x] Integrating the preview pane
* [x] Make the tm-edit-text-operations like ‘replace-selection’ be extensible via plugins
* [x] Encapsulate the entire editor+toolbars for re-use
* [x] Fix existing keyboard shortcuts
* [x] Extend the edit-bitmap widget with support for its own toolbars.
* [x] Rename “Text Editor Toolbar” (eg in control panel) because it is not just for text editing. Perhaps to “Formatting Toolbar”? Or “Editing Tools”? 
* [x] Maybe add HTML colour picker to colour-picker macro
* [x] Add support for Markdown

Fixes #1747

### CODE REVIEW

**Comment by Jermolene** [comment]
Most of the current editor operations are specific to TiddlyWiki wikitext, but alternatives for other types such as Markdown could be provided. Perhaps the displayed toolbar buttons should be filtered according to the current content type.

**Comment by silvyn** [comment]
Hello @Jermolene and again thank you for this great improvements.

For documentation context, I often use backtick. So because I'm curious and want to play and learn, I've duplicate a toolbar tid with success :)

capture d ecran 2016-03-09 a 10 30 01

I've not yet play with TextEditorToolbar.tid list to choose the right place.

I don't know how you edit SVG with few command line, so for my exercise, I've just feel in red the quote image.

$:/core/ui/TextEditorToolbar/code

```
<$button class="tc-btn-invisible">
<$action-sendmessage
	$message="tm-edit-text-operation"
	$param="wrap-selection"
	prefix="`"
	suffix="`"
/>
{{$:/core/images/format-code}}
</$button>
```

**Comment by Jermolene** [comment]
Hi @silvyn there's actually already a button for inserting backticks: it's the one labelled "ABC" 7 buttons from the left.

I'm just working on the tooltips now :)

**Comment by silvyn** [comment]
:D @Jermolene 
Thanks ;)

**Comment by Jermolene** [comment]
Thinking about the question of whether the rich text editor should be packaged as a separate plugin:

* Size of 5.1.12-prerelease without the rich text editor: 3,561,183 bytes / 1,388 tiddlers
* Size of 5.1.12-prerelease with the rich text editor: 3,754,673 bytes / 1,503 tiddlers

Delta:

* 3,754,673 - 3,561,183 = 193,490 bytes
* 1,503 - 1,388 = 115 tiddlers

I'm still inclined to keep it in the core for the reasons I've given before: that the rich text editor is a vital feature for beginners, and I think that the vanilla TiddlyWiki should be the best we can do for beginners. But I do recognise that this feature adds a lot to the size of the core; we might be able to ameliorate it by optimising the core images and a few other measures.

**Comment by pmario** [comment]
For me personally. ... I'd like to have the toolbar in an auto hide section. .. I don't need it, but I think the  the stamp functionality is nice. 

Having it in a plugin, that is default in the core is ok for me. But it should be removable. ... Like "Batteries included, but removable" :)

**Comment by sukima** [comment]
Agreed, there are times when I would want the toolbar, like in the case of giving my mom an empty HTML version, and cases when i don't want it, like when I use it for my own notes and the extra bloat is extraneous.

**Comment by twMat** [comment]
@Jermolene wrote:
>Also, later it would be good to extend the edit-bitmap widget with support for its own toolbars.

For doodles to be a practical and natural part of the workflow when composing a tiddler, I'd prefer a more intergrated approach so that you can edit a tiddler and simply insert an image straight into it and continue with the text authoring afterwards.

For this, there could be a "draw" button (just like there is for "insert image") but that actually inserts a edit-bitmap widget _below_ the current text-editor (a bit like an attachment). This could have it's own toolbar. The text being edited get's a transclusion so the bitmap will show at that spot in view mode. The bitmap could in reality be a separate (system-)tiddler but it thus shows both in tiddler edit mode (via edit template) and view mode (via regular transclusion).

Currently, I'd think the use of the bitmap editing is underused because on the one hand it is only good enough to make rough doodles with - which per se is often sufficient in when making notes - but on the other hand it is, for a rough doodle, too demanding to interrupt the current note composing and create a separate tiddler and then transclude it to the note you were working on.

**Comment by Jermolene** [comment]
Hi @twMat 

> For doodles to be a practical and natural part of the workflow when composing a tiddler, I'd prefer a more intergrated approach so that you can edit a tiddler and simply insert an image straight into it and continue with the text authoring afterwards.

That sounds like an argument for a "new tiddler" button on the text editor toolbar that creates a new tiddler and automatically creates a new link or transclusion or `[img[` call.

Or maybe something like your quick note thing, but for images?

> For this, there could be a "draw" button (just like there is for "insert image") but that actually inserts a edit-bitmap widget below the current text-editor (a bit like an attachment). This could have it's own toolbar. The text being edited get's a transclusion so the bitmap will show at that spot in view mode. The bitmap could in reality be a separate (system-)tiddler but it thus shows both in tiddler edit mode (via edit template) and view mode (via regular transclusion).

That sounds quite tightly coupled, but I certainly see the workflow.

I've been working on the bitmap editor over the last few days. It's sufficiently intertwined with the text editing machinery that it's worth working on them together.

Here are some images of what it's looking like so far:

screenshot 2016-03-13 18 30 31 screenshot 2016-03-13 18 28 21 screenshot 2016-03-13 18 27 36 screenshot 2016-03-13 18 27 09

**Comment by Jermolene** [comment]
Thanks @pmario 

> For me personally. ... I'd like to have the toolbar in an auto hide section. .. I don't need it, but I think the the stamp functionality is nice.

You're right, it should certainly be possible to hide or disable the toolbar.

> Having it in a plugin, that is default in the core is ok for me.

That's problematic wording. The definition of the core is the content of the `$:/core` plugin, which cannot itself contain further plugins.

> But it should be removable. ... Like "Batteries included, but removable / exchangeable" :) eg: exchange it with other future "rich text" editors. Having several of them imo is bloat.

It sounds like you mean that the rich text editor should be part of empty.html as a plugin, but not part of the `$:/core` plugin, is that correct?

**Comment by pmario** [comment]
>It sounds like you mean that the rich text editor should be part of empty.html as a plugin, but not part of the $:/core plugin, is that correct?

yes. .. The same is valid for the image editor.

**Comment by Jermolene** [comment]
I've pushed the commits for the bitmap editing functionality, and uploaded a new preview to http://rich-text-editor.tiddlyspot.com/

**Comment by twMat** [comment]
The following is intended for a blog post (for TWaddle) in that it is overly ambitious as a mid thread post, and it has a pontificating tone. However I'd have to tweak the article some more for the blog so instead of having it finished in a few days (or not at all) I'll just post it as it is currently. Anyone - feel free to skip it but it presents a conceptually different take on UX for when composing a tiddler and for example how to integrate the bitmap editor.
Thus I now step up on the banana box...

Further thoughts on integration between types of content, e.g drawings and text;

In composing a tiddler, the user should not experience a substantial differences in procedures between different types of content; there is no obvious "UX reason" why entering text, a (manual) list, a rendered list, or an image should differ. Currently, I think bitmap doodles are separate tiddlers for implementation reasons rather than UX. A doodle might rightfully be a tiddler (fulfilling tiddler philosophy) but then... it might not; For example, I hope we'll be able to encircle a mid text word or add a margin doodle, like you do when studying. These are not necessarily semantically meaningful in themselves any more than a sentence might be.

[TiddlerSections](http://tiddlersections.tiddlyspot.com/) is an unfinished project of mine not quite ready for display but the new text editor is touching common ground and my ideas are getting more and more redundant (which is good, of course) so I'm bringing it up to illustrate a different "take" on tiddler composing. The premise in TiddlerSections is to simplify composing content by regarding "sections" in the tiddlers text. A section is here simply a part of the content that is distinguished from adjacent content by different _needs_. The "need" could be different styling (e.g for a quotation) or a different type (e.g an image) or some other special element (e.g some rendered element). These sections are implemented by use of dedicated text fields and text editors - i.e a tiddler can thus have multiple text fields, one per section.

This also allows sections be managed individually which opens up exciting opportunities: As explored in [QuickTid](http://quicktid.tiddlyspot.com/) (an offspring from, and part in, TiddlerSections) - and similarly in the Stamp feature of Jeremys new toolbar - _pre-made_ content can be added chunkwise. This shuold have huge simplifying and time saving potential. But if each section is also a separate element, it can be a _functional block_ where the text content is really the input (the argument) for a "section function"! For example the text could be the input for a widget or a macro "surrounding" the text. The user sets a _type_ for the section, somewhat like you do for a tiddler, which decides how to treat the content.

If the section type is set to "image", there's the bitmap editor showing at that spot in tiddler edit mode. If section type is set to "myListFilter" it might (still in edit view) show a small form where to fill in list filter arguments. This is not implemented in TiddlerSections (as I don't have enough coding skills) other than that the select feature does surround entered text with pre- and post content such as `<div class="myStyle">` and ´</div>´.  

I think using sections could open up for a more unified interface for widgets, macros etc; Buttons to apply whatever-it-is and hiding code that the end user doesn't benefit from.

-----

Ok, that was it. There may be conceptual flaws but I figured it's better to post it now than much later or not at all.

**Comment by twMat** [comment]
@Jermolene - great additons to the bitmap editor tools. I'm not certain how/what the opacity accomplishes thought. I tried transcluding a drawingonto a colored div but none of the color came through in spite of setting transparency for the drawing.

BTW, I'm really excited about transparency in images because it might allow the "encircling of words or margin doodles" that I mentioned in the post just above this one, and also the previous [Glass](http://twaddle.tiddlyspot.com/#Glass) concept that I dabbled with.

**Comment by Jermolene** [comment]
I've just added keyboard shortcut support. You can try it out at http://rich-text-editor.tiddlyspot.com/, but there is not yet any way to learn the keyboard shortcuts - you can see them [here](https://github.com/Jermolene/TiddlyWiki5/blob/text-editor/core/wiki/config/KeyboardShortcuts.multids). Next step is to add the keyboard shortcuts into the tooltip.

**Comment by Infurnoape** [comment]
This is very awesome Jeremy. I hope you don't mind that I'm trying to keep up with you and to understand your designs which are amazing by refactoring my reduce button [plugin](http://reduce.tiddlyspot.com/) for my own use as an extra button whenever you release the editor?

**Comment by Jermolene** [comment]
@Infurnoape not at all, delighted that it's making sense, and apologies for the rapid incompatible changes! It would be great to have some community plugins adding editor toolbar buttons.

**Comment by twMat** [comment]
Of possible relevance;

From text-editor Atom [blog post](http://blog.atom.io/2016/02/03/introducing-block-decorations.html)

>Block decorations allow a package developer to insert DOM nodes in between lines. This new API opens up a number of new scenarios such as inline diffs, code evaluation, image previews, and very important use cases like watching nyan cat while you write code.

**Comment by Infurnoape** [comment]
I found a bug that should probably be looked at when the undo/redo for Firefox is looked at. After hitting undo or redo, the tiddler text disappears from preview unless you hit another key and if you save the tiddler at that point, it is empty. I think the issue has something to do with the undoManager API. I sense there needs to be something additional added to $:/core/modules/editor-operations/text/redo.js and $:/core/modules/editor-operations/text/undo.js so that it will remember what was in there before?

**Comment by Jermolene** [comment]
Hi @Infurnoape thanks, I hadn't observed that behaviour. As you've probably read, the usual `execCommand(undo)` doesn't work in Firefox. Annoyingly, I've not found a way to feature detect it, so the best we can do is browser sniffing. But to be honest I'm more inclined to drop the two buttons entirely; I don't think that they are hugely useful, given the standard keyboard shortcuts.

**Comment by Infurnoape** [comment]
If the undo and redo buttons were dropped, they could still be added back as a plugin. I am thinking of it for when I'd use them from my phone using chrome. I'd still need to figure out why tiddlywiki forgets what should still be in the preview. Any suggestions?


Happy Connecting. Sent from my Sprint Samsung Galaxy S® 5

-------- Original message --------

**Comment by sukima** [comment]
That bug reminded me of an odd FireFox issue regarding text changes. I experience the same behavior with my FireFox Vimperator plugin and had to [make a patch for it](https://github.com/vimperator/vimperator-labs/pull/203). I found that the code needed to manually trigger an `input` event to make FireFox update the DOM value.

So I recommend when the undo/redo buttons are pressed that they also execute:

```
editTiddlerTextArea.dispatchEvent(new InputEvent('input'));
```

See if that works.

**Comment by Jermolene** [comment]
Hi @sukima I tried your suggestion but it doesn't help in our situation. Looking at the ticket that you're referencing, I suspect that these are different issues: the Vimperator one concerns setting the content of a textarea via the "value" attribute, whereas we're using `this.document.execCommand("redo", false, null);`. Googling indicates that this is a [known problem](http://stackoverflow.com/a/16233334), with the best solution being apparently to maintain ones own undo stack, which I don't think is worthwhile.

I do plan to work on getting the new stuff working with CodeMirror, which does seem a pre-requisite for the most desktop-like editing experience.

**Comment by Infurnoape** [comment]
I've changed my mind about the importance of the undo and redo buttons because they are hugely important for mobile users. I've still been reverse engineering the Editor Toolbar and I realized that their branches if that is what you call them **$:/core/modules/editor-operations/text/undo.js** and **$:/core/modules/editor-operations/text/redo.js** are called from **$:/core/modules/widgets/edit-text-iframe.js** and it seems that the reason why the preview disappears is because after the execCommand is performed on the dummyTextArea in the iframe, the script just ends and doesn't loop back to **$:/core/modules/widgets/edit-text-iframe.js** so that it can complete a refresh on the dom using the newly changed dummyTextArea in the iframe? I think this is causing some kind of forgetfulness as to what the node should look like in the dom and the preview disappears. Here is where it would help if there were some kind of help online but regretably I can't find any examples of how to loop back. Putting a return doesn't seem to work either. Any suggestions, or am I just spinning my wheels?

**Comment by Infurnoape** [comment]
ok, I think I commented to soon because I just found the following from Codemirror but not sure how it might work after the execCommand call in undo.js ad redo.js:
```
var myCodeMirror = CodeMirror(function(elt) {
  myTextArea.parentNode.replaceChild(elt, myTextArea);
}, {value: myTextArea.value});
```
Any suggestions?

**Comment by Infurnoape** [comment]
Is there a way to see what methods of updating the immutable tiddler are exposed to $:/core/modules/editor-operations/text/undo.js?

**Comment by Infurnoape** [comment]
Well, I keep trying and I'm wondering if I am getting closer. So for **$:/core/modules/editor-operations/text/undo.js** I tried:
```
exports["undo"] = function(event,operation) {
    this.iframeNode.focus();
    this.iframeTextArea.focus();
    this.document.execCommand("undo", false, null);
    operation.cutStart = 0;
    operation.cutEnd = operation.text.length;
    operation.replacement = this.iframeTextArea.innerHTML;
    operation.newSelStart =this.iframeTextArea.selectionStart;
    operation.newSelEnd = this.iframeTextArea.selectionEnd;
};
```
But it doesn't appear that I know what I'm doing because it doesn't work like ctrl-z or ctrl-y.

**Comment by Jermolene** [comment]
Hi @Infurnoape there are basically two strategies for the undo/redo buttons to work:

1. Use the browsers undo/redo logic. To do this, one has to update the content of the textarea in a way that the browser recognises and includes in the undo history; that's why the existing code uses `createEvent("TextEvent")` to create a textInput event to simulate the input
2. Create our own undo stack, and maintain it as edits occur

The code at the moment uses approach (1), which fails in Firefox because `execCommand("undo")` is only supported for contentEditable elements in Firefox.

Option (2) would work, but I'm not keen to spend the time replicating the undo/redo circuitry for such a small gain.

**Comment by twMat** [comment]
Proposing feature button for positioning left-center-right. Particularly as html5 does [not feature](http://www.w3schools.com/tags/tag_center.asp) old html tag `<center>` and, as evidenced in a [post](https://groups.google.com/d/msg/tiddlywiki/qR4-Oc4xr1w/klt5B4NmAwAJ) by Eric, there is complexity in styling this "manually" even in Wikitext.

**Comment by pmario** [comment]
@twMat imo macros will win the game :)

**Comment by twMat** [comment]
>@twMat imo macros will win the game :)

@pmario - What do you mean? That the user should write a macro instead of having the button to do it?

**Comment by Jermolene** [comment]
Hi @twMat I think that @pmario means that one part of your request is easily satisfied by introducing a core macro for centering content. The other part is extending the snippet capability so that snippets can reference the currently selected text, and can have individual keyboard shortcuts.

I don't propose to do either of those enhancements at the moment; I think it's more important to get the new stuff out there and released so that everyone can build things on top of it.

**Comment by twMat** [comment]
>I think it's more important to get the new stuff out there and released so that everyone can build things on top of it.

Fair enuff and I agree.

**Comment by sukima** [comment]
Possible bug.

Excise selected text to tiddler creates weird tiddlers: `$(config-title)$_new-title.tid` and `$(config-title)$type.tid`):

tw5-excise-bug

**Comment by Jermolene** [comment]
Hi @sukima great stuff, an excellent catch. Fixed here:

https://github.com/Jermolene/TiddlyWiki5/commit/6f6cdc1bd0be2056a68233ff21d51c4e904dce71

**Comment by nameanyone** [comment]
@Jermolene, how to style the text editor inside iframe? (I'd like to adjust font size and background color, for example). I tried to dig in, if I'm not mistaken copyStyles is not working, since the only styles applied to the textarea inside the iframe are those coded explicitly in framed.js - display, width, margin and height.

Also, is there an "opt-out" switch that reverts to the simple (as before) editor?
Thanks!

**Comment by Jermolene** [comment]
For the record, the problem here was that copyStyles was broken on Firefox. Fixed here:

https://github.com/Jermolene/TiddlyWiki5/commit/e54cc7b211e10df5048b85a30ebea42e6f885a54

**Pull request merged**
