### PR TITLE
[Feature] add custom view template injections

### PR DESCRIPTION
**Pull request by joshuafontany**
See this googlegroups thread for the spark of this:
https://groups.google.com/forum/#!topic/tiddlywikidev/1OeWQD-HccU

I have attached 2 bundles of files that should allow testing of this by dragging into a vanilla wiki (or on tiddlywiki.com). My current tests are to automatically render the text field of any tiddler tagged `$:/tags/Macro` using a `<pre><code></code><pre>` block. Also, on any tiddler with a `name` field (see plugins), it will automatically use THAT as the title in the story river, pushing the actual title into the subtitle template (matching styles, just above the actual subtitle).

AAAAH, did I actually just do that? I'm not even sure how far you could push this, honestly....

### CODE REVIEW

**Comment by joshuafontany** [comment]
[customTemplateTest.zip](https://github.com/Jermolene/TiddlyWiki5/files/4675946/customTemplateTest.zip)

**Comment by joshuafontany** [comment]
I am going to experiment with this style of "injection" with the EditTemplates as well, and then update the PR.

**Comment by saqimtiaz** [comment]
I only have access to my phone today but at first glance this looks good. It solves a rather old and persistent issue: tweaking view and edit templates without editing shadow tiddlers.

**Comment by twMat** [comment]
@joshuafontany , would this enable us to add data to tiddlers without changing their *modified* date, i.e without actually modifying them? Or will the resulting fields behave just like any other in this regard?

I'm asking because, to name one thing, I want to be able to add meta-data to e.g plugins without modifying them. And -- a'la #1554 -- I want to imported tids to show at top in *Recent* tab but, again, without modifying them.

**Comment by saqimtiaz** [comment]
@twMat this pull request is related to tweaking and controlling view and edit templates. 
It does not have anything to do with adding data to tiddlers.

**Comment by pmario** [comment]
Hi, I didn't do test it. ... BUT it seems to modify the story river and contains "new transclusions". Transclusions are used to create "unique state tiddlers" using the `<<qualify` macro. 

If transclusions are changed at that level, it may change "known state tiddlers". Some of them are used by plugin authors. ... So this may be a breaking change. ... 

Just to be sure. I'm happy if the existing template is improved, but we have to be careful, that everyone knows, if we change, how unique states are named. ...

**Comment by joshuafontany** [comment]
Hi @pmario, yes the Qualify state would be the only thing I can think of that this may change, and I tried to make sure that on tiddlers that are not affected by any customizations use the "default" templates via an empty message in order to place it back exactly where it was before (in the qualify/transclusion stack). I haven't run robust tests against that yet....

**Comment by joshuafontany** [comment]
Threw these changes into all the EditTemplates that made sense (most of them).

WOW, this is probably my favorite thing I've done with tiddlywiki. I finally have a tabbed editor with a toggle to hide/reveal the Fields section. Putting together a set of test tiddlers now.

**Comment by joshuafontany** [comment]
And here is a JSON of all of the tiddlers necessary to test the custom EditTemplate injections. Drag them into a fresh wiki, and open the "Adat 1" tidder into edit-mode.

[custom_templates_edit_test.zip](https://github.com/Jermolene/TiddlyWiki5/files/4679659/custom_templates_edit_test.zip)

**Comment by joshuafontany** [comment]
I thought it would be good to explain the method I am using to do these custom templates. I am not changing the existing $:/tags/ViewTemplate or $:/tags/EditTemplate architecture at all. The $list widget that builds each tiddler in the story-river still does exactly that. What I have done is gone into key system tiddlers with those  tags and found the "bare minimum" code used to render the content, moved that to a macro, such as `\define tiddler-body-default()`. Then, in that place in the system-tiddler, I put (cutting out the debug and "missing tiddler" fail-safe code):
<$list variable="sectionTemplate" filter="[all[current]subfilter{$:/config/ui/ViewTemplate/body}]" emptyMessage=<<tiddler-body-default>> >

<$transclude tiddler=<<sectionTemplate>> >
<$/list>


This checks the $:/config/ui tiddler specified for a series of filters, and uses those titles as sections. BY DEFAULT this will return empty and place the original code back using the `emptyMessage` parameter. Because the list hosting these `sectionTemplates` exist in the tiddler defining the <<tiddler-body-default>> definition, I can use that macro anywhere in my own templates to render the default __whatever__, be that into a tab, a $reveal widget, a new <$div> with a specific class or id value that is a filtered translcusion (triple braces), etc. So I can insert or hide/show the default chunk of code within my own templates. So my glossary template tiddler is as simple as:

<<tiddler-body-default>>

<<glossary-item>>

The <<tiddler-body-default>> code is defined within the $:/tags/ViewTemplate "body" tiddler, and the <<glossary-item>> code is defined in a global macro tiddler ($:/tags/Macro) because I re-use it in other templates.

Because we are using the `subfilter{configTiddler}` operator, each filter run in that config tiddler gets fed the <<currentTiddler>> value. Then, the output is collected and returned as a title-list. This is used to render the new UI for that section. The use of filters allows __whatever__ custom triggers, conditionals, etc, you can conceive by using the current filter operators. I am currently using the existence of a tag for both the Glossary and $:/tags/Macro custom bodies. I will be building UI for my Youtube, Vimeo, etc bookmarks to transclude their player-embed code by grabbing the right parts from their link URL, and drive that on [tag[Bookmark]regexp:url<youtube-domain>], or [tag[Bookmark]regexp:url<vimeo-domain>], or whatever.

I realize now that one of the things that sparked this idea was listening to Jeremy on one of the tiddly-hangout videos talk about how robust the filter operator "language" has become now, and that many things in the core that were done in other ways could be revisited using Filters as the primary syntax. This plus seeing some of the really cool stuff being developed recently, and getting a better sense of how TW renders things "under the hood". Thanks for trying this out, and for all the feedback so far!

**Comment by pmario** [comment]
@joshuafontany please check the text. Some elements are not schown. You need to cover the code inside `` `code` `` backticks, otherwise github thinks they are html and renders them as invisible tags.

**Comment by joshuafontany** [comment]
@pmario, thanks! I forgot the default parser here was markdown and that would mis-parse the wikitext.

**Comment by joshuafontany** [comment]
This is working very well. I have changed the syntax of things slightly, and will need to put together a new demo package of custom config and template tiddlers. Until then, there are basic instructions and Debug/Visualization tools in the Advanced tab of the Tiddler Info section (pop open the Template Help button).

More later. ;D 🥳

**Comment by saqimtiaz** [comment]
@joshuafontany can you give me an example of how one could utilize this to use a field value to decide what template to use for the body of a tiddler? So that it's the only template used for the body, without potentially editing a bunch of tiddlers and removing tags? Does the first one win or are they all rendered?

It seems easier to add templates, but what about removing a template (for specific conditions) or ensuring that a given template is the only one used for a given section? This, for me, is the biggest shortcoming with the current implementation of view and edit templates.

**Comment by joshuafontany** [comment]
Hi Saq,

Yes, I agree with that summary. With the current implementation, Config filter results will totally replace (via transcluding those titles) the default content for that section of the tiddler's View or Edit templates. In this way, I have tried to reserve the "trigger" code to the Config/filter tiddlers, and thus avoid repeated/nested lists in my own templates. So, to your query specifics:

All filter tiddlers tagged with `$:/config/ui/ViewTemplate/body` are passed the currentTiddler value. All results are used as the new content. If you do not have `<<tiddler-body-view>>` in your transcluded content, then the "normal" body never appears. So, for your use case, you need 2 tiddlers. You can use any filter logic that returns the title of your custom template. I'll demo with `[contains:field[value]]`

```
title: $:/saqs/filterLogic (or whatever)
tags: $:/config/ui/ViewTemplate/body

[contains:field-to-check{valueByReference}then[$:/saqs/ui/ViewTemplate/body]]
```
and
```
title: $:/saqs/ui/ViewTemplate/body

!!! Header
...anything-but "tiddler-body-view" macro.
```

As you can see, you can now dynamically change the text field of the `valuebyReference` tiddler to change your filter results without editing the Filter OR the Custom Template tiddlers!

Best,
Joshua Fontanyt

**Comment by joshuafontany** [comment]
Here is a zip with the following tidders to test this. Because I have changed the [subfilter[]] operator, you would need to save and restart the test-wiki.

Test tiddlers (to remove these from your wiki, just copy/paste this list into the Fitler tab of Advanced Search, the select Delete):

$:/core/modules/filters/subfilter.js
$:/core/ui/EditTemplate/body
$:/core/ui/EditTemplate/body
$:/core/ui/EditTemplate/controls
$:/core/ui/EditTemplate/fields
$:/core/ui/EditTemplate/tags
$:/core/ui/EditTemplate/title
$:/core/ui/EditTemplate/type
$:/core/ui/PageTemplate/story
$:/core/ui/TiddlerInfo/Advanced
$:/core/ui/TiddlerInfo/Advanced/TemplateInfo
$:/core/ui/ViewTemplate/body
$:/core/ui/ViewTemplate/plugin
$:/core/ui/ViewTemplate/subtitle
$:/core/ui/ViewTemplate/tags
$:/core/ui/ViewTemplate/title
$:/themes/tiddlywiki/vanilla/base
$:/plugins/joshuafontany/silatglossary/config/ui/ViewTemplate/body/macro
$:/plugins/joshuafontany/silatglossary/config/ui/ViewTemplate/title
$:/plugins/joshuafontany/silatglossary/config/ui/ViewTemplate/subtitle
$:/plugins/joshuafontany/silatglossary/ui/ViewTemplate/body/macro
$:/plugins/joshuafontany/silatglossary/ui/ViewTemplate/title/named
$:/plugins/joshuafontany/silatglossary/ui/ViewTemplate/subtitle/named

[CustomTemplateTiddlers.zip](https://github.com/Jermolene/TiddlyWiki5/files/4713211/CustomTemplateTiddlers.zip)

**Comment by joshuafontany** [comment]
**Subfilter Operator Changes**

I have greatly extended the power of the subfilter operator in this PR. Here are the basic changes.

New suffixes: The operator now accepts a suffix list of of `title` and/or `tag`.

- `title` suffix will get the text content of the parameter-as-title, and loop through the filters inside. `subfilter:title[tiddler]` is equivalent to `subfilter{tiddler}`.
- `tag` suffix will collect all tiddlers tagged with the parameter value, and loops through all filters inside each one at a time (obeys tag-pill order).
- combining suffixes allows you to set the order of the filters in the "tag" to before or after the filters in the "tagged tiddlers". `subfilter:title,tag[tiddler]` gets the text field of the tag and **starts** the filter processing with that, while `subfilter:tag,title[tiddler]` appends the results of the filters inside the tag-tiddler to the **end** of the total results.

Simple, flexible, really powerful.

**Comment by joshuafontany** [comment]
Small bugfix, one of the Debug Icons+Titles in the EditTemplate was always rendering in error.

**Comment by Jermolene** [comment]
Thanks @joshuafontany this looks very interesting. I'm working my way through the easier outstanding PRs first, but will return to this.

**Comment by twMat** [comment]
Bump.
I'd like to see this in 5.1.23 if possible.

**Comment by Jermolene** [comment]
Thanks @twMat @joshuafontany I'm inclined to leave this until after v5.1.23, I'm sorry that we haven't had a chance to explore this properly yet.

**Comment by rubaboo** [comment]
@Jermolene,
I've been tracking the project on and off since late beta (and using TW2 for a number of years prior). Over the years there have been some incredibly talented contributors that came and went. I would like to think that they moved on due to their own reasons, but I'm afraid some of them did so due to unsatisfying experience with their PRs. Just saying. My own experience has been overwhelmingly positive, due to the tiny size and scope of the few PRs that I've managed to submit in the past.

**Comment by Jermolene** [comment]
> @Jermolene,
> I've been tracking the project on and off since late beta (and using TW2 for a number of years prior). Over the years there have been some incredibly talented contributors that came and went. I would like to think that they moved on due to their own reasons, but I'm afraid some of them did so due to unsatisfying experience with their PRs. Just saying. My own experience has been overwhelmingly positive, due to the tiny size and scope of the few PRs that I've managed to submit in the past.

Thanks @rubaboo I've picked up your comment in a separate discussion thread over at #5484.

**Comment by joshuafontany** [comment]
Closing this. UI experiments will have to wait until I get back to front-end stuff.

**Comment by clutterstack** [comment]
I understand that, for sure. I hope you and Jeremy do have a chance to capitalise on this work.

**Comment by joshuafontany** [comment]
@twMat @clutterstack I think this experiment was successful in that it showed there are ways to make the ui for tiddlers in the Story River flexible (context based UI). I am also really encouraged by the recent Customizer plugin & @Jermolene 's use of swappable UI for the Tiddlywiki-on-Fission project. I'd rather re-start from scratch with those in consideration than try tweaking this implementation further.

**Comment by kookma** [comment]
@joshuafontany  

This is interesting PR! Is there a chance to work on this?

**Pull request closed without merging**
