### PR TITLE
Update RefreshThrottling.tid

### PR DESCRIPTION
**Pull request by AnthonyMuscio**
Change word "preciously" to "previously" as I believe was intend.

2nd attempt

### CODE REVIEW

**Comment by AnthonyMuscio** [comment]
Again, this minor change is not appearing in the vercel preview

What do I or we do now?

**Comment by btheado** [comment]
When I view the preview, I see the change. https://tiddlywiki5-git-fork-anthonymuscio-patch-28-jermolene.vercel.app/#RefreshThrottling

**Comment by AnthonyMuscio** [comment]
Thanks @btheado I too see the change now.

It seems if you follow the link to soon you see an unmodified copy.

The change is now correct and this request can proceed.

too simple.

**Comment by Jermolene** [comment]
Thank you @AnthonyMuscio

**Pull request merged**
