### PR TITLE
DOCS: CREATE: Anchor Links using HTML.tid

### PR DESCRIPTION
**Pull request by 00SS**
A new tiddler documenting the process for creating anchors and using links for sub-tiddler navigation.

Arising from issue #3811 & Discussed on Google Groups: [Section Names using ID for internal Links](https://groups.google.com/forum/?hl=en#!topic/tiddlywiki/ikjxwjllFtE)

### CODE REVIEW

**Comment by 00SS** [comment]
I will have to update this PR and include [Tony's insight](https://groups.google.com/d/msg/tiddlywiki/ikjxwjllFtE/V9ByUWhEBAAJ) into using the `<<qualify>>` macro in both the `id` and `href` attributes in order to overcome the limitations of multiple transclusions.

With this inclusion, the internal links within a single tiddlers becomes much more robust. It may still be a challenge to use this for linking from one open tiddler to another one when the `<<qualify>>` macro is used, since the macro does not have a **tiddler** parameter for creating the string for another "given tiddler."

**Comment by 00SS** [comment]
The information on using the `<<qualify>>` macro has been added.

A preview can be seen [here](https://00ss.github.io/documentation/tiddlywiki.html#Internal%20Links%20using%20HTML).

**Comment by twMat** [comment]
@00SS - thank you for your work on this.

IMO the term "Internal link" is ambiguous. It is not obvious that it refers to links within a single tiddler. Maybe a better word would be "Tiddler-internal links" or "Tiddler-local links" or "Tiddler sub-links" or just "Linking within a Tiddler".

**Comment by 00SS** [comment]
Thanks @twMat 

My difficulty was trying to describe the effect taking into account that a link in open tiddler1 (or sidebar) can scroll to open tiddler2 (or sidebar). I will think about it some more.

Also, it may be wise to standardize how to refer to the `id` portion - as an **anchor**, **marker** or **target**. Pre-HTML5 it would be called an anchor using the `name` attribute, but now it is referred to in different ways.

> In HTML 4.01, the `<a>` tag could be either a hyperlink or an anchor. In HTML5, the `<a>` tag is always a hyperlink, but if it has no `href` attribute, it is only a placeholder for a hyperlink.

The other standardization is: does clicking the link **scroll** or **navigate** to the **anchor**/**marker**/**target**

Yet another consideration is on this present documentation keeping open the possibility of future modification of widgets like the `$link` and `$action-navigate` to take advantage of this, and if so, to perhaps decide on this tiddler suggesting a best practice method (like the HTML element to use for the `id` attribute or anything else).

One nice feature of being able to use a modified `<$link to="SomeTiddler" id="#somewhere">` would be that using the right javascript, the browser's history could be left untouched, and perhaps the link's `href` value not appended to the web page's URL. Of course the best part would be if a closed tiddler could be opened followed by navigation to the `id`

**Comment by Jermolene** [comment]
Hi @00SS I think we should use the term "anchor" and "anchor link" because that matches HTML nomenclature and avoids terms that we already use in TW.

**Comment by 00SS** [comment]
- The tiddler has been renamed from **Internal Links using HTML** to **Anchor Links using HTML**
- Text within the tiddler has been changed to use this terminology.
- [Google Groups post](https://groups.google.com/d/msg/tiddlywiki/ikjxwjllFtE/Jddk0T47BQAJ) has been made to allow others to comment
- A preview can be seen here: [Anchor Links using HTML](https://00ss.github.io/documentation/tiddlywiki.html#Anchor%20Links%20using%20HTML)

I would appreciate a check on the **Hints** section at the bottom of the tiddler to know if it is acceptable to suggest using the `tc-tiddlylink` `tc-tiddlylink-missing` & `tc-tiddlylink-shadow` classes for styling the link.

**Comment by 00SS** [comment]
This is ready for merging.
The preview can be seen here: 
https://00ss.github.io/documentation/tiddlywiki.html#Anchor%20Links%20using%20HTML

**Comment by Jermolene** [comment]
Congratulations @00SS this is a very high standard of work, I'm really impressed (I will merge once we've completed the discussion at #3767).

**Comment by twMat** [comment]
@00SS Great stuff! Super small correction - the first example reads:

`<h1 id="#heading-01"> My Heading</h1>`

Because it is a very first and clarifying example, and because the text explicitly discusses space characters, I think the (unsignificant) space character before "My" should be removed to avoid confusion.

**Comment by 00SS** [comment]
Thanks @twMat 
Corrected that now.

**Pull request closed without merging**
