### PR TITLE
Prevent the body from being scrolled when modal is open

### PR DESCRIPTION
**Pull request by felixhayashi**
Hi @Jermolene 

it is really distracting to see the story river scrolling when being inside a modal and using the mouse wheel. A simple addition to the modal code fixes this.

-Felix

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @felixhayashi the problem with this fix is that it changes the scrolling behaviour for long modals. Try pasting lots of content into `SampleWizard` and then triggering the default wizard in `Features`.

**Comment by felixhayashi** [comment]
Ah too bad, I missed that. I experimented with a javascript solution that prevents scrolling of the body when the modal is visible but I really favour a css solution here.

**Comment by felixhayashi** [comment]
Ok, the reason why I forgot that the modal needs to scroll is that I had recently introduced a max-height property set to `70vh` because it was mentioned in the tiddlymap's issue section that it is not nice to search for the modal buttons when the content is to large. So scrolling of the modal is independent from scrolling the body.

> Moreover, on small screens it can be hard to find the OK button. 
> https://github.com/felixhayashi/TW5-TiddlyMap/issues/51#issuecomment-74860245

I have various types of modals which often have changing button combinations (https://github.com/felixhayashi/TW5-TiddlyMap/issues/46) so it's not just about closing a modal.

IMO the modal should only adjust to the height of the content until a certain limit and then overflow.

My css is:

    .tc-modal-body {
      min-height: 250px;
      max-height: 70vh;
      overflow: auto;

What do you think @Jermolene?

-Felix

**Comment by pmario** [comment]
@felixhayashi ... There are merge conflicts now. .. If this PR still important for you, you should update it. Or close and create a new one!

**Comment by pmario** [comment]
IMO this can be solved with CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior
Browser support: https://caniuse.com/css-overscroll-behavior

@Jermolene ... IMO can be closed ... Our "Add plugin modal" in the Control Panel still has the same problem. .. Should a create a PR?

**Comment by Jermolene** [comment]
> IMO this can be solved with CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior
> 
> Browser support: https://caniuse.com/css-overscroll-behavior

I don't think overscroll control helps in this situation (overscroll is the browser behaviour when one tries to scroll above the top or below the bottom of content).

> @Jermolene ... IMO can be closed ... Our "Add plugin modal" in the Control Panel still has the same problem. .. Should a create a PR?

I do still think this is a problem. I investigated it again last year and didn't find any easy solutions.

**Comment by pmario** [comment]
>I do still think this is a problem. I investigated it again last year and didn't find any easy solutions.

IMO if this PR isn't a solution, it should be closed and an issue, with a reference to this PR should be created, to make sure we keep the reference in memory. 

I really would like to get rid of some more pending PRs that are open for years.

**Comment by ght** [comment]
> I don't think overscroll control helps in this situation (overscroll is the browser behaviour when one tries to scroll above the top or below the bottom of content).

I just made a minimal test-case and `overscroll-behavior: contain` *does*  help the situation. Paste this into the address bar and try it out: `data:text/html,<body style="height:200vh"><div style="height:80vh;overflow:scroll;overscroll-behavior:contain"><div style="height:110%25">` (Tested with Firefox and Chromium on Linux)

I didn't know about `overscroll-behavior` before, so thanks @pmario,  really good to know:)

---

I'd say this PR can be closed; I opened #5815 to track the feature request.

**Comment by pmario** [comment]
> > IMO this can be solved with CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior
> > Browser support: https://caniuse.com/css-overscroll-behavior
> 
> I don't think overscroll control helps in this situation (overscroll is the browser behaviour when one tries to scroll above the top or below the bottom of content).

@Jermolene ... I did test the overscroll-behaviour CSS setting and it works as expected. **It does solve the problem**. I did test it with FF and Edge browser

**Comment by Jermolene** [comment]
> @Jermolene ... I did test the overscroll-behaviour CSS setting and it works as expected. **It does solve the problem**. I did test it with FF and Edge browser

Indeed, it seems I'd misunderstood the purpose of the property. But it would be helpful to see some code.

**Comment by ght** [comment]
> But it would be helpful to see some code.

Paste the data URL from https://github.com/Jermolene/TiddlyWiki5/pull/1558#issuecomment-865178803 into the address bar, press enter, and inspect with the dev tools :) Scroll inside/outside the inner div, then toggle the `overscroll-behavior` off and scroll again.

I like data URLs for small test cases/demos like this since they don't depend on any external resource like jsfiddle or the like and are totally self-contained, just like TiddlyWiki :)

**Comment by Jermolene** [comment]
Thanks @ght much appreciated

**Comment by ght** [comment]
@Jermolene I think this old PR can be closed. A new fix for #5815 is being developed in #5816.

**Pull request closed without merging**
