### PR TITLE
update highlight.js to latest v9.18.1

### PR DESCRIPTION
**Pull request by BurningTreeC**

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Comment by Jermolene** [comment]
(Just a small point but you may have noticed that I've been fairly methodically changing your commit headings to be capitalised. The idea is to try to make the commit listing consistent and readable: https://github.com/Jermolene/TiddlyWiki5/commits/master)

**Comment by kookma** [comment]
Thank you both!

**Comment by kookma** [comment]
@BurningTreeC 
Look at the readme: https://tiddlywiki.com/prerelease/plugins/tiddlywiki/highlight/#%24%3A%2Fplugins%2Ftiddlywiki%2Fhighlight

It should be corrected for version number: It is 9.18.1
Readme shows it as 9.15.6

**Comment by kookma** [comment]
Hi Simon (@BurningTreeC ), 
I would much appreciate if you kindly update the highlight.js to latest stable one.
It seems from https://github.com/highlightjs/highlight.js/releases version 10.7.2 is the latest.

The reason is current version shows Fortran numbers wrongly (e.g 2.78_dp)

**Comment by Jermolene** [comment]
Thanks @kookma, I hope @BurningTreeC is around, we haven't seen them for a few weeks and it would be great to have their contributions again.

**Comment by kookma** [comment]
> Hi Simon (@BurningTreeC ),
> I would much appreciate if you kindly update the highlight.js to latest stable one.
> It seems from https://github.com/highlightjs/highlight.js/releases version 10.7.2 is the latest.
> 
> The reason is current version shows Fortran numbers wrongly (e.g 2.78_dp)

Gentle reminder for @BurningTreeC

**Comment by kookma** [comment]
@BurningTreeC 
This is gentle reminder for Simon

**Comment by kookma** [comment]
@Jermolene - this is a gentle reminder! I wish to have highlight.js 11.3+ in TW 5.2.1

**Pull request merged**
