### PR TITLE
Correct documentation for list-after field

### PR DESCRIPTION
**Pull request by kookma**
This PR addresses https://github.com/Jermolene/TiddlyWiki5/issues/6836

It corrects the docs for `list-after` field when the field exists but its value is empty

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @kookma there are some extraneous commits in this PR, I'm not quite sure what's happened.

**Comment by kookma** [comment]
Yes, it is strange. I just changed one tiddler in documentation!
I delete this PR and submit again! As I am not sure how can I modify and correct this.

**Comment by kookma** [comment]
@Jermolene 
One question: Is it okay to submit to master branch or the target is tw5.com?

**Comment by Jermolene** [comment]
Hi @kookma

> One question: Is it okay to submit to master branch or the target is tw5.com?

Updates to existing documentation should target tiddlywiki-com so that they get deployed to tiddlywiki.com without having to wait for a release.

Don't worry about this PR, I'll commit the changes shortly.

**Comment by kookma** [comment]
> Don't worry about this PR, I'll commit the changes shortly.

Thank you Jeremy! and sorry for inconveniences!

**Comment by Jermolene** [comment]
> Thank you Jeremy! and sorry for inconveniences!

Not at all, thank you for the fix @kookma

**Pull request closed without merging**
