### PR TITLE
Support obsidian external link

### PR DESCRIPTION
**Pull request by jeffrey4l**

### CODE REVIEW

**Comment by pmario** [comment]
What does this do. Can you be a bit more specific?

**Comment by Jermolene** [comment]
Thank you @jeffrey4l  for your contribution. With apologies for the bureaucracy, please could you prepare a separate PR to the 'tiddlywiki-com' branch with your signature for the Contributor License Agreement (see [contributing.md](https://github.com/Jermolene/TiddlyWiki5/blob/master/contributing.md)).

**Comment by pmario** [comment]
The file to sign is: https://github.com/Jermolene/TiddlyWiki5/blob/master/licenses/cla-individual.md

**Comment by Jermolene** [comment]
Thank you @jeffrey4l

**Pull request merged**
