### PR TITLE
putSaver: probe for server support on startup

### PR DESCRIPTION
**Pull request by edrex**
save fails until probe succeeds,
allowing other saver methods to take over

On non-webdav servers, download saver is used.
On webdav servers, DAV header is detected and put saver is
used.

Detection could be extended to other server types than webdav
(couchdb, riak, REST)

Follow up to #2288, #2277

### CODE REVIEW

**Comment by edrex** [comment]
Ok, I'm feeling like this is about firmed up. It doesn't interfere with the other savers now (only kicks in if/once an async server probe succeeds).

Remaining todos, which can come later:

- Basic overwrite protection using etags, to make using multiple devices safer
- A getting started doc

**Comment by Jermolene** [comment]
Thanks @edrex. A great improvement, and I'll happy to merge, but I'm thinking that the OPTIONS probe is still an undesirable overhead to add to the core. It could confuse people looking in dev tools. What do you think about moving it to a `tiddlywiki/webdav` plugin?

**Comment by edrex** [comment]
My goal is to establish a standard server env for hosting browser apps, so I'll tend to push for enabling protocol support by default.

OTOH, there are no suitable free hosting providers AFAIK (see #2291) so this is only useful for people/groups able to operate a server.

I'm fine with pulling it out into a plugin, especially if we can revisit including it in the default builds once there's a good hosting option non-techies can use.

**Comment by Jermolene** [comment]
Thanks @edrex, if the move doesn't impact your own use case then let's go ahead. Are you happy to do a pull request for the move?

**Pull request merged**
