### PR TITLE
Added tooltip option to Tabs macro

### PR DESCRIPTION
**Pull request by matabele**
Tooltips should be entered in the 'tooltip' field of each tab tiddler

### CODE REVIEW

**Comment by matabele** [comment]
In this version -- the <<currentTiddler>> is set to <<currentTab>> only around the $button widget. Hopefully this will not interfere with anything else (appears to be no problems.)

**Comment by matabele** [comment]
This seems to break the "default" tab -- but I can't see why. Any ideas?

**Comment by matabele** [comment]
OK -- after cleaning all of the state tiddlers, now functions correctly -- seems to have been caused by 'dirty' leftover state tiddlers.

**Comment by Jermolene** [comment]
Thanks @matabele

**Pull request merged**
