### PR TITLE
Add dragenteractions and dragleaveactions ...

### PR DESCRIPTION
**Pull request by BurningTreeC**
... to droppable widget

The `refresh` method needs some work here, too?

### CODE REVIEW

**Comment by saqimtiaz** [comment]
One thing to consider here is that our detection of "dragleave" does not work reliably on Firefox and is sometimes not triggered (visually indicated by the dragover class and associated effects persisting even when an element is no longer being dragged over). The dropzone widget had the same problem, for which I implemented a workaround when working on image import in the editor. However, we still need to resolve it for the droppable widget.

In this context it will mean that dragleave actions will not reliably be triggered in Firefox. It may be prudent to resolve those underlying issues before we add support for dragenter/leave actions.

**Comment by pmario** [comment]
https://stackoverflow.com/questions/10253663/how-to-detect-the-dragleave-event-in-firefox-when-dragging-outside-the-window

There seems to be a discussion at stackoverflow, which also points to some bugs at bugzilla. ..

**Comment by saqimtiaz** [comment]
There is discussion of the issue as seen in the dropzone widget and the fix implemented in the PR description at https://github.com/Jermolene/TiddlyWiki5/pull/5688

**Comment by BurningTreeC** [comment]
> One thing to consider here is that our detection of "dragleave" does not work reliably on Firefox and is sometimes not triggered (visually indicated by the dragover class and associated effects persisting even when an element is no longer being dragged over). The dropzone widget had the same problem, for which I implemented a workaround when working on image import in the editor. However, we still need to resolve it for the droppable widget.

Hi @saqimtiaz , is there a way to resolve it for the droppable widget?

> 
> In this context it will mean that dragleave actions will not reliably be triggered in Firefox. It may be prudent to resolve those underlying issues before we add support for dragenter/leave actions.

**Comment by saqimtiaz** [comment]
> Hi @saqimtiaz , is there a way to resolve it for the droppable widget?

I posted a link above to how we resolved it for the dropzone widget. We would need to see if that technique is transferrable to the droppable widget.

**Comment by BurningTreeC** [comment]
> > Hi @saqimtiaz , is there a way to resolve it for the droppable widget?
> 
> I posted a link above to how we resolved it for the dropzone widget. We would need to see if that technique is transferrable to the droppable widget.

Thank you @saqimtiaz , but I'm having a hard time to understand what's going on and how to implement this for the droppable widget

**Pull request closed without merging**
