### PR TITLE
Adjust documentation following pull #1422

### PR DESCRIPTION
**Pull request by aelocson**
i.e. the `each:list` operator.

### CODE REVIEW

**Comment by tobibeer** [comment]
@aelocson, thank you very much. Is there some documentation on **.operator-def** yet?

**Comment by aelocson** [comment]
There's no documentation on it yet. But I'm seriously considering your idea of rejigging it to use fields and be part of the view template, as that would be much more flexible and tiddlyesque. If that happens, `.operator-def` will become a thing of the past.

**Comment by tobibeer** [comment]
I see and I think I'm in favor. Once the "extended search" pull passes, those filter fields could be explicitly searched on TiddlyWiki.com alongside other fields.

**Comment by aelocson** [comment]
Yes, I'd be in favour of searching all fields.

**Comment by Jermolene** [comment]
Thanks @aelocson

**Pull request merged**
