### PR TITLE
Fix typos and Refnotes URL in kookma resources

### PR DESCRIPTION
**Pull request by clutterstack**
Fixed a few typos in tiddlers referring to Mohammad's resources, including a bad URL. My first pull request; hope it's appropriate.

### CODE REVIEW

**Comment by saqimtiaz** [comment]
@clutterstack thank you. We are in a bit of a post-release and holiday season lull at the moment. Expect things to pick up in January.

**Comment by clutterstack** [comment]
I'm in no rush, Saq. Kind of you to reply.

**Comment by kookma** [comment]
> Fixed a few typos in tiddlers referring to Mohammad's resources, including a bad URL. My first pull request; hope it's appropriate.

@clutterstack -  Hi Chris, I really appreciate this! 
Thank you!

**Comment by Jermolene** [comment]
Thanks @clutterstack and apologies, merging #5353 has given this PR a bunch of merge conflicts. Are these changes still relevant?

Also, it doesn't look like you've signed the CLA. With apologies for the bureaucracy, please could you prepare a separate PR to the 'tiddlywiki-com' branch with your signature for the Contributor License Agreement (see [contributing.md](https://github.com/Jermolene/TiddlyWiki5/blob/master/contributing.md)).

**Comment by clutterstack** [comment]
Hi @Jermolene ,

Looks like the edits are still relevant, just that the files have moved. I'll try to fix this PR.

**Comment by pmario** [comment]
@Jermolene ... Is it recommended to list every single 3rd party plugin on the TW homepage under the Community "tree"?

**Comment by Jermolene** [comment]
> @Jermolene ... Is it recommended to list every single 3rd party plugin on the TW homepage under the Community "tree"?

I think it's not unreasonable to try to list the important ones.

**Comment by clutterstack** [comment]
Leaving the higher-altitude problem of content curation aside, I've submitted a new PR to fix the conflict and am closing this one.

**Pull request closed without merging**
