### PR TITLE
Improve global "wikilink" parser disabling

### PR DESCRIPTION
**Pull request by pmario**
Based on https://groups.google.com/d/msg/tiddlywiki/e37DrMl2QLg/l6zuhlrZBAAJ

Problem: 

If `ControlPanel: Settings: Enable automatic CamelCase linking` ... is disabled every tilde `~` sign, that is used in the core UI will be visible. 

This PR fixes the problem and passes all TW tests from the "test" edition. It creates a new wikirule: "unwikilink" that also can be "disabled/enabled", with the existing UI, if needed.

### CODE REVIEW

**Comment by pmario** [comment]
There are 2 other wikirules, that will have a similar behaviour. .. Which will be a different PR, if needed.

`syslink` and `extlink` also use the tilde sign to modify the rendering behavior. ... BUT IMO fixing them, without real reported problems, seems to be not needed. ...

**Comment by Jermolene** [comment]
Hi @pmario this is a good problem to pick up. I'm not sure that switching wiki parser rules is the way to accomplish it though; instead, we could keep the current parse rules, and handle the disabling within the implementation of the corresponding widget (eg the link widget in this case). There's partial support already with the `tv-wikilinks` variable.

**Comment by pmario** [comment]
`tv-wikilinks` variable does something different.

the PR is for `~CamelCase` detection only. In the ControlPanel [Settings-tab](http://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FControlPanel%2FSettings%2FCamelCase) we disable the whole CamelCase detection, which causes the core UI to break, because everywhere, where we used the ~ tilde sign, it is visible. 

Splitting one rule to 2 like in the PR IMO fixes the problem in a simple and compatible way, without having any effect on the parsing performance. 

`tv-wikilinks` IMO should be for authors only, if they want to create their own templates. The core should step out of the way here.

**Comment by Jermolene** [comment]
Hi @pmario apologies for the lack of clarity. In order for my proposal to work, we'd need an additional attribute on the link widget that could be set by the parser to indicate that the widget was created in response to a camel case link.

**Comment by Jermolene** [comment]
@pmario I've just realised that a simpler and more correct approach may be just to remove any disabled camelcase in the core `$:/language` tiddlers (that's a matter of search and replace of `~TiddlyWiki` with `[[TiddlyWiki]]` and two others). That would make the core UI completely usable with camelcase disabled, and would avoid the anomaly that otherwise preceding tildes will be inconsistently invisible for people with camel case switched off.

**Comment by Jermolene** [comment]
Hi @pmario new users frequently expect the `~` to be able to disable other forms of wikitext syntax. I wonder if we might not split it out into a new "disable-wikitext" rule: it would match any tilde that:

* does not follow another tilde
* is not followed by another tilde or whitespace

The action of the rule would be to create a text node wrapping the text immediately after the tilde up until the first whitespace.

Then we could remove the existing tilde handling from syslink.js, extlink.js and wikilink.js.

What do you think?

What do you think?

Generally, I'm thinking that new users tend to be confused by CamelCase automatic linking, to the degree that we should perhaps consider disabling it by default

**Comment by pmario** [comment]
>Then we could remove the existing tilde handling from syslink.js, extlink.js and wikilink.js.
>
>What do you think?

I like this idea. 

---------

>Generally, I'm thinking that new users tend to be confused by CamelCase automatic linking, to the degree that we should perhaps consider disabling it by default

Yea, that thought has come to me too. ... May be CamelCase "autolinking" is just for users that started working with computers in the 80's or earlier ;)

**Comment by tobibeer** [comment]
> new users frequently expect the ~ to be able to disable other forms of wikitext syntax. I wonder if we might not split it out into a new "disable-wikitext" rule: it would match any tilde that

Totally like this! Can't think of anything that would break because of it, right now, so long as disabling parsers this way is but bound to the "next word".

**Comment by tobibeer** [comment]
In that sense, I think this PR should be closed and replaced with a new issue (just so that it doesn't show up in the list of open PRs).

**Comment by pmario** [comment]
If there is a new PR, that replaces this one and incorporates Jeremy's suggestions, I will close it.

**Comment by 00SS** [comment]
After further consideration I would like to suggest that both **CamelCase** and the **syslink** parser rule **be turned off by default** in both tiddlywiki.com and empty.html

The reasons for this are given by me in this post on tiddlywikidev Google Group (2019-02-12): [General usefulness of the parser rule: syslink ?](https://groups.google.com/forum/#!msg/tiddlywikidev/B5UsFTGN5Mg/B7xeWXd7BgAJ)

**Comment by Jermolene** [comment]
Hi @00SS I'm definitely keen to switch CamelCase off by default, but I'm not sure that I agree about disabling system tiddler linking. I'll reply to the google group thread with more details.

**Comment by pmario** [comment]
@Jermolene 

>Hi @pmario new users frequently expect the `~` to be able to disable other forms of wikitext syntax.

I know, it's a long time ago, but I did have a look at: [WikiText](https://tiddlywiki.com/#WikiText) and I couldn't find more possibilities, that would make sense for the `~`

eg: 

```
~<<<
block quote
<<<
```

I don't think that this would make sense. ... AND I think it will be very hard to implement. 

Same with `~<$link .... >2 lines</$link>` ... If you don't want a link. ... don't create one!

**Comment by Jermolene** [comment]
Hi @pmario I haven't experimented beyond [my note above](https://github.com/Jermolene/TiddlyWiki5/pull/2844#issuecomment-312029335) but it still seems reasonable.

**Comment by 00SS** [comment]
@Jermolene @pmario
It occurred to me that if CamelCase (and hopefully also syslink) are turned OFF at tiddlywiki.com and empty.html, perhaps they need to be left switched ON at https://tiddlywiki.com/prerelease/

This is so that all new features continue to be tested against possible side effects for those who prefer them to be ON.

**Comment by 00SS** [comment]
Ref: Issue #3779 AnthonyMuscio's [comment](https://github.com/Jermolene/TiddlyWiki5/issues/3779#issuecomment-465367690)

> 
> Broken Doco https://tiddlywiki.com/#TiddlerFields all references are broken or non existant
>
For someone seasoned in using TiddlyWiki and who has used tiddlywiki.com hundreds of times, one can sense frustration that the website tiddler seems broken or links are to non existent tiddlers.

Though regulars are aware they are just CamelCase links, so usually ignore the _italicized_ missing link, it is left to our respective imaginations to speculate how a new comer to the website would react, and how their impression would affect their enthusiasm to continue exploring.

**Comment by pmario** [comment]
>Though regulars are aware they are just CamelCase links, ...

I'm pretty sure, it was intended to add those tiddlers and may be more info. ... It's just - nobody did it ;/

**Comment by 00SS** [comment]
`{{TiddlerFields!!created}} = Mon Aug 26 2013 ...`
The lesson might be that links left to nowhere on tiddlywiki.com don't necessarily lead to documentation filling the gaps, just frustration or confusion for those that use it for some of its primary purposes - such as for documentation, getting a feel of the program, and gauging its state of development.

**Comment by pmario** [comment]
Just a reference to a new discussion at Talk TiddlyWiki: https://talk.tiddlywiki.org/t/the-using-of-camelcases-and-what-the-tilde-is-doing/287

**Comment by pmario** [comment]
Close this one in favour of a new issue.

**Pull request closed without merging**
