### PR TITLE
Make Stamp-Dropdown sortable by Drag&Drop

### PR DESCRIPTION
**Pull request by BurningTreeC**
This PR makes the Stamp-Dropdown items sortable by Drag&Drop
Therefor it uses the `list-tagged-draggable` macro and an additional `ItemTemplate`

This is very handy if a User has many Stamps and wants to order them by favourites

### CODE REVIEW

**Comment by BurningTreeC** [comment]
This PR also makes stamp-dropdown entries editable when we click them using <kbd>ctrl</kbd>-click

**Comment by saqimtiaz** [comment]
It would be helpful if you posted a demo @BurningTreeC

**Comment by BurningTreeC** [comment]
Thanks @saqimtiaz , here's a Demo:

[stamp-dropdown.zip](https://github.com/Jermolene/TiddlyWiki5/files/7037094/stamp-dropdown.zip)

**Comment by pmario** [comment]
I do like the possibility.

**Comment by saqimtiaz** [comment]
Looks good to me as well. Nicely done @BurningTreeC

**Comment by Jermolene** [comment]
Thanks @BurningTreeC @saqimtiaz @pmario

**Pull request merged**
