### PR TITLE
description notes remarkable instead of markdown-js

### PR DESCRIPTION
**Pull request by activescott**

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @activescott, and apologies for the delay. There's a tiny bit of bureaucracy before we can merge PRs from contributors -- please see the instructions for signing the "Contributor License Agreement" here: https://github.com/Jermolene/TiddlyWiki5/blob/master/contributing.md

**Comment by activescott** [comment]
@Jermolene Now it's my turn to apologize for the delay! I should have paid more attention to the contributing.md too. Thank you for your kind pointer in the right direction.

**Comment by activescott** [comment]
Signed in #4440

**Comment by Jermolene** [comment]
Thanks @activescott

**Pull request merged**
