### PR TITLE
targeted fix for 5366

### LINKED ISSUE #5366: [BUG] Crash on Node.js with ActionSetField when type field is given a value upon new tiddler creation
When the ActionSetField widget is used on a missing tiddler, it usually creates it, then sets the provided fields to their requested values. In Node.js mode, it instead crashes when given an explicit value for the type field.

1. Start a Node.js instance of TiddlyWiki 5.1.23 in a terminal, like `node ~/src/TiddlyWiki5/tiddlywiki.js ~/wikis/100000000000000/ --verbose --listen port=10000 host=0.0.0.0 tls-key=../tls/key.pem tls-cert=../tls/server.crt`
2. Create a tiddler with the following content: `<$button><$action-setfield $tiddler="A probably missing tiddler" type="text/plain"/>Crash test</$button>`
4. Click on the button, and experience the crash in the terminal:
``` 
...
syncer-server-filesystem: Dispatching 'save' task: A probably missing tiddler 
internal/fs/utils.js:781
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFile (fs.js:1436:5)
    at Object.exports.saveTiddlerToFile ($:/core/modules/utils/filesystem.js:414:6)
    at $:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:85:13
    at FileSystemAdaptor.getTiddlerFileInfo ($:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:72:2)
    at FileSystemAdaptor.saveTiddler ($:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:81:7)
    at SaveTiddlerTask.run ($:/core/modules/syncer.js:597:27)
    at Syncer.processTaskQueue ($:/core/modules/syncer.js:503:9)
    at Function.<anonymous> ($:/core/modules/syncer.js:90:9)
    at $tw.Wiki.exports.dispatchEvent ($:/core/modules/wiki.js:133:13)
    at $:/core/modules/wiki.js:166:10 {
  code: 'ERR_INVALID_ARG_TYPE'
}
...
```
FWIW, this has been tested with Node.js version v14.14.0 and v15.5.0

### PR DESCRIPTION
**Pull request by joshuafontany**
Fixes #5366

### CODE REVIEW

**Comment by joshuafontany** [comment]
@Jermolene I pulled this out of the experimental PR early as it was a fix for a reported bug. Should be good to merge this as is. Thanks!

**Comment by joshuafontany** [comment]
Caught and cleaned up a change I implemented elsewhere. Definitely good to merge now.

**Comment by joshuafontany** [comment]
@Jermolene This is a target fix around programmatically creating tiddlers that lack a text field. Good to merge.

**Comment by Jermolene** [comment]
Thanks @joshuafontany

**Pull request merged**
