### PR TITLE
TW5, Spanish Edition

### PR DESCRIPTION
**Pull request by PauDeLuca**
Spanish edition translated at 98%.

Hosted at http://tw5es-es.tiddlyspot.com/

### CODE REVIEW

**Comment by PauDeLuca** [comment]
Translation work finished at 98% approx
We'll start proofreading along the next days.

**Comment by Jermolene** [comment]
Hi @PauDeLuca are you ready for this to be merged?

**Comment by PauDeLuca** [comment]
Yes!
I'm happy with the work done so far. Thanks

**Comment by Jermolene** [comment]
Thanks @PauDeLuca

**Comment by Jermolene** [comment]
By the way @PauDeLuca there were some problems with this pull request:

* Accented characters in filenames cause problems with Git on several platforms
* You've included the re-engineering of the ThemeTweaks. I'm sympathetic to the problem that you're trying to solve, but the solution you've committed is not acceptable. It breaks the internal structure of TiddlyWiki, and several design principles that we've carefully observed up until now. I know from the earlier discussion that you disagree, but I'm afraid that we can't have the internal design of TiddlyWiki compromised in this way

**Comment by PauDeLuca** [comment]
I was not aware of the accented tiddlerfile names, sorry.
I made a test and then forgot to revert it back. I am sure I reverted the
theme-tweaks override later in commit 3163f5. I don't know why it still was
there when I requested the pull...



2016-05-12 16:57 GMT+02:00 Jeremy Ruston <notifications@github.com>:

**Pull request merged**
