### PR TITLE
Update server.js

### PR DESCRIPTION
**Pull request by somax**
Enable gzip compression for index.html

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @somax thanks for this. Apologies for the bureaucracy, but please could you send a separate pull request with your signature for the Contributors License Agreement - see contributing.md in the root of this repo.

**Comment by danielo515** [comment]
What is this for? To serve the content gzipped to save bandwidth? To save the wiki as a zip file? Thanks!

**Comment by sukima** [comment]
My inner troll becomes very agitated when commits and pull requests are cryptic and uninformative. :trollface: 

Joking aside, can the commit summary and message be [more descriptive](http://chris.beams.io/posts/git-commit/)?

**Comment by Jermolene** [comment]
Hi @somax as @sukima suggests, a more descriptive commit message would be useful: "Enable gzip compression for index.html". I also still need your signature on the CLA before I can merge - many thanks!

**Comment by somax** [comment]
Hi @Jermolene, sorry for the mess, I'm trying to fix the commit message, Is it possible to change the commit message that I am already push to github?

**Comment by danielo515** [comment]
I think you can do it directly on github

**Comment by Jermolene** [comment]
Closing this as it has been superseded by #1754

**Pull request closed without merging**
