### PR TITLE
move tip to the end of the tiddler so it does not distract reading

### PR DESCRIPTION
**Pull request by pmario**
move tip to the end of the tiddler so it does not distract reading 

---
<small>Submitted using https://saqimtiaz.github.io/tw5-docs-pr-maker/.</small>

### CODE REVIEW

**Comment by pmario** [comment]
I think those 3 tiddlers are much more readable now: https://tiddlywiki5-git-fork-pmario-move-tip-to-the-en-f19814-jermolene.vercel.app/#tv-filter-export-link%20Variable:%5B%5Btv-filter-export-link%20Variable%5D%5D%20%5B%5Btv-get-export-link%20Variable%5D%5D%20%5B%5Btv-wikilink-template%20Variable%5D%5D

OLD -- I think the tips do distract users from reading the content. It's good enough if the "note" comes at the end

https://tiddlywiki.com/#tv-filter-export-link%20Variable:%5B%5Btv-filter-export-link%20Variable%5D%5D%20%5B%5Btv-get-export-link%20Variable%5D%5D%20%5B%5Btv-wikilink-template%20Variable%5D%5D

**Comment by pmario** [comment]
@Jermolene -- this is a documentation only PR

**Comment by Jermolene** [comment]
Thanks @pmario – I prefer if minor tweaks like this do not change the "modified" date because it makes the "Recent" tab more useful for end users. Is that easy for you to change? If not, I'm happy to merge as it is.

**Comment by Jermolene** [comment]
Thanks @pmario

**Pull request merged**
