### PR TITLE
Allow additional server paths

### PR DESCRIPTION
**Pull request by natecain**
Add additional routes to the basic server from a "routes" list in wiki info file.  Each item in the list is an object with a path, serveType, renderType, and rootTiddler.

### CODE REVIEW

**Comment by tobibeer** [comment]
Is this still open considering #1148 & #2510?

**Comment by pmario** [comment]
@natecain ... the upcoming 5.1.18 will add a lot of new stuff to the server. So imo this one can be closed!

**Comment by pmario** [comment]
@Jermolene ... I think the existing node server can handle this one and more.

**Comment by pmario** [comment]
@Jermolene ... I think this one can be closed. There hasn't been any response from @natecain and he wrote: [Do not merge, has bugs](https://github.com/Jermolene/TiddlyWiki5/pull/976#issuecomment-59662251) here in the tread.

**Comment by Jermolene** [comment]
Thanks @natecain @pmario we have subsequently moved routes out into their own modules

**Pull request closed without merging**
