### PR TITLE
Update TiddlyClip by buggyjay.tid

### PR DESCRIPTION
**Pull request by le-pako**
Small edit to correct a typo on Firefox name and add a link. 
Also a first run at using Github to edit documentation :)

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @le-pako for the contribution - I'm afraid there's a minor piece of bureaucracy: we need all contributors to electronically sign the contributors license agreement to explicitly transfer their copyright to the TiddlyWiki project. See `contributing.md` in the root of this repo for instructions.

**Comment by felixhayashi** [comment]
Hi @Jermolene 

> I'm afraid there's a minor piece of bureaucracy: we need all contributors to electronically sign the contributors license agreement to explicitly transfer their copyright to the TiddlyWiki project.

just wanted to highlight that the contributer remains (!) to be the copyright holder but licenses you his work under the conditions stated in contributing.md which means it can be distributed under the current tw-license (bsd) or any other license you (as tiddlywiki copyright holder) plan to choose in the future. 

Excuse me if this remark appears nitpicky, I just think it is important to clearly communicate that the contributer does not lose his/her copyright.

-Felix

**Comment by Jermolene** [comment]
Thanks @felixhayashi you are quite right, I should have said "license" rather than "transfer".

**Comment by le-pako** [comment]
Thanks @Jermolene, I thought it wouldn't be required to simply help with documentation. Anyway, it's all set now.
Cheers

**Pull request merged**
