### PR TITLE
make tags input look cleaner

### PR DESCRIPTION
**Pull request by BurningTreeC**
... by making its background color transparent

### CODE REVIEW

**Comment by BurningTreeC** [comment]
bump

**Comment by Jermolene** [comment]
Hi @BurningTreeC I quite like this change but feel that it is inconsistent with our other usage of text boxes. I think it's the kind of thing we might do if we were to create a new default theme, for instance.

---

Here's what the add tag box looks like with this PR:

image

And here's what it looks like now:

image

**Comment by pmario** [comment]
hmmm. For me the existing version makes more sense, since it defines, to which element the dropdown arrow belongs to.

**Comment by BurningTreeC** [comment]
@pmario, yes I think you're right, closing this PR

**Pull request closed without merging**
