### PR TITLE
Add sidebar buttons to TopRightBar when sidebar is closed.

### PR DESCRIPTION
**Pull request by mklauber**
This change puts all the selected sidebar buttons into the TopRightBar when the sidebar is closed.  This is particularly helpful for things like creating lots of new tiddlers because the new tiddler button can be visible without the sidebar consuming screen real estate.

### CODE REVIEW

**Comment by danielo515** [comment]
This change adds an unnecessary right-margin when the screen is narrow.
Please test it out and try to fix it.

**Comment by mklauber** [comment]
Can you give a little more detail?  Looking at tiddlywiki.com with this tiddler overridden, it seems to have the same behavior as beforehand.  A small margin on the right when closed (not the same size as the number of buttons).  And when the sidebar disappears, the buttons float above the river, rather than shrinking it.

**Comment by danielo515** [comment]
As I said, all you have to do is shrink the window:

image

As you can see, I have to scroll right to see all the buttons

**Comment by mklauber** [comment]
Can you send me a example wiki and/or tell me your browser/OS?  When I try my change on tiddlywiki.com in Chrome, I don't see the same behavior.  Also, which version of tiddlywiki are you using?  

Before (tiddlywiki.com):
before

After (tiddlywiki.com):
after

**Comment by danielo515** [comment]
I'm just copy pasting your tiddler on tiddlywiki.com

Try to open chrome dev tools and activate the smartphone viewport

**Comment by mklauber** [comment]
Aha! Thanks, I can see what you mean now.  However for me, the same wide sidebar occurs regardless of whether my code is in place.  I think that may be an unrelated bug with small screens (the issue is more pronounced the smaller the screen).  If so, I think that should be handled in a separate PR.

screenshot from 2017-05-26 09-27-02

**Comment by danielo515** [comment]
I'll have e to check . It never happened to me before

**Comment by Jermolene** [comment]
This is a great idea, thanks @mklauber. I wondered why you couldn't just transclude the existing `$:/core/ui/PageTemplate/pagecontrols` instead of duplicating it's content. Is it a matter of the `.tc-page-controls` class on the wrapper? If so, could we explore fixing that in CSS-land?

**Comment by danielo515** [comment]
I just checked with current tw version and it is also happening, so it's a tw bug. Very annoying I have to say

**Comment by mklauber** [comment]
@Jermolene a simple transclusion runs into issues with the .tc-page-controls <div> pushing the chevron down into a second line.  a pretty simple fix move the div into the containing tiddler, and leave page controls as just the list, which is what I'll try to do on this PR.

**Comment by Jermolene** [comment]
HI @mklauber on reflection, I wonder if there are any backwards compatibility concerns. There may be people who favour the current combination of a minimal display of a single page control icon when the sidebar is hidden, but a full set of page control icons when the sidebar is shown. That combination doesn't seem possible with this change, which will mean that the appearance of existing TW's that hide the sidebar will change.

Perhaps the workaround is to add a new setting in control panel, a checkbox like "Show all page controls when sidebar is hidden"?

**Comment by mklauber** [comment]
@Jermolene Sorry for the delay, but I think that should do what you asked.

**Comment by mklauber** [comment]
@Jermolene Do you have any feelings on #2911 ? I don't know what the right answer is, other than don't enable the "mini-menu" when you've got "sticky titles" enabled.

**Pull request closed without merging**
