### PR TITLE
Remove dependency on wiki.js for story-startup and navigator

### PR DESCRIPTION
**Pull request by BurningTreeC**
This removes the indirection through wiki.js to access addToStory and addToHistory in story.js

It's probably the first step to simplify the story-navigator mechanisms

### CODE REVIEW

**Comment by BurningTreeC** [comment]
#4180

**Comment by Jermolene** [comment]
I'm happy with this, but I think we should leave the existing methods on the wiki object for backwards compatibility.

**Comment by pmario** [comment]
Why did you close it? ... We can add a deprecated warning into the removed code, instead of removing it. Then after eg 2 versions we can remove it

**Comment by BurningTreeC** [comment]
@pmario - closed it because I thought this wouldn't be of interest

**Comment by pmario** [comment]
I think the existing implementation is a bug, if you have 2 navigator widgets, that work for different stories. ... So imo it has to be fixed anyway. 

I would add a `console.log()` to the "deprecated" code, instead of removing it, since Jeremy wants the function to be still part of the `$tw.wiki` API

eg: `console.log("$tw.wiki.addToHistory() is deprecated! Use the this.story.addToHistory() from the story-object!")` ... same with addToStory.

So if a developer uses the "old" function they should immediately see, that there is something wrong. .. BUT old plugins still work. 

We could check our plugins and those of other important and core plugins, to see, if someone uses this function. ... But that's definitely much more work.

**Comment by pmario** [comment]
may be: `console.log("$tw.wiki.addToHistory() is deprecated since V5.1.23! Use the this.story.addToHistory() from the story-object!")`

**Comment by pmario** [comment]
I checked my plugins. 1 of them actually uses the "old" function. ... So Jeremy is right!

**Comment by BurningTreeC** [comment]
@pmario @Jermolene - now the old code is still in place, I've put it back. Should I add a console log that marks them as deprecated?

**Comment by pmario** [comment]
>... Should I add a console log that marks them as deprecated?

I think there should be a console.log()

**Comment by pmario** [comment]
@Jermolene ... needs to decide it.

**Comment by BurningTreeC** [comment]
@Jermolene do you have any thoughts on this one?

**Comment by Jermolene** [comment]
Hi @BurningTreeC @pmario we have a precedent in `$:/core/modules/filters.js` for displaying deprecation warnings to the console. But we should probably be smarter about it, and not re-display the same message more than once:

```
if(!errorHasBeenDisplayed) {
  errorHasBeenDisplayed = true;
  console.log("error");
}
```

**Comment by BurningTreeC** [comment]
@Jermolene - I'd need advice where to put the console log and how to handle it it's already been displayed

**Comment by Jermolene** [comment]
Hi @BurningTreeC for the moment we can just use console.log in the usual way; if there are issues with the amount of logging then we can address them later.

**Comment by BurningTreeC** [comment]
Ok @Jermolene, I've added the console logs like @pmario suggested in a post above

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Pull request merged**
