### PR TITLE
NoToZaczynamy.tid

### PR DESCRIPTION
**Pull request by zakrec**

### CODE REVIEW

**Comment by sukima** [comment]
Don’t feed the trolls

**Comment by sukima** [comment]
So I originally thought this was trolling. Mainly because there were six pull requests all labeled the same non-sense title description. (I tried google searching and got no results.) It wasn’t until I saw one of the pull request say:

> polish translation

Then I figured it out. Especially confusing because these changes were all on the main English sources which suggested to me it was a hack. Lack of clear titles and code changes to main sources instead of separate translated sources really confused me.

**Comment by sukima** [comment]
I have this blog post as a top five goto for me: https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message

**Comment by pmario** [comment]
Hi @zakrec 
Thank you very much for your help! But there will be some issues :)

If you split your translations into single pull requests, it will need a long time until the translation is done. There are too many texts in TW. ... So Jeremy created a translators edition: http://tiddlywiki.com/editions/translators/ ... You can download this one, translate the texts, save and send it to Jeremy by mail. .. He will be able to create a language out of it. 

Second methode: 

 - Fork the TW5 repo
 - create a feature branch eg: pl-PL
 - create a subdirectory here: https://github.com/Jermolene/TiddlyWiki5/tree/master/languages
 - take the core files from here: https://github.com/Jermolene/TiddlyWiki5/tree/master/core/language/en-GB
 - and copy them into your language tree
 - push it to your repo and create a pull request. 

If "Second method" doesn't make sense use the first one with the translators edition. 

... any questions. .. Just ask

**Comment by zakrec** [comment]
Hi @pmario 
Thank you for your help. I tried second methods but unfortunately I had a problem with uploading the entire folder with the translation. I downloaded the file as you suggested, and when i finish translating send it by @.

**Comment by sukima** [comment]
> I had a problem with uploading the entire folder with the translation

How so? A `git push` should have done the trick.

**Comment by pmario** [comment]
@Jermolene IMO same as: #2296 .... can't be merged as it is

**Comment by Jermolene** [comment]
Thanks @pmario

**Pull request closed without merging**
