### PR TITLE
Update cla-individual.md

### PR DESCRIPTION
**Pull request by EdDixon**
Adding myself to contributors list in preparation of xAP, WebTorrent, and other educational efforts using TiddlyWiki. 

Thanks,

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @EdDixon I'm afraid that I can't directly merge this pull request because I've committed other changes to the same file since you made it. Ordinarily, I can unpick things, but in this case if I do we'll lose the attribution between the commit and your user account.

The quickest way to get things moving would be if you could just create a new pull request on the latest version of the file - my apologies!

**Comment by EdDixon** [comment]
Will do thanks!

Ed Dixon
Corrections Adviser
Foundation for Learning Equality <http://learningequality.org/>
Give to FLE, Support FLE via Amazon Smile!
<https://learningequality.org/donate/>
M (575)-201-3691

**Comment by Jermolene** [comment]
Hi @EdDixon please do go ahead and create a new pull request if you get a chance, I'm closing this for the moment since I can't merge it as is.

**Comment by sukima** [comment]
FYI for future reference a merge commit can be used to _fix_ the discrepancy (conflict) while still keeping the attribution. Also if you dislike merge commits you could make a new commit but force the attribution using:

```console
git commit --author="Ed Dixon <ed@learningequality.com>"
```

Food for thought.

**Comment by sukima** [comment]
Now I'm going crazy here One could also apply the patch:

```console
git am <(curl -L https://github.com/Jermolene/TiddlyWiki5/commit/05b26d90d67b8b52528c61c8d79fb95b5df9c51a.patch)
# -- Fix the conflict (see git mergetool) --
git am --continue
```

**Pull request closed without merging**
