### PR TITLE
fix: add doc xls ppt type

### PR DESCRIPTION
**Pull request by linonetwo**
Add type for doc ppt xls, so they are recognized by `[is[binary]]`

But I also find some xls will be type `application/vnd.ms-excel`. I can't assign it because its extension is also `.xls`, and `registerFileType` don't allow multiple type have same extension.

### CODE REVIEW

**Comment by saqimtiaz** [comment]
You can register multiple types for the same extension, see https://github.com/Jermolene/TiddlyWiki5/blob/e26175e9c54f93ee4ac05aeecb32d9572e97cb23/boot/boot.js#L2417-L2418C68

**Comment by linonetwo** [comment]
@saqimtiaz I think that usage is wrong, the previous one will immediately be overwritten:

https://github.com/Jermolene/TiddlyWiki5/blob/e26175e9c54f93ee4ac05aeecb32d9572e97cb23/boot/boot.js#L548

**Comment by pmario** [comment]
no it will not be overwirtten. The register function creates arrays of types

**Comment by linonetwo** [comment]
It is a dict!

```
$tw.config.fileExtensionInfo[extension]
```

With typescript this will be crystal clear

```ts
fileExtensionInfo: Record<string, { type: string }>
```

**Comment by saqimtiaz** [comment]
Try this in the console in TiddlyWiki:

`$tw.config.contentTypeInfo`

You will see that multiple types can have the same extension because the  **type** is the key, not the extension.

**Comment by linonetwo** [comment]
I see, there are `fileExtensionInfo` and `contentTypeInfo`, I was only looking at `fileExtensionInfo`.

Anyway, I add it.

**Comment by Jermolene** [comment]
Thanks @linonetwo

**Pull request merged**
