### PR TITLE
add replace-text macros to core

### PR DESCRIPTION
**Pull request by BurningTreeC**

### CODE REVIEW

**Comment by BurningTreeC** [comment]
simple macros that allow replacing text in tiddlers and showing the diff

**Comment by Jermolene** [comment]
Hi @BurningTreeC could you kindly post a sample for people to try?

**Comment by BurningTreeC** [comment]
Here's a demo with a little user interface to play with: 

http://replace-text-testing.tiddlyspot.com/

**Comment by Jermolene** [comment]
Thanks @BurningTreeC it's cunning stuff and will be useful to many users, but I think for the core we need something more complete, as outlined in #3288.

**Comment by BurningTreeC** [comment]
Ok @Jermolene, closing this one

**Pull request closed without merging**
