### PR TITLE
implements list iterator variables

### PR DESCRIPTION
**Pull request by tobibeer**
provides `<<iterator>>`, `<<iterator-even>>` and `<<iterator-last>>` see #1328

### CODE REVIEW

**Comment by tobibeer** [comment]
Demo at: http://tbdemo.tiddlyspot.com/#Iterator

**Comment by Jermolene** [comment]
Ah sorry @tobibeer I didn't see this when I made my comment about making a pull request, apologies!

**Comment by Jermolene** [comment]
@tobibeer can you make another pull request with the associated documentation updates?

**Comment by tobibeer** [comment]
gladly

**Comment by Jermolene** [comment]
Hi @tobibeer I'm afraid I've realised that there is a serious problem with this change, and I think we're going to have to retract it. It's something that I should have figured out earlier on, and so I apologise.

You can see the problem if you modify the default view template (`$:/core/ui/ViewTemplate`) as follows:

```
\define frame-classes()
tc-tiddler-frame tc-tiddler-view-frame $(missingTiddlerClass)$ $(shadowTiddlerClass)$ $(systemTiddlerClass)$ $(tiddlerTagClasses)$
\end
<$set name="storyTiddler" value=<<currentTiddler>>><$set name="tiddlerInfoState" value=<<qualify "$:/state/popup/tiddler-info">>><$tiddler tiddler=<<currentTiddler>>><div class=<<frame-classes>>>

Story index: <<storyIndex>>

<$list filter="[all[shadows+tiddlers]tag[$:/tags/ViewTemplate]!has[draft.of]]" variable="listItem"><$transclude tiddler=<<listItem>>/></$list>
</div>
</$tiddler></$set></$set>
```

And also change the list filter in the middle of `$:/core/ui/PageTemplate/story` to:

```
<$list filter="[list[$:/StoryList]]" history="$:/HistoryList" template="$:/core/ui/ViewTemplate" editTemplate="$:/core/ui/EditTemplate" storyview={{$:/view}} emptyMessage={{$:/config/EmptyStoryMessage}} iterator="storyIndex"/>
```

Once you've made those two modifications each tiddler in the story river will show "Story index: 1", "Story index: 2", "Story index: 3" etc.

Now open a tiddler that isn't already open from the sidebar. The newly opened tiddler is shown with a blank story index. Then try closing a tiddler that does have a numeric story index; the rest of the tiddlers do not renumber themselves.

What's going on is that the code for assigning the iterator variables isn't being called when the output of the list widget is selectively updated. (Which is to say the list widget refresh logic that reuses existing child widgets when it can).

I don't think it's possible to fix this without breaking the ability to do selective updates. The only way to get the re-used child nodes to refresh themselves to the new value of the iterator variable is to remove and recreate the entire subtree, which undoes the benefit of selective updates.

**Comment by tobibeer** [comment]
Why not flag the entire list to redraw, when in-fact necessary?

**Comment by Jermolene** [comment]
@tobibeer I'm not keen on making the list widget any more complex. Most of that complexity is in the selective update mechanism and the navigation handling. Your proposal is essentially to be able to disable those mechanisms and add a small extension to handle the list iterators. Given how little there is to the list widget when one removes the selective update and navigation handling, I think there's a lot less net complexity to create a new simplified list-like widget that drops selective updates and navigation handling, but adds the iterator handling.

**Comment by tobibeer** [comment]
I fear the feature sets of either widget will possibly be (asked to be much) the same and then we will have a whole lot of duplicate, or worse, inconsistent code, e.g. "emptyMessage" or any drag and drop handling.

**Comment by Jermolene** [comment]
@tobibeer the bulk of the code of the existing list widget is concerned with selective updates or navigation, and so I don't think there would actually be a great deal more overlap than between any two widgets.

**Comment by tobibeer** [comment]
will consider...

1. a standalone "iterate" widget
2. the feature-set it possibly begs for
3. the required refresh logic
4. the format this would be published

**Comment by Jermolene** [comment]
@tobibeer great, I think it will be pretty useful.

**Pull request merged**
