### PR TITLE
added localisation for encryption dialog & de-DE translation

### PR DESCRIPTION
**Pull request by andreasabeck**
fixing issue https://github.com/Jermolene/TiddlyWiki5/issues/1585

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @andreasabeck thanks for this.

I think the problem, though, is that the decryption dialogue is presented before the store area is decrypted, and so we haven't had a chance to load the `$:/core` plugin, nor the translations. Does it work as expected in your tests?

**Comment by andreasabeck** [comment]
Hi @Jermolene, 

in boot.js line 500 I check for $tw.language being undefined, which should cause the Placeholder to be set constant to "Password". In my test that was working fine, the encryption dialogue was localised while the decryption dialogue is displayed in english because the translation is not availabe.

Cheers
Andreas

**Comment by Jermolene** [comment]
Ah, thanks @andreasabeck that makes sense. Are there any circumstances in which the translated decryption dialogue is displayed?

**Comment by andreasabeck** [comment]
Hi @Jermolene - the passwordPrompt.createPrompt is also used from startup/password.js to display the encryption dialog. In that case we can localise the placeholder for the password.

So for decryption it is not possible at all to localise, but the place where I made the distinction is also responsible for displaying the first "password" field (just before "repeat password") in the encryption dialog. Just to be sure I also checked that by replacing the string and it is the same in both dialogs.

**Comment by Jermolene** [comment]
Thanks @andreasabeck much appreciated.

**Pull request merged**
