### PR TITLE
allowing variable number of arguments for non-argument macros

### PR DESCRIPTION
**Pull request by Skeeve**
There are mainly just 4 new lines. All the other changes are just an indentation by one tab.

### CODE REVIEW

**Comment by tobibeer** [comment]
@Skeeve, can you give a quick example for how to implement this in a js macro?

**Comment by Skeeve** [comment]
It's long ago I propsed it, but from looking at the code, I thin it's used the same way it's used when you have named parameters plus some parameters more.

args.actualParameters is an array of all the parameters not named. Just access them by index.

Does this help?

**Comment by tobibeer** [comment]
> Does this help?

I'm afraid not. I think I perhaps misunderstood what this does. I thought that in a js macro I can access all parameters as anonymous arguments ...but it turns out, I cannot. Can I?

**Comment by Skeeve** [comment]
Okay… I checked again, but didn't verify.

When you have a javascript macro module with named parameters like now.js https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/macros/now.js
then

    <<now YYYY-0MM-0DD>>

will give you "YYYY-0MM-0DD" in the "format" variable.

Additionally (I think)

    <<now "YYYY-0MM-0DD" "some more" stuff>>

would give you, the "arguments" array containing the rest of the parameters.

But this only worked when you have at least one named parameter. This now also works for parameter-less macro functions like version.js.

How standard JavaScript is using it is described for example here: http://stackoverflow.com/questions/1959040/is-it-possible-to-send-a-variable-number-of-arguments-to-a-javascript-function

**Comment by tobibeer** [comment]
Ah, will test when back at my machine. I actually removed all declared parameters. Possibly that was the problem.

**Pull request merged**
