### PR TITLE
Tag picker rewritten using new v5.3.x syntax

### PR DESCRIPTION
**Pull request by pmario**
This PR closes  **[BUG] calling tag-picker macro with a tagFields=foo shows the tags field instead of foo #7461** 

@etardiff This PR replaces your: **Rewrite tag-picker macros as procedures #7883**

I did use your code as basis and did extend it with my code from:  **Fix and extend tag picker functions #7548**, since I need it to have a nice UI for tag-like fields. 

I did add a new Example tiddler, which was completely missing.

### CODE REVIEW

**Comment by pmario** [comment]
Slightly related to: **Work In Progress - Toc v5.3.x rewrite #7961**  since the new tag-picker can now be used to easily "populate" tag-like fields

**Comment by pmario** [comment]
Converted this PR into a draft. There seems to be a problem with the "focus selector" if used in combination with the `$:/core/ui/EditTemplate/tags` template.

Using keyboard handling to add tag-likes -> works
Using the mouse to click -> focus is completely lost. 

```
\procedure tagField() test

{{||$:/core/ui/EditTemplate/tags}}
```

image

**Comment by pmario** [comment]
@BurningTreeC ... Are you able to help with the keyboard focus handling mentioned at: https://github.com/Jermolene/TiddlyWiki5/pull/7978#issuecomment-1937825065

**Comment by BurningTreeC** [comment]
Hello @pmario ... I will have to take a look at what you are doing here. When I understand it, I'll happily help

**Comment by BurningTreeC** [comment]
Hello @pmario - could you please describe the problem more precisely?

**Comment by BurningTreeC** [comment]
Hi @pmario ... I found the problem.
In the procedure `get-tagpicker-focus-selector()` your using the reference to `$(thisTiddler)$` which somehow doesn't work.
First of all, I would like that `thisTiddler` gets CSSescaped first by the `escapecss[]` operator , so that it works correctly with all tiddler titles.
Then we need to find a way for the variable to be resolved within the procedure

**Comment by BurningTreeC** [comment]
@pmario ... if you make the `get-tagpicker-focus-selector()` a macro then it works. I was away from tiddlywiki quite some time and don't know anything about procedures and functions yet. So I don't know if `$(variable)$` gets resolved within a procedure but it seems it doesn't.
<hr>
Another thing: I've seen that you added an id so that the dropdown works for different tag pickers within a single tiddler.
We should somehow reuse that id and add it to the `tc-edit-add-tag` class. So that in the `get-tagpicker-focus-selector` we can identify the correct tag picker

**Comment by BurningTreeC** [comment]
Here's a working tag-picker with my small additions
[tag-picker.txt](https://github.com/Jermolene/TiddlyWiki5/files/14277958/tag-picker.txt)

**Comment by pmario** [comment]
Here's a working tag-picker with my small additions
[tag-picker.txt](https://github.com/Jermolene/TiddlyWiki5/files/14277958/tag-picker.txt)

Thx, I'll have a closer look soon.

---------

>First of all, I would like that thisTiddler gets CSSescaped first by the escapecss[] operator , so that it works correctly with all tiddler titles.

Assigning a title to `data-tiddler-something` will work with all unicode characters. So no CSS escapes needed.

**Comment by BurningTreeC** [comment]
> > Here's a working tag-picker with my small additions
> > [tag-picker.txt](https://github.com/Jermolene/TiddlyWiki5/files/14277958/tag-picker.txt)
> 
> Thx, I'll have a closer look soon.
> 
> > First of all, I would like that thisTiddler gets CSSescaped first by the escapecss[] operator , so that it works correctly with all tiddler titles.
> 
> Assigning a title to `data-tiddler-something` will work with all unicode characters. So no CSS escapes needed.

I made a different experience, but if you say so I'll have to take a closer look

**Comment by pmario** [comment]
With the help of your actions-debug and your new code I did find a solution without any CSS escapes. We only have to take care, that the `tag-picker-dropdown-id` is really unique and added to the right DOM element. 

So the `get-tagpicker-focus-selector` can be really simple. ... Some more experiments needed, but I think I do understand the mechanism now. 

Thanks for your input \o/

**Comment by pmario** [comment]
@Jermolene -- This one is ready for review now. 

All the tap-picker inputs should work with keyboard text inputs, keyboard down/up selection and mouse inputs now. 

If testing the "Examples" it's important to read the info texts, since example 3 is used to "populate" the field used for examples 4 and 5.

**Comment by Jermolene** [comment]
Hi @pmario I've merged #7883 so this will need some adjustments, many thanks.

**Comment by pmario** [comment]
I did update this PR. 

[Updated tag-picker docs and new "Examples" tiddler](https://tiddlywiki5-git-fork-pmario-tag-picker-new-syntax-jermolene.vercel.app/#tag-picker%20Macro:%5B%5Btag-picker%20Macro%5D%5D%20%5B%5Btag-picker%20Macro%20(Examples)%5D%5D)

**Comment by Jermolene** [comment]
Thanks @pmario

**Pull request merged**
