### PR TITLE
Make <<.tip in table less prominent 

### PR DESCRIPTION
**Pull request by pmario**
- Make <<.tip **in tables** less prominent
- Tiddler date is **not** modified
- Fix some minor typos 

---
<small>Submitted using https://saqimtiaz.github.io/tw5-docs-pr-maker/.</small>

### CODE REVIEW

**Comment by pmario** [comment]
Before: https://tiddlywiki.com/#ViewWidget

image

After: https://tiddlywiki5-git-fork-pmario-make-tip-in-table-1efd9f-jermolene.vercel.app/#ViewWidget

image

**Comment by pmario** [comment]
@Jermolene -- this is a docs-only PR

**Comment by Jermolene** [comment]
Hi @pmario I actually like having the word "Tip", but I would suggest that the CSS be changed to make it all caps and somewhat smaller and paler.

**Comment by pmario** [comment]
I did merge the wrong branch :/ So I'll close this one :/

@Jeremolene -- We should investigate a workflow to contribute to documentation, that is less error-prone

**Pull request closed without merging**
