### PR TITLE
Typo "module-type" instead of "plugin-type"?

### PR DESCRIPTION
**Pull request by cawoodm**
I'm guessing `module-type` should be `plugin-type`?

### CODE REVIEW

**Comment by tobibeer** [comment]
@cawoodm, good, please create another PR where you sign the [CLA](https://github.com/Jermolene/TiddlyWiki5/blob/master/licenses/cla-individual.md) so that this one can be merged

**Comment by Jermolene** [comment]
Hi @cawoodm 

`module-type` is correct; the passage is describing how tiddlers within plugins are processed. The individual tiddlers get a `module-type` field; the plugin as a whole gets a `plugin-type`.

> In the browser, any constituent tiddlers that are JavaScript modules (ie shadow tiddlers of content type `application/javascript` and possessing the field `module-type`) are executed during startup processing.

**Comment by cawoodm** [comment]
OK, a little confused and I think somehow we need the PluginMechanism tiddler to help folks like me get started writing Plugins. In TWC you could edit code directly but all the plugins I look at are encoded JSON. Perhaps a link to a tut or a HelloWorldPlugin built into tiddlywiki.com?

I'd also like to see a definition/distinction __in one place__ between plugin, widget, macro, module, parser...

**Comment by Jermolene** [comment]
Hi @cawoodm the documentation for developer oriented topics like building plugins lives at http://tiddlywiki.com/dev/; does that help?

**Comment by Jermolene** [comment]
> I'd also like to see a definition/distinction in one place between plugin, widget, macro, module, parser...

The special terms that are unique to TiddlyWiki are defined here:

http://tiddlywiki.com/#Concepts

**Comment by cawoodm** [comment]
Another one I just found: `"module-type": "library",`. I feel like when I started Harry Potter 4: too many characters in the scene! ;-)

**Comment by Jermolene** [comment]
Hi @cawoodm there is a complete listing of all the loaded module-types in control panel - just navigate to Info / Advanced / Loaded Modules.

**Pull request closed without merging**
