### PR TITLE
Upgrade to Jasmine 3

### PR DESCRIPTION
**Pull request by ento**
A more thorough version of #4223: upgrades the version of Jasmine bundled in the jasmine plugin to 3.4.0.

Jasmine's upgrade guides:

* To 2.x: https://jasmine.github.io/tutorials/upgrading_to_2
* To 3.x: https://github.com/jasmine/jasmine/blob/v3.0.0/release_notes/3.0.md
  * 3.x dropped support for Node.js 0.x: I assume it's fine since Travis tests are run only against the latest stable version of Node 

The test suite mostly worked as-is.

Some things I'd like to call out about the changes:
* jasmine-plugin.js: `evalInContext()` does something quite similar to `$tw.modules.execute()` and I'm not sure if there's a smarter way. I didn't see a way to use `$tw.modules.execute()` as-is because I needed to tweak the `sandbox` object.
* update-packages.sh: I'm not sure if it's fine to leave a shell script like this in this directory.

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @ento thanks, great work. I'm tagging it for merging after the imminent release of the v5.1.21 bugfix release.

**Comment by pmario** [comment]
@Jermolene ... imo wrong label :)

**Comment by Jermolene** [comment]
Hi @pmario the description for the label "post-v5.1.20" is "After the release of v5.1.20 (and any bug fix releases)", intended to accommodate the possibility of the v5.1.21 release I'm preparing now.

**Comment by pmario** [comment]
I did test this PR with Windows 10, node V 12.8.0 with _no problems_

Command:

```
node .\tiddlywiki.js .\editions\test\ --server  
and
node .\tiddlywiki.js .\editions\test\ --build index
``` 

All existing tests passed

**Comment by pmario** [comment]
bump @Jermolene

**Comment by Jermolene** [comment]
Hi @ento - it looks like you haven't signed the contributors license agreement (I may be mistake, I'm checking on my phone). Apologies for the bureaucracy, but please could you follow the instructions in contributing.md in the root of the repo, and send a separate PR to the tiddlywiki-com branch. Many thanks!

**Comment by ento** [comment]
@Jermolene Here's the PR #4222

**Pull request merged**
