### PR TITLE
DOCS Update: Documentation Macros.tid

### PR DESCRIPTION
**Pull request by 00SS**
Reformatting, additions etc. as detailed in Issue #3711

### CODE REVIEW

**Comment by 00SS** [comment]
I've been steadily working on these for a few months. Please see Issue #3711 for the background.

These 3 modified tiddlers can be seen & tested here: [https://00ss.github.io/documentation/tiddlywiki.html](https://00ss.github.io/documentation/tiddlywiki.html#Documentation%20Macros:%5B%5BDocumentation%20Macros%5D%5D%20%24%3A%2Feditions%2Ftw5.com%2Fdoc-macros%20%24%3A%2Feditions%2Ftw5.com%2Fdoc-styles)

I [kept track of most changes](https://00ss.github.io/help/Adding-a-table-of-contents-to-the-sidebar.html#Documentation%20Macros%20Request), but there were many and I have missed noting down a few. The changes that have a possibility of **breaking** something are in the **doc-macros** tiddler but the changes there can easily be seen when comparing the old and new versions.

One pleasant improvement is how icons/image buttons are displayed. Their SVG size and vertical alignment style has been adjusted to sit more naturally in their surrounding text.
`.doc-button svg { height: 1.3em; vertical-align: text-bottom; }`

To get an idea, compare these two versions of **Creating and editing tiddlers**: [Original](https://tiddlywiki.com/#Creating%20and%20editing%20tiddlers) vs [New Look](https://00ss.github.io/documentation/tiddlywiki.html#Creating%20and%20editing%20tiddlers%20%28New%20Look%29)

**Comment by 00SS** [comment]
@Jermolene 
It would be useful if this PR could be merged so that I can begin the next phase of Documentation for Beginners.
A preview of them can be seen here: 
 https://00ss.github.io/documentation/tiddlywiki.html

**Comment by Jermolene** [comment]
Hi @00SS thanks for this.

I notice that this PR targets the "master" branch, and just wondering if that's what we want. It would mean that all other dependent PRs will have to be merged to "master" rather than "tiddlywiki-com", which means that they won't be published until the next release. As long as you're only modifying files under `editions/tw5.com` perhaps we'd be better off targetting "tiddlywiki-com"?

**Comment by Jermolene** [comment]
Hi @00SS some of the new styles seem a bit low contrast:

Screenshot 2019-04-10 09 35 59

We should be trying to observe the [WCAG guidelines](https://www.w3.org/TR/WCAG/#contrast-minimum) on colour contrast, although there are certainly places where we break them.

**Comment by 00SS** [comment]
> some of the new styles seem a bit low contrast:

I thought about the contrast colour carefully before choosing this one.
This Documentation Macros tiddler has become quite large and intimidating.
If the maro examples are also black text, finding the right macro to use becomes even harder.
The macro examples are really a last resort - and basically for very new writers of Documentation who still haven't got the hang on how to use them. Once they have been used a few times, those are really not going to be looked at much again. But if they are not available, it makes a new contributor quite lost.

Thus I wanted them to be un-intrusive and almost background info.

> perhaps we'd be better off targetting "tiddlywiki-com"?

Thanks for spotting that! I will change them to the tiddlywiki-com branch.

Thank you also for making the time to get these going!

**Comment by Jermolene** [comment]
> Thus I wanted them to be un-intrusive and almost background info.

I sympathise! This is a dense tiddler with lots of information and it is hard to get it right. Nonetheless, I think we should increase the contrast a little.

**Comment by 00SS** [comment]
Hope I have correctly changed the base branch!
I darkened the code display from very light gray to #696969 - It looks better now!

The change can be seen in the preview: https://00ss.github.io/documentation/tiddlywiki.html

**Comment by 00SS** [comment]
@Jermolene 
I made the change suggested.
Changing the base branch did some strange things above.
Can this be safely merged? Or should I resubmit this?

**Comment by Jermolene** [comment]
Hi @00SS I noticed that you've closed quite a few PRs. My apologies for my slow progress in merging them -- you'll have noticed that I'm slow on everything, not just yours! I appreciate the frustration that results from this, and would like to reassure you that my slowness in merging is entirely my fault, and doesn't reflect on the high quality of your work. If you've the time, perhaps we can schedule a chat in the next few days to discuss things?

**Pull request closed without merging**
