### PR TITLE
New readable tabs macro

### PR DESCRIPTION
**Pull request by pmario**
This PR contains several commits, that create a step by step review, to exactly see what's going on: 

- https://github.com/Jermolene/TiddlyWiki5/commit/eb20d02717ae92b6bf795a0241a3b7a6315fe646 
  - adds the `\whitespace trim` pragma
  - activates the new tests, to make the test-run green

- https://github.com/Jermolene/TiddlyWiki5/commit/d8a5258a4013d9dd0948cdd5dea8f3dd45cadf43
  - adds indentation only
  - tests are green, so HTML doesn't change

- https://github.com/Jermolene/TiddlyWiki5/commit/046f43d080ea010745f98e8fee5b702bdb8f8c85
  - converts `$parameters$` to `<<__parameters__>>`
    - qualify and class definitions need to be adjusted to work with `<<__params__>>`
  - all the tests are green

- https://github.com/Jermolene/TiddlyWiki5/commit/1c81e372270e16f1cc055bc99ac3dd782c2b0673
  - split tabs-macro macro into different elements, to improve readability and "hackability"
    - tabs-button
    - tabs-tab
    - tabs-tab-list
    - tabs-tab-body
    - tabs ... main macro
  - all tests are green

- https://github.com/Jermolene/TiddlyWiki5/commit/659811aabb0c0c9988813ccb9c2b99125244cfab
  - adds the `code_body`
  - removes an experiment with the `default` parameter I accidentally committed.
  - all tests are green

I did plan 2 or 3 more PRs, where I do need to create issues first to explain, why I think they are important.

### CODE REVIEW

**Comment by pmario** [comment]
At the moment, there is no need to change the docs. It only changes the internal structure and the readability of the macro. The DOM / HTML output should be the same as it was. ... 

For the 2 new issues I did create there will / may be some changes also for the docs.

**Comment by pmario** [comment]
Bump

**Comment by Jermolene** [comment]
Hi @pmario I was thinking that we would leave this until after v5.2.2

**Comment by pmario** [comment]
I did test it with Edge 100 beta and Edge 101 dev .. The tabs-macro works for both versions. 

There is a bunch of new tests, that make sure, that the DOM output is the same as it was, except the whitespace is removed. 
The output doesn't contain invalid HTML code. .. What else can I do?

**Comment by Jermolene** [comment]
Indeed @pmario I don't see any obvious problems, it's just that the v5.2.2 release schedule won't allow for much meaningful testing in the field. Experience has taught me that changes can have unforeseen consequences that (by definition) we won't always be able to appreciate without trying it out.

**Comment by pmario** [comment]
Please merge, so it can be tested by other.

**Comment by Jermolene** [comment]
Thanks @pmario

**Comment by Jermolene** [comment]
I think you need to resolve a conflict here.

**Comment by pmario** [comment]
I have to do it again. .. I don't have any idea what happened. I just know that resolving with the github UI is crap. I can't see, if the resolved code is the same as I did submit.

**Pull request closed without merging**
