### PR TITLE
Introduce railroad plugin

### PR DESCRIPTION
**Pull request by aelocson**

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @aelocson

**Comment by tobibeer** [comment]
Perhaps overkill, but I think railroad diagrams would also be a great addition to document all the different regexps and where they are used at **tiddlywiki/dev**

**Comment by aelocson** [comment]
I agree entirely.

I'm also intending to use them to improve other parts of the main documentation site, e.g. the syntax of macro calls and text references. The current TextReference tiddler is particularly confusing: it's easy to misunderstand it as saying that `<` and `>` are part of the syntax of a text reference.

Do you think it would be better if the return path below a repeated component had an upward-pointing arrow near the end of it, a little like this?

railroad-arrow

**Comment by tobibeer** [comment]
I sure do, I was just wondering yesterday if that existed.

**Comment by aelocson** [comment]
It doesn't *yet* exist – I'll have to modify the underlying library to add an extra piece to the SVG.

**Pull request merged**
