### PR TITLE
Update Variables in WikiText.tid

### PR DESCRIPTION
**Pull request by r1chard5mith**
swapped `$(name$)` for `$(name)$` in line 12

### CODE REVIEW

**Comment by pmario** [comment]
Hi Richard, Welcome! Good catch! 
You'll need to sign the CLA. Have a look at: https://github.com/Jermolene/TiddlyWiki5/blob/master/contributing.md

**Comment by r1chard5mith** [comment]
Hi Mario, thanks. I didn't realise moving one character would make me a contributor, or I would have done it sooner :) I hope I signed the CLA correctly.

**Comment by pmario** [comment]
Actively using this and other forums, makes you a contributor :)

CLA looks good to me.

**Comment by Jermolene** [comment]
Good catch @r1chard5mith! Apologies for the delay in merging

**Pull request merged**
