### PR TITLE
Add GitFixUm community example

### PR DESCRIPTION
**Pull request by sukima**
Thought this was a unique enough example to be part of the TW5.com site.

### CODE REVIEW

**Comment by pmario** [comment]
Hi,
Nice info but do you really use those commands, described there? 

Most of them will lead to totally broken local branches or repos, if used by new users. Especially if merge conflicts are involved and they don't use 3rd party 3-way merge tools.

**Comment by sukima** [comment]
@pmario No I've never used it. I only saw the [original document](http://sukima.github.io/GitFixUm/#OriginalSource) which was a huge single ugly HTML page with tons of anchor tags and really bad JavaScript to manage the non-linear navigation. I immediately thought this 1980's Geocities relic needs a face lift. So I ported it to TiddlyWiki for a big win and wanted to share. The original author seems oblivious to pull requests (responses taking on average 10 months) so I decided to continue hosting it on GitHub as a fork.

I did not verify the validity of the information within only presentation of said information.

I'm considered a Git Guru at my place of work and I've never used the information in that. In fact, it is unlikely I would find myself in a situation where I would need to use such a document.

Content aside, it is an example of TiddlyWiki in the wild showing a use for documentation in a non-linaer fashion. That is if TiddlyWiki.com wants such things as examples. I'm working on other non-linear documentations so this PR is to the discretion of yourself. :wink: Cheers.

**Comment by pmario** [comment]
Good. As I wrote, the content is nice. I'm in favour of merging it. 

I was just wondering, why one would need those commands in the first place. ... So may be there should be some content of "Best Practice" how to work with TW and git / github. So one should never come to a point, where you need to fix your repo in such "low level" ways.

**Comment by sukima** [comment]
Agreed! The Octocat loves Pull Requests :grin:

**Comment by pmario** [comment]
:)

**Comment by Jermolene** [comment]
Hi @sukima it's a terrific thing, congratulations, and very happy to feature it on tw.com.

**Pull request merged**
