### PR TITLE
fix: make tag-picker "add-tag" button more solid

### PR DESCRIPTION
**Pull request by BurningTreeC**

### CODE REVIEW

**Comment by BurningTreeC** [comment]
This PR makes the add-tag-button behave like the add-tag keyboard shortcut

**Comment by BurningTreeC** [comment]
ping for 5.1.21 ?

**Comment by Jermolene** [comment]
Hi @BurningTreeC I'm trying to keep v5.1.21 as a bug fix release, and want to avoid any other changes that aren't trivial to verify.

**Comment by BurningTreeC** [comment]
ping @Jermolene

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Pull request merged**
