### PR TITLE
Add `m` flag for multiline to search-replace filter operator

### PR DESCRIPTION
**Pull request by BurningTreeC**

### CODE REVIEW

**Comment by saqimtiaz** [comment]
@BurningTreeC could you please add some tests?

**Comment by BurningTreeC** [comment]
If I knew how to do that @saqimtiaz I would do so

**Comment by saqimtiaz** [comment]
Looks like you found the tests.

You can run the tests locally with `node tiddlywiki editions/test`

Recommend adding two tests, one with the text being searched being a single line and one with multiple lines.

**Comment by BurningTreeC** [comment]
> Looks like you found the tests.
> 
> You can run the tests locally with `node tiddlywiki editions/test`
> 
> Recommend adding two tests, one with the text being searched being a single line and one with multiple lines.

Yes I found them but I have a hard time getting the right results. But I'll make it :+1:

**Pull request closed without merging**
