### PR TITLE
fr-FR next batch of translation updates

### PR DESCRIPTION
**Pull request by tw-FRed**
This PR also corrects 2 problems with my previous PRs:
* GettingStarted.tid was not committed in the right place
* doc-macros tiddler generated file name was wrong (latest Firefox on Linux)

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @tw-FRed - fantastic, much appreciated. Obviously I can't properly double check things for you, but hopefully  other French speakers like @xcazin and @silvyn are following your work.

**Comment by Jermolene** [comment]
Hi @tw-FRed I've reverted this PR in 4d3ebf4bf02d9eb369254d463548020601a692d3 because I noticed that it introduced a bunch of `.tid` files into the root of the repository. Perhaps they were included in error?

**Comment by tw-FRed** [comment]
> Hi @tw-FRed I've reverted this PR in [4d3ebf4](https://github.com/Jermolene/TiddlyWiki5/commit/4d3ebf4bf02d9eb369254d463548020601a692d3) because I noticed that it introduced a bunch of `.tid` files into the root of the repository. Perhaps they were included in error?

Hi @Jermolene 
The culprit is commit f8ce7e6, I'm going to make a new PR with things sorted out (hopefully). Really sorry for this.

**Comment by Jermolene** [comment]
> Really sorry for this.

No problem; I make mistakes all the time, and one of the wonderful things about open source development is that it's a pretty good way to catch one another's errors. Moments like this just prove that the system works

**Pull request merged**
