### PR TITLE
Make Escape in keyboard-driven-inputs behave like in AdvancedSearch/Filter

### PR DESCRIPTION
**Pull request by BurningTreeC**
This PR updates all keyboard-driven-inputs to have a more sophisticated functionality when hitting <kbd>Escape</kbd>

~~Note the new textoperation "focus-editor" which focuses the Editor when hitting <kbd>Escape</kbd> in an empty link-dropdown~~

### CODE REVIEW

**Comment by BurningTreeC** [comment]
I believe what I'm trying to achieve with the focus-editor textoperation is also possible with the wrap-selection textoperation

**Comment by saqimtiaz** [comment]
> I believe what I'm trying to achieve with the focus-editor textoperation is also possible with the wrap-selection textoperation

@BurningTreeC perhaps mark this as a draft while you look into that. Would be good to avoid adding a text-operation if it isn't strictly needed.

**Comment by BurningTreeC** [comment]
@saqimtiaz thanks, I just cannot mark it as draft atm because I'm away from my desk

**Comment by BurningTreeC** [comment]
@Jermolene - now this is ready to get merged

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Pull request merged**
