### PR TITLE
Add Button to remove tags from tiddlers $:/config/NewTiddler/Tags and $:/config/NewJournal/Tags

### PR DESCRIPTION
**Pull request by BurningTreeC**
This PR adds a Button in ControlPanel/Basics that only shows if the tiddlers `$:/config/NewTiddler/Tags` / `$:/config/NewJournal/Tags` have one or more tags. The button then adds the tags to the text field and deletes the tags field.

The text for the button is `Sanitize Tags` ... I couldn't come up with a better caption

### CODE REVIEW

**Comment by Jermolene** [comment]
> This PR adds a Button in ControlPanel/Basics that only shows if the tiddlers `$:/config/NewTiddler/Tags` / `$:/config/NewJournal/Tags` have one or more tags. The button then adds the tags to the text field and deletes the tags field.

Good idea.

> The text for the button is `Sanitize Tags` ... I couldn't come up with a better caption

Perhaps "Update to current format"?

**Comment by BurningTreeC** [comment]
I've changed it to "Update to current format" @Jermolene 

The button tooltip is "Remove the tags from the tiddler and add them to the text field" ... maybe there's a better wording?

**Comment by Jermolene** [comment]
> I've changed it to "Update to current format" @Jermolene

Thanks @BurningTreeC 

> The button tooltip is "Remove the tags from the tiddler and add them to the text field" ... maybe there's a better wording?

Perhaps "Update the tags configuration to the latest format"?

**Comment by BurningTreeC** [comment]
>Perhaps "Update the tags configuration to the latest format"?

changed @Jermolene

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Pull request merged**
