### PR TITLE
Make latex-parser.js render $$$ as display mode math

### PR DESCRIPTION
**Pull request by spelufo**
As discussed in #2139.

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @spelufo

**Comment by spelufo** [comment]
Thank you!

**Comment by Jermolene** [comment]
Actually @spelufo do you think it's maybe worth updating one of the examples to show display mode?

https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/katexdemo/tiddlers/HelloThere.tid

**Comment by spelufo** [comment]
Sure. How do people normally work with the wikis under editions? Can the node cli be used to generate a single file wiki? When I do `tiddlywiki --init katexdemo` and then try running the wiki with `tiddlywiki --server` I get the following
```
Warning: Plugins required for client-server operation ("tiddlywiki/filesystem" and "tiddlywiki/tiddlyweb") are missing from tiddlywiki.info file
```

Should I add those plugins to the katexdemo edition, or am I using the cli wrong?

**Comment by Jermolene** [comment]
Hi @spelufo it's a bit inconvenient, but for the moment you'll need to edit your tiddlywiki.info to add the two plugins that are needed for client server operation.

You can generate a single file wiki with the rendertiddler command:

http://tiddlywiki.com/#How%20to%20build%20a%20TiddlyWiki5%20from%20individual%20tiddlers

**Comment by Jermolene** [comment]
@spelufo I've belatedly realised that the `$$$` syntax clashes with the existing syntax for a typed block:

http://tiddlywiki.com/#Typed%20Blocks%20in%20WikiText

There's no obvious way to distinguish the two usages, so I think we'll have to retract this change. Annoying, as I imagine that display mode formulae are quite common.

There is an alternative, which is to use double `$$` for both display and inline modes, but require a newline before and after the opening `$$` and before and after the closing `$$`. For example:

```
Inline: $$\bold x + 3$$

Block:

$$
\bold x + 3
$$
```

A similar scheme is used to distinguish block and inline mode HTML elements.

**Pull request merged**
