### PR TITLE
Fix refreshing of transcluded functions

### PR DESCRIPTION
**Pull request by Jermolene**
This is currently just a failing test for #7696

### CODE REVIEW

**Comment by rmunn** [comment]
There's a comment in the transclude widget that its refresh "Doesn't need to consider transcluded variables because a parent variable can't change once a widget has been created". But that's not quite true of functions: their *text* can't change once the widget has been created, but their *result* can. So I think the refresh method of transclude widgets needs to check srcVariable.isFunctionDefinition, and if it is, call getVariableInfo again to get the new results. Then compare the old results to the new results and, if they are different, the widget needs to refresh.

BTW, a quick note about comparing the old results to the new results. Functions, like any other filter, could potentially return hundreds, or even thousands, of results. The point of comparing the old results to the new results is to skip a rerender if the results are the same, but that optimisation might fail if the cost of comparing the results is more than the cost of rerendering. So if the length of the results list is large, say more than a hundred items or so, it might be more efficient to just skip the comparison and say "yes, rerender". Performance testing would be needed to see where the inflection point is. But certainly if the list of results is fewer than about twenty items or so, it'll be worth it to compare the result lists and skip a rerender if the function result didn't change.

So I suspect that the `!this.transcludeVariable` check in the refresh() method needs to be changed, with a `functionNeedsRefresh()` method added:

https://github.com/Jermolene/TiddlyWiki5/blob/fa9bfa07a095548eb2f8339b0b1b816d2e6794ef/core/modules/widgets/transclude.js#L436-L444

**Comment by rmunn** [comment]
@Jermolene I opened https://github.com/Jermolene/TiddlyWiki5/pull/7755 to implement the `functionNeedsRefresh()` solution I proposed in my earlier comment. Note that PR #7755 merges into **this** PR's branch, i.e. if you merge #7755 it will add that commit to **this** PR, which can then be merged into master once you verify that the bug is indeed fixed. (I did it that way because I couldn't push a commit to your `fix-refreshing-transcluding-functions` branch directly as I don't have write access to your repo, so that was the simplest way I could find to add a commit to your PR branch).

My commit does, indeed, fix the bug, as verified by the test you added. Hopefully you can just merge it into this PR and save yourself some debugging work.

**Comment by Jermolene** [comment]
Thanks @rmunn, #7755 is a good fix, much appreciated.

**Comment by Jermolene** [comment]
Thanks @rmunn

**Pull request merged**
