### PR TITLE
Fix invalid header in upload plugin

### PR DESCRIPTION
**Pull request by webninjasi**
I've writing a simple server in golang for tiddlywiki and it doesn't work without this fix.

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @webninjasi thanks, it looks like that was a typo.

Before I merge, please would you mind creating a new pull request with your signature of the CLA, as described in contributing.md in the root of this repo. Many thanks!

**Comment by webninjasi** [comment]
Hi @Jermolene , I added it now. Thanks

**Comment by Jermolene** [comment]
Thanks @webninjasi, and welcome to the project. Are you in a position to publish your server code?

**Comment by webninjasi** [comment]
Yes. It is a fairly simple personal server, I'll publish it when I've got some time.

**Pull request merged**
