### PR TITLE
New Checklist and Modified Checkbox Widgets (with docs)

### PR DESCRIPTION
**Pull request by matabele**
A new ChecklistWidget which extends the operation of the CheckboxWidget to toggling an item in any field or index.

A modified CheckboxWidget which extends its operation to handle the toggling of a tag or string in a data index.

Both widgets will write an index only if the target type has been set to ‘Data-Dictionary’. This offers a measure of protection against an unintended overwrite of the ‘text’ field of the target.

### CODE REVIEW

**Comment by matabele** [comment]
A demo wiki with examples may be found [here.] (http://checkbox-list.tiddlyspot.com/)

**Comment by tobibeer** [comment]
Please excuse my being picky: Any particular reason to merge the two in one?

**Comment by matabele** [comment]
@tobibeer 
In the process of fixing my github, I had to delete everything off my github account and off my laptop. When I re-submitted to the new branches, I put the two together -- no particular reason.

**Comment by tobibeer** [comment]
ok, I see ...we'll see how it goes :-)

**Pull request closed without merging**
