### PR TITLE
Custom copy clipboard notifications

### LINKED ISSUE #8208: [IDEA] Meaningful Notifications for Permalink and Permaview Messages
**Is your feature request related to a problem? Please describe.**
When you click on Permalink or Permaview, a notification appeared on the left top of screen saying `Copied to clipboard`. This confusing specially when these messages are used with custom buttons (like Utility plugin from kookma)

**Describe the solution you'd like**
Use a better meaningful notifications like:
Permalink copied to clipboard
Permaview copied to clipboard

**Additional context**
Customization would be an extra benefit. So, user can sand their custom notification.

### PR DESCRIPTION
**Pull request by Jermolene**
Fixes #8208 by allowing custom notification messages to be provided for the following messages:

* tm-copy-to-clipboard
* tm-permalink
* tm-permaview

Two points to watch:

* The notification mechanism requires a tiddler title to display. It is not possible to provide a snippet of wikitext
* Separate messages are used for the operation succeeding and failing

### CODE REVIEW

**Comment by pmario** [comment]
I do get a RSOD with both FF lastest and Edge latest on Windows 11

- At page startup, there is a notification "Failed Copy to Clipboard"
- Then Tiddler-Toolbar -> More -> Permalink creates a RSOD - see screenshot.

image

Console says: 

image

Not sure if that helps, but "Pause on exception" stops here.

image

**Comment by Jermolene** [comment]
Thanks @pmario fix coming up

**Comment by kookma** [comment]
> Thanks @pmario fix coming up

I still get the RSOD on https://tiddlywiki.com/prerelease/#WidgetMessage%3A%20tm-copy-to-clipboard (Today: 2024.05.30)

**Comment by Jermolene** [comment]
Thank you @kookma much appreciated, fixed in 7a50b2b554d21fde0a4da03e051c1a0521e71426

**Pull request merged**
