### PR TITLE
Cycle operator improvements plus docs

### PR DESCRIPTION
**Pull request by saqimtiaz**
Added a `step size` parameter to the `cycle` operator as a second operand, in response to user requests in the discussion at #5021

Removed the suffix `reverse` for cycle as this can now be accomplished with a step size of `-1`

Added docs for `cycle[]` and updated docs for `toggle[]`

### CODE REVIEW

**Comment by saqimtiaz** [comment]
@Jermolene bumping this. Please merge so I can invite feedback and potential improvement to docs.

**Comment by kookma** [comment]
I like to give a try and see how step size works!

**Comment by Jermolene** [comment]
Thanks @saqimtiaz

**Comment by saqimtiaz** [comment]
@Jermolene thank you.

**Comment by kookma** [comment]
Thank you @saqimtiaz 
I will go through the docs and give a try to see how `cycle` with step size works! By the I notices there several typos in doc.

See https://tiddlywiki.com/prerelease/#cycle%20Operator

```
[toggle[<titles>],[step-size]]
```

The syntax is for `toggle` not  `cycle` the description is also seems is written for `toggle`

**Comment by saqimtiaz** [comment]
@kookma the line you pasted is indeed a typo and will be fixed.

The description is indeed for `cycle[]` but uses the word toggle. I welcome alternative suggestions for how to describe it.

**Pull request merged**
