### PR TITLE
enables quotes in triple quotes as well as triple single quotes for attributes and params

### LINKED ISSUE #1540: Triple single quotes around attributes and parameters
It's currently awkward to pass a string that contains `"""` as an attribute value.

Macro parameters support `[[`…`]]` as delimiters, so there's a solution available thee.

But is there a reason why `'''`…`'''` isn't allowed?

```
<<format '''Here is some text about TiddlyWiki's `"""` syntax.'''>>

<$codeblock code='''<$codeblock code="""an example"""/>'''/>
```

### PR DESCRIPTION
**Pull request by tobibeer**
fixes #1540 

allows to use a title like `foo "bar baz"`

allows to define an attribute using triple single quotes, e.g.

* `<$foo bar='''baz mumble'''/>` => where **bar**=`baz mumble`
* `<$foo bar='''baz 'mumble''''/>` => where **bar**=`baz 'mumble'`
* `<$foo bar="""baz "mumble frotz gronk""""/>`  => where **bar**=`baz "mumble frotz gronk"`

fixes issue reported by wimm:
https://groups.google.com/d/msg/tiddlywiki/sKv57A9-eCk/qjYuiMY9AQAJ

**Note**: To understand how the modified regular expressions work, simply copy them and paste them at http://regexper.com. Then it's much simpler than you might think.

The solution came about with some [help from Pranav C Balan on StackOverflow](http://stackoverflow.com/questions/41845715/capture-with-single-quotes-in-triple-quoted-string).
### Demo

http://2736.tiddlyspot.com

### CODE REVIEW

**Comment by tobibeer** [comment]
**ping**

**Comment by Jermolene** [comment]
Hi @tobibeer 

My apologies for the delay. Since this PR affects an area that has modest test coverage, please could you include some tests?

https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/test/tiddlers/tests/test-html-parser.js
https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/test/tiddlers/tests/test-wikitext-parser.js

**Comment by tobibeer** [comment]
@Jermolene, gladly. Didn't check for existing tests here

**Comment by tobibeer** [comment]
@Jermolene: Tests added. 👍

**Comment by Jermolene** [comment]
Hi @pmario it's a shame the attribute parser didn't use @tobibeer's approach from the beginning. I'm not in favour of adding this for triple single quotes because we'll end up with two subtly different behaviours for attribute parsing.

**Pull request closed without merging**
