### PR TITLE
[wip] porting the Nord palette

### PR DESCRIPTION
**Pull request by BurningTreeC**
https://github.com/arcticicestudio/nord

this palette is very popular, available for highlight.js, codemirror, all kinds of desktop/terminal applications ...
would be great to have it in tiddlywiki, too

this is a draft PR, certain things needs to be improved, but looks very good in tiddlywiki

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @BurningTreeC can we have a screenshot?

**Comment by BurningTreeC** [comment]
bildschirmfoto von 2019-03-03 19-39-34

**Comment by BurningTreeC** [comment]
in the screenshot codemirror and highlight.js use the same "nord" theme

**Comment by Jermolene** [comment]
Looks great!

**Comment by BurningTreeC** [comment]
Thanks! I like it a lot, it's very popular ... I want to adapt Monokai, too and another light palette from the popular ones ... don't want to invent something new

**Comment by Jermolene** [comment]
Great -- I'm all in favour of more core palettes. Perhaps you might pick up @jdjdjdjdjdjd's palettes too? Somebody needs to make a PR of them, and they might as well be all rolled together?

**Comment by BurningTreeC** [comment]
> Somebody needs to make a PR of them, and they might as well be all rolled together?

Yeah, if he's ok with it I'll add them

**Comment by Jermolene** [comment]
Thanks @BurningTreeC perhaps make a post on the GG thread about them?

**Comment by Jermolene** [comment]
btw I'm also interested to see whether I get a notification when you flip this PR from draft status...

**Comment by BurningTreeC** [comment]
now I cannot switch back to draft but the [wip] should be sufficient

**Comment by Jermolene** [comment]
I didn't get a notification; that's a shame, means that people probably still need to ping me when a PR is ready.

**Comment by BurningTreeC** [comment]
@Jermolene, it's still work in progress, so you'll get another PR finishing this the coming days, ok?

**Comment by Jermolene** [comment]
Ah, OK, no problem.

**Pull request merged**
