### PR TITLE
Replace spaces between horizontal tabs with margin

### PR DESCRIPTION
**Pull request by nameanyone**

### CODE REVIEW

**Comment by nameanyone** [comment]
Before:
screenshot_2015-12-29_00-17-37_before

After:
screenshot_2015-12-29_00-16-51_after

**Comment by nameanyone** [comment]
Spaces also appear between Page Controls buttons. Removing those will require editing each button tiddler as well as the "aggregator" tiddler ($:/core/ui/PageTemplate/pagecontrols I think).

**Comment by pmario** [comment]
Is there a reason, why you want to change this?

The TW layout wikitext is very complicated to read. So we should do everything, to make it easier to read. Your change imo makes it harder to read. ... BUT

I can see the difference and I like consistency. So using margins for spacing is preferable over using spaces. ... Are you sure, that there are no other unwanted side effects?

**Comment by nameanyone** [comment]
Actually, I'm always struggling with this issue. Trying to make macros, templates and such easier to read by adding newlines and indents introduces space character in-between controls. That throws off attempts to align everything consistently using css. Spaces and newlines inside widget <$...> tags is ok, so I've been doing that instead.

**Comment by pmario** [comment]
I see. We'll see, what @Jermolene  says :)

**Comment by tobibeer** [comment]
White-space that has an impact on layout has no place in core templates, imho.

If you want readability, the one way to do it would be...

```
<$some-widget attr="value" a="val"
/><$another attribue="value"
>foo</$another>
```

Yes, this may look ugly, but it's simply a design constraint imposed by TiddlyWiki... which contradicts standard html that it suggests it supports.

We may like it or not, but white-space breaks things, ever so slightly.

**Comment by Jermolene** [comment]
Thanks @nameanyone

**Comment by nameanyone** [comment]
> We may like it or not, but white-space interpreted as text breaks things, ever so slightly.

Can we change that, or will that break more than it will fix?
Say, if there is nothing else but whitespace between tags (html or widgets), ignore it.

**Comment by pmario** [comment]
>Can we change that, or will that break more than it will fix?
Say, if there is nothing but whitespace between tags (html or widgets), ignore it.

Since TW uses wikitext to create the TW layout, it will break more, than it would fix. ... There are some discussions in the closed issue section already.

**Comment by tobibeer** [comment]
@nameanyone, @pmario, @Jermolene ...one thing to consider and keep in mind is also that any superfluous text actually adds (element) widgets of type text.

**Comment by nameanyone** [comment]
> Since TW uses wikitext to create the TW layout, it will break more, than it would fix. ... There are some discussions in the closed issue section already.

Are you referring to #912? That's unfortunate. Still, we could use explicit paragraph tags when specifically required...

**Pull request merged**
