### PR TITLE
Fix for tag ordering issue #6382

### PR DESCRIPTION
**Pull request by Jermolene**
A failing test for fixing #6382

[UPDATE 4th Jan 2022](https://github.com/Jermolene/TiddlyWiki5/pull/6383#issuecomment-1004640078) – Added a naive fix for the failing test, which breaks 121 other tests

[UPDATE 8th Jan 2022] The fix is now pretty reasonable. It ensures that tiddler ordering behaviour always matches that of a freshly loaded wiki.

### CODE REVIEW

**Comment by Jermolene** [comment]
The underlying issue is that the wiki methods that iterate over tiddlers do so in order of insertion into the store. The last commit 51175616d37275c402a7a6f14a5e16d925f4a794 fixes the failing tests introduced in 32f79d16c680f1cf8c8a38b6bd2305bb2c961ba5, but it also breaks approximately 121 other tests. Examining a sampling shows that the tests currently have a dependency on the insertion order.

The fix in 51175616d37275c402a7a6f14a5e16d925f4a794 is naive – presumably it would be more efficient to maintain a sorted array of titles in addition to the store object itself – but it is easy to reason about, and gives us a sound basis for fixing the 121 affected tests.

I'd welcome other thoughts on this – @saqimtiaz @joshuafontany @clutterstack @flibbles

**Comment by Jermolene** [comment]
Oops the fix needs more work – we're still pushing new tiddlers to the top of the previously sorted titles arrays.

**Comment by Jermolene** [comment]
I've updated the fix to maintain the sorted order of the array. Now there are 122 other tests failing.

**Comment by flibbles** [comment]
Wait, tag ordering isn't the same as tiddler store ordering.

Tags order themselves based on the tag's "list" field, and the tiddlers' declaration of "list-after" and "list-before". Outside of those directives, I always thought that the tag ordering was undefined. Sorting the underlying tiddler store would have much more of an effect (not to mention introduce performance overhead considering how often wiki.getTiddlerTitles is called. Wouldn't it be better to...

1. Just accept that tag ordering is undefined outside of "list", "list-after", and "list-before"?
2. Or have the tag indexer keep its internal lists sorted whenever it's updated?

**Comment by flibbles** [comment]
I would think option 1 would be better. If someone actually cared about tag ordering, they'd use those directives, or they'd just add [sort[]] to their filters.

**Comment by flibbles** [comment]
> In terms of performance, there's actually no impact on wiki.getTiddlerTitles because we only do the sorting once, and thereafter the burden falls on adding new tiddlers which require the binary search to find the correct insertion point. Tiddler creation is relatively rare (it can't affect the refresh performance, for instance).

Oh, it will? It looked like in https://github.com/Jermolene/TiddlyWiki5/commit/51175616d37275c402a7a6f14a5e16d925f4a794 that it was sorting Object.keys()'s return results every time. If that was just a naive approach, and we just sort whenever we add new tiddlers, then I think this may actually be preferable. I think Object.keys() allocates a new array every time, whereas if we kept a sorted array around, we could just return that, and it'll be more time and memory efficient.

**Comment by flibbles** [comment]
Oh, I see what's happening. I didn't _see more context_. We're populating tiddlerTitles on request and caching it, and then purging it after any tiddler changes. I guess that works too.

Pity. I've written all my plugins under the assumption that [all[]] and [tag[]] returned an undefined order. Now they'll all be sorting unnecessarily.

**Comment by Jermolene** [comment]
Hi @flibbles 

> This may cause plugin tests for many developers to break as well (myself included).

Indeed, it smashes a wrecking ball through the core tests too. But I find it hard to defend the current behaviour because it is so baffling for end users.

**Comment by clutterstack** [comment]
> I've updated the fix to maintain the sorted order of the array. Now there are 122 other tests failing.

Github doesn't have enough emojis.

I have some fatigue in the way of my powers of comprehension at the moment, but if I'm understanding correctly:

* there's a mechanism that sorts tiddlers alphabetically in tag-pill lists, except for newly-created ones, which show up in order of creation until reload (disregarding `list-*`)
* this is actually only one example of how the order of filter results must actually be changing on reload?
* alphabetical order is preferred
* this can be enforced on tiddler creation by sorting the tiddlers in the store or keeping a sorted array of tiddler titles
* should not be a performance hit to do the latter
* but currently 122 tests depend on tiddlers being in the store in their order of insertion (does this indicate widespread dependency on this order in core, or is it limited to tests?)
* ? Any changes to plugins or unit tests that break would likely be limited to adding a sort() to some filters?

How it would affect me if you change this

* hahahaha I have no unit tests
* possibly some plugins I have written will break in some way I didn't know I was depending on that order
* that's fine. Only I use them, and they're always in some state of brokenness.

After all that: I don't have strong feelings on the approach. :)

It's rather pedal-to-the-metal at my new job or I would feel more comfortable committing to help adapt tests (or whatever they're indicating might need fixing in core, though my JS is rudimentary) if you wanted to press on.

**Comment by Jermolene** [comment]
Thanks @clutterstack 

> I have some fatigue in the way of my powers of comprehension at the moment, but if I'm understanding correctly:

That's right.

> * but currently 122 tests depend on tiddlers being in the store in their order of insertion (does this indicate widespread dependency on this order in core, or is it limited to tests?)

It's just the tests. They create tiddlers in more or less random order, and then run filters to test the results. Very often the ordering reflects the default insertion order.

> * ? Any changes to plugins or unit tests that break would likely be limited to adding a sort() to some filters?

Yes, that will work for a lot of the tests. For the tests that are actually sensitive to ordering one would have to change the expected result that is being tested against.

> * possibly some plugins I have written will break in some way I didn't know I was depending on that order

If so, your users will likely already be seeing different results in a freshly loaded wiki vs. one in which they have dynamically created tiddlers.

> It's rather pedal-to-the-metal at my new job or I would feel more comfortable committing to help adapt tests (or whatever they're indicating might need fixing in core, though my JS is rudimentary) if you wanted to press on.

Thank you! One thing that we're going to need help with is explaining the change in a way that will make sense to end users.

**Comment by Jermolene** [comment]
I've just pushed fixes for the failing tests.

In most cases, the underlying insertion order was showing through in the expected test results. Some of the cases are subtle – for example, the `each` and `eachday` operator are dependent on the store ordering.

I'd welcome another set of eyes on these.

**Comment by Jermolene** [comment]
I've found another unexpected consequence of these changes: stylesheets are now sorted differently

<details>
<summary>Screenshots of the differences</summary>

The current prerelease:

Screenshot 2022-01-08 at 09 39 13

This branch:

Screenshot 2022-01-08 at 09 38 56

</detail>

A couple of thoughts while I give this more consideration:

* Changing stylesheet ordering is not acceptable, and will need to be fixed
* This may invalidate some of the changes to the expected test results in ee03ee57f59aa3a21a518c0190acbdd060497a49

**Comment by saqimtiaz** [comment]
It suggest checking whether this is also impacts ordering of templates/cascades.

**Comment by flibbles** [comment]
I haven't checked, but it's my understanding that stylesheet ordering was originally determined by plugin priority, THEN alphabetical order. It wouldn't be too hard to change the core to sort by plugin priority. It might make sense to do that too.

Otherwise there's the pre-existing problem where someone makes a stylesheet tiddler and gets the results they want, but then they reload, and because their tiddler now sorts before other plugins, the css applies differently.

**Comment by Jermolene** [comment]
I've improved the fix to avoid the problem of the stylesheets being reordered. 

The order of tiddlers in the HTML file is sorted using localeCompare(), and that determines the insertion order in previous versions. So if we want to be compatible with older versions we have to use localeCompare() to order tiddlers, not a plain sort().

I've also removed the sorting of the shadow tiddlers; we should instead use the ordering determined by the plugin unpacking process.

We're now at 92 failing tests, which will need careful review.

**Comment by Jermolene** [comment]
Hi @flibbles 

> I haven't checked, but it's my understanding that stylesheet ordering was originally determined by plugin priority, THEN alphabetical order. It wouldn't be too hard to change the core to sort by plugin priority. It might make sense to do that too.

That's correct, and that behaviour is now retained in this PR.

> Otherwise there's the pre-existing problem where someone makes a stylesheet tiddler and gets the results they want, but then they reload, and because their tiddler now sorts before other plugins, the css applies differently.

That problem should now be fixed in this PR.

**Pull request merged**
