### PR TITLE
fix: formatDateString with [UTC]xxx didn't use passed date

### LINKED ISSUE #6614: [BUG] utils.formatDateString always return now
**Describe the bug**

```js
> temp0[0].fields.created
Date Fri Aug 30 2013 16:42:00 GMT+0800

> $tw.utils.formatDateString(temp0[0].fields.created, "[UTC]YYYY0MM0DD0hh0mm0ssXXX")
"20220409165524954"
```

**To Reproduce**
1. Go to tiddlywiki.com
2. in console
3. type `$tw.utils.formatDateString(new Date('Fri Aug 30 2013 16:42:00 GMT+0800 (中国标准时间)'), "[UTC]YYYY0MM0DD0hh0mm0ssXXX")`
4. See `"20220409165524954"`

**Expected behavior**

Should be `2013xxxx`

**TiddlyWiki Configuration (please complete the following information):**
 - Version 5.2.2
 
**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 100

**Additional context**

I'm developing a saver from HTML to nodejs, and I found all changed tiddler changed their created time to now by https://github.com/tiddly-gittly/tw-mobile-sync/blob/92038618aab1df072d4d9b9031812186000b41ae/src/browser-background-sync.ts#L202-L210 as described in https://talk.tiddlywiki.org/t/can-i-use-two-sync-method-together-to-sync-between-mobile-and-desktop/2813/2

### PR DESCRIPTION
**Pull request by linonetwo**
Fixes #6614

tested locally

### CODE REVIEW

**Comment by pmario** [comment]
There should have been a test that "should have failed" at https://github.com/Jermolene/TiddlyWiki5/blob/73138b79aaaafa32b3a0abf8ba80c96eb3a18d56/editions/test/tiddlers/tests/test-utils.js#L71

So it seems not every path of the code is covered by tests for this function. .... @linonetwo .. Is it possible, that you add a new test too?

Did you try the test-system yet?

**Comment by linonetwo** [comment]
Ok, I will add a testtried. I have test cover in my own plugins using jest, but haven't try the one in tiddlywiki.

**Comment by linonetwo** [comment]
Sorry, but how to run this? I was expecting there is something like `npm test` for it.

**Comment by linonetwo** [comment]
I see from github action, it is `./bin/test.sh`, now it is passing.

**Comment by linonetwo** [comment]
Test failed in my timezone, but will work in England...

```
date = new Date(2014,10,9,17,41,28,542)
console.log(date, date.getUTCHours())
2014-11-09T09:41:28.542Z 9
// 9 should be 17 ...
```

**Comment by Jermolene** [comment]
Thanks @linonetwo

**Pull request merged**
