### PR TITLE
add tw5-com math operator doc operator tiddlers

### PR DESCRIPTION
**Pull request by BurningTreeC**
... should I go ahead adding all or are they already prepared or added in a moment?

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @BurningTreeC are you offering to complete the docs for the maths filter operators? That would be an enormous help, thank you, much appreciated!

**Comment by BurningTreeC** [comment]
@Jermolene, yes I thought if they're not already done I could do that

**Comment by BurningTreeC** [comment]
I'll just go ahead

**Comment by Jermolene** [comment]
Terrific, thanks @BurningTreeC

**Comment by twMat** [comment]
In deed, thank you @BurningTreeC !!!

**Comment by BurningTreeC** [comment]
@Jermolene @twMat , I'm a bit in doubt what the correct naming should be in regard of Binary, Unary and a possibly third category for operations on all input titles like the minall maxall operators that take the full input list and return a single list-item. Should that be something like a `Unary Array Mathematics Operators` or just `Unary` or `Binary`, whatever matches?

**Comment by BurningTreeC** [comment]
`Arrayary`?

**Comment by BurningTreeC** [comment]
I'm just struggling with the naming logic, but I'll finish this and we'll see then...

The question is like in the maxall case, it's a series of binary comparisons, but the operation as a whole doesn't take an operand, so it somehow is an unary operation, on an array ... many small binary operations ... may someone else decide about the naming

**Comment by BurningTreeC** [comment]
@Jermolene, ready for review

**Comment by pmario** [comment]
???????

**Comment by BurningTreeC** [comment]
?

**Comment by Jermolene** [comment]
Hi @BurningTreeC apologies, but I'd forgotten about this PR and gone ahead and added the docs myself... I think yours might be a bit more concise, do you see any improvements here worth carrying over?

**Comment by BurningTreeC** [comment]
@Jermolene no this wouldn't improve anything... I'll close this one

**Comment by Jermolene** [comment]
Thanks @BurningTreeC and apologies again.

**Pull request closed without merging**
