### PR TITLE
Enable gzip compression for index.html

### PR DESCRIPTION
**Pull request by somax**
Enable gzip compression for index.html

### CODE REVIEW

**Comment by danielo515** [comment]
Sorry for asking this again. What's the benefit of this? I'm not saying this is not good, I'm expressing my lack of knowledge. If you could explain what is this used for I will be very grateful.

**Comment by Jermolene** [comment]
Thanks @somax 

@danielo515 gzip compression means that HTML/CSS/JS is automatically compressed with the ZIP algorithm by the web server. It's enabled on tiddlywiki.com and gives a pretty good saving: the 2.8MB of the original HTML file is actually transferred as 1MB of compressed data. The effectiveness of gzip compression is one of the reasons I'm not hugely in favour of minifying JavaScript code.

**Comment by Jermolene** [comment]
@somax just a thought, but does this code still work with browsers that don't support gzip compression?

**Comment by danielo515** [comment]
Hello @Jermolene 

Thank you for the clear explanation. From the commit I understand that this only applies to the server side of the  node version. Then this depends on the server that serves the file right? As far as I know tiddlywiky.com is hosted on github. How do you have enabled such feature?

**Comment by Jermolene** [comment]
Hi @danielo515 yes, the server needs to support gzip compression. GitHub Pages supports gzip compression automatically; there's nothing special needed to enable it.

**Comment by Jermolene** [comment]
Hi @somax 

Here's a curl request to retrieve index.html uncompressed from tiddlywiki.com:

```
curl http://tiddlywiki.com --silent --write-out "size_download=%{size_download}\n" --output /dev/null
```

And here's a curl request to retrieve a compressed index.html:

```
curl http://tiddlywiki.com --silent -H "Accept-Encoding: gzip,deflate" --write-out "size_download=%{size_download}\n" --output /dev/null
```

I get 2974401 bytes and 1052847 bytes respectively.

Perhaps you could use variants of those commands to test whether your modified server is capable of returning uncompressed data when required.

**Comment by somax** [comment]
Hello @Jermolene

I've just made some changes that support return data according to the requirement, please have a look.

**Comment by msiemens** [comment]
Any progress on this PR? GZIP reduces my personal wiki from 3.0 MB to merely 640 KB.

**Comment by danielo515** [comment]
Hello @msiemens, 

How are you serving your personal wiki? I am curious about it.

**Comment by msiemens** [comment]
@danielo515 Via node.js on a private webserver. It's text only at the moment whereas tiddlywiki.com contains some images which are [known to compress badly with GZIP](http://webmasters.stackexchange.com/a/57590).

For what it's worth, I'm using TiddlyWiki behind an Apache proxy so for now I simply enabled GZIP in the `.htaccess` to get the same effect as in this PR.

**Comment by danielo515** [comment]
Hello @msiemens 

Thank you for the response. I did a test just g-zipping my html file on my desktop and it falls from 2.6 MB to just 666 KB, which is impressive. Such level of improvement would make an huge difference on slow connections or limited ones such mobiles. This would be specially interesting for TW that wants to be a blog-like thing.

And just adding this to the HTML file will it be compressed before send?

Regards

**Comment by Jermolene** [comment]
@msiemens I'm not enthusiastic about this change. In it's current form the index.html is re-compressed every time it is requested, which makes for poor performance. We'd probably want to cache the compressed copy. That complicates things immensely, especially if TW5 is being used behind a server like nginx that also supports caching. It seems a lot simpler to let Apache/nginx etc. handle these details, as you're doing at the moment.

@danielo515 when the TiddlyWiki HTML file is served by most static hosts (eg GitHub and Dropbox), gzip compression is automatically applied.

For blogging, the idea is to generate static HTML files, rather than distributing the entire TiddlyWiki HTML file.

**Comment by msiemens** [comment]
@Jermolene: I think it would be helpful to have some kind of performance tips in the documentation which mentions using the server's GZIP compression.

**Comment by pmario** [comment]
@Jermolene ... The server stuff completely changed since this PR was created. ... So imo should be closed, since you weren't happy with the solution, in the first place.

With the new server structure, it should be possible to create a "compressed" path plugin, that wouldn't need to change the core but also provides the functionality.

**Comment by pmario** [comment]
It's still open. .. Is this intentional?

**Comment by pmario** [comment]
@Jermolene 
You wrote:

>Thanks @pmario I think my reasoning above stands so I'm closing.

But you didn't??

**Comment by pmario** [comment]
@Jermolene you wanted to close it. See: https://github.com/Jermolene/TiddlyWiki5/pull/1754#issuecomment-442223186 Pls do!

**Comment by Jermolene** [comment]
Thanks @pmario, it seems I do often click the wrong button (!)

**Pull request closed without merging**
