### PR TITLE
Add Theme-tweaks parameter to .controlpanel-tab macro

### PR DESCRIPTION
**Pull request by PauDeLuca**
-Created system tiddler named $:/core/ui/ControlPanel/Theme-tweaks that transcludes  the contents of  $:/themes/tiddlywiki/vanilla/themetweaks

-Updated parameter list for .controlpanel-tab in the documentation macros

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @PauDeLuca you may have missed my message in the groups about this:

https://groups.google.com/d/msg/tiddlywiki/WtVtrmjTxtw/teLANQykBQAJ

> The difficulty is that the ThemeTweaks tab is not part of the core; it is part of the “Vanilla” theme plugin. So it should not be named with a $:/core prefix.

> The `controlpanel-tab` is defined like this:

> `\define .controlpanel-tab(_) <<.tab "$:/core/ui/ControlPanel/$_$">>`

> Could you perhaps just invoke the underlying `tab` macro directly:

> `<<.tab "$:/themes/tiddlywiki/vanilla/themetweaks">>`

**Comment by PauDeLuca** [comment]
I understand it, but I don't fully get it.

Right now I see a plugin feature hardcoded as a control panel tab.
Adding the tab to the core and transcluding its content from the plugin maybe would allow tweaking other themes that include such a feature, maybe in a tiddler tagged $:/tags/ControlPanel/Theme-tweaks or so.
Meanwhile, we could keep a macro for each element, with one parameter per subelement.
Defining a new macro with no parameters that covers only one subelement of the controlpanel-tabs looks a bit chaotic to me.

Take a look at the attachment, maybe It explains my point better.
I'm testing if my approach could have unexpected consequences in the way TW works, but I cannot force any error so far.
(Please, change the file extension back to .html --I added .pdf to dodge GitHubs file support issues)
[Theme-tweak_test.html.pdf](https://github.com/Jermolene/TiddlyWiki5/files/238521/Theme-tweak_test.html.pdf)

**Comment by PauDeLuca** [comment]
Reformulating my thoughts (we spaniards may sound harsher than we actually are when speaking in english, sorry for it), it looks a bit chaotic non-systematic having a macro and four parameters to call the elements of a category and needing a new macro to call the remaining element.
I'm thinking... 
What if the Theme Tweaks-tab was a sub-tab of the Appearance-tab included in $:/core/ui/ControlPanel/Appearance and that subtab called the tweak features of the plugin by means of a filter instead of directly or by transclusion? 
Would it look better? I'll try to modify the commit in that way, if you think it might work better.

Thank you.
P.-)

**Comment by Jermolene** [comment]
Hi @PauDeLuca I think the fundamental problem here is that the macro `controlpanel-tabs` only works for control panel tabs that are defined in the core, even though there is no requirement that control panel tabs have to live in the core.

Anyhow, it's not too unreasonable, as the macro looks like a shortcut for invoking the underlying `tabs` macro on a core control panel tab.

Hence my suggestion to use the underlying macro instead. Would that not work?

**Comment by PauDeLuca** [comment]
It certainly would, but it would not be consistent with the criteria the other macros work.... nor efficient.

To keep documentary consistence all the tabs should be invoqued by the same macro:
If there was a way to make <<.tab Appearance>> <<.tab Sources>> possible I would not complain at all, but as it is, consistently using the underlying macro looks like this:

<<.tab "$:/core/ui/ControlPanel/Appearance">>
<<.tab "$:/core/ui/ControlPanel/Advance">>
<<.tab "$:/core/ui/ControlPanel/Saving">>
<<.tab "$:/themes/tiddlywiki/vanilla/themetweaks">> 

...etc. forcing a documentation writer -we are mostly bookworms, not geeks- to remember and accurately type an obscure string like <<.tab "$:/themes/tiddlywiki/vanilla/themetweaks">> (51 characters!) every time we need the caption name of a particular component in a particular visual style (rarely more than 15 characters), will surely have two consequences:

-From the point of view of terminology, we lose guarantee over precision and consistency (if I doubt when trying to remember my own translation of "saving" in the specific context of the control panel tabs, I can be sure that everyone else will).

-From the point of view of visual styles, direct styles will be preferred over style macros, by matters of economy, efficiency, usability and overall practicity... exactly what style guides are intended to provide and the usual reasons why making people follow style guides is so hard to implement.

<<.controlpanel-tab Themetweaks>> seems a reasonable compromise between usability and accuracy (however, having all the macro parameters in lowcase would be even more balanced and error-free), and creating a core tab "Theme Tweaks" where the plugin tiddler can pour its content (by transclusion as in my suggestion, or by any other referencial mean), allows it... and it works.

The same happens, as far as I know, with the control panel tab "Server" and the InfoPanel "Sources", which I haven't looked into yet, but I guess that a similar approach would work.

**Comment by Jermolene** [comment]
Hi @PauDeLuca apologies for the late response, and thanks for your patience.

> To keep documentary consistence all the tabs should be invoqued by the same macro:

I think the heart of the problem is this: the inconsistency lies in the underlying implementation of the control panel tabs (in the sense that the "theme tweaks" tab differs from the others because it is part of a plugin and not part of the core).

So an attempt to repair the inconsistency at the documentation level is doomed to introduce more inconsistency -- the fix you've suggested essentially makes the "theme tweaks" tab look as if it were a core control panel tab by using the naming conventions used in the core. Anyone looking at how the control panel is constructed will be confused by the apparent presence of two simultaneous conventions: a naming convention, and a tagging convention.

I'm in favour of making things as easy as possible for documentation writers, but I really don't see a way to square this circle. There is structural complexity here, and I don't see a good way to make it disappear.

**Pull request closed without merging**
