### PR TITLE
fix: use `isShadowTiddler` insteadof `allTitles`

### PR DESCRIPTION
**Pull request by linonetwo**
About https://github.com/Jermolene/TiddlyWiki5/discussions/7278#discussioncomment-5076129 @pmario @Jermolene 

Before

截屏2023-02-27 22 39 24

After

截屏2023-02-27 22 43 31

### CODE REVIEW

**Comment by linonetwo** [comment]
And this method is checking isShadow like before

截屏2023-02-27 22 48 01

截屏2023-02-27 22 47 52

**Comment by Jermolene** [comment]
Hi @linonetwo I don't think this works properly because of the possibility that a tiddler is both a shadow tiddler and an ordinary tiddler (this can happen if the shadow is overridden). In these cases, isShadowTiddler() returns true, but there can still be an ordinary tiddler overriding it.

**Comment by linonetwo** [comment]
Thanks, I use `tiddlerExists` instead, which is 

> Test for the existence of a tiddler (excludes shadow tiddlers)

**Comment by Jermolene** [comment]
Great, thanks @linonetwo I think this a worthwhile improvement.

**Comment by pmario** [comment]
@Jermolene .. it seems we use `tiddlers.indexOf(title)` 3 more times. 

IMO we should check, if they can optimized too. 

image


`indexof(...== -1` .. is used 136 times. Should we have a closer look there too?

**Comment by Jermolene** [comment]
None of those matches are relevant here. The key thing was that the code was searching the array returned by `wiki.allTitles()` instead of using `wiki.tiddlerExists()`.

**Comment by pmario** [comment]
Yea. I've just seen that too. ... :)

**Pull request merged**
