### PR TITLE
Doc macros new syntax

### PR DESCRIPTION
**Pull request by pmario**
This PR is a draft atm, since: 

**It is proposed to move the doc-macros + their style tiddlers into a core macro**. Those macros are also handy for plugin authors. Having them as a core plugin would allow us to make reference documentation consistent for the whole ecosystem. 

@Jermolene -- What do you think about this proposal?

This PR does not contain the proposed plugin -- yet?!

-------------

This PR does convert the doc-macros into the new v5.3.x syntax. It may be possible to make some code look prettier, but I think they all still work in a backwards compatible way. 

This PR also fixes the issues

- #8003 and
- #8004

There are new "info boxes" now, which all use $:/palette colour variables to allow palette switching.

**Note boxes** look like this now

image

**Tips** look like this now

image

**Warnings** look like this now

image

**Note together with a Warning" looks like this now

image

**Documentation Macro** docs is improved

image

**Tiddler Info Area**

Tiddler info section will get a link to the https://saqimtiaz.github.io/tw5-docs-pr-maker/ edition.

image

### CODE REVIEW

**Comment by kookma** [comment]
This is just a crude idea: 
What do you think if we could have an official plugin like author-tools, or utility, ...
and then move all related tools to it. This way we have a smaller core and a full bundle of tools for developers.

**Comment by kookma** [comment]
> What else would you like to be part of an "author-tools" plugin?

I think for documentation and plugin developers we can collect useful tools and include here. Examples are boilerplate tiddlers, badges, cards, faqs, ...

I think documentation tools and utility tools can be extensively improved and yet shipped as a separate plugin!
I am always in favor of small core, even few tens of kB smaller.

**Comment by pmario** [comment]
>It is proposed to move the doc-macros + their style tiddlers into a core macro. Those macros are also handy for plugin authors. Having them as a core plugin would allow us to make reference documentation consistent for the whole ecosystem.
>
>@Jermolene -- What do you think about this proposal?

@Jermolene -- any opinion?

**Comment by Jermolene** [comment]
Hi @pmario it seems a reasonable idea but I do have some concerns:

* It would mean that the docs were no longer self-contained. Visiting tiddlywiki.com and exporting some or all tiddlers as JSON would produce an export that would not work on other wikis. There would be no easy way to explain to users what the problem is and how to fix it. (At the moment there is a dependency in the docs on the railroad plugin, but the consequences of it not being installed are obvious and localised; the dependency on the docs macros is much harder to manage because important functionality would fail without the docs macros - eg the examples)
* I also have plans that have come up recently on talk.tiddlywiki.org to do more work on getting the docs working properly as a plugin that can be installed alongside the users own content. In that situation, I think we'd want to have the macros integrated with the content so that it works everywhere

Perhaps instead we can offer a simple, well signposted way for users to download all the docs macros as a JSON file?

**Comment by pmario** [comment]
I think your concerns are valid. 

>Perhaps instead we can offer a simple, well signposted way for users to download all the docs macros as a JSON file?

I think we can create a "Bundle doc-macros" button somewhere, which also creates a "bundle info-tiddler". The info tiddler IMO should contain the TW-version from which the bundle was exported and the date of export, including a list of all the tiddlers that have been exported. 

I'll have a closer look.

**Comment by pmario** [comment]
tiddler info section will get a link to the https://saqimtiaz.github.io/tw5-docs-pr-maker/ edition.

image

**Comment by pmario** [comment]
This draft will be closed, since it was replaced by PR:  **Doc macros and documentation tiddler** #8036  and  several others

**Comment by pmario** [comment]
Close this one, since most of the other "smaller" PRs have been merged. see: https://github.com/Jermolene/TiddlyWiki5/pull/8037

**Pull request closed without merging**
