### PR TITLE
allow single-line text-area

### PR DESCRIPTION
**Pull request by tobibeer**
otherwise autoHeight will never let it be smaller than some 48 pixels

...must be some browser default

### CODE REVIEW

**Comment by Jermolene** [comment]
Wouldn't it be clearer to expose the "rows" attribute of the input element as a widget attribute?

**Comment by tobibeer** [comment]
Could be clearer, would achieve the same, not sure anyone needs it... seeing as we have css and **minHeiight** and also **autoHeight**. So, I thought this would simply / meaningfully change the default, afaics only for the very case where we actually want it to be as slim as possible... otherwise not having an effect.

**Comment by Jermolene** [comment]
On my browsers, the textarea ends up with "rows=1" but the correct height. It's not clear whether all browsers handle the ambiguity in the same way

**Comment by tobibeer** [comment]
Ok, so it needs exposing via the rows attribute.

**Comment by tobibeer** [comment]
Closing in favor of #2152.

**Pull request closed without merging**
