### PR TITLE
Documentation macros and improvements to filter docs

### PR DESCRIPTION
**Pull request by aelocson**
As [discussed][1], I've introduced some documentation macros.

As part of testing these, I've also rewritten the step-by-step introduction to filters and made further improvements to the Filter Syntax tiddler.

[1]: https://groups.google.com/forum/#!topic/tiddlywikidocs/VekFdHhtwKA

### CODE REVIEW

**Comment by aelocson** [comment]
I think the merge conflict is with wikitext/Variables in WikiText.tid which @tobibeer changed in pull request #1334.

I was aware of that change before I sent this current request, and I duly copied the latest content of that file to my local repository before I made my own change to it. But I guess I should instead have synced my local repository first. However, I've not yet figured out how to do that. Annoyingly, it appears to be impossible to sync a GitHub repository, and the [instructions][1] for syncing a local clone gave me baffling error messages.

Advice on best practice here would be most welcome!

[1]: https://help.github.com/articles/syncing-a-fork/

**Comment by tobibeer** [comment]
If accepted, the wikitext-examples should be part of the doc macros ... in a next iteration.

Here's a recent addition I just added to a pull request:

https://github.com/tobibeer/TiddlyWiki5/commit/80631b35ea68cb38e73230bf30784c405eb6870a#diff-2

**Comment by aelocson** [comment]
Can GitHub show me which files and lines are in a conflicting state? I couldn't find any indication of that in the diff, but I believe the only file in conflict is Variables in WikiText – [diff][1].

[1]: https://github.com/Jermolene/TiddlyWiki5/pull/1355/files#diff-22

**Comment by tobibeer** [comment]
Yes, that's what I was referring to.

**Comment by aelocson** [comment]
I've got your changes to that file locally (and they're included in this pull request). But I did that behind Git's back, as it were, just by copying the file's content from Jermolene's repository into my local copy. This is what has confused Git, because I didn't sync first (because I couldn't figure out how to).

I started working on the changes in this pull request several days ago, before you sent #1334. I started with a fresh local clone of my GitHub fork, but that had become out of date by the time I came to generate my pull request today.

Clearly I need to learn how to do a sync operation between repositories, which is why I'm asking for advice.

**Comment by aelocson** [comment]
How, for example, do you keep the master branch of your tobibeer/TiddlyWiki fork "even with Jermolene:master"? What's your workflow in terms of the Git command line?

The master branch of my own aelocson/TiddlyWiki fork keeps falling behind, and I don't know how to keep it in sync. A couple of times, I've had to resort to deleting that fork altogether and starting a new one. That can't be right.

**Comment by tobibeer** [comment]
Perhaps try ...

* `git fetch upstream`
    * to get those updates
* `git merge upstream/master`
    * to merge it into your branch
    * possibly reverting this one file first and storing a backup
* `git push`
    * to put it up here

**Comment by aelocson** [comment]
Thanks for the link to your wiki, @tobibeer.

It turns out I needed to do `git remote add upstream` first.

But my local repository is now a mess, and I need to fix bug #1357 with the railroad plugin. So I will close this pull request, back up my local copy of the changes it involved, and start with a fresh local clone.

**Comment by aelocson** [comment]
I've finally got there, and I think I now understand what I'm doing. I thought I did before, but I'd got entirely the wrong end of the stick about how Git branches work. Thanks for your help, @tobibeer.

**Comment by tobibeer** [comment]
call me a noob :-)

**Pull request closed without merging**
