### PR TITLE
Create new CheckList Widget (and associated docs)

### PR DESCRIPTION
**Pull request by matabele**
A supplementary widget to the $checkbox widget, which extends list operations to any field or index. The `field`, `checked`, `unchecked` and `default` attributes  have been removed (as this functionality is better expressed elsewhere), and the code has been simplified.

Discussions with regard the development of the CheckList widget may be found
-- here: https://github.com/Jermolene/TiddlyWiki5/issues/1957
-- and here: https://github.com/Jermolene/TiddlyWiki5/pull/2003

The widget, along with test cases and usage examples may be found [here.] (http://checkbox-list.tiddlyspot.com/)

There are several redundant widgets in the core, for example the $fieldmangler widget -- perhaps these legacy widgets could be gradually moved over to a plugin: `$:/plugins/legacy-widgets` as and when their functionality is superseded (as will be the case should the $checkbox widget be simplified.)

This plugin could be provided with the blank edition -- but could be easily removed where not required.

### CODE REVIEW

**Comment by tobibeer** [comment]
@matabele, I like the idea of legacy widgets in plugins very much. Then you can easily remove them and see if anything breaks and what... and if you're not confident about it, just keep them.

**Comment by felixhayashi** [comment]
Hi @matabele 

thanks for the PR. I like the checklist widget very much, however, I do not see any reason to deprecate the checkbox widget. It serves a purpose (toggling the value of a single field) that is not catered for by checklist or radio: 

* The radio widget is not meant to do that but to switch values.
* The checklist widget always operates on lists meaning it would add brackets when adding a value with spaces `[[Bill Gates]]`. So toggling a value on a non-list field without brackets then you need checkbox.

Moreover, it is a useful shorthand to avoid radiowidgets when switching between two values using selected and unselect.

**Comment by matabele** [comment]
Have now changed the name of the `list` attribute to `field` as suggested.

**Comment by felixhayashi** [comment]
> Have now changed the name of the list attribute to field as suggested.

Thanks!

**Comment by matabele** [comment]
@felixhayashi 
I have now extended the operation of the widget to handle data dictionaries (and fixed a couple of bugs.)

**Comment by matabele** [comment]
@felixhayashi @tobibeer 
And, by way of a companion widget, I have extended the operation of the Checkbox widget to handle data dictionaries (and revised some of the code): https://github.com/Jermolene/TiddlyWiki5/pull/2196

**Comment by tobibeer** [comment]
@matabele, why would you have two complex PR's open for the same widget? This makes it a little hard to understand which change does what. How do #2196 and #2205 go together and what (to do) about #2103?

**Comment by felixhayashi** [comment]
> I have now extended the operation of the widget to handle data dictionaries (and fixed a couple of bugs.)

@matabele, very nice. Looking very much forward to have this available in the next release. Thanks for your effort.

I agree with @tobibeer, it makes more sense to stick to the same PR when working on the same module.

**Comment by matabele** [comment]
@tobibeer 
Sorry about the confusion -- mostly due to my inadequate understanding of how Github works. Some options seem to be available sometimes, and on other occasions they are not offered.

Anyway:
- there's one pull request (this one) for the Checklist widget (this includes both the widget, and its associated documentation)
- there are two pull requests https://github.com/Jermolene/TiddlyWiki5/pull/2196   https://github.com/Jermolene/TiddlyWiki5/pull/2205 for the modified Checkbox widget (one is the widget itself and one the associated changes to the documentation.)

If I could work out how, it would be neater if #2196 and #2205 could be merged (they are both in the same branch of my fork, but have separate PR's as I submitted the code first.)

**Comment by matabele** [comment]
@tobibeer @felixhayashi 
I did try sharing some of the modules for the Checkbox and Checklist widgets -- in the end, it turned out that the only entirely shared module was `CheckboxWidget.prototype.render` and, as sharing necessitated more complex passing of attributes, it seemed simpler to have two entirely independent widgets.

This, in addition, facilitates maintaining backward compatibility for the Checkbox widget.

**Comment by felixhayashi** [comment]
> and, as sharing necessitated more complex passing of attributes, it seemed simpler to have two entirely independent widgets.

@matabele Exactly my opinion, I said the same somewhere in another discussion on these widgets: It makes no sense to refactor the code here. The checkbox functionality for using it on tags is a legacy feature and should not influence the clean implementation of the checklist widget in any way, i.e. you should not make the checklist widget complicated just to have some shared code with the checkbox widget, which is not even used for this task anymore.

**Comment by tobibeer** [comment]
@matabele, all you need to do to amend a PR is to commit your updates to the same branch from which you made the PR... then you can close the other PR.

**Comment by tobibeer** [comment]
> So please don't bother.

Very much agree. Keep the focus on list-fields with checklist. It should not ever go into "single-value-mode" ...that is not what it's for.

**Comment by matabele** [comment]
@tobibeer 
I didn't notice that the 2nd PR included the widget from the 1st PR -- I've now closed the first PR and edited the descriptions accordingly. Think this all makes sense now.

**Comment by tobibeer** [comment]
> I didn't notice that the 2nd PR included the widget from the 1st PR -- I've now closed the first PR and edited the descriptions accordingly.

Ah, that's where the confusion came from. So, a PR will always be against an entire branch, not some commit.

**Comment by matabele** [comment]
@tobibeer 
If I commit direct from my laptop (using SourceTree) -- I can choose which commits to include in a PR. On Github, however, there seems no way to do this (I had assumed only new commits were included in a new PR.)

Github still confuses me :-/

**Comment by tobibeer** [comment]
@matabele, I'd be in favor of allowing other embedded action-widgets to be triggered by the checkbox- or checklist-widgets.

**Comment by tobibeer** [comment]
Hi @matabele, should not require too much code, but not sure how much this is wanted but the checklist-widget could also provide a **cycle** attribute where the user could specify a *filter* and all items that would be cycled through, going back to the first item when clicking at the last.

**Comment by matabele** [comment]
@tobibeer 
Sorry, I don't quite understand what you're getting at with regards the `cycle=` attribute. The widget currently ties the checkbox to a single item in list (and toggles the value.) To manipulate all items, the widget must be placed inside a $list widget.

How do you see the `cycle=` attribute working? 
-- click once: sets the first item from the filter output
-- click again: unsets the first item, and sets the second item 
-- click again ...

**Comment by tobibeer** [comment]
@matabele, let me explain:

**Status Tags**: #open, #next, #wait, #done...

When in...

* #open and I click =>
* #next is assigned, when clicked =>
* #wait assigned, then =>
* #done is assigned ...and finally => back to
* #open

**Comment by matabele** [comment]
@tobibeer 
This could be added to the Checklist widget, but doesn't seem appropriate -- what would the checkbox states indicate?

I think this may be better implemented with the ActionListops widget -- it is already possible using two of these widgets like so (one to cycle the items, and one remove the last item and add the first item to a target):

`<$button>
<$action-listops $tiddler="ListopsData" $index="DataIndex" $subfilter="+[putlast[]]"/>
<$action-listops $tiddler="CycleTags" $tags="[list[ListopsData##DataIndex]first[]] -[list[ListopsData##DataIndex]last[]]"/>
Move the head to the last item
</$button>`

Place your list in `ListopsData##DataIndex` and the current (cycled) tag will appear in `CycleTags!!tags`. 

It may be possible to write a new listops filter operator to achieve both operations in one line -- can't think how to do this offhand, as two states need saving to two different targets (the updated list, and the first item.) Seems this would need an additional parameter to specify the second target.

I suppose a new filter operator could search the target for any item appearing in the list to be cycled, and exchange it for the next item in the list (else, if either an item is not found, or end of list -- exchange it for the first item in the list.)

**Comment by matabele** [comment]
@tobibeer 
OK -- already possible in one line:
`<$button>
<$action-listops $field="status" $subfilter="[list[]first[]] [list[]after{!!status}] +[replace{!!status}] +[first[]]"/>Cycle Status</$button>`

Place the list to be cycled in the 'list' field, and the status will update in the 'status' field

**Comment by matabele** [comment]
@tobibeer 
Appears the status needs to be seeded with any item before this will work. I think, without the seed, the first item from the list gets added and then removed.

**Comment by matabele** [comment]
@tobibeer 
The self seeding version:
`<$button>
<$action-listops $field="status" $subfilter="[list[]first[]]  [list[]after{!!status}]+[replace{!!status}] [list[]first[]]+[first[]]"/>Cycle Status</$button>`

**Comment by matabele** [comment]
@tobibeer 
As I suspected -- the replace[] operator removes the last item before replacing the marker, and if there's no marker, discards it (I should probably fix this). The following version works as expected:
`<$button><$action-listops $field="status" $subfilter="[list[]first[]]  [list[]after{!!status}]-[{!!status}]+[first[]]"/>Cycle Status</$button>`

The middle terms `[list[]after{!!status}]-[{!!status}]` walk through the list -- the outer terms `[list[]first[]] +[first[]]` take care of seeding the first item, and cycling back to the first item at the end of the list (without lising two items.)

**Comment by tobibeer** [comment]
> This could be added to the Checklist widget, but doesn't seem appropriate -- what would the checkbox states indicate?

You're right. We're talking about buttons.

> I suppose a new filter operator could search the target for any item appearing in the list to be cycled, and exchange it for the next item in the list (else, if either an item is not found, or end of list -- exchange it for the first item in the list.)

I think that would be the right approach. But, yes, as you said, this is getting OT... so, let's have this conversation elsewhere, perhaps even on TiddlyWikiDev. (And let's possibly delete all of the last comments concerning cycling to clean up this PR.)

**Comment by tobibeer** [comment]
@matabele, I removed all the **cycle** comments... and will remove this one later as well.

**Comment by felixhayashi** [comment]
Thanks @matabele 

> This could be added to the Checklist widget, but doesn't seem appropriate -- what would the checkbox states indicate?

Maybe I am not up to date with all the discussions going on but I think this will be a bit complicated, also, the checklist is, unlike a button, an element with its own state and logic. This could conflict when other widgets are triggered. I'd use a button for that.

With regard to git(hub):

Maybe you could do a git `rebase` to turn all commits into one, so all changes are flattened and become comparable?

I noticed you directly created the PR from your master branch. Usually, if you start a fix/feature, you would create a new dedicated branch for that in your fork e.g. `feature/checklist` or `checklistfeature`. Then you can easily do a rebase or do a `soft reset` of the `head` and do a recommit to squash commits into one at the end. See http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git. – Maybe that is not possible anymore because you also did other commits into master as well that are not related to the checklist PR.

**Comment by felixhayashi** [comment]
> Maybe you could do a git rebase to turn all commits into one, so all changes are flattened and become comparable?

At least this is what a git grand-master (@sukima) once told me ;) and I agree it is good style as it allows better comparison and doesn't spam the TW5 repo with commits.

**Comment by matabele** [comment]
Can't get rid of the 'Mars Jingle' which is interfering with my commits -- going to try deleting everything and rebasing with a fresh copy

**Comment by twMat** [comment]
Was this ever followed up? (Fellow matabele sadly passed away so he can obviously not answer me.)

The functionality to toggle individual values in a list is very valuable so, for the record, here's a wikitext solution: http://toggle-in-field.tiddlyspot.com/

**Pull request closed without merging**
