### PR TITLE
Don't minify codemirror.js

### PR DESCRIPTION
**Pull request by BurningTreeC**
The vim-cursor problem that should have been solved by #5172 is only solved when codemirror.js is NOT minified. I've tested this several times and there seems to be a problem with the minified code. This PR adds the un-minified version of codemirror.js

### CODE REVIEW

**Comment by Jermolene** [comment]
Wow, I've heard of such things. Have you reported upstream?

**Comment by pmario** [comment]
But this makes the plugin unusable because of size!

**Comment by pmario** [comment]
I don't use the vim keymap. So why should I want to carry the extra weight around?

**Comment by BurningTreeC** [comment]
@pmario I'll see if after reporting this upstream there's a quick fix for this

**Pull request merged**
