### PR TITLE
Extend $draggable to support an optional drag handle

### PR DESCRIPTION
**Pull request by saqimtiaz**
This PR extends the $draggable widget to optionally use a CSS selector identifying the child DOM node to be used as the drag handle. 

This allows for use cases like dragging a "card" where only the header of the card is draggable but the drag image shows the entire card and you can still select text within the card and interact with it as normal.

### CODE REVIEW

**Comment by Jermolene** [comment]
Looks good, thanks @saqimtiaz

**Comment by saqimtiaz** [comment]
@Jermolene I am leaving this as a draft until I can review with a fresher head. Will mark it ready for review and ping you once that is done.

**Comment by saqimtiaz** [comment]
@Jermolene this is now ready, I have done some cross browser testing as well (Chrome, FF and IE11).

**Comment by Jermolene** [comment]
Thanks @saqimtiaz

**Pull request merged**
