### PR TITLE
Added canCancel to the loging prompt

### PR DESCRIPTION
**Pull request by danielo515**
It would be also useful to accept a parameter to determine if username is needed or to provide a default one.

This has been discussed a bit on #2553

### CODE REVIEW

**Comment by danielo515** [comment]
Hello @Jermolene,

I think this is a very simple PR that can be merged without much revision.

Regards

**Comment by Jermolene** [comment]
Hi @danielo515 thanks.

The callback function would appear to still call `self.login` even if the user clicks cancel, shouldn't we test for the `data` parameter being null?

If we let the user cancel the login dialogue, shouldn't there be a means to make another attempt?

**Comment by danielo515** [comment]
Hello @jermolene

You're right. I'll implement it. Sadly due to #2561 the result will be exactly the same, at least on chrome. 

Regards

**Comment by danielo515** [comment]
Hello @Jermolene 

Let me know if it looks fine now.

Regards

**Comment by danielo515** [comment]
Hello @Jermolene
 Anything else required to merge this PR?

**Comment by ght** [comment]
This can be closed since the problem it solves has been solved in the meantime.

See [the resolution of the related #2553](https://github.com/Jermolene/TiddlyWiki5/issues/2553#issuecomment-866285675). I somehow missed this related PR back when I looked at that.

**Comment by Jermolene** [comment]
THanks @ght @danielo515

**Pull request closed without merging**
