### PR TITLE
Prevent long no-space field values from overflowing

### PR DESCRIPTION
**Pull request by felixhayashi**
See #1552 which was closed when I renamed the branch.

### CODE REVIEW

**Comment by 00SS** [comment]
I was bugged by this issue and a search led to this old Pull Request.
I think it should be implemented, as it solves a really ugly overflow scenario when looking at very long unbroken field names when using a tiddler's `More Actions > Info` button.

I tried it out and the fixed effect is much better than the present one.

**Comment by pmario** [comment]
@Jermolene ... #1552 shows the "before/after" image. .. May be merged?

**Comment by pmario** [comment]
@Jermolene ... This is still a problem. IMO it should be merged!

**Comment by Jermolene** [comment]
Hi @pmario I can't reproduce the problem any more. For example, at https://tiddlywiki.com/prerelease/#Working%20with%20TiddlyWiki

image

**Comment by pmario** [comment]
See the screenshot in #1552 The map.data has no spaces in it, so it doesn't break the line

**Comment by pmario** [comment]
this can be reproduced with 5.1.23

**Comment by Jermolene** [comment]
Thanks @pmario I was confused because the first example in the screenshot in #1552 is of a field that does contain spaces.

**Comment by pmario** [comment]
Yea, the first screenshot is **after the fix**.

**Comment by Jermolene** [comment]
> Yea, the first screenshot is **after the fix**.

I realised that, the issue is that the second screenshot actually shows two fields that overrun, the first of which contains spaces and the second doesn't.

**Comment by pmario** [comment]
May be we did fix the first overflow issue already. The second one with no spaces is still an issue. The PR is 5 years old

**Comment by pmario** [comment]
@Jermolene ... This is still a problem with a simple fix with 1 line of CSS. 

I did test the fix with the prerelease and it works as expected.

**Comment by Jermolene** [comment]
Thanks @felixhayashi @pmario

**Pull request merged**
