### PR TITLE
change representation of å in Jingle to fix issues on OS X

### PR DESCRIPTION
**Pull request by edrex**
Changes the coding for the å character in "editions/tw5.com/tiddlers/community/resources/TiddlyWiki_Jingle_by_Måns_Mårtensson.tid". The old coding deeply confuses Git (2.3.8 (Apple Git-58) as well as 2.5.3/homebrew) on OSX (10.11.1):

```
$ git clone https://github.com/Jermolene/TiddlyWiki5
$ git status
On branch master
Untracked files:

	"editions/tw5.com/tiddlers/community/resources/TiddlyWiki_Jingle_by_M\303\245ns_M\303\245rtensson.tid"
$ rm "editions/tw5.com/tiddlers/community/resources/TiddlyWiki_Jingle_by_Måns_Mårtensson.tid"
$ git status
	deleted:    "editions/tw5.com/tiddlers/community/resources/TiddlyWiki_Jingle_by_Ma\314\212ns_Ma\314\212rtensson.tid"
$ git checkout .
$ git status
Untracked files:

	"editions/tw5.com/tiddlers/community/resources/TiddlyWiki_Jingle_by_M\303\245ns_M\303\245rtensson.tid"
```

It also freezes/pins CPU in Emacs with the magit extension, which is real annoying.

Discussed at [stackoverflow:git-and-the-umlaut-problem-on-mac-os-x](http://stackoverflow.com/questions/5581857/git-and-the-umlaut-problem-on-mac-os-x), but setting `core.precomposeUnicode true/false` there don't help here, i think because the coding on disk is actually broken somehow.

The problem will still persist on refs with the old coding, but short of a destructive rewrite this is the best we can do. @Jermolene, what platform was 15c76d997eb540e552ecf1f5d55d7ffea73fe558 made on? I suspect windows..

### CODE REVIEW

**Comment by edrex** [comment]
just for reference, I composed this commit in Linux since OSX git is too confused to do anything. plz plz plz merge this soon.

**Comment by edrex** [comment]
@pmario, can I get you to take a look at this? That accent keeps crashing my editor so I'd like to get it merged.

**Comment by felixhayashi** [comment]
@matabele, telling from your google groups post, you are affected by this?

**Comment by matabele** [comment]
@felixhayashi 

Yep -- I have been forced to enter my commits directly on Github, as this file breaks my local git.

In an attempt to get my git working:
-- deleted all repos on my Github account
-- deleted all repos on my HDD
-- created a new fork on Github
-- cloned this to my HDD
-- as soon as I open the repo, I have one uncommitted file (which can not be removed)

**Comment by pmario** [comment]
>@pmario, can I get you to take a look at this? That ligature coding keeps crashing my editor so I'd like to get it merged.

@edrex I'm using windows atm. I can't reproduce the issue. ... .. Jeremy IMO uses OSX with a Mac book So he should see the problem. ...

**Comment by edrex** [comment]
@matabele can you check out this branch and verify that the file goes away? you may have to `rm` it if it's still showing as an untracked file once you check out the branch.

**Comment by matabele** [comment]
@edrex 
OK -- will do shortly. In the process of updating my git.

**Comment by matabele** [comment]
@edrex 
Upgraded git to v.2.7.0 (homebrew) -- checked out your repo -- and all seems fine :-)

**Comment by matabele** [comment]
@edrex @felixhayashi 
Continuing with setting up -- node can now build from the repo -- looks like the fix is good.

Many thanks for the help :-)

**Comment by felixhayashi** [comment]
> Continuing with setting up -- node can now build from the repo -- looks like the fix is good.

:+1:

**Comment by sukima** [comment]
I use Git on OS X El Capitan (installed through `brew install git`) and I've never ran into this issue. Weird.

**Comment by matabele** [comment]
@sukima 
What filesystem are you using for git?

**Comment by sukima** [comment]
@matabele the standard that is installed with OS X and FileVault active. I believe this is HFS+ right?

**Comment by matabele** [comment]
@sukima 
Yes -- the standard is now HFS+

Was wondering if the inconsistent behaviour might be something to do with the fs, since our environments look to be very similar -- but same fs as well :-/

**Comment by sukima** [comment]
**CONFIRMED** This is indeed broken on OS X!

Here is exactly what happens:

[asciicast](https://asciinema.org/a/2azmjycmjvkkl9nldye38ezur)

**Comment by felixhayashi** [comment]
…that is why I do not use apple, they include random smileys in the output and there is nothing you can do against that.

**Comment by sukima** [comment]
@felixhayashi WAT?!

> they include random smileys in the output and there is nothing you can do against that

What are you referring to? Apple has never provided _random smileys_ in output. Are you referring to my command prompt? That's a [bash script I wrote](https://github.com/sukima/dotfiles/blob/master/bash/modules.d/extendedprompt#L2-L30) because I _like_ having emojis in my command prompt. It's a personal preference.

(Apologies if your comment was a joke and it went over my head).

**Comment by felixhayashi** [comment]
> That's a bash script I wrote because I like having emojis in my command prompt. It's a personal preference.

:grimacing: was a joke of course. 

> I like having emojis in my command prompt. It's a personal preference.

+1 cool idea.

**Pull request closed without merging**
