### PR TITLE
Warn when importing core tiddlers

### PR DESCRIPTION
**Pull request by bimlas**
See https://groups.google.com/d/msg/tiddlywiki/YZlPGP0qX1o/3tUpyoHXDgAJ

image

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @bimlas this is a great idea. I have two thoughts:

* Checking for the prefix `$:/core/` may not be quite right; there are some templates that are reasonable to override. So perhaps we should check for `$:/core/modules/`
* The implementation can be simplified by plugging into the existing "upgrader" mechanism -- basically, "upgrader" modules are called for each tiddler being imported, and gives them an opportunity to block them, or add a warning message. See the tiddlers prefixed `$:/core/modules/upgraders/` for the three core upgraders, and the `invokeUpgraders()` method in wiki.js. For this we'd add a new upgrader module for handling core module overwrites

**Comment by pmario** [comment]
I think, the text "You are about importing risky tiddlers... " is misleading. The action to overwrite core modules is risky. ... The modules themselves are well tested and not risky.

**Comment by bimlas** [comment]
@pmario Please, write the message that should appear - you are better in English than me. :)

**Comment by pmario** [comment]
I'm not sure, why navigator.js needs to check for this behaviour. It's not responsible for the import mechanism. 

There is the `th-importing-tiddler` hook, which can be used to add additional checks and test them.

**Comment by bimlas** [comment]
I've moved the changes to the $:/core/modules/upgraders/system.js because that performs similar checks.

image

**Comment by 00SS** [comment]
Suggested slightly "better English" wording for the warning:

You are about to import a tiddler that will overwrite a core module tiddler. This is a risky action that may make the system unstable. It is strongly recommended that you do NOT overwrite these tiddlers in an important TiddlyWiki; only in a testing environment.

**Comment by bimlas** [comment]
Sorry for the late reaction, I rewrote the text.

**Comment by Jermolene** [comment]
Thanks for your patience @bimlas

**Pull request merged**
