### PR TITLE
Remove spaces between tags

### PR DESCRIPTION
**Pull request by nameanyone**

### CODE REVIEW

**Comment by nameanyone** [comment]
screenshot_2015-12-28_22-58-59_crop

**Comment by pmario** [comment]
This PR has no content. ... no files changed. may be you forgot `git add . `?

**Comment by nameanyone** [comment]
I see. I'm not using git, instead I'm re-entering my (tested, of course) edits right here using Github file editor. What needs to be done here is remove the newline at the very end of $:/core/ui/TagTemplate, changing 
```
<$macrocall $name="tag-body" colour={{!!color}} palette={{$:/palette}}/>

```
to
```
<$macrocall $name="tag-body" colour={{!!color}} palette={{$:/palette}}/>
```
Github editor silently ignores such a change, I did not notice until you pointed it out...

**Comment by pmario** [comment]
yea, this is a problem, which we may not be able to fix. IMO there are some editors, that need a new line at the end of the file.

**Comment by tobibeer** [comment]
I don't believe there are editors that require a final newline in a text-file. There only are editors that have their ways of expecting one and informing you that they do. If they were to break based on a missing newline at the end, they'd quickly be gone.

**Comment by felixhayashi** [comment]
> I don't believe there are editors that require a final newline in a text-file

Unix:
http://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file/18789

**Comment by tobibeer** [comment]
@felixhayashi, all it says in [IEEE Std 1003.1](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap03.html#tag_03_392) is that `The lines do not contain NUL characters and none can exceed {LINE_MAX} bytes in length, including the <newline>.` It does not appear to state that a text-file is required or expected to end in `\n`.

So, sure, I can see how (some) editors may think they have to enforce this as a rule. But if they were to break and throw an error when opening a text-file that does not end in a newline, by telling you it was not a valid text-file... I think they'd receive a huge, well deserved smirk and may find themselves never being used again. ;-)

**Comment by Jermolene** [comment]
Firstly, the TW core does already in several places depend upon the absence of a newline at the end of a text file. For example:

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/ui/ViewToolbar/close.tid

Secondly, some combinations of text editor and/or git tools can silently add newlines to the end of text files that are missing one. Accordingly, we regularly get pull requests with inadvertent additions of newlines.

There is a fix that we can use in one specific case: tiddlers that need a text body that not only lacks a newline at the end, but also doesn't contain a newline.

Such tiddlers can be written with an explicit single line text field. For example:

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/wiki/config/NavigationUpdateAddressBar.tid

Although we could apply that technique more broadly, it wouldn't help a situation like the tag template where we have a multi-line text body.

**Pull request closed without merging**
