### PR TITLE
Add Tw Pre-release & Td Releases To Tw.com

### PR DESCRIPTION
**Pull request by Spangenhelm**
Hi @Jermolene,
Following the issue https://github.com/Jermolene/TiddlyDesktop/issues/54 here are my propositions of modifications to add Tiddlydesktop releases and the tiddlywiki pre-release to tw.com.

Hope this will help,
Thank you

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @Spangenhelm. I had to merge manually which means that the commit history doesn't reflect your contribution.

I didn't include  your suggestion of a "PreRelease" tab in the "Releases" tiddler because I don't want to have to update tiddlywiki.com whenever there is a new prerelease. Plus we need to try to discourage people from adopting the prerelease for day to day use.

**Comment by Jermolene** [comment]
Oh, and I meant to say that I have uploaded a new prerelease to http://tiddlywiki.com/prerelease

**Comment by Spangenhelm** [comment]
Hi @Jermolene 

>  I had to merge manually..

Unfortunatly i know i should of warn you before because i had some questions that i have noted somewhere and that i forgot to discuss before doing my pull-request (late at night or too early in the morning.. second mistake lol)
anyway, about this:

>I didn't include your suggestion of a "PreRelease" tab in the "Releases" tiddler because I don't want to have to update tiddlywiki.com whenever there is a new prerelease.

No need because i did not talk about any version number, it was just to let people know it existed (mostly early adopters) and we don't care about what version it is because we know it will always be the most recent available so i don't see any problem with this but as always it is up to you.

>Plus we need to try to discourage people from adopting the prerelease for day to day use.

Well we have clearly warned people that this version is not meant for production then i don't see any problem with this either. To me it is like beta versions often available for trial on websites, good for experienced users who don't want to wait while regular users will just use the stable version. Plus you will notice that the default selected tab on opening is on purpose __not__ the pre-release but the last __stable__ one (5.1.8 here) so it is like a "default" choice proposed to the user.

**Comment by tobibeer** [comment]
I'd also agree that "/prerelease" should be linked somewhere in the **TiddlyWiki Releases** tiddler with a sentence on what it is and what it ain't for.

**Pull request closed without merging**
