### PR TITLE
Update body-editor.tid not to set autofocus when ...

### PR DESCRIPTION
**Pull request by BurningTreeC**
... the text in the input field doesn't match an EditorTypeMapping

This PR is a try to address #7798

### CODE REVIEW

**Comment by pmario** [comment]
I did test it and it seems the "auto-focus" text field does not work anymore, if the editor is switched from view-mode to edit-mode.

**Comment by BurningTreeC** [comment]
> The cursor does not automatically focus on the search box when the website is opened

I cannot reproduce that. It must be an issue not related to this PR

**Comment by BurningTreeC** [comment]
> I did test it and it seems the "auto-focus" text field does not work anymore, if the editor is switched from view-mode to edit-mode.

You mean if you open a tiddler for editing? Then it should work fine...

**Comment by BurningTreeC** [comment]
I'm closing this PR as I've seen that there are downsides that are unresolved

**Pull request closed without merging**
