### PR TITLE
added gitea saver

### PR DESCRIPTION
**Pull request by m42e**

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @m42e this looks good.

**Comment by kookma** [comment]
@Jermelon
at the file:///C:/Users/Mohammad/Downloads/tiddlywiki.html#%24%3A%2FControlPanel under Saving tab, **gitea saver**
- The message is
`These settings are only used when saving to ~gitea`
Note to ~gitea it should be Gitea

- the tab title is `gitea saver` should be `Gitea Saver`

**Comment by kookma** [comment]
@m42e 
It would be nice to share here or in the forum or as documentation tiddler howto for setting up TW on Gitea! A sample can be found here: https://kookma.github.io/TW5-GitHub-Saver/

**Comment by mclucario** [comment]
Hey. I just stumbled over this feature. I really wanna use this but I don't understand how to set it up. Can you help me?

**Pull request merged**
