### PR TITLE
Additions to the fr-FR edition by @idoine, slightly amended by @xcazin

### PR DESCRIPTION
**Pull request by xcazin**
Hi, here is a big pull request, thanks to the huge work from @idoine. 

By the way, @idoine, we could use smaller increments: this has been rather difficult to review. I'd say a dozen of tiddlers at a time would be a good balance between too much pull requests and too much additions to review. In some cases, I boldly unmade some proposals you made (like shadow => ombre or Lazy Loading -> Téléconsigne), although it would have been better to debate them first on the discussion list.

All in all, an impressive job, thanks a lot!

### CODE REVIEW

**Comment by idoine** [comment]
Thanks to your pullrequest. I agree with you. It's better to debate for this two words. I'm not really satisfied with "ombre", and I can understand that "téléconsigne", which seem to me a good "templated transclusion" in french, need some comments.

;)

**Comment by idoine** [comment]
I forget to tell you, about two tiddlers "now" and "tabs" in the french release.  I just delete them in my one.

**Comment by idoine** [comment]
Could you tell me, when and where I can discuss about translation of "shadow" => ombre or latent and "Lazy loading" => "Téléconsigne" ?

**Comment by xcazin** [comment]
@idoine, my point is that you shouldn't invent words without getting the community consentment. And if we eventually can't find a good phrase to convey the meaning of a term, we really should let it in English. 

For instance, I'm pretty sure that **téléconsigne** doesn't convey anything close to the *lazy loading* concept, while **tiddler ombre** is less obvious to me (I'd indeed prefer **tiddler latent** or **cache** if *shadow tiddler* really had to be translated). 

In such cases, we really should ask their opinion to the community (for instance here: https://twitter.com/TiddlyWikiFR).

**Comment by idoine** [comment]
I agree, but I just read the pull request, I use of the word "ombre" in many tiddler. Just one was modify. Is it possible to modify all of them ?

**Comment by xcazin** [comment]
@idoine. One of the nice features of github is that you can stack commits in pending pull requests :-) I juste added one that replaces ombre by shadow, until we make a better decision.

**Comment by idoine** [comment]
Thanks. I just understand ;)

**Comment by idoine** [comment]
So, I vote for "latent", because "cache" isn't often visible for enduser

**Comment by Jermolene** [comment]
Thanks everyone. Is this ready to merge? I'm keen to get 5.1.9 out today if possible.

**Comment by xcazin** [comment]
Hi @Jermolene. Yep, ready to merge. With those two commits, the fr-FR edition normally look like http://fr-edition.tiddlyspot.com/. It would be nice to get @idoine contribution in 5.1.9.

**Comment by Jermolene** [comment]
Thanks @xcazin and @idoine

**Comment by idoine** [comment]
I'm happy to be in time to get this train ^^

**Pull request merged**
