### PR TITLE
Fix typo; closes #4815

### LINKED ISSUE #4815: [BUG] Minor typos, mostly in documentation
**Describe the bug**
- [Simple ways to write protect tiddlers](https://github.com/Jermolene/TiddlyWiki5/blob/tiddlywiki-com/editions/tw5.com/tiddlers/howtos%2FSimple%20ways%20to%20write%20protect%20tiddlers.tid): `but to edit them your will have to find` → `but to edit them you will have to find`
- [[all[tiddlers]search:text:literal[ and and ]]](https://tiddlywiki.com/#:[all[tiddlers]search:text:literal[%20and%20and%20]]): duplicate `and`
- [BuildCommand](https://github.com/Jermolene/TiddlyWiki5/blob/tiddlywiki-com/editions/tw5.com/tiddlers/commands%2FBuildCommand.tid): `See TiddlyWikiFolders for details of defining build targets.` → `See [[tiddlywiki.info Files]] for details of defining build targets.`
- [list-thumbnails Macro](https://github.com/Jermolene/TiddlyWiki5/blob/tiddlywiki-com/editions/tw5.com/tiddlers/macros%2Flist-thumbnails%20Macro.tid): shouldn't the caption say `list-thumbnails`? Because the caption `thumbnails` is already "taken" by [thumbnail Macro](https://github.com/Jermolene/TiddlyWiki5/blob/tiddlywiki-com/editions/tw5.com/tiddlers/macros%2Fthumbnail%20Macro.tid)
- [SystemTags](https://github.com/Jermolene/TiddlyWiki5/blob/tiddlywiki-com/editions/tw5.com/tiddlers/concepts%2FSystemTags.tid): `$:/tags/Macro` is listed twice, the second time it should be `$:/tags/Macro/View`
- [$:/plugins/tiddlywiki/freelinks/readme](https://github.com/Jermolene/TiddlyWiki5/blob/master/plugins/tiddlywiki/freelinks/readme.tid): `customising the shadow tiddler $:/plugins/tiddlywiki/freelinks/macros/view. This tiddler` → `customising the shadow tiddler [[$:/plugins/tiddlywiki/freelinks/macros/view]]. This tiddler`

### PR DESCRIPTION
**Pull request by fkohrt**

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @fkohrt many thanks for your contribution! With apologies for the bureaucracy, please could you prepare a separate PR to the 'tiddlywiki-com' branch with your signature for the Contributor License Agreement (see [contributing.md](https://github.com/Jermolene/TiddlyWiki5/blob/master/contributing.md)).

**Comment by fkohrt** [comment]
Sure thing, see #4845

**Comment by saqimtiaz** [comment]
@Jermolene docs update, can merge.

**Comment by Jermolene** [comment]
Thanks @fkohrt @saqimtiaz

**Pull request merged**
