### PR TITLE
Update draggable.js - fix the call to updateDomNodeClasses

### PR DESCRIPTION
**Pull request by BurningTreeC**
…sses

If I'm not wrong then the "updateDomNodeClasses" is unused and the "assignDomNodeClasses" is missing

This renames "updateDomNodeClasses" to "assignDomNodeClasses"

### CODE REVIEW

**Comment by pmario** [comment]
Why is this needed?

**Comment by saqimtiaz** [comment]
The fix needs to be the other way around, instead of renaming the method, rename the call to the method. This is an error introduced in a recent round of widget refactoring.

**Comment by BurningTreeC** [comment]
@saqimtiaz  @pmario I've now renamed the call to the method

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Pull request merged**
