### PR TITLE
Incorporate “diff” engine to show visual differences

### PR DESCRIPTION
**Pull request by Jermolene**
It is proposed to add a “diff-match-patch” engine to TiddlyWiki to enable the display of visual differences like this:

screenshot 2018-02-11 12 51 11

I've pushed this branch to https://tiddlywiki.com/prerelease for you to try out.

# Mechanism

This PR uses the [Google diff-match-path](https://code.google.com/archive/p/google-diff-match-patch/) library, exposed as a new `<$diff-text>` widget which is in turn available via `<<compareTiddlers>>` macro.

# User Interface

The differencing engine is exposed in several different places.

A new editor preview panel showing the differences between the current state of the tiddler being edited and when it was last saved:

screenshot 2018-02-11 12 52 36

A new editor preview panel for shadow tiddlers showing the differences between the current state of the tiddler being edited and the underlying shadow:

screenshot 2018-02-11 12 53 15

A revised “$:/Import” listing that shows the differences between incoming tiddlers and any existing text:

screenshot 2018-02-11 12 53 58

# Todo

* Documentation
* Figure out any other useful places for diffing
* Figure out other uses for the match and patch parts of the library
 * Compactly storing versions as diffs is one example
* Display differences for other fields, not just “text”
* Add extension points for visual differencing of bitmaps

We also need to decide whether this should go into the core, or be refactored as a plugin. I'm inclined to keep it in the core because I believe that the functionality that it offers is both fundamental and universal: every TiddlyWiki user edits tiddlers, and seeing visual differences is a critical aid to understanding those edits. Having said that, this patch adds approximately 30,000 bytes to empty.html, taking it from 2,016,354 to 2,047,137 bytes, so we should be asking the question.

### CODE REVIEW

**Comment by danielo515** [comment]
Hello @Jermolene 

This is a great addition. Here are my thoughts.

- I would prefer a mechanism to see side by side diff. I never liked the inline one and the google library has this config by default. It effectively hides changes more than highlighting them. Just take a look a this screenshot, where I have changed one sentence by the word perpendicular
image
As you can see, Is barely legible.
- Please don't get this into the core. Surely it is an extremely useful feature, but just for those that need it. Basic users are not used to this kind of git diffing, read-only wikis does not need this, and of course people wanting to use a different library does not need it either. I can see how this can improve for example NoteSelf experience, but only if it is non-opinionated and easy to configure. Definitively useful, but not absolutely essential.
- > Compactly storing versions as diffs is one example

  I my opinion this is just another plugin. I mean, it should be a plugin functionality, and it should not be part fo this particular plugin. This is more related to the saving mechanism rather than tiddlywiki. NoteSelf for example has this feature for almost a year, and adding it as part of the core will make it redundant, and I maybe even incompatible.

I can't think of any better place to see the diffing by now. I'll keep thinking.

Congratulations

**Comment by sukima** [comment]
Personal bike shedding here but i really don’t like the side by side views and always use the default in all cases.

Perhaps a config setting to do one or the either?

And can I say this the most suprising and exiting feature I’ve seen in a while. Thank you @Jermolene !! This is amazing!!!!!!

**Comment by sukima** [comment]
I vote core! I think it would offer some really useful ui especially if it could be reliable to be available in the core like http and crypto are.

There are some advantages having TW act a but like a framework offering utilities like that. Yes core seems good.

It could always be extracted later if needed. But this is a feature I personally would *not* mind adding some size to the empty.html

**Comment by diego898** [comment]
I think this is wonderful! Especially the addition to the import mechanism! I vote to make it part of the core. As far as 

`Compactly storing versions as diffs is one example`

I think this is a **wonderful** idea, but I can see arguments for not having it enabled/included by default.

**Comment by pmario** [comment]
I think it's great! - **Please implement it as a plugin**!

I did use the same library for the beaker-adaptor, that never got released, since beaker internal API will change with version 0.8 ... I mainly wanted to use the patch - match parts

It seems that both source and minified source are part of the commit. IMO only minified should be included!

The license should be a link to the original license, since we didn't modify the source. right?

**Comment by danielo515** [comment]
> It could always be extracted later if needed. But this is a feature I personally would not mind adding some size to the empty.html

 It is even easier to make it a plugin and make it default. You don't mind to add some size to the empty, but others may have different opinions. Making it a plugin you can decide to include it if you really don't mind the size, making it part of the core will penalize every user that do not want it.
Bloating the core is never a good Idea IMO

**Comment by Jermolene** [comment]
@pmario the uncompressed source is just there for reference, and is not included in the build - look at the tiddlywiki.files file. I've done the license similarly to other plugins; if we change the approach I guess we should do so consistently.

@danielo515 I think side by side diffs are much harder to do but I'm open to having them as an option if the necessary code is written.

**Comment by pmario** [comment]
> I think side by side diffs are much harder to do but I'm open to having them as an option if the necessary code is written.

As far as I can remember, that's a setting for the library. ... There are several parameters that can be tweaked quite a bit. ..

**Comment by danielo515** [comment]
Hello @Jermolene 

> @danielo515 I think side by side diffs are much harder to do but I'm open to having them as an option if the necessary code is written.

As @pmario said is a library config option. The tricky part can be creating an UI where side by side diff fits correctly, that could be hard.  As an alternative, I think we should configure the library to try to show bigger diffs, for example line diffs or word diffs, instead of character diffs, which are pretty much useless.

**Comment by pmario** [comment]
@danielo515 ... oh. I think, I did misunderstand the side-by-side option. ... The config I did talk about, is about word or line diffs. 

A diff like this, in [line 66](https://github.com/Jermolene/TiddlyWiki5/pull/3073/commits/bca1a5f5d695efc59a7d2242efd2179a4efd774b) don't work out of the box. ... This would need 2 different diffs. One word/char based and one line-based.

**Comment by danielo515** [comment]
Let's put words into images. @pmario taking your example as reference, this is the kind of diffing that  I like:

captura de pantalla 2018-02-12 a las 11 57 41

But because that takes a lot of space it would require a dedicated UI. 
As an alternative, we can use the same diffing, but inlined at line level, something like this:

captura de pantalla 2018-02-12 a las 11 59 03
 
Not sure if this is possible with the google library though.

**Comment by Jermolene** [comment]
Hi @danielo515 

> Not sure if this is possible with the google library though.

The core of the "diff" part of the Google diff-match-patch library takes two texts and returns an array of differences, each of which is a string that is added, removed or retained between the first and second text.

The library does include a primitive HTML output function, but we don't use it (my implementation adds visualisation of hidden characters). There's no code that I've found for the side-by-side view.

**Pull request merged**
