### PR TITLE
Add "Gruvbox Dark" color palette

### PR DESCRIPTION
**Pull request by BurningTreeC**
this adds the "gruvbox dark" color palette (https://github.com/morhetz/gruvbox) which is also available for highlight.js and codemirror

### CODE REVIEW

**Comment by kookma** [comment]
@BurningTreeC 
Love this!

The light mode is also great!

**Comment by kookma** [comment]
I drag and drop this into https://tiddlywiki.com/prerelease/
The codeMirror uses the light (white) mode!

Is there any way CodeMirror automatically use the new pallet color?

**Comment by BurningTreeC** [comment]
>Is there any way CodeMirror automatically use the new pallet color?

No, you need to explicitely add the gruvbox codemirror theme. See the "usage" section of the codemirror plugin for how to add color schemes

**Comment by Jermolene** [comment]
Thanks @BurningTreeC it occurs to me that maybe for the palettes that have been adapted from other sources we should have a "credits" or "source" field?

**Comment by BurningTreeC** [comment]
Yes @Jermolene, I'll add a credits field now

**Comment by Jermolene** [comment]
Hi @BurningTreeC could you perhaps retrospectively add one for the other palettes you've ported?

**Comment by BurningTreeC** [comment]
@Jermolene, I've ported the "Nord" palette, which has a "license" field pointing to the original MIT license

**Comment by BurningTreeC** [comment]
... same with the "Solarized Light" palette, it also has a license field pointing to the license. Do you think a "credits" field is still needed in those cases?

**Comment by Jermolene** [comment]
Hi @BurningTreeC apologies, in that case we should probably be using the same "license" field for consistency.

**Comment by BurningTreeC** [comment]
Ok @Jermolene, done :smile:

**Comment by Jermolene** [comment]
Thanks for your patience @BurningTreeC

**Comment by BurningTreeC** [comment]
No problem @Jermolene! Thanks for merging!

**Comment by kookma** [comment]
A minor point: 
Testing on https://tiddlywiki.com/prerelease/ the Comment plugin which is an essential one, on this new palette looks great! Except the border color! Is there any way to quickly adjust the border color?
It is light blue.

**Comment by BurningTreeC** [comment]
@kookma - the comments plugin has its own styles built in. this would be a new issue

**Comment by kookma** [comment]
@BurningTreeC 
Okay, so I think this for Jermey to see if the Comment plugin can gets its color from palettes or not!

**Comment by kookma** [comment]
> > Is there any way CodeMirror automatically use the new pallet color?
> 
> No, you need to explicitely add the gruvbox codemirror theme. See the "usage" section of the codemirror plugin for how to add color schemes

Actually it would be great if plugins can get their color from palettes set by user!

By the way I have attached the two gruvbox-dark styles for codeMirror and Highlight.js here! I will also announce this in Forum.


[gruvbox-dark-for-Highlightjs-codeMirror.zip](https://github.com/Jermolene/TiddlyWiki5/files/4325715/gruvbox-dark-for-Highlightjs-codeMirror.zip)

Thank you both of you!

**Pull request merged**
