### PR TITLE
 New filter "recent"

### PR DESCRIPTION
**Pull request by nameanyone**
Select tiddlers where a specified date field (default "modified") is within the last N days (default 0, meaning today).

Discussion at #1854.

### CODE REVIEW

**Comment by felixhayashi** [comment]
Noooooooooooooooooooo waaaaaaaaaay! I was just searching whether such a filter exists and wanted to create an issue that proposes to invent it. and now it is possible? Really great! I'll pull the latest wiki and start testing it :) :)

**Many thanks @nameanyone this feature was highly missing!!**

**Comment by felixhayashi** [comment]
Hi @nameanyone maybe an addition:

This filter has much potential! If this filter was called something like "timedistance" instead of "recent" then we could also negate it to show all tiddlers which have a date that comes after the date specified in the filter e.g. "[!timedistance:due[14]]" (notice the negation) shows all tiddlers that have a due field that has a date that lies within the next 14 days. "[timedistance:created[14]]" shows all tiddlers that were created minimum 14 days ago.

What do you think?

**Comment by nameanyone** [comment]
@felixhayashi  I'd have to check, right now I'm thinking negation is parsed and processed outside of a filter function. Plus, in this particular case it's natural to have negation mean "older than X days", rather than "less than X days in the future".

**Comment by nameanyone** [comment]
Ok, negation is actually a prefix and processed inside a filter function. So yes, I could add it. How about something like this:

days[-7] - modified within last 7 days
days:due[7] - due within 7 days from now
!days[-7] - modified more than 7 days ago
!days:due[7] - due in more than 7 days from now

I think having "time" in the name would be misleading when in actuality time (hours and less) gets truncated.

**Comment by felixhayashi** [comment]
Really creative, never thought about negative numbers but this is actually quite intuitive. I like your suggestions.

> I think having "time" in the name would be misleading when in actuality time (hours and less) gets truncated.

I Agree, "days" is the better term.

-Felix

**Comment by nameanyone** [comment]
I'd like to get Jeremy's input before I proceed. @Jermolene, does this make sense, are you ok we add "days" filter? Should I replace "recent" or leave it and add "days"? "days" supercedes "recent" functionally.

**Comment by nameanyone** [comment]
Second thoughts: how do I decide if negation is worth implementing? The same effect can be achieved by a separate Filter Run with a minus sign.

**Comment by felixhayashi** [comment]
> The same effect can be achieved by a separate Filter Run with a minus sign.

Hmm this is true...

**Pull request merged**
