### PR TITLE
Misc. small fixes

### PR DESCRIPTION
**Pull request by heronils**
... found while skimming through a diff.

### CODE REVIEW

**Comment by pmario** [comment]
lgtm

**Comment by Jermolene** [comment]
Thank you @heronils. Please could you make a PR that targets the "tiddlywiki-com" branch so that the changes are published immediately.

**Comment by heronils** [comment]
@Jermolene could you point me in a direction how to do this?

**Comment by heronils** [comment]
ah i think know what you mean.

**Comment by heronils** [comment]
Ok, i actually need help @Jermolene . When i select base: `tiddlywiki-com` instead of `master` from the drop down of your repo in the PR b GUI, then i get:

```
Can’t automatically merge. Don’t worry, you can still create the pull request. 
```

But when i did this last time, #4338 happened (Sorry about this). As @Arlen22 had this too (#3854), could it be that something is misconfigured on your side?

**Comment by heronils** [comment]
PR_cant_merge

**Comment by heronils** [comment]
F it, im just trying it again.

**Comment by heronils** [comment]
Wait, no.

On `https://github.com/Jermolene/TiddlyWiki5/compare/tiddlywiki-com...heronils:fixes?expand=1`
i see tons of commits below the text entry, and my four are at the bottom. Is this normal? Is this a 'PR that targets the "tiddlywiki-com" branch'?

Irritating.

**Pull request closed without merging**
