### PR TITLE
Updated release notes

### PR DESCRIPTION
**Pull request by saqimtiaz**
Hope this helps @Jermolene

### CODE REVIEW

**Comment by Jermolene** [comment]
Great thanks @saqimtiaz is it now up to date?

**Comment by saqimtiaz** [comment]
@Jermolene I got all the filter changes and few others as well by going through the PRs that have been closed. 

It would still be worth going the commit history to see if there is anything to add that didn't have an associated PR.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz I usually update the release note by tracking through the commit history, scrolling back to the last commit message mentioning "release notes", and then working forwards.

**Comment by saqimtiaz** [comment]
@Jermolene I can take a look at the commit history as well later today.

**Comment by Jermolene** [comment]
Marvellous, thank you @saqimtiaz

**Pull request merged**
