### PR TITLE
Master

### PR DESCRIPTION
**Pull request by le-pako**
Created svg icons, empty and filled. Usable for carousel for instance.

### CODE REVIEW

**Comment by pmario** [comment]
hi Francisco,
It would be nice, if you could add an image, so we can see how your svgs look like. (For those who are lazy :)

The usual way to create PRs is to create a feature branch from master and then create a pull request. 
So in the history graph your PR can be seen. If you directly pull from master, this is not possible. .. 

The way I create PRs is: 

```
git checkout master
git pull jermolene master
git checkout -b new-feature-branch
```

make changes to the branch

```
git add .
git commit -m "some useful description"
git push origin new-feature-branch
```

and create a pull request from there. 

My remote branch settings look like this. So "jermelone" is the alias for upstream. This may be different to your settings. So adjust the commands above to your settings. 

```
$ git remote -v
jermolene       https://github.com/Jermolene/TiddlyWiki5.git (fetch)
jermolene       https://github.com/Jermolene/TiddlyWiki5.git (push)
origin  git@github.com:pmario/TiddlyWiki5.git (fetch)
origin  git@github.com:pmario/TiddlyWiki5.git (push)
```

**Comment by Jermolene** [comment]
Hi @le-pako thanks.

On a matter of policy, the icons that are included in the core are generally those that are needed by the core itself. I don't think we should turn the core into an icon library. Rather, I'd like to see the availability of bundles of icons as plugins.

So, if you think you might be interested in producing more icons, perhaps it might be better to do a pull request for a new `tiddlywiki/icons` plugin?

**Comment by le-pako** [comment]
Hi Mario,

thanks for your feedback and instructions. Sorry for messing up. I'm quite
unfamiliar with Github, so I'm not sure how to add an image: how would you
do? Wouldn't it be pulled with the other changes?

For the branch topic, as a newbie I don't master yet the concepts (and
consequences) between master, branches and commits. :( I thought my master
was distinguishable from Jeremy's. I use the Github app to keep it simple
(I prefer not to get into terminal commands), but the interface is not so
clear on these points.
Anyway I'll remember to create and work off of a custom branch and not a
master.

My apologies if I'm not causing trouble, it's not my intention.

Cheers

**Comment by le-pako** [comment]
Hi Jeremy,

thanks for taking the time to look at my pull request. You must be busy and
my contributions so far have been of marginal value.
I'm learning through trying to build plugins. I planned on bundling my
icons, but these seemed so basic I thought they should be built-in. Having
them in a dedicated plugin would be a more flexible way (specially to
lighten the core). I'll have to see how to create or contribute to such
pull request.

Also I'm by no means an expert on icons :) that's why I use and love
Font-Awesome. However I steer away from dependencies.

Cheers

**Comment by pmario** [comment]
>...so I'm not sure how to add an image: how would you
do? Wouldn't it be pulled with the other changes?

You can create a small screenshot, depending on your OS it can be .gif or .png. Just drag and drop it from the file explorer to this github edit area. .. It will be uploaded and displayed only here in the PR. So there is no need to make it part of the PR.

**Comment by pmario** [comment]
>... For the branch topic, as a newbie I don't master yet the concepts (and
consequences) between master, branches and commits. :( I thought my master
was distinguishable from Jeremy's.

It is distinguishable form Jeremy's master but it will be easier and imo less error prone for others to pull your branch and test it. see: https://github.com/Jermolene/TiddlyWiki5/network how it looks like.

**Comment by pmario** [comment]
> ... I use the Github app to keep it simple
(I prefer not to get into terminal commands), but the interface is not so
clear on these points.
Anyway I'll remember to create and work off of a custom branch and not a
master.

If you use the windows app, imo it's not possible to create branches. ... So in the long run the command line should be an option :/

>My apologies if I'm not causing trouble, it's not my intention.

We highly appreciate any kind of feedback and PRs are even more valuable. So just keep them coming and be prepared, that not everything will be merged ;)

I did create a series of videos for github, github for windows and how to work with TW but I didn't upload them yet :/ So I'll post the links here, so you'll get notifications or you can subscribe to my [yt-channel]( https://www.youtube.com/user/pmariojo/feed)

**Comment by Jermolene** [comment]
Hi @le-pako 

> My apologies if I'm not causing trouble, it's not my intention.

Not at all, Git is mind-bendingly complicated, and we've all had to struggle to learn it. It's still the one piece of software that I use regularly that regularly makes me feel stupid!

Helping each other in a public forum like this is beneficial because everyone gets to see the dialogue, and can learn from it.

> thanks for taking the time to look at my pull request. You must be busy and my contributions so far have been of marginal value.

Actually, I suspect everyone wants to land big, dramatic pull requests that implement long requested missing features, but the fact is that a good flow of minor tweaks and fixes are essential to keep the project healthy. Making and accepting a simple pull request can be pretty swift, and I always appreciate the attention to detail and perfectionism that drives them.

**Comment by sukima** [comment]
I found the following video changed my git-fu from beginner to advanced! It's dry but well worth it. Once I realized git was just pointers it was a breeze to understand the commands:

https://www.youtube.com/watch?v=1ffBJ4sVUb4

**Comment by le-pako** [comment]
Thanks a lot guys! I'm starting to get a better picture now. 

@pmario 
Here's a snapshot of the suggested icons. I'll just bundle them in my plugin for now.
circle-icons

>If you use the windows app, imo it's not possible to create branches atm. ... So in the long run the command line should be an option :/

The Mac app does support it :) It buys me some time before the dreaded terminal... :smile: 
Also, I'm checking again your howto videos and it makes more sense now...
@sukima Thanks for the pointers, I'll view these when I get a chance

Cheers

**Comment by Jermolene** [comment]
> The Mac app does support it :) It buys me some time before the dreaded terminal... :smile: 

I use the GitHub Mac app for all my day to day gitting (apart from merging pull requests which I do using the web interface). With Git, if I need to do anything on the command line I generally rely on Google to remind me of the magic incantations.

**Comment by tobibeer** [comment]
this can be closed, I think

**Comment by pmario** [comment]
@Jermolene ... IMO it was agreeable to create additional and unused icons as plugins. imo should be closed.

**Comment by Jermolene** [comment]
Thanks @pmario

**Pull request closed without merging**
