### PR TITLE
Merge pull request #1 from Jermolene/master

### PR DESCRIPTION
**Pull request by EdDixon**
update

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @EdDixon this pull request is empty, I'm guessing because you're finding your feet with GitHub! Don't worry, it does become clearer eventually -- although I don't think I could use Git if Google didn't exist...

**Comment by EdDixon** [comment]
RIght, was simply attempting to update my repo which was a few months behind with no changes not sure what went worng on this end but will walk through it again here thanks :)

**Comment by pmario** [comment]
Hi Ed. I did create 3 short videos, that may help you. https://www.youtube.com/playlist?list=PLuiC_HFhI4OyfLdEqdK4lkFpFJLI4NrKo  ... 

It doesn't show, how to update an outdated branch. So your master is the same as Jeremy's master. ... I did have a look at the process, as I did the first series. .. but the mechanism with the web UI was too complicated. ... But since then, the web ui chnaged a lot. so may be I should have an other look :)

**Comment by EdDixon** [comment]
@pmario  I agree, and they seem to have changed some of the merging features available thorough the site here since I last used it. I may have been trying to get 2 birds with one stone, in an attempt to add my name to the contributors list per the contributing.md while also getting the merge I need to get me up to date. Since 5.1.10 was just announced, I am going to refresh the entire repo on my side and start from scratch cloning locally here and then simply push what I have to my own fork and the official repo when I have anything I think might be PR ready. @Jermolene do expect a PR for my addition to the contributors list ASAP and let me know should the be any issues. It is important that I am doing this as an individual and not as a part of any of the other projects I hope to integrate with.  Thanks,

**Pull request closed without merging**
