### PR TITLE
has:field — tested & documented

### PR DESCRIPTION
**Pull request by tobibeer**
implements #2065, allowing to filter by whether a field exists or not via `has:field[some-field]`, rather than whether both field and value are both set using a plain `has[some-field]`.
## Demo

http://2065.tiddlyspot.com

### CODE REVIEW

**Comment by tobibeer** [comment]
@Jermolene, it would be great if you can perhaps merge filter related PR's more timely so as to avoid merge conflicts over filter tests or even failing tests.

I'm inclined to make another filter related PR for a new [count](http://count.tiddlyspot.com) filter I just created.

**Comment by Jermolene** [comment]
Please can you tag the documentation with the version

**Comment by Jermolene** [comment]
Add `has:value`, make `value` be the default suffix.

**Comment by tobibeer** [comment]
@Jermolene: added from version to docs

> Add has:value, make value be the default suffix.

Already the case, see docs.

**Comment by Jermolene** [comment]
Hi @tobibeer apologies for the delay

**Pull request merged**
