### PR TITLE
Signing the CLA for @donmor

### PR DESCRIPTION
**Pull request by donmor**
I'm signing the CLA so that I can create a pull request to Jermolene/TiddlyWiki5.

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @donmor thanks -- although my apologies I forgot to add that the PR should target the `tiddlywiki-com` branch. I tried to change the base here but it adds all the intervening commits too, hopefully it'll be easier for you to change it. Many thanks.

**Comment by donmor** [comment]
Branch have been changed



Gosh I almost changed the original PR( #3943 ) to the tiddlywiki-com (:0) I changed the #3943 just on see the mail and changed it back a minute ago

**Comment by donmor** [comment]
Oh no

Now I know what the meaning of "it adds all the intervening commits too" is.

I'd close it and create a new PR instead

**Comment by donmor** [comment]
The new PR is #3957

**Comment by sukima** [comment]
When you change the base in github you also need to rebase the branch in your git repo! I am guessing by the branch name (`patch-1`) that you used the GutHub GUI instead of the typical git clone workflow. Sigh, looks like GutHub strikes again. This is why I personally prefer desktop apps (or command-line) over whack-a-do website editors. Sorry there!

**Comment by Jermolene** [comment]
Many thanks everyone.

**Pull request closed without merging**
