### PR TITLE
preventDefault drag behaviour inside textarea

### PR DESCRIPTION
**Pull request by BurningTreeC**
fixes errors when trying to drag inside textarea while an eventhandler is listening for drag events

### CODE REVIEW

**Comment by Jermolene** [comment]
That's great, thank you @BurningTreeC. I notice that you haven't yet signed the CLA; could you please send a separate PR with your signature (see contributing.md in the root of the repo). Many thanks, and apologies for the bureaucracy

**Comment by BurningTreeC** [comment]
thanks @Jermolene,
this is a quick fix, but I'd like to have it like the standard editor which is handling it perfectly. I just couldn't figure out how

**Comment by Jermolene** [comment]
We should probably update to the latest version of CodeMirror...

**Comment by BurningTreeC** [comment]
that would be great

**Pull request merged**
