### PR TITLE
pt-PT translation update

### LINKED ISSUE #2620: Portuguese translation has wrong DateFormat
When you install the Portuguese language years show as "AAAA" and time of edit is displayed in English format.

### PR DESCRIPTION
**Pull request by nmota**
pt-PT Language translation update.
Also fixes #2620.

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @nmota thanks for this, and apologies for the delay. Please could you sign the CLA as described in CONTRIBUTING.md in the root of this repo? Many thanks!

**Comment by nmota** [comment]
Done, and thank You!

**Comment by pmario** [comment]
@Jermolene if you accept the CLS from this PR.   the PR  #2622  should be closed. since it is a dupe now.

**Comment by Jermolene** [comment]
My apologies @nmota for asking you to sign the CLA twice!

**Comment by Jermolene** [comment]
Thanks @pmario btw!

**Pull request merged**
