### PR TITLE
Fix typo in release notes

### PR DESCRIPTION
**Pull request by rmunn**

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @rmunn much appreciated. Could I ask you to kindly sign the Contributor License Agreement (see contributing.md in the root of this repo), apologies for the bureaucracy!

**Comment by rmunn** [comment]
Signed CLA: https://github.com/Jermolene/TiddlyWiki5/pull/3991

**Comment by rmunn** [comment]
And don't worry about the bureaucracy aspect; I'm a software developer myself, so I completely understand the need to be careful about licenses and copyright assignment. :-)

**Comment by rmunn** [comment]
Signed again, in the right branch this time, in #3992.

**Comment by Jermolene** [comment]
Thanks @rmunn

**Pull request merged**
