### PR TITLE
Update GettingStarted.tid

### PR DESCRIPTION
**Pull request by zakrec**
Polish translation

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @zakrec thanks for the contribution.

It looks like you are translating the content of the documentation portion of http://tiddlywiki.com itself. It may make sense to work on a translation of the user interface of TiddlyWiki first, to produce a language plugin for Polish. In the case of a few languages we do have translations of the tw.com documentation (notably German and French), but they are a much, much bigger job than just translating the user interface.

If you're interested in working on a Polish language plugin there are a couple of different approaches, one entirely [based in the browser](http://tiddlywiki.com/#Translate%20TiddlyWiki%20into%20your%20language), and one [based on Node.js](http://tiddlywiki.com/dev/#How%20to%20create%20a%20translation%20for%20TiddlyWiki).

@pmario can advise on creating a Polish edition of the TiddlyWiki documentation. Essentially, it involves sending a pull request that sets up `editions/pl-PL`. But as I say, it makes more sense to work on the language plugin first.

Finally, please could you send a separate pull request to sign the Contributor License Agreement, as described in [contributing.md](https://github.com/Jermolene/TiddlyWiki5/blob/master/contributing.md). Many thanks!

**Comment by twMat** [comment]
@zakrec - do you have anything to add to @Jermolene 's comments?
If not, and if this will not be picked up on by anyone else, then I suggest we close this PR.

**Comment by pmario** [comment]
@zakrec ... see: https://tiddlywiki.com/#Translate%20TiddlyWiki%20into%20your%20language

@Jermolene ... This PR may be closed, since it can't be merged as it is.

**Comment by Jermolene** [comment]
Thanks @pmario

**Comment by ght** [comment]
Was this intentionally reopened?

**Comment by Jermolene** [comment]
Hi @ght it looks like I reopened it in error, apologies for the confusion.

**Comment by ght** [comment]
No worries, that's what I guessed. I was just browsing old open issues and open PRs looking for some low hanging fruits to start contributing :)

**Comment by Jermolene** [comment]
Hi @ght great, don't hesitate to ask questions, or for help.

**Pull request closed without merging**
