### PR TITLE
New fr_fr Macro Calls in WikiText (Examples).tid

### PR DESCRIPTION
**Pull request by idoine**

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @idoine are #1821 through #1836 all still relevant after the big commit from @xcazin?

**Comment by idoine** [comment]
I thought you wait an agrement from Xavier, so I try to give him all my past pull request.

**Comment by xcazin** [comment]
@idoine, can you elaborate a bit on this? Are your pull requests #1821 to #1836 redundant with #1841 ?

**Comment by idoine** [comment]
yes it was redundant. Sorry

**Comment by idoine** [comment]
I confirm. The 1841 contains every modified tiddler with the lasted modifs.

**Comment by Jermolene** [comment]
Thanks @idoine I'll close #1821 to #1836

**Pull request closed without merging**
