### PR TITLE
Trim Saga: whitespace trimming three big tiddlers

### PR DESCRIPTION
**Pull request by flibbles**
Here are the three biggest files which benefit from whitespace trimming.

My later PRs will include more files per pull, but these ones were big, and took a lot of walking through.

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @flibbles in the light of the imminent release of v5.2.1 as discussed in #6259, we need to hold off merging the rest of these until the following release. I've added this ticket to #6266 where I'm collecting issues for that release.

**Comment by Jermolene** [comment]
> Sure thing. Would you like me to hold off on creating any new PRs for trimming?

I think that whatever is easiest for you will be fine, thank you. It's certainly no problem to let them pile up, and in the meantime they can be reviewed by others too.

**Comment by flibbles** [comment]
...And maybe this one too?

**Comment by Jermolene** [comment]
Thanks @flibbles

**Pull request merged**
