### PR TITLE
Make AdvancedSearch/Filter navigatable by keyboard

### PR DESCRIPTION
**Pull request by BurningTreeC**
This PR makes the AdvancedSearch/Filter Tab navigatable like the other three Tabs (Standard, System and Shadows)

### CODE REVIEW

**Comment by BurningTreeC** [comment]
@Jermolene - this is ready to get merged

**Comment by BurningTreeC** [comment]
@Jermolene - no this isn't yet ready. I'll make it ready this evening

**Comment by Jermolene** [comment]
Hi @BurningTreeC it looks like the state tiddler used for storing the search text is still being changed. Is that necessary?

**Comment by BurningTreeC** [comment]
Hi @Jermolene ,

>it looks like the state tiddler used for storing the search text is still being changed. Is that necessary?

If you refer to `$:/temp/advancedsearch/input` then yes, it's a necessary change

But if this gets merged I can have another look at all the AdvancedSearch search-tabs and see if I can make the searchTiddler being `$:/temp/advancedsearch` again

**Comment by Jermolene** [comment]
Hi @BurningTreeC I'm afraid that that is a breaking change: we have dependencies on the existing title elsewhere in the core, and can expect end users to do so too. Can we address it before merging?

**Comment by BurningTreeC** [comment]
@Jermolene - yes I'll make the necessary changes so that it uses `$:/temp/advancedsearch`

**Comment by BurningTreeC** [comment]
@Jermolene - this PR is now ready. I've changed it so that it uses `$:/temp/advancedsearch` again as the main filter-tiddler/search-tiddler (also for the other AdvancedSearch search-tabs)

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Comment by BurningTreeC** [comment]
Thanks @Jermolene - I'd like to create a follow-up PR but would like to hear your opinion about a detail:

The AdvancedSearch/Filter Tab when pressing <kbd>Escape</kbd> (after some items were selected by up/down) first resets the input field to the filter. Then when pressing <kbd>Escape</kbd> again, it clears the input field.

I'd like to make this behavior the default for all keyboard-driven-inputs... What do you think?

**Comment by Jermolene** [comment]
Hi @BurningTreeC I think that sounds reasonable. Would the second time escape is pressed lead to the dropdown being removed too?

**Comment by BurningTreeC** [comment]
>Would the second time escape is pressed lead to the dropdown being removed too?

Yes, @Jermolene

**Comment by Jermolene** [comment]
Hi @BurningTreeC that's great, and worth doing I think.

**Pull request merged**
