### PR TITLE
just fixes list filter, no further refactoring

### PR DESCRIPTION
**Pull request by tobibeer**
Previously did not correctly handle / match the source but only output the list as is.

replaces https://github.com/Jermolene/TiddlyWiki5/pull/1419

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @tobibeer

**Comment by Jermolene** [comment]
@tobibeer @aelocson does this need any docs updates?

**Comment by Jermolene** [comment]
@tobibeer it turns out that there is a problem with this change. What steps did you take to test it?

The immediate problem is that it causes the main story river to display in reverse order.

**Comment by aelocson** [comment]
This modification causes the titles in the `list` field to be reordered to match the order of the input titles. It also has other strange effects, such as making the Advanced Search button in the sidebar do nothing. Presumably this means that several things in the core rely on the old behaviour.

The aim seems to be to make `list` behave more like `!list`, but that's a flawed goal: `!list` doesn't care about the order in which it removes input titles, but it leaves the order of the remaining titles unchanged.

It's already possible to obtain the intersection of the input titles with those in the `list` field, by using the `+` prefix on a filter run.

**Comment by tobibeer** [comment]
need to investigate more

**Comment by tobibeer** [comment]
Essentially, this one of the cases where `A` and `!A` do not at all form a whole but instead model entirely independent things.

The basic list filter defines a set irrespective of the input, whereas negation works modifying on the input list.

Possibly, what is now `[list[]]` should rather have been `[get:list[]]`.

While not respecting set theory is deeply confusing, I'm afraid it is going to stay that way without any acceptance / inclinations for implementing more sensible and comprehensive paradigms ...which will sure have consequences and need more adjustments than I had considered ...which, however, seem worthwhile and necessary to me, but are possibly too fundamental for most everyone else.

I'd really love to avoid that log for inconsistencies or ways to scratch items off that list, but I guess there's no way around it.

**Comment by Jermolene** [comment]
> which, however, seem worthwhile and necessary to me, but are possibly too fundamental for most everyone else.

I really think that the best answer to frustrations with the filter syntax is to make it possible to have pluggable alternative filter languages (this has come up on a few recent hangouts). Then we can explore incompatible alternatives more easily. I'm particularly interested in adopting an existing language like LISP or FORTH. (Note that I don't mean specifically LISP and FORTH, I mean languages that are like them :smile:)

**Pull request merged**
