### PR TITLE
Added ActionSendMessageWidget

### PR DESCRIPTION
**Pull request by danielo515**
Added ActionSendMessageWidget to the list of possible message emiters on edit-tiddler message

### CODE REVIEW

**Comment by danielo515** [comment]
Mmm, maybe it's not necesary to include the ActionSendMessageWidget since it is mentioned on the button documentation. I find it more clear this way, but it is up to you

**Comment by Jermolene** [comment]
Thanks @danielo515 I think that is clearer.

**Comment by danielo515** [comment]
Thanks Jeremy,

Then should I proceed to update the rest of tm-messages?

**Comment by Jermolene** [comment]
Hi @danielo515 

> Then should I proceed to update the rest of tm-messages?

Yes, great, thank you.

**Pull request merged**
