### PR TITLE
retrieves url from connectionTiddler for modal to AddPlugins

### PR DESCRIPTION
**Pull request by tobibeer**
* concerns: **$:/core/ui/ControlPanel/Modals/AddPlugins**
* the current code would otherwise fail when using a custom global tab template
* also uses variable to simplify template

## Context

* [discussion](https://groups.google.com/d/msg/tiddlywiki/UAHlzJrZB5c/JEk3z1VTEQAJ) regarding using [tobibeer/inc](http://tobibeer.github.io/tw5-plugins/#inc) to quick-edit tab-contents with a custom tabs macro that allows to use a custom global tabs template

### CODE REVIEW

**Comment by tobibeer** [comment]
Possibly, this is not fixing whatever my original issue was. Will need to investigate more.

**Comment by tobibeer** [comment]
Ok, this appears to work as intended now. Fixed the install button `url` reference as well.

**Comment by tobibeer** [comment]
@Jermolene: May I ask why this was closed? Perhaps you mistook my last comment as "it's all good in the core now" whereas I was referring to the PR?

**Comment by tobibeer** [comment]
@Jermolene, for all I know, this fixes an issue (at least for me) while not creating another.

From what I remember, it only works in the core, because the tiddler accidentally looks at the right tiddler... which it no longer does when using a [custom tabs template](http://tobibeer.github.io/tw5-plugins/#Quick%20Edit%20Tabs) (which I would like to see in the core).

**Comment by Jermolene** [comment]
Hi @tobibeer I don't recall closing this issue, but I guess I did indeed misinterpret your comment.

I'm not sure that I understand what this PR is trying to fix though. What is a "custom global tabs template"?

**Comment by tobibeer** [comment]
> What is a "custom global tabs template"?

A "custom global tabs template" is a modification to the tabs macro that allows to specify a custom template to be used for the tabs contents, globally. So you can define how you want tab contents to render, by default.

However, that requires for this particular **url** field to be read from a specific tiddler other than "currentTiddler", in this case the "connectionTiddler", since the former appears to change due to using a template for tab contents.

**Comment by tobibeer** [comment]
In other words, we're not losing anything here. Instead, we simply increase specificity a little bit as to where the **url** field is to be read from.

**Pull request closed without merging**
