### PR TITLE
Replace \s\s* with \s+ in regex

### PR DESCRIPTION
**Pull request by BlueGreenMagick**
Which achieves the same thing
\* is the 0 or more quanitifier
\+ is the 1 or more quantifier

### CODE REVIEW

**Comment by pmario** [comment]
Please check your markdown text. IMO not everything is rendered as expected here.

**Comment by BlueGreenMagick** [comment]
Thanks, didn't notice that. Fixed!

**Comment by simonbaird** [comment]
This should be an instant merge IMO. What's the blocker?

**Comment by simonbaird** [comment]
Oh, is it because [the blog post|https://blog.stevenlevithan.com/archives/faster-trim-javascript] says that \s\s* is faster?

That post if from 2007, so I very much doubt it's still relevant. Also I doubt the performance deltas would be noticable in any practical way.

**Comment by simonbaird** [comment]
The benchmarks are Firefox 2 and IE 6...

**Comment by Jermolene** [comment]
Hi @BlueGreenMagick @simonbaird @pmario apologies I missed this. Indeed we'd need more rationale before merging this. Otherwise we'll spend the next 20 years explaining to people why we use regexps wrong.

**Comment by pmario** [comment]
FireFox 88 (latest) got some really cool extensions to regexp matching indexes. see: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/88#javascript and: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec Indices!

**Comment by BlueGreenMagick** [comment]
No need to change what is working I guess!

**Pull request closed without merging**
