### PR TITLE
Convert newline to LF style

### PR DESCRIPTION
**Pull request by araname**
Convert line endings to LF style ("\n") to ensure consistency in repository.

### CODE REVIEW

**Comment by pmario** [comment]
git will do this automatically. So IMO there is no PR needed. If I check out your source in windows, git will auto add them again.

**Comment by pmario** [comment]
also see: https://help.github.com/articles/dealing-with-line-endings/

**Comment by araname** [comment]
I'm already set core.autocrlf to input. My changes are needed to use several platform.

**Comment by sukima** [comment]
Why, line endings should not be an issue in HTML/JavaScript. What editor are you using that can't handle alternative line endings?

When you perform a git clone does it not use `\n`? It does on mine (tested in Ubuntu and MacOS X).

**Comment by pmario** [comment]
>I'm already set core.autocrlf to input. My changes are needed to use several platform.

I'm using win10 and ubuntu 16.04 atm. No changes needed for me.

**Comment by sukima** [comment]
To add some context we had a large project just like this at work. One of our main contributor to the project swapped between Windows and Mac. One day he upgraded his IDE and asked it to _auto-format_ the sources. This resulted in every file changing it's indentation style and end of lines. He added the entire change as one commit and called it **whoo boy!**. 5 years later we are still burned by this commit. Every `git bisect` or `git log` always finds it's way back to that _whoo boy_ commit. It is infuriating!

I even when so far as to research how to [migrate git histories](https://developer.atlassian.com/blog/2015/08/grafting-earlier-history-with-git/) but we decided to just live with it.

In another project we had mixed styles and instead of one big commit we simple leave the files as is. When we go to work on a specific file we do one commit that fixes the style for that one file then continue. This way `git bisect` and `git logs` make sense and are easier to grok.

I'd suggest we adopt a policy on style and when a pull request is presented who ever is doing the merge would append one final style fixing commit at the end and then merge. Eventually all files will be using the same style guides. Now code should follow the same style guides.

**Comment by pmario** [comment]
I did have a little closer look to the source code files. It seems to be mainly in `languages/sv-SE/` directory. So we should try to find the source of windows endings.

**Comment by pmario** [comment]
It seems they are there since the beginning. https://github.com/Jermolene/TiddlyWiki5/commits/master/languages/sv-SE So @Jermolene How did you get those files?

Somehow, we need to fix this. .. I thought git would ..

**Comment by Jermolene** [comment]
Hi @pmario 

> How did you get those files?

@SuperDOS, the original translator, was having difficulties with GitHub and so sent me a ZIP of the translated files which I then added to the repo. Presumably they were created on Windows.

**Comment by sukima** [comment]
I've always wanted to know what it is about GitHub that makes it _difficult_ for people. I find Facebook to be about 1000 times more difficult than GitHub and I usually never hear someone complain about Facebook. ¯\\\_(ツ)\_/¯

**Comment by SuperDOS** [comment]
yes edited with notepad++ on windows a while back.

**Comment by pmario** [comment]
@sukima 
There are only language files and 2 js files files in this PR:

https://github.com/araname/TiddlyWiki5/commits/6deb4014e58a707e5ac35416b96f6d72255564ab/plugins/tiddlywiki/xmldom/files/sax.js

https://github.com/araname/TiddlyWiki5/commits/6deb4014e58a707e5ac35416b96f6d72255564ab/plugins/tiddlywiki/xmldom/files

The js files have been initially included by Jeremy at Feb. 1st (see the links). The next commit is from @araname. So I think we should have no problems with bisect. 

@Jermolene 
You did use your MAC to import the stuff. -- commit -- push -- without editing the files. right. 
That would be a reason, why the windows endings slipped in. 

**So from my point of view, we should merge the PR.** .. From then on, git should take care of the line endings again.

**Comment by pmario** [comment]
just as a reference. some git settings that should work for windows users. http://stackoverflow.com/a/33424884

**Comment by araname** [comment]
I only convert for files 'languages/fr-FR/ThemeTweaks.multids' and 'languages/ko-KR/ThemeTweaks.multids'

**Comment by araname** [comment]
I converted for tiddlers about languages.

**Comment by pmario** [comment]
@Jermolene ... IMO this one can be closed, since it is no tiddlywiki problem. git can be (and is) adjusted, to do the right thing

**Comment by Jermolene** [comment]
Thanks @pmario

**Pull request closed without merging**
