### PR TITLE
Make Chinese simplified translation more localized

### PR DESCRIPTION
**Pull request by oflg**

### CODE REVIEW

**Comment by oflg** [comment]
Thanks @BramChen, I've been using your translations. 
Here I some translations changed to a more simplified Chinese usage.

**Comment by linonetwo** [comment]
LGTM, but this means later @BramChen  can't help us update the simplified Chinese translation like before?

**Comment by oflg** [comment]
> LGTM, but this means later @BramChen  can't help us update the simplified Chinese translation like before?

I'm just doing some side work, and BramChen can certainly do the same as before.

**Comment by BramChen** [comment]
Many thanks @linonetwo, @oflg 

>
> I'm just doing some side work, and BramChen can certainly do the same as before

ACK @oflg

**Comment by Jermolene** [comment]
Thanks @BramChen @linonetwo @oflg

**Pull request merged**
