### PR TITLE
Overhaul the filter operator documentation

### PR DESCRIPTION
**Pull request by aelocson**
This is a big piece of work, with changes in a scary number of files. However, all the changes are in `editions/tw5.com/tiddlers`, and all but a few ancillary knock-on changes are to files in `.../tiddlers/filters`. No JavaScript has changed, but I've added a trivial JavaScript macro in `.../tiddlers/system/if-macro.js` to achieve conditional formatting in tables.

The changes are basically rewrites of all the filter operator tiddlers. I've tried to make the presentation as straightforward, logical and consistent as possible, making use of some new power macros in `.../tiddlers/system/operator-macros.tid`. The examples for each operator have been split out into their own tiddlers, to keep the reference tiddlers uncluttered. The examples are all now interactive, with a `Try it` button on each. And as far as possible, I've adjusted the examples so that they relate to tiddlers that are actually present on tiddlywiki.com. I've added tiddlers for the days of the week to make it easy to illustrate operators like `before`, `first` and `next`.

I've split the Filter Syntax tiddler into several smaller tiddlers – one for each level of the syntax – and there are now lots of links to those smaller tiddlers. I've added new railroad diagrams in `all.tid` and `regexp.tid` to clarify idiosyncrasies of their syntax. (Note that I've also sent pull request #1390 with significant improvements to the railroad plugin. I don't think anything in this documentation pull request depends on #1390, though.)

The Filter Operators tiddler now includes a table all of the operators with a brief description of their purpose, making it easier to quickly scan through for the one you want. I've arranged many of the operators in the table into four distinct groups, leaving the miscellaneous remainder at the top of the table (as they're actually some of the most common ones).

As part of this overhaul, I've introduced a few new pieces of terminology with accompanying concept tiddlers for most of them:
* absolute and relative operators
* dominant append – i.e. what `$tw.utils.pushTop` does
* hard and soft links
* input and output of a filter step
* title selections – i.e. what the input and output of a filter step are – a filter step basically "selects" titles, so I think it makes sense to refer to the output (and hence also the input) as a "selection"

I've moved "order of tagged tiddlers" – i.e. the rules for `list-before`, etc – to its own tiddler. Previously it was buried at the bottom of the Tagging tiddler.

There are also a few minor related tweaks to the documentation style guide.

And that's that :)

### CODE REVIEW

**Comment by aelocson** [comment]
A convenient preview of these changes can be seen at http://ae-doc-preview.tiddlyspot.com/

**Comment by tobibeer** [comment]
@aelocson, this is great work in all regards, content, presentation, structure!

Some feeback...

> At least one [whitespace](http://ae-doc-preview.tiddlyspot.com/#Filter%20Whitespace) character must appear between each run of a filter expression.

This does not appear to be true, try `{{{[[a]][[b]]}}}`.

~

As for the examples, not sure if they should be individual tiddlers. Do you want this paradigm throughout the documentation? I sure see the practicality in this, but it will quite increase the number of tiddlers in the long run... perhaps for the better. It makes it sure easier to get a long list of all examples. In other words the tiddler "Operator Examples" shouldn't really be non-existing.

For purposes of aggregation, I would put the **Try It:** button right before each filter expression rather than below. I also think each example should have an explanatory line.

~

When I look at **sameday Operator** I see some cryptic parameter symbols *f* and *d*? Why is that? I find them a little confusing. How do they help?

~

As for presenting those filter parameters, doesn't it make more sense to put the parameters into tiddler fields and then have a conditional template show the table, rather than invoking some custom macro in each single one? Another benefit would be that you can easily query against those tiddlers, e.g. "which use a suffix?"

~

Considering #1405, I never even noticed there were **butfirst**, **bf**, or **rest**. I really don't understand why there have to be three filter operators literally crowding and overwhelming the namespace like that. I think it a poor practice which should be avoided. Other than that, concerning #1405 is there a usecase where you would want an offset without a limit? I would actually vote for deprecating the above three.

~

Anyhow, with those unfortunate aliases, I think the documentation of each should always transclude one master, e.g. **rest** in all the aliases, rather than point there.

**Comment by aelocson** [comment]
Hi @tobibeer, and thanks for this extremely helpful feedback.

> This does not appear to be true, try {{{[[a]][[b]]}}}.

Absolutely right, and I spotted that myself earlier this morning. Check my commits on my pull request, and you'll see I've already corrected this mistake.

> As for the examples, not sure if they should be individual tiddlers. I prefer they wouldn't be.

Why, though?

It might perhaps make sense to *transclude* each example tiddler into the corresponding main tiddler. One reason I didn't do that was it made several of the main tiddlers very cluttered. Another reason was that transclusion can make search results confusing – the search would find only the standalone example tiddler, which would be annoying if the user had grown used to thinking of the examples as an integral part of the main tiddlers. So it seemed clearer to split them out explicitly.

> it will quite increase the number of tiddlers in the long run... perhaps for the better.

It's also in keeping with the [philosophy of tiddlers][] as stated on tw5.com.

[philosophy of tiddlers]: http://tiddlywiki.com/#Philosophy%20of%20Tiddlers

> In other words the tiddler "Operator Examples" shouldn't really be non-existing.

Agreed. And, in accordance with your parent–child tagging technique, `Operator Examples` should have the tag `Examples`. But let's go one step at a time. We can do this iteratively.

> For purposes of aggregation, I would put the **Try It:** button right before each filter expression rather than below.

I think that would make things less clear once the user had clicked the button and it had changed to a `Hide` button. It would look as if the button were a toggle for the entire example, rather than just for the results.

I did initially briefly try putting the button on the right-hand end of each example expression, but it looked inconsistent, because the expressions are all different lengths. But maybe floating it over to the right margin would work.

> When I look at **sameday Operator** I see some cryptic parameter symbols *f* and *d*? Why is that? I find them a little confusing. How do they help?

They keep the rest of the text simple and concise, by allowing it to say things like "field *f*" instead of "the field whose name is specified as the operator's parameter". I've done that throughout the operator documentation, not just for **sameday**.

> Doesn't it make more sense to put the parameters into tiddler fields and then have a conditional template show the table, rather than invoking some custom macro in each single one?

That's a very good idea. The only drawback is that the search would fail to find the text if it was in fields. But it'll already fail to find quite a lot of the text, given that some of it's tucked away in the macro definition. So yes, I think you're right. But I'll wait for @Jermolene's response before I go ahead.

> Another benefit would be that you can easily query against those tiddlers, e.g. "which use a suffix?"

Yes. Excellent. Note to self: keep bearing in mind that TiddlyWiki is a *database*…

> I really don't understand why there have to be three filter operators literally crowding and overwhelming the namespace like that.

Presumably there was originally only one such, and it's been renamed twice, but preserving the old names for backward compatibility.

> Other than that, concerning #1405 is there a usecase where you would want an offset without a limit?

Given the existence of `butlast`, it seems reasonable and logical for `butfirst` to exist, even if you can't think of a use for it just at the moment. Note that `first` and `last` are redundant – they're synonyms for `limit` and `!limit` – but they're perhaps easier to understand.

The slightly irritating thing is that the filter syntax only allows one "real" parameter (if we ignore the suffix). This plethora of slicing operators could otherwise be reduced to a single `slice[from,to]` operator, with negative indices counting back from the end as in JavaScript.

> I think the documentation of each should always transclude one master, e.g. rest in all the aliases, rather than point there.

On the other hand, if two of the synonyms are deprecated (and I don't actually know if they are), you could argue that by making it slightly inconvenient to get from a deprecated one to the preferred one, we're encouraging use of the preferred one.

I'm not fully convinced that using transclusion as an alternative to redirection is a good idea. It works fine if the user is going to do nothing but read the tiddlers. But you know what TiddlyWiki users are like – they want to click the edit button, lift the lid, and see how it works. In those cases, transclusions are frustrating. It would be OK if transclusions offered the reader an option to jump to the source tiddler (i.e. as if the transclusion was a clickable link), but they don't.

Ultimately I guess that was another reason why I split the examples out and simply linked to them. It was the least obstructive option from the reader's point of view.

Having said that, you may well be able to convince me :)

**Comment by tobibeer** [comment]
>  did initially briefly try putting the button on the right-hand end of each example expression, but it looked inconsistent, because the expressions are all different lengths. But maybe floating it over to the right margin would work.

I think that's a good idea. The sole point being that for aggregation it would be nice if things were a wee more concise.

> On the other hand, if two of the synonyms are deprecated (and I don't actually know if they are), you could argue that by making it slightly inconvenient to get from a deprecated one to the preferred one, we're encouraging use of the preferred one.

I have a bit of troulbe understanding the nature of the term "deprecated". Does that indicate that the thing is no longer developed / improved or that it will be removed in the future? I always assumed the latter but that never seems to be the case. On the other hand, if these names are aliasas, it cannot be said that those filters are deprecated, at all.

> They keep the rest of the text simple and concise, by allowing it to say things like "field f" instead of "the field whose name is specified as the operator's parameter". I've done that throughout the operator documentation, not just for sameday.

I think the distinct style is meaningful. I can get used to the short names, but they may be scary for people that are not so much into math an symbols. Eventually, they make you jump a little, back and forth between the definition and where they're used. Readable words may make it simpler.

Visually, I find it a distracting to see them in the header column. They come accross as if actual variables, which they're not.

What would you think of...

**suffix** | the name of a *field*
**parameter** | a possible *value* of the *field*

or perhaps

**suffix** | *f* — the name of a field
**parameter** | *s* — a possible value of field *f*

Instead of...

**suffix** ***f*** | the name of a field
**parameter** ***s*** | a possible value of field *f*

perhaps also...

**negation**

instead of

**! output**

~

Thinking of conditional viewteplates, the examples to a filter operator could easily be automatically shown at the very end of the operator tiddler, no markup in the wikitext.

**Comment by aelocson** [comment]
> The sole point being that for aggregation it would be nice if things were a wee more concise.

Agreed.

> I have a bit of troulbe understanding the nature of the term "deprecated".

What meaning did you have in mind when you introduced it into this discussion in your previous comment? You said you "would actually vote for deprecating" `bf`, `butfirst` and `rest`.

I understand a deprecated feature to be one that is no longer recommended. As you say, there can be various reasons for moving a feature to that status, and the term "deprecated" doesn't by itself indicate the reason.

> they may be scary for people that are not so much into math an symbols

Such people are perhaps not the most likely ones to be reading about filter operators! But the use of a placeholder variable to signify an arbitrary member of class is common in many disciplines.

I agree that it would be nice to avoid them here, but the only alternative seems to be a bewildering amount of circumlocution. For examples, see some of the previous filter documentation.

And we can't use the words `suffix` and `parameter` as the variables, because phrases like "the field **parameter**" would be downright misleading.

> **suffix** | the name of a *field*
> **parameter** | a possible *value* of the *field*

That's not bad, but it might get confusing in the subsequent text, beyond the initial table.

> **suffix** | *f* — the name of a field
> **parameter** | *s* — a possible value of field *f*

I'd be happy with that. Or the variable could go to the end, to be less dominant.

> **negation** instead of **! output**

That's what I started with, but then I found a few operators where I needed to split the *input* into two as well, one for **input** and one for **! input**.

> the examples to a filter operator could easily be automatically shown at the very end of the operator tiddler

Yes, they could. I'm still in two minds as to whether transcluding the examples is better than linking to them.

**Comment by tobibeer** [comment]
> I understand a deprecated feature to be one that is no longer recommended.

Mhhh, but it keeps lingering around. I see.

> That's what I started with, but then I found a few operators where I needed to split the input into two as well, one for input and one for ! input.

I am pretty sure that whenever you tried to document that "feature" you were documenting a bug. To me it's quite inconclusive and elusive what "! input" is trying to tell me.

**Comment by aelocson** [comment]
> I am pretty sure that whenever you tried to document that "feature" you were documenting a bug.

Could be so. All I had to judge by was what the code actually said.

The only two operators where I've documented **! input** are `list` and `title`. In both cases, the plain operator is absolute, while the negated operator is relative.

But note that the `sort` operators and also the `limit` operator have their own special meaning for `!`.

> `var n = "!" === operator.prefix;`

I would suggest adding a boolean field on the operator object, e.g. `operator.negated` or `operator.inverted`. There's no point in repeating the string comparison on every iteration.

**Comment by aelocson** [comment]
I wonder if capital letters would be clearer than lowercase for the "symbols":

… the last N input titles …
… those input tiddlers in which field F does *not* have the value S …

Note also that by saying "field F" and "the value S" – as opposed to just "F" and "S" – we're giving a substantial clue to the uninitiated reader as to how to make sense of these symbols.

**Comment by tobibeer** [comment]
:+1: on both capital letters and wordy clues

**Comment by tobibeer** [comment]
> I would suggest adding a boolean field on the operator object, e.g. operator.negated or operator.inverted. There's no point in repeating the string comparison on every iteration.

That is true. Even if there were at some point multiple prefixes, it would be better to simply store **operator.negate** and **operator.foo**, depending on what the parser identified. As my commit is tentative and awaiting Jeremy's feedback anyhow, I added those changes to #1419.

**Comment by aelocson** [comment]
I've added a commit that capitalises the placeholder symbols and moves them out of the first column.

http://ae-doc-preview.tiddlyspot.com/

**Comment by tobibeer** [comment]
Nice, thanks, @aelocson. So, let's see if we can't get the grounds for only one type of negation... and perhaps get those custom fields properly searchable, maybe via... https://github.com/Jermolene/TiddlyWiki5/pull/1386 and some settings tiddler that defines the default settings for searches.

**Comment by Jermolene** [comment]
Hi @aelocson this is another tour de force, congratulations. I'm very impressed with the quality of your work.

The only query I have is with the "relative" vs. "absolute" terms: I wonder if we can find terms that apply better. Perhaps "strict filters" (which only select titles in the source list) and "loose filters" (which can select any titles). But I think it makes sense to merge the pull request at this point, and continue the discussion.

**Comment by aelocson** [comment]
Hi @Jermolene – and welcome back!

> The only query I have is with the "relative" vs. "absolute" terms

My reasoning was that the former consider only the set of tiddlers they're given as their input, while the latter ignore their input and are not subject to any such restriction.

"Strict" and "loose" don't really work for me. "Loose" sounds like it does some sort of fuzzy matching.

How about "restricted" and "unrestricted"?

**Comment by Jermolene** [comment]
The rationale is that the best word for "restricted"/"relative" might be "filter"; the everyday common usage of the word implies that the result is a strict subset of the source. The trouble, of course, is that we already use that word for the entire expression. Hence using the "strict" qualification.

Perhaps there are words that are already used for list or set processing that may be suitable? "Subset operator" vs. "superset operator"?

**Comment by aelocson** [comment]
You're right that "filter" would have been perfect. "True filter" or "genuine filter" would be clearer than "strict filter".

"Subset operator" is pretty good, although it restricts sentence construction somewhat: for example, you can't say "this operator is subset". But "superset operator" doesn't work – "superset" implies a relationship between the output and the input, whereas the key thing about the operators in this category is that they have *no* relationship whatsoever to their input.

We could use the word "injection" (now well established in software development): these operators essentially *inject* an entirely new value into the filter pipeline. We could speak of "injection operators" and "subselection operators", or (to permit more flexible sentences) "injecting operators" and "subselecting operators".

**Comment by Jermolene** [comment]
"open filter operator" vs. "subset filter operator"?

**Comment by aelocson** [comment]
Yes, I could go with those.

Other ideas:
* root operator
* modifying operator (or modifier)
* qualifying operator (or qualifier)

The difference between the two is similar to that between `obj` and `.field` in `obj.field`.

Could you expand slightly on what you don't like about "absolute" and "relative"? The analogy to absolute and relative filenames struck me as apposite.

**Comment by tobibeer** [comment]
I think whatever the notion, it should reflect that some filter runs create an initial set of tiddlers, so it's a (set-)initializing filter, whereas the others are (set-)modifying filters.

**Comment by Jermolene** [comment]
> Could you expand slightly on what you don't like about "absolute" and "relative"? The analogy to absolute and relative filenames struck me as apposite.

The terms do indeed make me think of pathnames, but I don't find it so helpful. Pathnames are an algebra of a sequence of symbols, but here we're in the domain of sets.

**Comment by aelocson** [comment]
Thanks for the clarification, @Jermolene. That makes perfect sense.

I like Tobias's idea of "initialising" and "modifying". And the word "filter" doesn't have to be part of the name. So we could say that the two classes of filter operator are "set initialisers" (or perhaps "set constructors") and "set modifiers".

**Comment by Jermolene** [comment]
Great, I like "constructors" and "modifiers"; we don't always need the word "set".

**Comment by tobibeer** [comment]
:+1:

**Comment by aelocson** [comment]
Lovely. I'll adjust the documentation tomorrow or Friday.

**Pull request merged**
