### PR TITLE
Fix "line-width" svg icon

### PR DESCRIPTION
**Pull request by BurningTreeC**
The icon has an artifact which is visible on internet explorer

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @BurningTreeC please can you show before and after screenshots of the icon in IE and a regular browser?

**Comment by pmario** [comment]
I can see something with IE 11.418 with line-width. I don't see a problem with list. 

BTC-PRs

**Comment by pmario** [comment]
Didn't test the PRs.

**Comment by pmario** [comment]
The funny thing is. If I open AdvancedSearch and the image-gallery example tiddler, the problem goes away. If AS is closed, the problem comes back...

**Pull request closed without merging**
