### PR TITLE
Write system tiddlers to _system subdirectory on node.js

### PR DESCRIPTION
**Pull request by nome**
The current scheme for creating system tiddler files on node.js has two issues:

Firstly, filenames containing `$` are difficult to work with on unix, because
this character is used for variable expansion.

Secondly, within TiddlyWiki, system tiddlers are hidden; but in a wiki
directory, they are always visible along with regular tiddlers. Actually hiding
them without breaking cross-platform compatibility is tricky (Windows doesn't
handle dot files well), but we can move them to a separate subdirectory.

Solution: When generating filenames for new/renamed tiddlers, strip the $:/
prefix from system tiddlers and store them in a subdirectory tiddlers/_system.

This change does not affect existing system tiddlers or the ability to
manually place system tiddlers anywhere beneath the tiddlers directory.

---
Initially discussed in #2332. The implementation follows @sukima's suggestion. An additional proposal made was to fully replicate the logical tiddler "path" in the filesystem, and the code here is written with this possibilty in mind (a future modification to `generateTiddlerFilename` could replace all occurences of `"/"` with `path.sep`). Since there may be unforeseen details and corner cases where this could cause trouble, for now we only do the `$:/` -> `_system` replacement.

### CODE REVIEW

**Comment by nome** [comment]
Maybe someone should actually test this on Windows/Mac. I think it should work, though.

**Comment by Jermolene** [comment]
Hi @nome thanks for this. There is in fact already a function to recursively create directories in the filesystem utilities:

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/utils/filesystem.js#L90-L111

Can the same function be used here?

I'm also wondering if we might not be able to make the logic more extensible than this. An approach I've considered in the past might be to introduce a configuration table that maps filter expressions to directory paths. For example:

```
[tag[Tasks]] ➤ /mytasks/tiddlers
[is[system]] ➤ /system
```

I'm pretty sure there has been some earlier discussion on GitHub about this idea, but can't locate it right now.

**Comment by nome** [comment]
> Can the same function be used here?

I've updated the PR to use the existing function.

> I'm also wondering if we might not be able to make the logic more extensible than this.

Sure. However, mapping filter expressions to _directories_ does not allow us to handle the `$` issue, because then we can't influence the file name consistently.

Another option would be allowing the user to specify a filter which maps tiddlers to (relative, logical) file paths; i.e. `[tag[Tasks]addprefix[mytask/tiddlers/]]` or `[is[system]removeprefix[$:/]addprefix[_system/]]`. Then I could even do `[is[system]removeprefix[$:/]addprefix[.]]` in my personal config without breaking things for Windows users.

This would seem to imply replacing `/` in tiddler titles with `path.sep`, i.e. replicating the tiddler "path" in the filesystem as suggested earlier. We could limit the impact by doing this only for tiddlers which match the user-specified filter, without including any predefined filter (for now). This way, a simple update won't break anyone's wiki and the change can be tested thoroughly before (potentially) adopting it as a default.

**Comment by Jermolene** [comment]
Hi @nome using filters to transform the title into a path is neat. I think we'll need to separate the filter component from the transformation component, though, otherwise we might run into difficulties chaining these transformations. So there'd be an ordered list of filters, each associated with a transformation. The system would execute the first transformation with a matching filter.

**Comment by nome** [comment]
@Jermolene Don't we get the same result if we concatenate (i.e. logically OR) the filters and pick the first result? Maybe I'm just overlooking the problem...

**Comment by Jermolene** [comment]
@nome I think you're right; we could just use the result of the first filter that returns at least one entry.

**Comment by nome** [comment]
Superseded by #2379.

**Pull request closed without merging**
