### PR TITLE
bug: fix kb widget empty parameters

### PR DESCRIPTION
**Pull request by BurningTreeC**

### CODE REVIEW

**Comment by BurningTreeC** [comment]
to reproduce: open the preview and type: `<$keyboard>`

**Comment by BurningTreeC** [comment]
Bildschirmfoto vom 2019-07-12 18-22-30

**Comment by BurningTreeC** [comment]
ping for 5.1.20

**Comment by BurningTreeC** [comment]
another simple bug-fix

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Pull request merged**
