### PR TITLE
add localisable strings

### PR DESCRIPTION
**Pull request by araname**

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @araname apologies for the delay

**Comment by Jermolene** [comment]
Thank you @araname I hadn't realised that you had managed to pack so many good fixes into this pull request. There are a couple of minor issues that I'd like to address before merging:

* in `boot.js`, please can we use the string identifiers "InternalJavaScriptError/Title" and "InternalJavaScriptError/Message"?
* when composing the new draft title in `navigator.js`, rather than just using concatenation, I think it would be better to parameterise the count and the title, as we do with, say, `$:/language/InvalidFieldName`. That would allow us to cope with languages where the phrasing order might be different
* there may be a misunderstanding about `$:/language/OfficialPluginLibrary`. It is used to describe the tiddler that points specifically to the URL of the official plugin library, rather than describing the "plugin library" area of Control Panel, which can of course connect to multiple plugin libraries. So I think you need to retract the changes around this tiddler

My apologies for overlooking this request, I very much appreciate the effort you have put into it.

**Comment by araname** [comment]
I think better use "InternalJavaScriptError/Hint" then "InternalJavaScriptError/Message" about string identifiers of "Internal JavaScript Error".

**Comment by Jermolene** [comment]
Thanks @araname will you be able to update this pull request?

**Comment by araname** [comment]
I want to move string 'move' in ``ControlPanel.multids`` to ``Misc.multids`` or ``Search.multids``.

**Comment by araname** [comment]
This is replaced with #2036.

**Pull request closed without merging**
