### PR TITLE
update highlight.js to latest release v9.15.6

### PR DESCRIPTION
**Pull request by BurningTreeC**
this updates highlight.js to v9.13.1

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @BurningTreeC. It looks like the CSS file not change in the upgrade, is that right?

**Comment by BurningTreeC** [comment]
@Jermolene about the CSS - the current stylesheet has a link on top where it's been copied from

under that link I couldn't find those styles

I tested with the current styles and it looked good at first sight

but let's see before merging if there isn't something useful or important in the new styles

I'll report back

**Comment by BurningTreeC** [comment]
@Jermolene, I've updated the default.css to the one in the highlight.js repo

does the current default.css include adjustments for the different languages?

**Comment by kookma** [comment]
@BurningTreeC  Thank you!
I will wait to finalize it!

**Comment by BurningTreeC** [comment]
@Jermolene, the styles are indeed cleaned-up now. You can see that at the [highlight.js demo](https://highlightjs.org/static/demo/).  I've updated `highlight.pack.js` to include the previously included languages and I made some popular additional choices. I can undo that, but I think it makes sense, here's the list with the new ones in bold:

Apache
**AsciiDoc**
Bash
C++
C#
**CMAKE**
CoffeeScript
CSS
Diff
**Dockerfile**
**Elixir**
**Erlang**
**Erlang REPL**
**Fortran**
**Go**
**Haskell**
HTML XML
HTTP
Java
JavaScript
JSON
Makefile
Markdown
**Matlab**
Nginx
Objective-C
Perl
PHP
Properties
Python
Ruby
**Rust**
Shell Session
SQL
**TypeScript**

**Comment by Jermolene** [comment]
Great thanks @BurningTreeC -- I was going to ask to have Erlang included :)

**Comment by kookma** [comment]
@BurningTreeC 
Thank you for adding more language (specially Fortran and Matlab).

Cheers

**Comment by kookma** [comment]
Please correct the read me of plugin! Explicitly state what is the version highlight.js

**Comment by juanbono** [comment]
@BurningTreeC  Any updates on this? I can update the version on the readme if you want :)

**Comment by Jermolene** [comment]
Hi @BurningTreeC just checking you're aware of the merge conflict?

**Comment by BurningTreeC** [comment]
got it, thanks @Jermolene

**Comment by BurningTreeC** [comment]
the update to version 9.15.6 adds some languages, they're listed in readme.tid

let me just test a second ...

**Comment by BurningTreeC** [comment]
ok, lgtm :+1:

**Comment by BurningTreeC** [comment]
@Jermolene, this is ready

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Comment by kookma** [comment]
> the update to version 9.15.6 adds some languages, they're listed in readme.tid
> 
> let me just test a second ...

Hello Simon,
 There is a bug in Highlight.js for Fortran language!

Try this in TW 5.1.20pre
```
program test
real:: xm, ym
xm=12.325e5
ym=1.23_wd
end program
```

and also on

https://kookma.github.io/TW-Commander/


It seems there is a bug in parser! It cannot parse the 1.23_wd
I have created a patch and if you note there is no issue with https://kookma.github.io/TW-Commander/

--Mohammad

**Comment by kookma** [comment]
If you drag and drop the below tiddler
https://kookma.github.io/TW-Commander/#%24%3A%2Fplugins%2Ftiddlywiki%2Fhighlight%2Fhighlight.js

to TW 5.1.20pre, you will see the issue has gone!

--Mohammad

**Comment by BurningTreeC** [comment]
Hi @Mohammad, this could probably be an issue for the [highlight.js repository](https://github.com/highlightjs/highlight.js/)

**Pull request merged**
