### PR TITLE
MWS: Query recently updated tiddlers in a bag

### PR DESCRIPTION
**Pull request by PotOfCoffee2Go**
#  getBagRecentTiddlers

## Objective

The purpose of `$tw.mws.store.getBagRecentTiddlers(bag_name, last_known_ _tiddler_id, limit)` is to be able to poll (server-side) the MWS tiddler database for latest new, updated, deleted tiddlers by bag.

## Why?
The getBagRecentTiddlers function will allow a companion server-side application to process incoming tiddlers and possibly store results back on the database for distribution to MWS web users.

> The *currently in progress*  MWS synchronization mechanism [mwsadaptor](https://github.com/Jermolene/TiddlyWiki5/pull/7915#issuecomment-2009187719) will perform the distribution to web clients.

# Implementation
The connection between MWS and the companion application would be established by creating an *edition* with a plugin profile including both MWS and the application.

```
"plugins": [
    "tiddlywiki/tiddlyweb",
    "tiddlywiki/filesystem",
    "tiddlywiki/multiwikiserver",
    "independent/application"
],
``` 

## Fundamental Tasks
- [x] Create prototype of function
- [x] Build server-side REPL for interactive testing [mws-repl](https://github.com/PotOfCoffee2Go/mws-repl)
- [ ] Discuss bug and feature requests
- [ ] Create and implement tests into MWS test suite
- [ ] Documentation
- [ ] Peer review
- [ ] Finalize code for release

### CODE REVIEW

**Comment by PotOfCoffee2Go** [comment]
HI @Jermolene ,

Being a new contributor, I was hoping you could perform a quick review of this PR and  the two commits. If you see anything that I should be aware of for future contributions; syntax wise, too many//few inline comments, or anything that would I should be aware make your job easier.

My editor is set to remove unnecessary  white-space  at the end of lines and insures files end with an blank/empty line. I don't see them as my git diff ignores white-space changes - is that OK with you?

thanks

**Review by Jermolene — COMMENTED** [review]
Thanks @PotOfCoffee2Go. You've done a great job of matching the coding style and feel of things.  In due course a PR like this should ideally include some tests.

I am now thinking, though, that this functionality should be exposed as an option to the existing getBagTiddlers() and getRecipeTiddlers() APIs. We'd add an "options" parameter, and use "last_known_tiddler_id" to indicate a starting point.

The motivation is just to keep the API surface area smaller, and takes inspiration from Amazon S3 which has a similar "start-from" parameter for the ListObjectsV2 API.

Parenthetically, to compensate for their relentless growth, I intend to split sql-tiddler-database.js and sql-tiddler-store.js to move each of the methods into its own separate source file.

**Comment by Jermolene** [comment]
> In due course a PR like this should ideally include some tests.

Apologies @PotOfCoffee2Go I missed that this PR does already include a test, good to see thank you.

**Comment by PotOfCoffee2Go** [comment]
Thanks @Jermolene

> "I am now thinking, though, that this functionality should be exposed as an option to the existing getBagTiddlers() and getRecipeTiddlers() APIs. We'd add an "options" parameter, and use "last_known_tiddler_id" to indicate a starting point."

Agree - but until happy that is working as advertised should (for now) be separate. Also have hit a snag where messages get missed when a process batch uploads tiddlers to the database. - topic for another day.

> "I intend to split sql-tiddler-database.js and sql-tiddler-store.js to move each of the methods into its own separate source file."

"Great minds think alike" ;)

I believe sql-tiddler-store.js should be set up similair to the way the 'routes' are - having individual sql-tiddler-store.js(s) performing their respective tasks. But keep sql-tiddler-database.js as a single module so the lower level access to the database is consolidated.

Plus tests should be set up the same way - I have 10+ tests already written in my tests-sql-tiddler-recent.js but to implement and merge into tests-sql-tiddler-store.js is painful at best.

If you want - create an issue describing the MWS store/module directory structure  you envision and assign it to me. I will attempt to build it using the existing code as a foundation - or at least do my best with a little help. 

Advise that a 'store/module/tests' directory should follow the same structure.

**Comment by Jermolene** [comment]
Hi @PotOfCoffee2Go I committed a [revision](08649dd1ebb6a6d3b819155bf85172dbb325e825) to the sync mechanism incorporating some of your code. It is still a bit rough around the edges, and I have yet to do the refactoring into separate files, but it gets the tiddler_id stuff out to the browser, and gives us a good basis for the next step, which is adding support for using Server Sent Events so that `GET /recipes/:recipe_name/tiddlers.json` can stream changes back to the browser.

**Comment by PotOfCoffee2Go** [comment]
At the time of this PR the event handlers and the functions $tw.mws.store.getRecipeLastTiddlerId() and getRecipeTiddlers() with the option **last_known_tiddler_id** had not been fully implemented.

They provide the ability to 'Query recently updated tiddlers in a bag'  (well, recipe which is better) making this PR already completed in the course of building MWS.

These functions allow storing the state of the recipe ('last tiddler id'). Using $tw.mws.store.getRecipeLastTiddlerId() and comparing with the last state can quickly determine if further processing is needed as the recipe tiddlers have changed. (An important option is also the 'include_deleted' - which solved one of my use cases.)

I have not bench-marked the performance gains using last_known_tiddler_id over polling the complete recipe to see if there was a change. But running on a Raspberry Pi (greatest bench mark tool ever) - the performance advantages are very noticeable.

So - closing this PR, as no longer an issue.

**Pull request closed without merging**
