### PR TITLE
Update Lists in WikiText.tid

### PR DESCRIPTION
**Pull request by springerspandrel**
Under CSS Classes heading, added an existing CSS class to the second bulleted list item (rather than the undefined MyClass), so that the illustration shows some effect.

### CODE REVIEW

**Comment by springerspandrel** [comment]
Ah, it was a mistake to suggest the .hljs-type class, because that relies on the highlight plugin. Perhaps .tc-muted would be better, as it's in the core.

**Comment by saqimtiaz** [comment]
@springerspandrel you may find this useful for modifying pull requests, or submitting new ones: https://saqimtiaz.github.io/tw5-docs-pr-maker/

**Comment by springerspandrel** [comment]
Saq, it's not clear to me what's better/worse about the GitHub edit process vs your docs-pr-maker. Editing a tiddler at tiddlywiki.com just offers an "either-or":

 [edit this tiddler in Docs PR Maker](https://saqimtiaz.github.io/tw5-docs-pr-maker/#currentTiddler%20Variable) or [edit it directly on GitHub](https://github.com/Jermolene/TiddlyWiki5/edit/tiddlywiki-com/editions/tw5.com/tiddlers/variables/WidgetVariable_%20currentTiddler.tid)

What's at stake in the difference between these? I'll go whichever route you recommend. Perhaps others are similarly unsure when/why to choose which option.

(I closed this particular request because I saw the error in my suggestion, and also thought it would be wiser to start fresh because of today's new release.)

**Comment by saqimtiaz** [comment]
@springerspandrel I think the key difference is that using the PR maker lets you edit tiddler(s) in the familiar UI of TiddlyWiki and then submit them as a PR. In particular, submitting a PR with changes to multiple tiddlers should be significantly easier.

 Also, the PR makers allows to load an already submitted PR, make further changes to it, and submit it again rather than having to start a new PR from scratch.

The key requirements for the PR maker are a GitHub account and a GitHUb authentication token (a direct link to create the token need is provided in the walkthrough at the beginning).

I would welcome both any feedback on the PR makers, as well as thoughts on how these details could be better conveyed to the larger community.

**Comment by springerspandrel** [comment]
OK, I've tried submitting my first change through the docs-pr-maker link you shared. As far as I understand, one advantage here is that we're not necessarily limited to making changes to an existing tiddler. I notice that inputActions is a variable that has no explanatory tiddler. We also don't have a tiddler for the currentTab variable. So, with this interface, I could propose adding such tiddlers. (On the other hand, I'm not confident with generating such documentation myself; so I'll stick to easy fixes and straightforward examples, for now.)

**Pull request closed without merging**
