### PR TITLE
update the file name from uniquetitle to unusedtitle

### PR DESCRIPTION
**Pull request by inmysocks**
Also changed the baseName parameter to basename to be more consistent with other macros.

### CODE REVIEW

**Comment by 00SS** [comment]
For the parameter to be more consistent with other core macros, the second word starts with a Capital letter. Please look at the table in the [previous PR](https://github.com/Jermolene/TiddlyWiki5/pull/3880#issuecomment-477318721)

Also I believe the parameter should **not** be called basename or baseName, but should be **baseTitle**.

**basename** already has a different definition in TiddlyWiki.

**Comment by inmysocks** [comment]
If you have specific changes you would like than feel free to open a pull request with them.

**Comment by kookma** [comment]
@inmysocks 
I think basetitle is correct to be consistent with basetitle in action-createtiddler!
Please correct this!

Thank you

**Comment by 00SS** [comment]
I am simply pointing out the trends I see in the documentation. Consistency is really useful in the long run.

$basetitle is an **attribute** of the $action-createtiddler widget
Global macros have **parameters** and as mentioned normally follow a slightly different construction - thus my suggestion of **baseTitle**
The suggestion by @kookma is also valid, as it is consistent with the attribute that has exactly the same function.

Someone with more experience might have to decide.

**Comment by inmysocks** [comment]
Closing this in favour of #3885

**Pull request closed without merging**
