### PR TITLE
Motovun jack

### PR DESCRIPTION
**Pull request by pmario**
This PR does the following:

 - makes the svg size smaller
 - removes unused meta tags
 - removes unused xml namespaces
 - makes the SVG valid using [W3C-Validator](http://validator.w3.org/#validate_by_input)
 - smoothes some motovun jack paths, 
 - removes unnecessary nodes .. some of them are so close together, that they can be 1
 - back feets are 2 paths now.
 - left ear is rounder now. 

It also removes the width and height parameters. Due to a [IE bug](https://gist.github.com/larrybotha/7881691) it doesn't use them anyway and the `pt` unit is for print media.

Tested with FF 36, 38,   Chromium 40,   IE 11 ... It doesn't cause any incompatibilities, since we scale our svg images with CSS.

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @pmario thanks, that's jolly good. What tool did you use to do the processing? I've been playing with https://jakearchibald.github.io/svgomg/

**Comment by Jermolene** [comment]
The other thing I meant to add was that there is an embedded version of Jack in the `$:/core/icon` icon.

**Comment by pmario** [comment]
I used the "Optimized Inkscape SVG" saver. It allows to remove most of the app specific meta data. ... But I still needed to remove some stuff by hand :/ ... 

Inkscape also has an XML editor, where you can inspect / modify the internal xml structure. ... There you can change IDs and other attributes ... without braking the SVG. 

.. I'll have a look at the core icon.

**Comment by Jermolene** [comment]
Thanks @pmario

**Comment by pmario** [comment]
@Jermolene 
added the icon. tested with ff, chromium, ie11 especially in the control panel, plugin section. seems to be ok and is a little bit smaller :)

**Comment by Jermolene** [comment]
Thanks @pmario

**Comment by Jermolene** [comment]
Actually, now that I look at the images in detail, I can see that there are significant visual differences. Here's the new image:

screenshot 2015-03-31 09 02 07

And here's the old one:

screenshot 2015-03-31 09 03 00

As you can see, the shapes of the ears are completely different. I'm going to revert since the goal of this ticket was to reduce the file size without impacting the appearance.

**Comment by pmario** [comment]
IMO there are only 2 differences.

 - the left ear
 - the back of the head. 

For me both shapes are artefacts from tracing a jpg to svg. ... I wanted to reduce the file size and fix these anatomical incorrect shapes. ... 

Plus there is a transform() in the original. This transform() and the `pt` cause the need for some CSS rules eg: `tc-tiddler-frame svg ... max-width:100%` that wouldn't be necessary without it. .... 

But anyway ... it's your mascot. 

I can revert the ear and the head, without increasing the size again. .. I'll create a new pull request, if you want.

**Comment by Jermolene** [comment]
Hi @pmario are you saying that the changes to the ear/head were intentional, and not part of the optimisation process?

I agree that getting rid of the transform would be desirable.

**Comment by Jermolene** [comment]
btw @pmario if we do make changes to the visual appearance of the icon then there's quite a few copies of it floating around the project that need to be changed to be consistent (eg, the TiddlyDesktop icon, Twitter avatar etc). So it's a bigger job than tweaking a couple of files.

**Comment by pmario** [comment]
I'll create a new pull request.

**Comment by Jermolene** [comment]
Thanks @pmario

**Pull request merged**
