### PR TITLE
Droppable widget: dragenteractions and dragleaveations

### PR DESCRIPTION
**Pull request by BurningTreeC**
Hi all,
and especially @saqimtiaz 

I've prepared this PR which incorporates the modifications Saq made for the dropzone widget
I'd like to hear what Saq says to the implementation

### CODE REVIEW

**Comment by saqimtiaz** [comment]
Hi @BurningTreeC, nice to see that you decided to take a crack at this. Unfortunately I am on leave until the end of the month and will not have the opportunity to properly review this before then.

 My recommendation is to try and create a test case that exhibits the original bug in Firefox, as signified by the persistent dragover state, and confirming that these changes resolves the issue. You will also need to test on other browsers to ensure that the behaviour there is unchanged.

**Comment by BurningTreeC** [comment]
> Hi @BurningTreeC, nice to see that you decided to take a crack at this. Unfortunately I am on leave until the end of the month and will not have the opportunity to properly review this before then.
> 
> My recommendation is to try and create a test case that exhibits the original bug in Firefox, as signified by the persistent dragover state, and confirming that these changes resolves the issue. You will also need to test on other browsers to ensure that the behaviour there is unchanged.

Thanks @saqimtiaz , what would be a test case?
Would it be sufficient to use the "Open" tab without `\whitespace trim`?

**Comment by BurningTreeC** [comment]
@Jermolene , may I prepare a PR for the dragenteractions only and have a look at this at a later point?

**Comment by Jermolene** [comment]
> @Jermolene , may I prepare a PR for the dragenteractions only and have a look at this at a later point?

I think we should try to deal with them both at the same time.

**Comment by pmario** [comment]
@BurningTreeC ... Is there a link to the description of the "problem" this PR should solve?

**Comment by BurningTreeC** [comment]
Hi all,

I'd like to revive this PR

It does the following:

- adds dragenteractions
- adds dragleaveactions
- handles dragEnter and dragLeave like in dropzone.js

What do you think?

**Comment by saqimtiaz** [comment]
Note also that while excessive dragenter events firing in edge cases are not a problem for the dropzone and were not handled by the fix I introduced there, they would be problematic here as they would lead to the extra invocation of actions.

**Pull request closed without merging**
