### PR TITLE
exposes paramString as variable in macro scope

### PR DESCRIPTION
**Pull request by tobibeer**
implements #1373

useful in js macros that do their own parsing, if any

demo: http://tbdemo.tiddlyspot.com/#paramString

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @tobibeer the trouble here is that only macrocall widgets that were generated by parsing the `<<name>>` syntax. It won't work with direct invocations of the `<$macrocall>` widget.

**Comment by tobibeer** [comment]
@Jermolene: Considering the way **$macrocall** asks you to pass individual parameter attributes, how could it possibly do that ...or why would it?

**Comment by Jermolene** [comment]
@tobibeer that's my point. This proposal results in inconsistent behaviour between the two modes of macro calling. It's based on the assumption that there is a string of unparsed parameters, which is not generally the case. Any macro that wants to parse it's own parameters can simply reach into the parse tree node of the widget (if present) and inspect it as required.

**Comment by tobibeer** [comment]
> Any macro that wants to parse it's own parameters can simply reach into the parse tree node of the widget (if present) and inspect it as required.

I see a usecase for and a useful pattern in macros simply using the paramString, ignoring any core parsing when its not helpful.

How about giving the macrocall widget a **$paramString** attribute to cover this case?

**Comment by Jermolene** [comment]
Hi @tobibeer sorry to be unclear. I'm saying several things:

* it is already possible for a JS macro to access the paramString of any associated parse tree node if it wants to
* I don't like the idea of exposing paramString as a variable because it's behaviour is inconsistent, only working if the macro is invoked in some ways and not others

**Comment by tobibeer** [comment]
> it is already possible for a JS macro to access the paramString of any associated parse tree node if it wants to

This makes this pull request superfluous indeed.
How would I access the **paramString** in a js macro?

**Comment by Jermolene** [comment]
My apologies @tobibeer, macros cannot access the entire param string of the macro call. In fact, the parameter string is only retained as the parsed individual parameter values.

**Comment by tobibeer** [comment]
> This proposal results in inconsistent behaviour between the two modes of macro calling.

We already have two inconsistent modes. This merely extends on the differences. As mentioned at https://github.com/Jermolene/TiddlyWiki5/issues/1479#issuecomment-73808479, a wikitext macro likewise doesn't know of all macrocall widget attributes. What do you think of **$paramString** to be more consistent?

**Comment by Jermolene** [comment]
I'm not sure that we do have two inconsistent modes. We have a low level widget syntax that's designed for consistency with HTML with some flexible, regular extensions for the needs of widgets. Over the top of that, we have the syntactic sugar of a layer of shortcut syntax for commonly used idioms, exposing a subset of the functionality of the underlying widget(s). In the case of wikitext macro calls versus the macrocall widget, the big difference is that the former doesn't allow for contained, parsed content, so there's no need for the complex rules about closing tags.

> As mentioned at #1479 (comment), a wikitext macro likewise doesn't know of all macrocall widget attributes. What do you think of $paramString to keep consistency?

I don't think you're addressing my objection: JavaScript macros currently can't tell whether they were invoked by the macrocall widget or the shorthand syntax and to let them do so would break the layering. Breaking the layering is bad because it leads to bugs and unexpected interactions between modules.

There is no paramString by the time we get to calling the JavaScript macro. There's been a whole pipeline of parsing and rendering. What you're asking is like asking for an HTML webcomponent to be able to access it's attributes as a literal string, rather than parsed through the DOM.

If you've got a macro that wants to parse it's own parameters then why not do this:

```
<<mymacro """ my individual parameters with their own strange parsing rules """>>
```

If you don't like the amount of typing then you could consider a new parser rule implementing a shortcut syntax.

**Comment by tobibeer** [comment]
Wherein exactly lies the harm in a **$paramString** widget attribute setting the context variable?

As for "their own strange parsing rules" — I am pretty sure you can imagine a whole range of parsers that have nothing whatsoever to do with html attributes.

**Comment by Jermolene** [comment]
> Wherein exactly lies the harm in a $paramString widget attribute setting the context variable?

I've tried to explain the issues at some length. I'm not sure how else to explain it.

> As for "their own strange parsing rules" — I am pretty sure you can imagine a whole range of parsers that have nothing whatsoever to do with html attributes.

And so we have a parser module system to cater for the cases where custom parsing is required.

**Comment by tobibeer** [comment]
There is a common syntax for macros. Why invent my own? It makes no sense to me.

```
++myCustomParser "which would use the very same macro logic underneath but since our own paramString can't be passed down to a js macro we need to invent something else"++
```

Have this multiplied by x plugins and you have a level of complexity where people lose faith and interest. NestedSlidersPlugin? Sure, they say it's very powerful, but the study guide to its parametrical symbols... well, I guess I'll read it another day.

Here's plain macro markup extended with a very basic mechanism with no discernible problem attached, at least I wouldn't know which.

So, I'm closing this.

**Comment by Jermolene** [comment]
> There is a common syntax for macros. Why invent my own? It makes no sense to me.

As you say, there is a common syntax for macros. Your request is for a way to be able to invent your own.

> Here's plain macro markup extended with a very basic mechanism with no discernible problem attached, at least I wouldn't know which.

I think I've explained what I see as the problems, did that make sense?

**Comment by tobibeer** [comment]
`<$macrocall $name="foo" $paramString="bar"/>` looks very straight forward to me.

Perhaps the syntax of a macro could be enhanced to more explicitly declare it: `<<foo => bar>>`

I quite doubt that you don't see a need for custom parsers... and a desire not to invent custom wikitext parser rules for each and every one of them when that basic macro parser would do just fine, except for its limited ways of parsing parameters.

**Pull request closed without merging**
