### PR TITLE
Add Encrypt Tiddler Plugin to ressources

### PR DESCRIPTION
**Pull request by danielo515**
Encrypt tiddler plugin has its own demonstration wiki. Added as resource to tw.com edition.

### CODE REVIEW

**Comment by sukima** [comment]
Curious the [documentation](http://danielorodriguez.com/TW5-EncryptTiddlerPlugin/) didn't mention but what kind of encryption is being used? What library(ies) are used for encrypting? Is it the same library that comes with TiddlyWiki already (Stanford JavaScript Crypto Library, which surprisingly tw.com also has no documentation on)? How does the mechanism work and how is it still secure?

FWIW: Security is a PITA!

**Comment by felixhayashi** [comment]
Hi @sukima 

just go to the demo site and encrypt a tiddler. you will see a field `encrypted` that holds the following data:
       {"iv":"SvX/vdDjT4rhFKeIV4hvrQ","v":1,"iter":1000,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","salt":"8Wp+I7MG5fg","ct":"+b3H4153BiN2sdx6yp0iRfLrnOyHDITbendYF+8hGs6oHqlHu1t/h2PR1WprOjxPq8rWYCUBi/e93t9en8/kM82n8fGwbvFawz4aHnfXIFcaZaphJwOJat776lLh1ArhE8Wl3NchhVYcwykfYjqzG05KuA6OviA"}

So it's 128 bit AES with cipher block chaining mode. Not sure why not 256 bit AES is chosen though...

**Comment by danielo515** [comment]
I just use the mechanism that tw provides. I did not make any choose.

**Comment by danielo515** [comment]
Maybe I have to make that clear on docs

**Comment by sukima** [comment]
@danielo515 Cool, that's exactly what I was wondering if it use the built in TW crypto. That really awesome that it does. I only recommend mentioning that in your docs and then maybe a link to TW's crypto tiddler.

Although looking at TW.com the TW crypto tiddler needs some love to update it's docs on the subject (like 128 bit AES via the Stanford JS Lib).

**Comment by pmario** [comment]
> ... (like 128 bit AES via the Stanford JS Lib).

IMO this info is not enough. It doesn't say anything about security, of the used workflow. There are many more parameters, that are important? 

I'd suggest to just link to the library homepage http://bitwiseshiftleft.github.io/sjcl/ and say that we use the library default settings, which imo is the case. 

Then we should add, that **nobody should ever expose sensitive data to the internet.** The internet doesn't forget anything. Encryption, that is considered secure today may be outdated tomorrow. 

... Most of the time crypto keys are not the problem. **Weak user passwords and weak key management** are the problem. 

So if someone wants to use TW encryption to obfuscate some tiddlers for the web, imo that's ok. 

But if you want to store sensible information, use it local only, or use **open source** OS level harddisk encryption.

**Comment by Jermolene** [comment]
Thanks @danielo515, I've pushed the update to tiddlywiki.com.

**Pull request merged**
