### PR TITLE
Update GenesisWidget.tid

### PR DESCRIPTION
**Pull request by AnthonyMuscio**
Add "or HTML element" to the description of "attributes not starting with $".

### CODE REVIEW

**Comment by AnthonyMuscio** [comment]
This is my second attempt and my change is not appearing in the preview, I am not sure what I am going wrong.

I just wanted to add "or HTML element" at the end of the description of "attributes not starting with $"

**Comment by pmario** [comment]
It is visible for me in the preview. Are you sure you did open the right preview or try CTRL-F5 to clear the browser cache

**Comment by AnthonyMuscio** [comment]
Thanks @pmario what ever the reason it showed when I tried again.

I can confirm the preview is as expected.

**Comment by Jermolene** [comment]
Thanks @AnthonyMuscio

**Pull request merged**
