### PR TITLE
Make folded-state variable qualified

### PR DESCRIPTION
**Pull request by BurningTreeC**
This PR makes the `folded-state` variable a `qualified` one through `<<qualify "$:/state/folded">>`

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @BurningTreeC perhaps there are backwards compatibility concerns here:

1. Users may have set up their wikis with certain tiddlers folded and wish to retain that state over an upgrade
2. Users may have custom code that folds/unfolds tiddlers

It may still be worth doing despite the incompatibility, but it is important that we don't break compatibility unknowingly.

Another consideration is that perhaps these state tiddlers should be based off the identity of the story river, not its location in the widget tree. Otherwise moving a story river (eg to rearrange columns) will change the names of all the state tiddlers.

**Comment by pmario** [comment]
I'm not sure, why this is different to the existing behaviour. Tiddler titles need to be unique. So there isn't any difference. It's just not human readable anymore. I think, that's a regression.

**Comment by saqimtiaz** [comment]
> 2\. Users may have custom code that folds/unfolds tiddlers

This is highly likely to be the case. The problem with qualified state tiddlers for folding is that they cannot be manipulated from action strings invoked elsewhere.

**Comment by BurningTreeC** [comment]
Yes @pmario @saqimtiaz - I've now understood the point. I'm going to close this PR

**Pull request closed without merging**
