### PR TITLE
Docs: Add information about the Chinese TiddlyWiki community

### PR DESCRIPTION
**Pull request by Jermolene**
Following [a discussion on talk.tiddlywiki.org](https://talk.tiddlywiki.org/t/we-setup-a-chinese-forum/8206/2?u=jeremyruston), it is proposed to add a new section to HelloThere that highlights the international TiddlyWiki communities.

image

@linonetwo - I used Google Translate to get "华人社区", please correct to a better phrasing if needed

@sycom @xcazin - would it be a good idea to add a tiddler for the French community?

### CODE REVIEW

**Comment by linonetwo** [comment]
I would suggest 中文社区 , which take the "language" part of Chinese, instead of "race" part of Chinese. This means We also welcome Traditional Chinese users (currently it is mostly simplified Chinese users).

Anyway, thanks for adding this.

**Comment by Jermolene** [comment]
Thanks @linonetwo @xcazin.

@linonetwo - what links should be included for the Chinese community?

**Comment by linonetwo** [comment]
If just one link, let's use https://talk.tidgi.fun/topic/6 , so new users can start chatting with people immediately.

Though for a TiddlyWiki community, https://tw-cn.netlify.app is more appropriate because it is made of Tiddlywiki, so you can use 

```tid
# A Chinese community tutorial program that people can edit together:
#* Main site: [ext[https://tw-cn.netlify.app/]]
#* Accelerated access: [ext[https://tw-cn.cpolar.top/]]
#* Alternate: [ext[https://tiddly-wiki-chinese-tutorial.vercel.app]]
# Tiddlywiki Chinese Chat Forum: [ext[https://talk.tidgi.fun/topic/6]]
# Chinese translation of Tiddlywiki official website [ext[https://bramchen.github.io/tw5-docs/zh-Hans/]]
# The best Chinese introductory tutorial for newbies [ext[https://keatonlao.github.io/tiddlywiki-xp/]]
```

or Chinese version

```tid
# 大家可以一起编辑的中文社区教程项目：
#* 主站：[ext[https://tw-cn.netlify.app/]]
#* 加速访问：[ext[https://tw-cn.cpolar.top/]]
#* 备用：[ext[https://tiddly-wiki-chinese-tutorial.vercel.app]]
# 太微中文交流论坛：[ext[https://talk.tidgi.fun/topic/6]]
# 太微官网汉化版：[ext[https://bramchen.github.io/tw5-docs/zh-Hans/]]
# 最适合新手的中文入门教程：[ext[https://keatonlao.github.io/tiddlywiki-xp/]]
```

**Comment by Jermolene** [comment]
Thank you @linonetwo, I've updated the community tiddler. I've also moved the link up to the Quick Start section:

image

**Comment by Jermolene** [comment]
I've just noticed that this PR incorrectly targets the "master" branch. I'll recreate it to target "tiddlywiki-com".

**Comment by Jermolene** [comment]
The replacement PR is #7792

**Pull request closed without merging**
