### PR TITLE
Clicking an opened tab closes it

### PR DESCRIPTION
**Pull request by matthew-groth**
see the comment on my commit for my hesitations about this.

### CODE REVIEW

**Comment by matthew-groth** [comment]
Also, could someone explain why there are also the two "	Merge remote-tracking branch 'Jermolene/master'" commits here? Isn't that irrelevant since that's just me keeping my fork up to date?

**Comment by pmario** [comment]
So this PR folds the tab content area. right?
IMO this should be a second macro. The tabs default behavior shouldn't be changed in that way.

**Comment by pmario** [comment]
> Isn't that irrelevant since that's just me keeping my fork up to date?

It depends, which commands you use to pull from upstream. ... But I think github will optimize those commits away, if Jeremy merges it. ... 

Which command or software do you use to pull the latest version from github?

**Comment by matthew-groth** [comment]
I wouldn't say it folds it, rather it just reverses opening it. But we probably mean the same thing.

> Which command or software do you use to pull the latest version from Github?

I used the Github desktop app for these. I just thought it was a bit odd for these to appear in this PR, but I think you're right that it won't matter in the end.

**Comment by matthew-groth** [comment]
> IMO this should be a second macro. The tabs default behavior shouldn't be changed in that way.

I can see why some people might prefer opened tabs to not be closeable. I do think this should be available for people with less effort though, and an entire new macro seems like overkill. 

I was thinking of adding a boolean parameter that defaults to the old way like `closeable="false"`, but I wouldn't know exactly how to add that in without again adding another reveal widget. 

Is there an easy way to do a boolean `if` statement? If not, I'll go ahead and wrap another `$reveal` around the whole thing for both cases, but I'm concerned that's not an efficient way to do this.

**Comment by tobibeer** [comment]
> I wouldn't say it folds it, rather it just reverses opening it. But we probably mean the same thing.

Imho, the default should always be the first, unless specified otherwise as in #2701. So, the usecase of "display no contents" should be the explicit exception... where your handling would be desirable.

**Comment by matthew-groth** [comment]
One example of when this could be very useful is on mobile or otherwise narrow windows. The sidebar is displayed above the opened tiddler in this case, so I often want it to go away.

**Comment by tobibeer** [comment]
Good point. For that, I would prefer a conditional sidebar, w/ general tabs on a desktop but toggling on mobile, leveraging some variable-based conditional attribute depending on environment variables.

**Comment by matthew-groth** [comment]
I'd just like to emphasize the "otherwise narrow windows" part. This issue actually comes up most often for me on desktop, since I sometimes like running TW in a narrow window off to the side of my screen. So I think it should be based on window size and not device. Perhaps this is what you meant, but just making sure.

**Comment by tobibeer** [comment]
> So I think it should be based on window size and not device.

Whatever floats your boat. To me, this is under the umbrella term "environment".

**Comment by matthew-groth** [comment]
Closing because not everyone might want this and also I should have made it on a separate branch on my fork

**Comment by Jermolene** [comment]
Hi @matthew-groth this functionality would perhaps make a useful plugin...

**Pull request closed without merging**
