### PR TITLE
Fix tiddlers should not be interactive after being closed

### PR DESCRIPTION
**Pull request by Jermolene**
The problem identified in #8341 is that in the classic story view it is possible to interact with a tiddler while the "close tiddler" animation is running. In particular, typing into the tiddler after closing it will create a new draft.

This PR fixes the problem by cloning the DOM node that is being removed, and animating the clone, allowing the original DOM node to be deleted immediately.

The only problem I have found is that when editing an image tiddler the image will briefly appear blank while the tiddler is closing. This is because the underlying DOM "cloneNode()" method doesn't replicate the content of canvases. I think we could fix that by manually copying canvas content, but I am not sure that it is worth the investment.

### CODE REVIEW

**Comment by oeyoews** [comment]
It looks like the issue is resolved, but it has brought about some minor problems. First, the editing area seems to flash black for an instant. Secondly, I'm concerned about the performance. Using the cloning element method seems to cause a slight delay when closing, although it's not very noticeable. @Jermolene 

https://github.com/Jermolene/TiddlyWiki5/assets/72405338/50665339-9168-4596-bb47-83838147694a

**Comment by Jermolene** [comment]
Thanks @oeyoews your video is very interesting – there are a few frames where the tiddler appears black:

image

I am not seeing the same behaviour, but it seems plausible that the differences are related to the browsers graphics support. I will investigate the alternative approach of just disabling the event handlers for the DOM nodes that are being exited.

**Comment by pmario** [comment]
With my tests I could not replicate the "black" area. For me it was just a white background, with not text on it. Using FF and windows 11 - Same with FF and ubuntu 22.04 -- So it seems to be a FireFox thing.

**Comment by Jermolene** [comment]
Hi @oeyoews @pmario I've changed this PR to an alternative, and much simpler fix: detect if the current focus is within the DOM nodes we're about to remove, and if so just blur the focus to remove it.

This appears to fix the OP in narrow terms: it resolves the problems of interacting with a departing element via the keyboard, but it is still possible to interact with a departing element via the mouse.

**Comment by oeyoews** [comment]
> Hi @oeyoews @pmario I've changed this PR to an alternative, and much simpler fix: detect if the current focus is within the DOM nodes we're about to remove, and if so just blur the focus to remove it.嗨，我已将此 PR 更改为另一种更简单的修复方法：检测当前焦点是否在我们将要删除的 DOM 节点内，如果是，只需模糊焦点即可将其删除。
> 
> This appears to fix the OP in narrow terms: it resolves the problems of interacting with a departing element via the keyboard, but it is still possible to interact with a departing element via the mouse.这似乎从狭义上解决了 OP：它解决了通过键盘与离开元素交互的问题，但仍然可以通过鼠标与离开元素进行交互。

I tested it, it seems ok

**Comment by pmario** [comment]
@Jermolene -- I have never been able to reproduce the problem described in the original issue, with any of my browsers. So do not wait for my feedback.

**Comment by Jermolene** [comment]
> @Jermolene -- I have never been able to reproduce the problem described in the original issue, with any of my browsers. So do not wait for my feedback.

Hi @pmario that is frustrating. Have you tried the reproduction steps listed in #8341?  I think the instructions are pretty clear, but they do need to be followed precisely – in particular you must use the keyboard as described:

1. Visit https://tiddlywiki.com/
2. Use control panel to adjust animation speed to (say) 2000
3. Click the "new tiddler" button
4. Start typing in the body of the tiddler then – quickly – type "ctrl-enter" and then just as quickly type some additional random characters
5. Look at the "Recent" tab to see an unexpected draft tiddler

I think it is quite important that we are all able to share the same experience of using the software, so it would be helpful if you were able to give it another try and see if we can figure out what could possibly be going wrong with such a simple sequence of steps.

**Comment by pmario** [comment]
@Jermolene -- Sorry. I did not switch to the **Recent** tab. -- This PR seems to fix the problem

**Comment by Jermolene** [comment]
Great thank you @pmario that's very helpful.

**Comment by oeyoews** [comment]
image This reminds me of this, why is the draft tiddlers generated but not displayed in the tiddlywiki UI? Is there some lack of processing? In this special case @Jermolene 

> @Jermolene -- Sorry. I did not switch to the **Recent** tab. -- This PR seems to fix the problem

**Comment by pmario** [comment]
>This reminds me of this, why is the draft tiddlers generated but not displayed in the tiddlywiki UI? Is there some lack of processing? 

If Draft tiddlers exist, a tiddler is in edit mode. 
If an "open" tiddler is removed from the $:/StoryList tiddler, it is automatically shown at the bottom of the view template. 
That's a protection against data-loss. 

Some users managed to create several new draft tiddlers with the same title. Then they saved all of them and did overwrite there own content. -> That's why those "Draft Reminders" have been created.

**Comment by Jermolene** [comment]
> This reminds me of this, why is the draft tiddlers generated but not displayed in the tiddlywiki UI? Is there some lack of processing? In this special case @Jermolene

The reason that the draft tiddler appears in the recent tab but not as one of the red "draft reminders" at the bottom of the window is that this isn't a real draft tiddler – it lacks the "draft.of" and "draft.title" fields.

**Comment by oeyoews** [comment]
Can this patch be merged now? Recent versions of codemirror6 are quite affected by this bug, and the problem now is that the focus event is always stuck on the draft entry. This patch to tiddlywiki seems to fix this problem as well. @Jermolene 

https://github.com/user-attachments/assets/c7b01fdf-7648-4815-a22d-d7f4a1c356f8

**Comment by Jermolene** [comment]
Thanks @oeyoews

**Comment by oeyoews** [comment]
https://cm6-tw5-bug.tiddlyhost.com 

Well, I'm back again. After I upgraded to codemirror6 and tiddlywiki prelease, I changed the transition time to zero, but the draft entry still appeared. Unlike before, now the draft entry will not appear only when the transition time is non-zero.

I'm not sure if it's a problem with tiddlywiki or codemirror, because the draft entry is still affected by excessive time. I'm more sure that the integration between the new version of codemirror6 and tw is not handled properly. I'm a little exhausted. This is just a record. I may not have time to check this problem recently. So I won't upgrade the version of codemirror6.

**Comment by oeyoews** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/EditContext I tested this bug on Firefox and it didn't reoccur. It only appeared on Chrome. I think this is a bug in Chrome's editcontext API (because the author of codemirror6/view has been modifying this recently).

https://github.com/codemirror/view/commits/main/

> https://cm6-tw5-bug.tiddlyhost.com
> 
> Well, I'm back again. After I upgraded to codemirror6 and tiddlywiki prelease, I changed the transition time to zero, but the draft entry still appeared. Unlike before, now the draft entry will not appear only when the transition time is non-zero.
> 
> I'm not sure if it's a problem with tiddlywiki or codemirror, because the draft entry is still affected by excessive time. I'm more sure that the integration between the new version of codemirror6 and tw is not handled properly. I'm a little exhausted. This is just a record. I may not have time to check this problem recently. So I won't upgrade the version of codemirror6.

**Comment by Jermolene** [comment]
Thanks @oeyoews, frustrating.

**Pull request merged**
