### PR TITLE
Add podcast link

### PR DESCRIPTION
**Pull request by FND**
not sure this is the right place, but I figured it deserved being mentioned somewhere - so feel free to reject this and put the link elsewhere (or rephrase, for that matter)

### CODE REVIEW

**Comment by pmario** [comment]
@FND cool that you "pinged" "the changelog"

@Jermolene Was a nice show. ... this PR may be one to be closed fast :)))

**Comment by Jermolene** [comment]
Thanks @FND, much appreciated. It was fun to do. Apologies for bureaucracy but would you mind signing the CLA please?

**Comment by FND** [comment]
I've updated this PR accordingly. In case that's invalid (i.e. I can't sign the CLA while remaining a "genderless, faceless person" :bow: ), it might be easier for you to just reject this and rephrase it.

**Comment by Jermolene** [comment]
Thanks @FND, it's great to have you as a contributor.

**Pull request merged**
