### PR TITLE
Adding the missing 'language' type

### PR DESCRIPTION
**Pull request by Spangenhelm**
What about the 'core-version' field ? Should we add it ? Therefore we will need to add some doc about it. (how to use it correctly etc...)

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @Spangenhelm thanks, yes we probably should document the core-version field too.

**Comment by Spangenhelm** [comment]
Hi @Jermolene, sorry i have forgotten to modify the table entry in the same tiddler, is it worth opening a new pull-request ? I don't mind doing so i'm just asking for the best way to handle this kind of situation.

Also do you remember that you've had removed the docs about core-version in 2013 ? Do you need help "restoring" it ? Let me know..

**Comment by Jermolene** [comment]
Hi @Spangenhelm yes please do send a new pull request.

> Also do you remember that you've had removed the docs about core-version in 2013 ? Do you need help "restoring" it ?

No, I'd forgotten, can you point to the commit?

**Comment by Spangenhelm** [comment]
Hi @Jermolene apparently the commit about the core version is this one (removed in 2013) : https://github.com/Jermolene/TiddlyWiki5/commit/8496337d30019559a1b4dad5cc456164cd990021

I have just added the modification we have talked about and send a pull-request for it.

+

**Pull request merged**
