### PR TITLE
Missing advice in Contributing.tid 

### PR DESCRIPTION
**Pull request by felixhayashi**
Hi @Jermolene,

I am adding CLAs to my project as well and I noticed the following:

In the CLAs it says

> If You do not own the Copyright in the entire work of authorship, please follow the instructions in contributing.md, which is in the root directory of the project repository.

However as for TiddlyWiki5, there is no advice given on how to handle such situation in the `contribution`.md

Hence this pull request.

-Felix

### CODE REVIEW

**Comment by sukima** [comment]
These two commits would be better squashed together `git rebase --interactive`. Also a commit message with a body explaining the above situation (described in the pull request message about missing advice in one file referencing another). That way when a `git blame` stumbles on this change it will make sense instead of "Updating Contributing... well figured that based on the diff but why, what motivated someone to add that? there must have been a reason at one time. Oh well guess it wasn't too important, I think it will be ok to edit/delete this part." See the whoops? Now granted this is a text file not code but the principle is the same. Food for thought.

**Comment by felixhayashi** [comment]
Hi @sukima 

> Also a commit message with a body explaining the above situation (described in the pull request message about missing advice in one file referencing another).

I usually put the explanation in the pull request message. Maybe you are right, I should include it in the commit as well.

> These two commits would be better squashed together

I thought rebase only works for different branches, didn't know I can merge two commits of the same branch. Anyhow, I used the github ui for this patch with quick copy paste, no terminal so I take your advice for the next time...

-Felix

**Comment by sukima** [comment]
I'd do it but it would create a new pull request since I don't have access to force push your branch. However, whoever merges this pull request can do it during the merge.

**Comment by Jermolene** [comment]
@sukima I think that if I collapse the pull request then it appears in GitHub as being my commit; I think @felixhayashi gets erased from the history. How do other projects handle this?

**Comment by sukima** [comment]
@Jermolene I think that during a rebase the commiter gets changed but the author stays. I do know git lets you set the author as part of the commit message.

In my recent explorations with interactive rebasing on github it recognizes that I rebased a commit by someone else and places them as the author (big avator picture) and myself as a commiter (little avatar overlay). An example were I rebased and squashed a coworker's pull request:

screen shot 2015-03-10 at 5 26 50 pm

**Comment by Jermolene** [comment]
Thanks @sukima that's encouraging. I'll give it a shot tomorrow.

**Comment by Jermolene** [comment]
OK, I've failed to figure it out, I'm afraid, so I'm merging as is. Reading around, it does look like some projects insist that contributors squash their pull requests before submission, perhaps we should take that route.

**Comment by sukima** [comment]
@Jermolene Oh! I bet I know other projects "insist that contributors squash their pull requests before submission." Because to rebase requires write access to the repo with that branch and with forks that is not the case. In the example I gave both parties had write access to the same repo.

I apologize I don't know why I didn't think of that before. Your last comment must have spurred my brain.

**Comment by Jermolene** [comment]
Ah, thank you, good, that makes sense.

I'm cautious about requiring pre-squashed pull requests, though, for fear of putting off more of our contributors, many of whom are git neophytes. But on the other hand I'm painfully aware that the project commit history is not always as readable and neat and tidy as I'd like.

**Pull request merged**
