### PR TITLE
Overhaul the macro and variable documentation

### PR DESCRIPTION
**Pull request by aelocson**
Phase two of the documentation overhaul. This covers the tiddlers in the `macros` and `variables` folders, although there are tiny knock-on effects in a lot of other files, too.

I've added railroad diagrams for the syntax of macro definitions, macro calls, and the value of the `transclusion` variable.

As with the filter operators, I've split the examples out into their own tiddlers and given each example a "Try it" button.

I've used macros to ensure that all results shown are directly generated from the example source shown. In cases where a `\define` pragma forms part of an example, I've placed the pragma in a tiddler of its own and then said:

    <$importvariables filter="$:/editions/tw5.com/macro-examples/say-hi">
    <$codeblock code={{$:/editions/tw5.com/macro-examples/say-hi}}/>
    
    </$importvariables>

I discovered that several of the core macros weren't documented at all, so I've rectified that.

I've also introduced `definitions` tiddlers for Base64, CSS, CSV, JSON, and data URIs.

I've put a preview of the documentation changes in this pull request at:

http://ae-doc-preview.tiddlyspot.com/

### CODE REVIEW

**Comment by nicholas-spies** [comment]
Dear @aelocson ,
I am in awe of you work!
I was wondering if you saw any value at all in my attempt to reduce the documentation that I have had access to into an outline form, which at least I (as you might imagine!) find to be much more readable, as is a way of parsing the meaning for the documentation, just as one would take notes at university.

The trouble is is that I am not conversant with posting what I have done, for people to review and give their opinions about it. I send, instead a tiny bit of it as a couple of  picture for you to look at:
random text
and

**Comment by nicholas-spies** [comment]
...here is the other picture. My intention is to have this format serve the full spectrum of needs for documentation for beginners to developers. Here is the way I describe transclusion in the documentation itself, making it a kind of built-in tutorial. Please give me an honest appraisal of this approach, for if it is not to the taste of more informed people such as yourself, it is wasted effort. BTW: I do have knowledge enough to have any opinion of your work (not that it is directed to such as I to begin with, but as it is the diagrams are generated by program they are a big win. I believe that the outline forms I present here could also be achieved by programming, perhaps derived from the programmer's documentation at least largely automatically. Many thanks for your tremendously important contributions.

**Comment by nicholas-spies** [comment]
translusion

**Comment by aelocson** [comment]
@nicholas-spies,

Many thanks for your kind comments and for posting these interesting images. I remember this documentation technique being discussed on a hangout a few weeks ago.

Hierarchical bullets are excellent for making notes in which each item is essentially an independent sentence (and often an abbreviated one). But I'm not convinced that comprehension is improved by breaking a complete fluent sentence into such a structure.

It's fundamentally a matter of form and content. For the content to be as clear and easy to understand as possible, the *form* in which it's expressed needs to be so consistent that it quickly retreats into the background of the user's mind, allowing the meaning to come to the front. This is why it's so important for the documentation to be written with a consistent style and vocabulary.

Your suggested "poetic" layout is inconsistent with the way in which sentences are normally presented in the world. As a result, I feel it draws too much attention to itself and actually makes it harder to understand the content.

It also makes each tiddler less compact, with the result that one has to scroll more to see everything about a topic. And it makes each sentence seem more intricate than it really is. (In revising the TiddlyWiki documentation, one of the things I'm doing is trying to flatten out any excessively nested lists.)

I'm very aware (perhaps too aware!) that sentences can be parsed into a tree structure, just as computer code can. Perhaps this is contributing to my sense of unease with your suggestion, as the way you've split the sentences up doesn't match the parse tree. To take the very first item in your first image as an example:

> TiddlyWiki is designed
> * to be non-linear,
> * structuring content
>   * with stories, tags,
>   * hyperlinks,
>   * and other features.

Why is "structuring content" a sibling of "to be non-linear"? (It makes no sense to read "TiddlyWiki is designed structuring content".) Why is "with" part of the first child under "structuring content", when it's actually part of the expression that introduces the whole list? Why does "tags" not have a bullet point of its own?

I'm not meaning to criticise the exact way in which you've rendered that particular sentence. Rather, I'm suggesting that it would require a vast amount of effort to produce this layout in a consistent way, because there are so many fiddly little problems to worry about and deal with.

Your technique would work much better if the content involved was fragmentary and note-like, rather than consisting of fluent sentences. But then it would probably be too abbreviated for a newcomer to make much sense of.

With regard to the idea of the explanatory text using itself as its own example, this is a lovely elegant concept, but I fear it would bewilder the average reader of the documentation. (I notice that your text even mentions this possibility, and is duly peppered with meta-text to clarify which part is which.)

The community is crying out for a simple linear explanation of this magnificent non-linear machinery, hence the work Eric Shulman is doing on writing a book. The documentation on tiddlywiki.com consists of material for newcomers (which should surely be presented in as normal a way as possible) and reference material for those who have embarked (which I think should be presented in a way that is clean, compact and distraction-free).

**Comment by aelocson** [comment]
I've put a preview of the documentation changes in this pull request at:

http://ae-doc-preview.tiddlyspot.com/

**Comment by nicholas-spies** [comment]
Dear Astrid (and others reading this),

Yours is definitely the most cogent expression of why my attempt to
"explode" the documentation into an outline form with lots of white space
should probably be abandoned. You have picked out many misgivings that I
have been confronting myself with this approach, as your analysis of the
first bit of text reveals. This is why it has taken me several iterations
to get to this point, and yet another iteration probably would have
addressed some of the inconsistencies you have spotted—which could easily
turn into a near-infinite regress of modifications. The fact that this has
been so laborious in itself should have led me to understand its failings,
and I do not take issue with any of the points you raise, as all are
well-taken.

Thank you for seeing the value—and pointing out the disadvantages—of my
attempt to use an explication of the structure of the documentation itself
as a kind of tutorial. However, I agree that this too results in a lot of
explanation—as if, in a book, the footnotes were longer than the text!

My only explanation for started down this path is that have been mildly
dyslexic since childhood, as I mentioned to Jeremy, which makes reading for
me a bit of a chore, so my "pre-parsing" of the text seemed to be a way of
my avoiding misunderstanding it, to prevent back-tracking, and so forth. I
realize that this problem is my own and hardly appropriate to inflict upon
the public at large. (And probably explains why I became a video editor
rather than an author.)

I leaped at the opportunity to join with Erik Shulman's to help write his
book, precisely because it is a book (not a TiddlyWiki file). I have been a
video editor most of career and co-authored a text on the Forth language
(Forth: A Text and Reference, Kelly and Spies, Prentice Hall, 1986). Both
experiences, as well on some work on branching multimedia projects, have
lead me to the conviction that there exists an "optimal path" that is
obvious most obvious when working in linear media, as being the best way to
create such material for an intended audience, be it to develop a dramatic
narrative or to explain an industrial process, or get a president elected
[I cut about one quarter of the national campaign spots (ads) for Carter in
1976 and devised an original workflow to do so for nearly all of them].

Of course, there is no "law" that determines which, of the myriad possible
ways material may be presented, should be presented (unless you have the
freedom of an independent artist, who has earned this right by public
acclaim). It is often realized by a process of exploration and consensus,
first between co-authors and feedback provided by (book) editors or test
audiences, reworking the material to satisfy the local audience, who act as
"representatives" of the final audience for the work, down to the point
that the work is released.

The trouble with creating documentation in a branching medium is that the
"optimal path"—the best way of learning—is obscured by the very flexibility
that make the branching media so attractive for a host of other tasks. I
suggested at one point that if TiddlyWiki were to be used as a distribution
medium for its own documentation, it should be somehow "locked down" so
that the documentation reflects A) its purpose to teach (different levels)
of users and, B) its use as a reference by any class of user. This is a
noxious design issue in itself, as it is impossible to anticipate where A)
stops and B) begins.

Again, in my mind, this makes it almost mandatory to have the documentation
in form of a book (which is primarily linear, but can be read in any order,
and can satisfy reference needs with tables of contents and figures,
appendices, and a large index).

Thanks again for your keen observations,

Best wishes,

Nicholas Spies

**Comment by aelocson** [comment]
> as if, in a book, the footnotes were longer than the text!

A very tangible analogy! (I've seen books like that, and they make me shudder.)

When an explainer has to also explain their method of explanation, the result is likely to be convoluted.

> my "pre-parsing" of the text seemed to be a way of my avoiding misunderstanding it, to prevent back-tracking, and so forth.

Very interesting. It might be possible (albeit not easy) to create a plugin that used a natural-language parsing library to break a sentence into its constituent phrases and produce a corresponding spaced or tiered display.

> there exists an "optimal path"

It depends on the nature of the content. There's no optimal path through a dictionary or an encyclopedia, and TiddlyWiki's reference documentation is similar to that: the user looks up what they need to know, and follows cross-references to related topics as desired. That seems fine.

On the other hand, there *is* presumably an optimal path to be found through the tutorial material, and this definitely deserves to be found. A newcomer perusing the Concepts branch of the table of contents on tiddlywiki.com would be overwhelmed, and have no idea where to start.

It would be nice if they could instead start by reading a sequence of tiddlers that would guide them through the main ideas, gradually bringing them up to speed. It's difficult, though, as so many of the concepts are interdependent, and people differ so much with regard to what they already know.

> The trouble with creating documentation in a branching medium is that the "optimal path"—the best way of learning—is obscured by the very flexibility that make the branching media so attractive for a host of other tasks.

Yes. The mistake is to write the tutorials as if they're reference material.

But note that it's easy enough to link tiddlers together into an ordered sequence, with each one ending with a link to the next, and to avoid including any other links. In other words, it's easy enough to encourage the reader to tackle a set of topics in order.

**Comment by nicholas-spies** [comment]
It gladdens me to have been disabused of my folly by one who seems to share my thoughts about many things. Now I see quite clearly that I must not only learn JavaScript to make any sort of contributions that matter, as well as being satisfying to me, and that I must also study the work of others to appreciate the layers of abstraction (macros, filters, plugins, etc and their syntax) that work together to produce the magic that TiddlyWiki is capable of producing.

In this regard, I downloaded and started reading ae-doc-preview, until I had to retire. I found it to be a wonderfully clear and look forward to understanding TiddlyWiki far better for having read it fully.

My sincere thanks for taking the time to make your comments and observations. I can only hope that some day I shall be able to return the favor.

--Nick Spies

**Comment by Jermolene** [comment]
Thanks @aelocson, I'm deeply grateful for your dedication to improving the documentation. There's a lot of work here, but you make it look easy. 

I've uploaded a new prerelease to http://tiddlywiki.com/prerelease

**Comment by aelocson** [comment]
@Jermolene, I'm a bit baffled by this merge conflict. The only problem the git command line found when I tried to merge your master was the `modified` date field in editions/tw5.com/widgets/LinkWidget.tid.

I've resolved that (taking two attempts, because I forgot that my text editor would automatically update the modified field, reintroducing the same conflict…). I've pushed the change to my variable-docs branch, but the pull request is still claiming to be in conflict.

Possibly it's because there have now been *three* changes to the `modified` field, even though my latest one should be the same as yours in 950a86c7b75ae4b3454d707022b2ee4e49c1f2f8..

I wonder why GitHub provides no way of seeing *which* files are in conflict. It must know.

**Comment by aelocson** [comment]
Ah, I seem to have solved this by doing a wholesale replacement of LinkWidget.tid with the copy from your master branch. Once you've merged this pull request, I'll send another with the tiny change I wanted to make to that file.

**Comment by Jermolene** [comment]
Thanks @aelocson

**Comment by Jermolene** [comment]
By the way @aelocson I wondered if you'd be able to attend a hangout? It would be great to have you in the discussions about documentation. Would a different time/day suit you better than the regular Tuesday 4pm GMT slot?

**Comment by aelocson** [comment]
The main difficulty is my low broadband speed. I watch the hangouts by first downloading them from YouTube, and a typical two-hour one takes me over 45 minutes to download. I suspect that if I tried to watch live, the feed would be too choppy to make much sense of.

**Comment by aelocson** [comment]
There's also the question of bandwidth. I work from home most of the time, and my internet connection (which suffices for my normal use of it) is paid for my employer, but is limited to 15GB a month. I normally download the hangout on the one day a week that I spend in the office. (A two-hour hangout downloads in about 2 minutes there.)

**Comment by aelocson** [comment]
> Once you've merged this pull request, I'll send another with the tiny change I wanted to make to that file.

It turns out there's no need: the merge has successfully handled that.

**Comment by Jermolene** [comment]
Hi @aelocson understood about bandwidth (and pretty cool that you can download the hangouts so easily). If there is a time when you know ahead of time that you'll have access to bandwidth do let me know, I'd be very happy to arrange a hangout around your availability (rough UK working hours can mostly work for me, and sometimes other times too). I want to experiment with different time slots for the hangout so it's good to have a reason!

**Comment by nicholas-spies** [comment]
As you may know, today FireFox came out with a video phone over IP
capability, which I haven't tried yet, but could well be better than Google
Hangouts, which have well-known limitations that many have groused about.
Astrid, audio-participation would take a fraction of the bandwidth of
video, as you doubtless know.

--Nick

**Comment by aelocson** [comment]
@nicholas-spies, my concern about the bandwidth was more about receiving than sending: there's presumably no way to avoid receiving the video content of the hangout along with its audio. Audio participation isn't possible for me at the moment anyway, as I don't have a microphone (or a webcam). My comments would be limited to the sidebar.

But I'll try and be at next Tuesday's hangout as a feasibility test.

@Jermolene, the hangouts are extremely easy to download using youtube-dl.

**Comment by nicholas-spies** [comment]
Astrid,

Sorry for the inaccurate data. A cheap headset would cure the audio
problem, and VGA webcams can be had for US$15 or so, if you are near a
friendly hole-in-the-wall Taiwanese computer shop, if such exist where you
are located, It would be interesting to know TW participants' respective
bandwidths compare and how they deal with them,. Mine is fiber-optic to
house --> 100Mb ethernet inside, at a nominal rate of 75 Mbps—up and down;
pathetic by world-wide standards, but very fast for the US.
--Nick

**Comment by aelocson** [comment]
Certainly I can buy a headset and webcam. But there's no point if my connection can't keep up. That's why I'm interested to try the hangout on Tuesday, to see what happens.

**Comment by nicholas-spies** [comment]
What is your connection speed, if I may ask?

**Comment by aelocson** [comment]
It rarely gets above 1Mbps.

**Comment by nicholas-spies** [comment]
I'm sorry to hear that :-( I should think that at least telephone-quality
audio would succeed in getting through, or at least hope so when you try it.

Good luck!
--Nick

**Pull request merged**
