### PR TITLE
Fix tiddler title alignment if no icon is acitve

### PR DESCRIPTION
**Pull request by pmario**
The tiddler title is miss-aligned by 0.1em margin right from an empty span, if no icons are specified. 

The image shows it all. "Hello There" text is moved to the right, because of the `.tc-tiddler-title-icon` margin-right setting. 

The PR fixes the miss-alignment, because the span is only included into the DOM, if a tiddler icon-field or $:/config/DefaultTiddlerIcon is defined.

tiddler-title-not-aligned-if-no-icon

### CODE REVIEW

**Comment by pmario** [comment]
@Jermolene ... Don't merge yet. The span also makes the title line higher, which is a side effect that is needed. I will probably need to adjust a CSS setting.

**Comment by pmario** [comment]
@Jermolene .. Can be merged now. .. The line height fix is needed for titles that contain chars like "g".

**Comment by Jermolene** [comment]
Thanks @pmario

**Comment by Jermolene** [comment]
Thanks @pmario

**Pull request merged**
