### PR TITLE
Add syncer status hook and option to disable polling

### PR DESCRIPTION
**Pull request by Arlen22**
Please merge https://github.com/Jermolene/TiddlyWiki5/pull/5880 first, unless you just want to merge these two commits in without squashing them.

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @Arlen22 it looks like conflicts need to be resolved now that #5880 is merged.

**Comment by Arlen22** [comment]
@Jermolene ok, I resolved the conflicts, which did not result in any changes, as expected, so it should work now.

**Comment by Arlen22** [comment]
Don't merged yet though, it looks like something still might be missing. I'm double checking everything right now.

**Comment by Arlen22** [comment]
Alright, it was just easier to make a new one to make sure nothing got lost. 

https://github.com/Jermolene/TiddlyWiki5/pull/5882

**Pull request closed without merging**
