### PR TITLE
fix for sidebar not showing #3223

### LINKED ISSUE #3223: sidebar retain causes sidebar not to show
test: tiddlywiki.com and tiddlywiki.com/prerelease - click the hide-sidebar button and click it again -> sidebar doesn't show content

only happens if retain="yes"

### PR DESCRIPTION
**Pull request by BurningTreeC**
I believe this fixes #3223

### CODE REVIEW

**Comment by BurningTreeC** [comment]
@Jermolene - too late for 5.1.16?

**Comment by BurningTreeC** [comment]
just bumping this for the release :medal_sports: 

:laughing:

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Comment by BurningTreeC** [comment]
Thanks @Jermolene - about the prerelease docs - it's more a fix for sidebars not **showing**

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Pull request merged**
