### PR TITLE
Ask permission Jermolene for make a pull request

### PR DESCRIPTION
**Pull request by koke24**
Hi, Jermolene

I want to make a pull request for some changes I have done on TiddlyWiki. I added a way to save the user name to a cookie so it is loaded everytime you log in the wiki. This way your changes are always signed.

Regards

### CODE REVIEW

**Comment by sukima** [comment]
## Nit Pick

The commit message _Ask permission Jermolene for make a pull request_ seems disconnected from the code change:

```diff
diff --git a/licenses/cla-individual.md b/licenses/cla-individual.md
index 1e6018d..b219cb0 100644
--- a/licenses/cla-individual.md
+++ b/licenses/cla-individual.md
@@ -266,3 +266,5 @@ Matthew DeAbreu, @mdeabreu, 2016/01/05
 Cameron Fischer, @flibbles, 2016/01/08
 
 Jim, @ARRRRGH, 2016/01/11
+
+Koke Laast, @Koke24, 2016/01/27
```

Perhaps _Add Koke Laast as a contributor with CLA Signing_ would make more sense.

**Comment by Jermolene** [comment]
Hi @koke24 thanks, and welcome to the project

**Comment by Jermolene** [comment]
Ah, I guess I ought to have corrected the commit text as I was merging, apologies @sukima.

**Comment by Jermolene** [comment]
@sukima I've added a note to the agenda for this afternoon's hangout if you can join us:

http://hangout-96.tiddlyspot.com/#LoweringBarriersToContribution

**Comment by koke24** [comment]
Hi, @sukima 

I am a total freshman with this thing of GitHub. I am sorry for the unrelated title :-)

Best regards

**Comment by sukima** [comment]
@Jermolene, I apologize with the timezone difference (Eastern/UTC-5:00) I'm currently at work and could not attend.

**Pull request merged**
