### PR TITLE
Use qualified-preview-state in default body-editor for reuse in preview button

### PR DESCRIPTION
**Pull request by BurningTreeC**
The preview button and the default body-editor don't share the same `showeditpreview` state anymore when it's qualified
This can be seen when the `$:/config/ShowEditPreview/PerTiddler` tiddler is set to yes and one tries to open the preview in the current prerelease -> nothing happens
This PR assures that both the body-editor and the preview use the same qualified state

### CODE REVIEW

**Comment by BurningTreeC** [comment]
Hi @Jermolene

Could this be considered?

**Comment by pmario** [comment]
I can confirm, that `$:/config/ShowEditPreview/PerTiddler = yes` creates a problem in the current prerelease. 

This PR seems to fix it.

**Comment by Jermolene** [comment]
Oops sorry @BurningTreeC I just noticed that there are merge conflicts. Are you able to resolve those? Many thanks

**Comment by BurningTreeC** [comment]
Hello @Jermolene I will solve the merge conflicts asap

**Comment by BurningTreeC** [comment]
Hello @Jermolene - The merge conflicts are now resolved and I tested this and it seems to work correctly. Please test

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Pull request merged**
