### PR TITLE
Introduce railroad plugin

### PR DESCRIPTION
**Pull request by aelocson**

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @aelocson, this is very high quality.

Something I've only just noticed is that the diagram source is evaluated as JavaScript. Even though we use the boot kernels' sandbox the JavaScript will in fact have global access in the browser.

The implication of that is that wikis that include the railroad plugin would provide a vector for malicious wikitext tiddlers to steal data. That's an obstacle to syndicating/federating content.

The best solution I can think of would be to require that the railroad diagram source be within a JavaScript module tiddler, with the module-type set to "railroad-diagram". The railroad widget would need a tiddler parameter to identify the diagram to be rendered.

We need to filter JavaScript modules in any case for federation/syndication.

**Comment by aelocson** [comment]
That's a good point, @Jermolene. I hadn't realised that $tw.utils.evalSandboxed exposes the global scope, but closer investigation shows that this is indeed the case.

Another solution would be for the railroad widget to parse its content itself (rejecting anything invalid with an informative error message) and then internally make the corresponding JavaScript calls to the library. In this way we could reduce the content's syntax to something less clunky, say by using

* `[a]` instead of opt(a)`
* `{a}` instead of rep(a)`
* `[{a}]` instead of optrep(a)`
* `(a b c)` instead of seq(a, b, c)`
* `(a | b | c)` instead of alt(a, b, c)`
* `"a"` instead of lit(a)`
* `/a/` instead of box(a)`
* `:abc:` instead of com(abc)`

and by not requiring the outermost call to syn() / Diagram().

This would be easier for me to implement. At present, I'd be floundering if I tried to implement a new module type.

**Comment by Jermolene** [comment]
> Another solution would be for the railroad widget to parse its content itself (rejecting anything invalid with an informative error message) and then internally make the corresponding JavaScript calls to the library

Yes, that would definitely be much the cleanest and most elegant approach.

> This would be easier for me to implement. At present, I'd be floundering if I tried to implement a new module type.

To be honest, it's not a great solution - there wouldn't be an easy way to support the live preview, for instance. So if you're comfortable writing a parser, then please go ahead, I think it would be cool.

**Comment by aelocson** [comment]
No problem. I'll close this pull request and later in the weekend open a new one… or rather two – one for the plugin and a separate one for the FilterSyntax tiddlers.

**Pull request closed without merging**
