### PR TITLE
Steps towards effective Arabic translation of Tiddlywiki

### PR DESCRIPTION
**Pull request by Kamal-Habash**
Hi Jermolene and Tiddlywiki community

This is my first Github contribution, and I have to say , I really like Tiddlywiki and  I appreciate all the great work. 

This is a humble contribution which contains an Arabic translation of 603 strings out of the proposed 941 strings in the translator edition. I hope you'll find these contributions significant to be merged in the master

I'll be working soon to finish the translator's edition strings, and I'll create a proper cascading for the Arabic tiddlers. 

Regards

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @Kamal-Habash I'm very happy to receive another translation, and hope that it will help bring TiddlyWiki to a wider audience. 603 strings out of 941 makes it already one of our more complete translations.

For our existing Farsi translation we use an experimental feature that switches the page to right-to-left mode, which may be more suitable for this translation too:

https://github.com/Jermolene/TiddlyWiki5/blob/master/languages/fa-IR/plugin.info#L8

**Comment by Jermolene** [comment]
Hi @Kamal-Habash my apologies for the delay, I think this is good to merge but please could you first prepare a separate PR targetting the 'tiddlywiki-com' branch with your signature for the Contributor License Agreement (see [contributing.md](https://github.com/Jermolene/TiddlyWiki5/blob/master/contributing.md)).

**Comment by Kamal-Habash** [comment]
Hi @Jermolene , 
forgive me for  this elementary question , but I am new to this,
I did sign the CLA , do I need to create the language as a branch in tiddlywiki-com ?

**Comment by Jermolene** [comment]
Hi @Kamal-Habash 

>  do I need to create the language as a branch in tiddlywiki-com ?

No, updates to the core should target the "master" branch, as you have done.

**Comment by Jermolene** [comment]
Hi @Kamal-Habash I've updated the translation to use `"text-direction": "rtl"`, and also added the new translation to the "Full" edition. In 5 minutes or so you'll be able to try it out at https://tiddlywiki.com/prerelease/editions/full/index.html

**Comment by Kamal-Habash** [comment]
Thanks @Jermolene , This is Cool ! ,
I noticed that you and @kookma  worked on a enhancing a feature for bidirectional contents at  https://github.com/Jermolene/TiddlyWiki5/pull/4541 

and @kookma did a nice work here at http://kookma.rtl.tiddlyspot.com/ 

I think this a great solution for bidi contents that don't compromise the readability of . how can I add this to my Arabic TW ?

**Pull request merged**
