### PR TITLE
Don't steal focus to the type input field if autofocus is set to "text"

### PR DESCRIPTION
**Pull request by BurningTreeC**
Another try making this PR happen

### CODE REVIEW

**Comment by BurningTreeC** [comment]
yay!

**Comment by BurningTreeC** [comment]
Hello @Jermolene

This PR now builds fine
Are there occasions where we want autofocus if we're not in a browser?

**Comment by Jermolene** [comment]
Hi @BurningTreeC I'm concerned that this approach is not backwards compatible. Would it be possible to use a dynamic value for the autofocus attribute in this case?

**Comment by BurningTreeC** [comment]
Hello @Jermolene - what do you mean by dynamic value for the autofocus attribute?

**Comment by Jermolene** [comment]
Hi @BurningTreeC it looks like this PR is attempting to apple an additional condition governing the setting of autofocus. I wonder if that can be done in wikitext instead.

**Pull request closed without merging**
