### PR TITLE
Add/refactor PaletteManager

### PR DESCRIPTION
**Pull request by BurningTreeC**
this adds $:/PaletteManager that contains all the editor-logic

$:/snippets/paletteeditor transcludes the PaletteManager

$:/core/ui/ControlPanel/Appearance/Palette transcludes it, too

this adds a special $:/core/macros/utils tiddler which is NOT tagged $:/tags/Macro. It contains a special macro named `colour` which returns the parameter name instead of the resolved color. that allows to import it in a separate locally defined macro in the PaletteManager, feed it with an index of the palette which contains a colour macro and get the index it calls ... that original index defining the color can be revealed below for instant editing

### CODE REVIEW

**Comment by BurningTreeC** [comment]
I'm done with this PR

it contains some changes that need review/approvement

**Comment by Jermolene** [comment]
Hi @BurningTreeC this looks very promising. Here's a screenshot for others:

Screenshot 2019-03-09 17 31 29

The new feature of being able to edit the underlying colour for colours defined with the `<<colour>>` macro is cool. I notice that for doubly indirected colours one needs to click reveal twice. For example, here I edited the palette the redefine` foreground` as `<<colour external-link-foreground>>`:

Screenshot 2019-03-09 17 34 34

I also wonder whether it's obvious enough what's going on.

**Comment by BurningTreeC** [comment]
Hi @Jermolene , would it be ok to simply add a short description what this is, like "edit the external-link-foreground color:"?

**Comment by Jermolene** [comment]
Hi @BurningTreeC I think we need to address it by a combination of improving the text, the layout, and perhaps colouring (see how the XLSX plugin uses colour coding in the control panel for a crazy example).

I do wonder also whether these places where we're using tables for UI (the tag manager springs to mind) might not all benefit from being rebuilt using grid layout or perhaps flexbox. Tables do some weird stuff and can be a nightmare to deal with.

**Comment by BurningTreeC** [comment]
I understand @Jermolene ... we need a template

**Comment by BurningTreeC** [comment]
```
.grid {
    display: -ms-grid;
    display: grid;
    -ms-grid-columns: (1fr)[5];
    grid-template-columns: repeat(5, 1fr);
    border-top: 1px solid black;
    border-right: 1px solid black;
}

.grid > span {
    padding: 8px 4px;
    border-left: 1px solid black;
    border-bottom: 1px solid black;
}
```

something like this would generate a grid-table

```

<div class="grid">
        <span><strong>Id</strong></span>
        <span><strong>Full Name</strong></span>
        <span><strong>Country</strong></span>
        <span><strong>Created at</strong></span>
        <span><strong>Email</strong></span>
        <span>0</span>
        <span>Aaron Kris</span>
        <span>Philippines</span>
        <span>1991-05-23T14:19:51</span>
        <span>Ophelia_Mitchell@karley.name</span>
        <span>1</span>
        <span>Simeon McLaughlin</span>
        <span>Singapore</span>
        <span>2012-03-07T00:08:36</span>
        <span>Sabrina_Barton@torey.net</span>
        <span>2</span>
        <span>Kelsie Shanahan</span>
        <span>Brazil</span>
        <span>1985-03-10T20:13:04</span>
        <span>Karianne@salvatore.biz</span>
</div>
```

found it here: https://medium.com/evodeck/responsive-data-tables-with-css-grid-3c58ecf04723

one can also do:

```
grid-template-columns: 1fr 2fr 4fr;
```

I used https://autoprefixer.github.io/ to generate the corresponding `-ms` - prefixed styles, but haven't tested them with internet explorer

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Pull request merged**
