### PR TITLE
Signing the CLA (Eskha)

### PR DESCRIPTION
**Pull request by es-kha**

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @es-kha and welcome to the project! Is there anything particularly you're interested in helping with? Do let me know if there's anything I can do to help.

**Comment by es-kha** [comment]
> 

Thank you Jeremy for your welcome message.

I have signed the CLA, in order, at first, to help with the documentation part. I think that Saq an Mario work should really help to bootstrap contribution for non dev / non git user like me.

As a background, I am a user of TiddlyWiki and follower of its community on a nearly daily basis since 2008.

I am also in the process of cleaning and packaging as plugins / edition different elements I am using in my daily TiddlyWiki thanks to all the ideas of the community. I hope to be ale to share it back quite soon with the community. If at some point in the future you consider any elements worth using in official plugins, I will also happily help wit the integration of these elements.

Last but not least, I really would like to thank you for all the work you have done with creating and upkeeping TiddlyWiki all these years as well as the community you have built around it.

**Comment by Jermolene** [comment]
Thanks @es-kha that's great to hear, and thank you for the kind words. Let me know if I can help with anything.

**Comment by pmario** [comment]
@Jermolene . It seems the PR isn't merged yet?!

**Comment by pmario** [comment]
uups .. Is it the right branch?

**Comment by Jermolene** [comment]
> uups .. Is it the right branch?

We do usually prefer CLA signatures on tiddlywiki-com, but it's easy enough for me to resolve conflicts downstream when we do merge CLA signatures to master.

**Pull request merged**
