### PR TITLE
add unusedtitle macro tests - should have full code covery

### PR DESCRIPTION
**Pull request by pmario**
This PR adds new tests for the `<<unusedtitle>>` macro, to be able to implement future changes without breaking the existing behaviour.

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @pmario I understand why you've included numbers in the filenames of the tests, but it's not very consistent with other tests. Is there an alternative approach?

**Comment by pmario** [comment]
>Is there an alternative approach?

I'll have a closer look

**Comment by Jermolene** [comment]
Thanks @pmario

**Comment by pmario** [comment]
@Jermolene -- I did remove the numbers from the test files.

**Comment by pmario** [comment]
@Jermolene ... These tests should be merged prior to activating this PR:  **add startCount to unusedtitle macro, new tests, new docs #7941**

**Comment by pmario** [comment]
@Jermolene .. I did completely remove the numbers from the filenames as requested. IMO this should be ready to merge now

**Comment by pmario** [comment]
@Jermolene -- This PR contains tests only. Should be save to be merged

**Comment by pmario** [comment]
@Jermolene -- this PR adds some more tests and it blocks an other PR, since the new PR relies on those tests to pass.

**Comment by Jermolene** [comment]
Great stuff, thanks @pmario

**Pull request merged**
