### PR TITLE
Fix katex plugin fonts

### PR DESCRIPTION
**Pull request by BurningTreeC**
Made such a bad mistake, let's forget about it and merge the actual fonts

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Comment by kookma** [comment]
Please correct the read me of plugin! Explicitly state what is the version katex.

**Comment by BurningTreeC** [comment]
@kookma , there's no version mentioned in the readme so there's nothing to update for me. Please make a PR how you intend it, otherwise it'll stay as it is

**Comment by kookma** [comment]
@BurningTreeC 
Sure, I will. I am new to make PRs. I am learning it and will do that for this case soon.
By the way, it should be mentioned what version of KaTeX is used.

Cheers

**Pull request merged**
