### PR TITLE
Update DateFormat.tid

### PR DESCRIPTION
**Pull request by twMat**
very minor tweak

### CODE REVIEW

**Comment by sukima** [comment]
What does this do? How does the `0` differ from the not-`0`?

**Comment by twMat** [comment]
E.g times:  19:2:3 vs 19:02:03

**Comment by twMat** [comment]
Good idea. I added so there are now two examples to clarify the diff.

**Comment by Jermolene** [comment]
Thanks @twMat sorry I missed this, I fixed it in a75434a347eb2fb31ff7a5fce4d3cba301c5eeb0 (and added the YYYY for the year).

**Pull request closed without merging**
