### PR TITLE
big-green button: border-radius 2px

### PR DESCRIPTION
**Pull request by BurningTreeC**
make it a bit more beautiful

### CODE REVIEW

**Comment by pmario** [comment]
That is highly subjective. ... Border radius 2 is barely seen on my screen, that's why it's OK. ... BUT if it would be 3px like the buttons here, it's already starting to get ugly.

**Comment by Jermolene** [comment]
It's helpful if PR's that make visual changes are accompanied by before and after screenshots so that people can comment without having to build the PR

**Comment by BurningTreeC** [comment]
Bildschirmfoto vom 2019-07-08 15-02-15
Bildschirmfoto vom 2019-07-08 15-02-46

**Comment by BurningTreeC** [comment]
More plugins Button - after

Bildschirmfoto vom 2019-07-08 15-04-00

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Comment by Jermolene** [comment]
Sorry I meant to add that this seems OK to merge, I agree that the very square corners we have at the moment don't look professional.

**Comment by BurningTreeC** [comment]
@Jermolene - reopened

**Pull request merged**
