### PR TITLE
Highlight Plugin - DOS batch file and Powershell script language support added

### PR DESCRIPTION
**Pull request by Jebtrix**
I was very surprised not to find DOS batch files or Powershell script highlighting support. I have quite a few and believe these should be included in the same club as BASH is.

### CODE REVIEW

**Comment by pmario** [comment]
@Jebtrix ... This PR hasn't been merged for a long time and has conflicts now. Ìf it still a thing it may be updated. If not please close it!

@Jermolene ... If not updated for eg: 3 days pls. close!

**Comment by pmario** [comment]
@Jermolene ... The rope has be deleted. So it should be save to close the PR!

**Comment by pmario** [comment]
@Jermolene -- This PR has long been outdated. So it should be closed.

**Comment by Jermolene** [comment]
Thanks @pmario

**Pull request closed without merging**
