### PR TITLE
navigate to tiddler above or below when cancelling, closing, deleting

### PR DESCRIPTION
**Pull request by BurningTreeC**

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @BurningTreeC. Is there any chance that users might want to configure whether the target is the next or previous tiddler?

I also wondered whether this logic should be in the associated message handlers in the navigator widget, so that anyone using those messages will get the same behaviour, without needing a custom navigate action.

**Comment by twMat** [comment]
I would really like this addition but/and agree it should be configurable.

**Comment by BurningTreeC** [comment]
>Thanks @BurningTreeC. Is there any chance that users might want to configure whether the target is the next or previous tiddler?

Yes the chance is high

>I also wondered whether this logic should be in the associated message handlers in the navigator widget, so that anyone using those messages will get the same behaviour, without needing a custom navigate action.

I haven't looked at the navigator widget itself, maybe I can try giving it a shot...

**Comment by BurningTreeC** [comment]
>I haven't looked at the navigator widget itself, maybe I can try giving it a shot...

No, the javascript way is too complicated for me at the moment

**Comment by Jermolene** [comment]
> No, the javascript way is too complicated for me at the moment

I can't disagree there; it's overdue for refactoring.

**Comment by pmario** [comment]
new discussion at: Meta-Issue: Refactor the Navigation mechanism #4180

**Pull request closed without merging**
